### ISSUE TITLE
NBFC prevents charging on Lenova Yoga 2 13

### ISSUE THREAD

**Issue by hugobuddel** [hirschmann/nbfc#10]
The fan sound of the Lenovo Yoga 2 13 (non pro) laptops are prone to be loud, as was the case with my Windows 8.1 laptop. Installing Notebook Fan Control unfortunately did not help in reducing the noise but instead prevented my battery from charging. Hovering over the battery icon in the tray would show "22% available (plugged in, not charging)". Charging resumed after uninstalling NBFC.

The root cause of the issue is unclear to me, maybe it's on Lenovo's side. (Well, the noisy fan certainly is.) However, it could potentially help other Yoga owners if it would be possible for NBFC to detect and warn about the problem.

An even more unlucky fellow on the Lenovo forums made me aware of the issue:
https://forums.lenovo.com/t5/Lenovo-Edge-Yoga-Lavie-Z-Flex/Yoga-13-and-battery-is-plugged-in-not-charging/m-p/1768703#M21346

**Comment by hirschmann** [comment]
I’ve tried to gather some information about this issue and it looks like it is not solely related to NBFC.
It seems like tools which access or monitor the hardware provoke this issue, but sometimes it seems to appear pretty randomly.

I’m afraid the only one who can solve this problem is Lenovo.

**Comment by hugobuddel** [comment]
Thank you for looking into it @hirschmann . The problem indeed seems kinda mysterious. Hasn't happened with my laptop since, hopefully it stays that way!
