### ISSUE TITLE
[Ubuntu 16.04] File Descriptor does not support writing

### ISSUE THREAD

**Issue by tumtom** [hirschmann/nbfc#100]
Hallo Stefan,

mit dem vorgeschlagenen Fix konnte ich unter Ubuntu 16.04 bauen, allerdings bekomme ich bei starten mit:
_mono nbfc.exe start_
ein
_File Descriptor does not support writing_.

Auch ein sudo hilft nicht weiter.

Kann ich dir irgendwie ein Log erstellen um beim Problem finden zu helfen?

Gruß,
Tom

**Comment by hirschmann** [comment]
Hi,

ist der nbfc service richtig installiert und läuft?
Eine Anleitung zur Installation gibts hier: https://github.com/hirschmann/nbfc/wiki/First-steps

Was gibt _nbfc.exe status_ aus?

Zum Log:
Schau in: `/var/lib/mono/eventlog/`

Es kann sein, dass das mono eventlog bei dir deaktiviert ist.
Hier ist eine Anleitung wie man das prüfen und ggf. aktivieren kann: https://lukewickstead.wordpress.com/2014/01/04/set-up-enable-the-event-log-under-mono-gnulinux/

**Comment by tumtom** [comment]
Hallo Stefan,

vielen Dank für die schnelle Antwort!

Ich hab die Anleitung gefolgt und bekomme jetzt nach einem Neustart die
Meldung:

/mono nbfc.exe start//
//The classes in the module cannot be loaded./

/mono nbfc.exe status//
//Service enabled        : False//
//Selected config name    : Acer Aspire E13//
//Temperature        : 0/

Could not get fan info because the service is disabled

Ein /ps aux | grep nbfc/ ergibt

/root      2752  0.1  1.4 783720 58280 ?        Sl   18:19   0:02
/usr/bin/mono /usr/lib/mono/4.5/mono-service.exe -m:NbfcService
/opt/nbfc/NbfcService.exe -l:/run/nbfc.pid/

Gruß,

Tom

Am 24.07.2016 um 17:06 schrieb Stefan Hirschmann:

**Comment by hirschmann** [comment]
"The classes in the module cannot be loaded" deutet darauf hin, dass der Service ein Plugin nicht laden kann. Eventuell weil die target framework version von Plugin und Service nicht übereinstimmen.

Ich habe jetzt target framework version der Linux Plugins angepasst: afbb0572a1a019f7934122ca5f39a164f50f4493

Einfach die neueste Revision pullen und bauen. Du kannst den neuen build einfach über die alten Dateien kopieren, aber musst vorher den Service komplett stoppen per: `systemctl stop nbfc`
Dann einfach drüberkopieren und den Service wieder starten per: `systemctl start nbfc`

Btw bei mir lief auch alles ohne diesen Fix problemlos, aber es kann nicht schaden wenn Service und Plugins das gleiche target framework haben.

**Comment by tumtom** [comment]
Hallo Stefan,

hab das grade durchgeführt, das Problem bleibt leider.

Ich würde dir gerne ein Log zukommen lassen, das Log für mono bekomme
ich leider auch nicht aktiviert.

Meine etc/environment:
/PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/nbfc"//
//MONO_EVENTLOG_TYPE=local/

Der Ordner ist erstellt:
/ls -l /var/lib/mono///
//insgesamt 4//
//drwxr-xr-x 2 root root 4096 Jul 24 19:00 eventlog/

aber leer:
/ls -l /var/lib/mono/eventlog//
//insgesamt 0/


Gruß

Thomas

Am 24.07.2016 um 21:05 schrieb Stefan Hirschmann:

**Comment by hirschmann** [comment]
Ich habe Ubuntu 16.04 in einer VM installiert und es sieht so aus als ob das _ec_sys_ kernel Modul, das vom neuen NBFC EC-Plugin für Linux genutzt wird nicht mehr verfügbar ist.

Was du machen kannst um das Problem zu lösen:
- `/opt/nbfc/Plugins/StagWare.Plugins.ECSysLinux.dll` löschen
- `nbfc/Core/PluginsStagWare.Plugins.ECLinux/bin/ReleaseLinux/StagWare.Hardware.LPC.dll` und `nbfc/Core/PluginsStagWare.Plugins.ECLinux/bin/ReleaseLinux/StagWare.Plugins.ECLinux.dll` nach `/opt/nbfc/Plugins` kopieren
- versuchen den service zu starten

Sorry für den Aufwand, der NBFC Plugin-Loader ist momentan noch zu dämlich mehrere Plugins durchzuprobieren (steht auf der todo Liste).

**Comment by hirschmann** [comment]
Fixed: 08598e2201a5c23e312ac0ba67587dea11188f8f

**Comment by erkexzcx** [comment]
I am trying to summarize what we have: https://wiki.archlinux.org/index.php/Fan_speed_control#Troubleshooting
