### ISSUE TITLE
Please add support for OMEN Laptop 15-en0xxx

### ISSUE THREAD

**Issue by lan-hx** [hirschmann/nbfc#1000]
The config for HP Omen 15 dc00xxxx (in the issue) does work somehow, but it gets wrong with the max/min speed. The noise is really annoying sometimes.

**Comment by mikeb2k** [comment]
Where did you find that conf? I cant find it in the app.

**Comment by r-ul-ex** [comment]
[HP OMEN Laptop 15-en0xxx.xml.worked_control.zip](https://github.com/hirschmann/nbfc/files/5982740/HP.OMEN.Laptop.15-en0xxx.xml.worked_control.zip)
!Updated 2021.02

CPU fan speed register 46
GPU fan speed register 47

CPU fan control register 176/177
GPU fan control register 178/179

nbfc shows fan speed with this params, but can't control, because locked  EC fan manual control  

[dsdt.dsl.zip](https://github.com/hirschmann/nbfc/files/5561990/dsdt.dsl.zip)

**Comment by r-ul-ex** [comment]
full speed both fan if write 4 to register 236 
right fan stoped if write 20 to register 236, left fan set speed to 40% but stop too, if CPU temperature < 37°

**Comment by renatilma** [comment]
@r-ul-ex is there any update on this config? Have the same issue with annoying fan spinning on idle, unfortunately.

**Comment by korbel** [comment]
@renatilma Try this:

Write registers (CPU, GPU): 44, 45
Read registers (CPU, GPU): 46, 47
Reset value: 255
Min: 0, Max: 100

There is a working config somewhere on HP Omen discord server with these values iirc.

**Comment by renatilma** [comment]
@korbel Thanks, it works, I recently found some config on reddit, probably that one on discord is the same.

**Comment by schroef** [comment]
Do any of you know why there seems to be a delay when they kick. When i look at the percentages, i feel it kicks in pretty late.
I also noticed this settings just control one 1 fan, the GPU fan will not spin. I adjust the the min-max and now GPU fan also spins. Im not sure what fan is for what component. The default file onle left dan seemed to be spinning so i guess its left is CPU fan and right is GPU fan?

What is this dsdt.dsl?

**Comment by renatilma** [comment]
@schroef Yes, left for CPU, right for GPU, and heat pipes connect CPU and GPU so they heat each other too. For me both fans spin well and synchronously with config values from korbel's comment, didn't notice any significant delay. And as I know NBFC uses only CPU temp to control fans unlike the original EC, which control each fan by CPU and GPU temp independenlty (due GPU has different critical temps and liimits).

**Comment by 1maxpayne1** [comment]
> [HP OMEN Laptop 15-en0xxx.xml.worked_control.zip](https://github.com/hirschmann/nbfc/files/5982740/HP.OMEN.Laptop.15-en0xxx.xml.worked_control.zip)
> !Updated 2021.02
> 
> CPU fan speed register 46
> GPU fan speed register 47
> 
> CPU fan control register 176/177
> GPU fan control register 178/179
> 
> nbfc shows fan speed with this params, but can't control, because locked EC fan manual control
> 
> [dsdt.dsl.zip](https://github.com/hirschmann/nbfc/files/5561990/dsdt.dsl.zip)

Hi buddy

did you uninstall HP OMEN GAMING HUB ?
your config works for me. but sometimes when i clicked HP gaming hub hot keys, the fans go to maxium. 
sometimes it suddenly goes to maxium even i did nothing.

**Comment by renatilma** [comment]
@1maxpayne1 maybe your NBFC writing interval is too long and gaming hub overrides values to defaults? Try it with 1-2 sec.
I stopped using NBFC for Omen because it leads to "critical battery level" issues and I didn't find solution for this.
