### ISSUE TITLE
Acer Aspire E1-572G

### ISSUE THREAD

**Issue by zoumpoulakis-manos** [hirschmann/nbfc#101]
Can anyone help me creating a config for my E1-572G laptop? I can provide any files requied (debug, etc.) and EC information.
I am experiencing serious problems with fan speed and need to control it!

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
