### ISSUE TITLE
Please support 10th gen INTEL CPU (i5 10300H).

### ISSUE THREAD

**Issue by madedimas** [hirschmann/nbfc#1014]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
If you're about to request a config for a specific notebook model, please follow these steps before creating a new issue: [**Config requests**](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Describe the solution you'd like**

**Additional context**

**Comment by olaf829** [comment]
My laptop is ideapad gaming 3i,,,
What lineup should I set to apply when I run this program? If not, request configuration.

**Comment by jose1711** [comment]
from https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests:

> Don't ask if someone can create a configs for you. Instead, read the tutorial of how to create a NBFC config and try to create a config on your own
