### ISSUE TITLE
Please add HP ZBook Studio x360 G5

### ISSUE THREAD

**Issue by YuriyDulich** [hirschmann/nbfc#1016]
Please add subject to correct control and detecting fan speed. Current I use HP ZBook Studio G3 preset but here two issue: 

- when fan speed very low or disable the program shows negative value of fan speed

- second menu with correct name GPU FAN, not CPU FAN2
and if it's possible add GPU temp
thank you so much!

**Comment by 000masa000** [comment]
Working on it. Wondering if you have issues with DPC Latency using LatencyMon when running notebook fancontrol, would appreciate if you can try it?
