### ISSUE TITLE
Services is disabled

### ISSUE THREAD

**Issue by Gasiyu** [hirschmann/nbfc#1021]
**Describe the bug**
nbfc status "Could not get fan info because the service is disabled"

**To Reproduce**
$ mono nbfc.exe status
Service enabled		: False
Read-only		: False
Selected config name	: 
Temperature		: 0

Could not get fan info because the service is disabled

**Expected behavior**
Services enabled

**System information**
 - Manjaro Openbox 20.10
 - NBFC 1.6.3
 - [Log Files](https://del.dog/fucrecavoc.txt)

**Additional context**
$ sudo systemctl status nbfc
● nbfc.service - NoteBook FanControl service
     Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2020-11-24 20:41:48 WIB; 12min ago
   Main PID: 96745 (mono)
      Tasks: 7 (limit: 19002)
     Memory: 32.9M
     CGroup: /system.slice/nbfc.service
             └─96745 /usr/bin/mono /usr/lib/mono/4.5/mono-service.exe -l:/run/nbfc.pid -m:NbfcService /opt/nbfc/NbfcService.exe

Nov 24 20:41:48 akbr systemd[1]: Starting NoteBook FanControl service...
Nov 24 20:41:48 akbr systemd[1]: nbfc.service: Can't open PID file /run/nbfc.pid (yet?) after start: Operation not permitted
Nov 24 20:41:48 akbr systemd[1]: Started NoteBook FanControl service.
Nov 24 20:41:49 akbr mono[96745]: NbfcService: Service NoteBookFanControlService started

**Comment by Gasiyu** [comment]
Also get this problem on pop os 20.10

**Comment by Gasiyu** [comment]
Fixed by deleting StagWare.Plugins.ECSysLinux.dll and restart nbfc services
https://wiki.archlinux.org/index.php/fan_speed_control#Configuration_2

**Comment by mitat52** [comment]
> Fixed by deleting StagWare.Plugins.ECSysLinux.dll and restart nbfc services https://wiki.archlinux.org/index.php/fan_speed_control#Configuration_2

how about for windows?
