### ISSUE TITLE
Only one CPU fan (of 2) being controlled - HP Elitebook X360 1030 G3

### ISSUE THREAD

**Issue by SamCoppen** [hirschmann/nbfc#1027]
Fan control works for some period of time. Then one of the two CPU fans in my laptop will spin up on its own whilst NBFC still controls the other.

**Comment by jvmccallum** [comment]
Hi,

Can I ask which profile you use to control the 1030 G3 fans?

Thanks

**Comment by SamCoppen** [comment]
Hi,

I created one but I believe the HP EliteBook Folio 1040 G1 profile did write to the correct registry. IIRC it was reading wrong so it would say the fans were 200% for example, which is why I made one.

I can post the XML if that helps.

Thanks

**Comment by jvmccallum** [comment]
Hi,

If possible that would be fantastic!

Thank you,

**Comment by SamCoppen** [comment]
Hi,

Pretty new to this so let me know if that works.

https://github.com/SamCoppen/NBFCProfile.git

Thanks,

**Comment by Jeizi67** [comment]
Hi Sam
Your NBFC Profile works great and made my office place much more comfortable ;-)
I put the Target to 25%. 
Fan-Speed is most of the time  around 45%. 
Sometimes it drops to 0 for a second, then it goes up to 84% for another second and then it comes back to 45% . This happens very fast, so the vent don't have time enough to spin up...
CPU-Temp is most of the time below 60°C
Thanks!

**Comment by SamCoppen** [comment]
> Hi Sam
> Your NBFC Profile works great and made my office place much more comfortable ;-)
> I put the Target to 25%.
> Fan-Speed is most of the time around 45%.
> Sometimes it drops to 0 for a second, then it goes up to 84% for another second and then it comes back to 45% . This happens very fast, so the vent don't have time enough to spin up...
> CPU-Temp is most of the time below 60°C
> Thanks!

**Comment by SamCoppen** [comment]
No problem @Jeizi67, glad I could help.

**Comment by krptg0** [comment]
Hi, I'm just bumping to say that @SamCoppen profile works also on HP EliteBook x360 1030 G8.

Thank you !
