### ISSUE TITLE
Need support 10th gen Intel CPU

### ISSUE THREAD

**Issue by madedimas** [hirschmann/nbfc#1037]
Please, i really need this software.
My laptop is Hp Pavilion 15 Dk-1064TX 🙏🏻

**Comment by ikrasnopeev** [comment]
It was done here: https://github.com/Dwedit/nbfc
But you have to build it manually.

**Comment by madedimas** [comment]
Can u give me tutorial how to make ot work?

**Comment by madedimas** [comment]
Ow...i need install this software first:
1. Visual Studio 2019 (Community)
2. WiX Toolset v3.11
Then To build, run the build.ps1

**Comment by madedimas** [comment]
I already run build.ps1 with powershell but i dont see .exe file on nbfc-master/windows/setup/NbfcBoostrapper

Please help how to make it work :(

**Comment by madedimas** [comment]
Woaa thanks @ikrasnopeev my manual build Nbfc for 10th cpu already installed perfectly.

**Comment by mcun312** [comment]
@madedimas I have been trying to build the same file for hours, nothing seems to work.. installed both mentioned softwares, do you mind sharing how did you make it work please? I’m frustrated..

**Comment by owenliu66** [comment]
> @madedimas I have been trying to build the same file for hours, nothing seems to work.. installed both mentioned softwares, do you mind sharing how did you make it work please? I’m frustrated..

I also have this problem...  please help...
