### ISSUE TITLE
HP Probook 450 G3

### ISSUE THREAD

**Issue by AndreyChirita** [hirschmann/nbfc#104]
Please add configuration file for HP Probook 450 G3 with Core i7. Thank you!

**Comment by wassupjg** [comment]
Yes, please add a profile for the HP Probook 450 G3!

Many thanks! Your work is much appreciated.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
