### ISSUE TITLE
Bug on Hp envy x360 13"

### ISSUE THREAD

**Issue by LelilolZH** [hirschmann/nbfc#1046]
**Describe the bug**
Reads wrong the temperature and cant change the fan speed.

**Expected behavior**
fix the bug

**System information**
 - operating system Winows 10 Home
 - NBFC  version 1.6.3

**Additional context**
There are a lot different models of Hp envy x360 13" with the processors I710th gen I510th gen I310th gen and Ryzen 7, Ryzen 5 and Ryzen 3. All Ryzens processor are the from the 4000 series. My processor was the `AMD Ryzen 7 4700U with Radeon Graphics`. Hope that helps ;)

**Comment by hashkat0x67** [comment]
Mussman LG
