### ISSUE TITLE
T14 Fan Not Controlled Properly

### ISSUE THREAD

**Issue by Snuupy** [hirschmann/nbfc#1049]
Device: Lenovo T14 Gen 1 (AMD)

nbfc is able to detect the temp sensor and fan speed it seems, but setting the fan speed manually (say, at 100%) makes the fan pulse (higher rpm then lower rpm, every few seconds)

Tried using T480 and T540p profile.

**Comment by Snuupy** [comment]
Update: I can get this working with tpfancontrol v0.62 for some strange reason. Not sure how to grab the correct pin information to plug it into nbfc.

**Comment by marcohald** [comment]
@Snuupy I have the same issue with an e595.
maybe there is a write to an register needed to stop automatic controlling.

**Comment by Snuupy** [comment]
This is still a problem on my T14.

**Comment by HighKo** [comment]
I have the same problem on a T14 AMD Gen1

**Comment by fly2high1** [comment]
Same problem for me. T14 Intel
