### ISSUE TITLE
Asus K95VB. Cannot find valid parameters with ec-probe.

### ISSUE THREAD

**Issue by lanmaster** [hirschmann/nbfc#105]
Hello.
Please help me to get right working config for my Asus K95VB.
Thanks.

**Comment by RypeDub420** [comment]
Did you try monitoring for a while, then dumping to a text file and examining the output?

Re-read the EC-Probe Tool page, near the bottom for the monitor command.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
