### ISSUE TITLE
Lower the lowest fan speed on thinkpad?

### ISSUE THREAD

**Issue by Janaue** [hirschmann/nbfc#1053]
I have a thinkpad L15 amd and the nbfc works with the profile for the x230. With tpfancontrol 0.62 [[ which has coarse  steps, 0,1,2,3,4,5,6,7] not the 0.62L version which has finer steps from 255->0] and nbfc i can control it but the lowest fan speed is 2600 rpm or 14% on nbfc,  which is too high in terms of noise. Is it possible to force a lower RPM for step 1, it by changing the EC or the BIOS ?

**Comment by CallofDugi** [comment]
Hello everybody,
Could someone create a config for an Acer Aspire V5-571PG-53314G75Mass?
Many many thanks!
With best regards
CallofDugi
