### ISSUE TITLE
[Config] HP EliteBook 840 G7

### ISSUE THREAD

**Issue by Gf2k2** [hirschmann/nbfc#1059]
Unfortunally none of the recommended Configs seems to be working. I tried creating one by myself but seem to lack the necessary knowledge.

**Comment by kocane** [comment]
I totally got my hopes up for a moment, that this would be an actual config :-(

**Comment by SkyREgit** [comment]
For **HP Eltebook 840 G5**, config **HP ProBook 450 G1** is working.
