### ISSUE TITLE
Could nbfcbootstrapper.exe host a Trojan?

### ISSUE THREAD

**Issue by blackrider020** [hirschmann/nbfc#106]
You build an awesome application and I used it for at least 2 years on my HP 4710s laptop, but now, after I updated to W10 my antivirus sees nbfcbootstrapper.exe as Trojan (Trojan.Win32.Generic). 
Do you have a solution for this? My computer is infected? Thank you!

**Comment by hirschmann** [comment]
If you have downloaded nbfc from github (https://github.com/hirschmann/nbfc/releases), you can be pretty sure that it's just a false positive.
To verify this assumption, upload the setup to virustotal.com.

If you want to be sure the setup is clean, you can also build nbfc from source: https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC
