### ISSUE TITLE
Custom fan curve for controlling fan speed.

### ISSUE THREAD

**Issue by the-r3dacted** [hirschmann/nbfc#1065]
**Is your feature request related to a problem? Please describe.**
Don't really know if it's considered a problem, but I don't like hearing my fan ramp up to 70% when booting into Windows, when idle, because I forgot to reset the program to read only.

**Describe the solution you'd like**
A customizable fan curve, following the temperature of both the GPU and CPU.

**Additional context**
So, I'd tell the program when below like 50C, don't run the fans. Once over 50C, I could set it to gradually increase until it gets to 70+% at 80C. It would be controlled by the highest temperature, whether it be the CPU or the GPU would depend on the load.

**Comment by the-r3dacted** [comment]
That's what happens when the program is stale 😢

**Comment by the-r3dacted** [comment]
I fucking responded you cunt

**Comment by OMNIDROID2995** [comment]
Why so aggressive? Grab Claude Sonnet via Github Copilot or try ChatGPT. Tell the AI which sensors you have (“sensors” from lm_sensors) and that you want to set a script with different fan percentages for "sudo nbfc set --speed" to certain temperatures. Your script is ready, which you can use in systemd with your own .service file. It has helped me a lot with a cheap HP notebook, as it can't overheat even at the lowest fan speed (normally it always revs up unnecessarily and switches on at strange times).
