### ISSUE TITLE
Asus N53Jn

### ISSUE THREAD

**Issue by Agroq** [hirschmann/nbfc#107]
Hey. Can you help me to create a configuration for my notebook? Please.
I'm just bad at English, I can not use your user manual. 
Thank you

Read & Write confih file - 
[EC6662.zip](https://github.com/hirschmann/nbfc/files/422404/EC6662.zip)

**Comment by Agroq** [comment]
Pls help me

**Comment by Hourri** [comment]
+1 I need it too for one of my notebooks :)

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
