### ISSUE TITLE
How to actually use chip documentation?

### ISSUE THREAD

**Issue by k8ieone** [hirschmann/nbfc#1070]
Hi, I'm trying to make a NBFC config for the Asus G2K. I already found where I need to write for controlling the fan, I just need to disable the EC's auto control.

I found a service manual online, which said that the EC in this laptop is ITE IT8510TE. I found [this doc](https://www.qdatasheet.com/datasheet-download/889363/1/ITE/IT8510TE) for it online.

I think this is the register I was looking for:
![image](https://user-images.githubusercontent.com/28711937/106965236-98441300-6743-11eb-9b3f-5721c50b9100.png)

My question is: How do I get from that info (offset: 10h, bit: 7-6) to something I can actually locate in the output of `ec-probe dump` and write to with `ec-probe write`?

I'm looking forward to hearing from anyone.

**Comment by webloft** [comment]
The address offset in this documentation may be not the same offset you get via software.
If so you would need to set the bits 7-6 of a single byte which means other bits may be necessary to keep.

So if the register value is 0x3B for example and you set bits 7-6 to 10 you'll get 0xBB
and would write that as (offset 10h = 0x10)

ec-probe write 0x10 BB

**Comment by k8ieone** [comment]
Hi and thanks for your response.  

I just tried `ec-probe write 0x10 BB`, but I got this error:
```
usage: ec-probe.exe [--version] [--help] <command> [<args>]
Argument value value "0B" cannot be converted to the required type System.Byte.
```

I also tried writing to different registers, but it looks like I can't write `BB` anywhere.

**Comment by webloft** [comment]
Then you need to write 

ec-probe write 0x10 0xBB

**Comment by k8ieone** [comment]
Indeed, I do. Sorry, I was half asleep when I was trying this.

Now, I found that the default value of `0x10` is `00`. So from what I understand, to change bits `7` and `6` to `1` and `0`, I have to write `40` (or `80` if you were counting from 0), right?

EDIT: The docs do count from 0, so I assume you did too.

**Comment by webloft** [comment]
7-6 looks like the common bit notation (starting right with position 0) 

position 7 = 1
position 6 = 0

So the correct value should be 0x80.
