### ISSUE TITLE
NoteBookFanControlService (really) started ???

### ISSUE THREAD

**Issue by tomprost** [hirschmann/nbfc#1073]
**Describe the bug**
A clear and concise description of what the bug is - I just don't see, whether **NBFC is started ?**!!!
### 
**To Reproduce**
tom@Satellite-L350D:/opt/nbfc$ **mono nbfc.exe status -a**
Service enabled	: False
Read-only		: False
Selected config name: 
Temperature		: 0
Could not get fan info because the service is disabled

**BUT at the same time -->**

tom@Satellite-L350D:/opt/nbfc$ **service nbfc status**
● nbfc.service - NoteBook FanControl service
     Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-02-09 11:58:18 CET; 15min ago
    Process: 690 ExecStart=/opt/nbfc/nbfcservice.sh start (code=exited, status=0/SUCCESS)
   Main PID: 748 (mono)
      Tasks: 10 (limit: 3184)
     Memory: 63.0M
     CGroup: /system.slice/nbfc.service
             └─748 /usr/bin/mono /usr/lib/mono/4.5/mono-service.exe -l:/run/nbfc.pid -m:NbfcService /opt/nbfc/NbfcService.exe

Feb 09 11:57:59 Satellite-L350D systemd[1]: Starting NoteBook FanControl service...
Feb 09 11:58:02 Satellite-L350D systemd[1]: nbfc.service: Can't open PID file /run/nbfc.pid (yet?) after start: Operation not permitted
Feb 09 11:58:18 Satellite-L350D systemd[1]: Started NoteBook FanControl service.
Feb 09 11:58:58 Satellite-L350D mono[748]: NbfcService: Service NoteBookFanControlService started
tom@Satellite-L350D:/opt/nbfc$ 

**Expected behavior**

**System information**
 - operating system
 - NBFC version
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview))

**Additional context**

**Comment by jose1711** [comment]
Hard to tell but your shell prompt suggests you're not `root`? Can you please run everything under `root` again and post the output?
