### ISSUE TITLE
Linux Build is Failing again...

### ISSUE THREAD

**Issue by bender2305** [hirschmann/nbfc#108]
Hello,

trying to build the linux version under linux mint 17.3 and an the same error as mentioned in an older thread happens to me. Unfortunately the solution described there is not working, there is already a nuget.exe in the main folder and mozroots --import --sync fails with "Couldn't retrieve the file using the supplied information." Am I doing something wrong? Any help would be appreciated. Build output is attached below. Thank you very much!

  

>   WARNUNG: The initialization function tries to access Value on this instance
>     WARNUNG: The initialization function tries to access Value on this instance
>     WARNUNG: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
>     Unable to find version '1.4.7.0' of package 'clipr'.
>     Unable to find version '2.5' of package 'Extended.Wpf.Toolkit'.
>     Unable to find version '1.0.5' of package 'Hardcodet.NotifyIcon.Wpf'.
>     XBuild Engine Version 12.0
>     Mono, Version 3.2.8.0
>     Copyright (C) 2005-2013 Various Mono authors
> 
>     Build started 18.08.2016 08:03:00.
> 
>     /home/martin/Downloads/fancontrol/Windows/Setup/NbfcSetup/NbfcSetup.wixproj: warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
>     /home/martin/Downloads/fancontrol/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj: warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
>     /home/martin/Downloads/fancontrol/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj: warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.
>     Project "/home/martin/Downloads/fancontrol/NoteBookFanControl.sln" (Build target(s)):
>     Target ValidateSolutionConfiguration:
>     Building solution configuration "ReleaseLinux|Any CPU".
>     Target Build:
>     Project "/home/martin/Downloads/fancontrol/Core/StagWare.Configurations/StagWare.FanControl.Configurations.csproj" (default target(s)):
>     Target PrepareForBuild:
>     Configuration: Release Platform: AnyCPU
>     Target GenerateSatelliteAssemblies:
>     No input files were specified for target GenerateSatelliteAssemblies, skipping.
>     Target GenerateTargetFrameworkMonikerAttribute:
>     Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
>     Target CoreCompile:
>     Skipping target "CoreCompile" because its outputs are up-to-date.
>     Done building project "/home/martin/Downloads/fancontrol/Core/StagWare.Configurations/StagWare.FanControl.Configurations.csproj".
>     Project "/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Hardware.LPC/StagWare.Hardware.LPC.csproj" (default target(s)):
>     Target PrepareForBuild:
>     Configuration: Release Platform: AnyCPU
>     Target GenerateSatelliteAssemblies:
>     No input files were specified for target GenerateSatelliteAssemblies, skipping.
>     Target GenerateTargetFrameworkMonikerAttribute:
>     Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
>     Target CoreCompile:
>     Skipping target "CoreCompile" because its outputs are up-to-date.
>     Done building project "/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Hardware.LPC/StagWare.Hardware.LPC.csproj".
>     The project 'OpenHardwareMonitorLib' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
>     The project 'StagWare.BiosInfo' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
>     Project "/home/martin/Downloads/fancontrol/Core/StagWare.FanControl/StagWare.FanControl.csproj" (default target(s)):
>     Target PrepareForBuild:
>     Configuration: Release Platform: AnyCPU
>     Target GenerateSatelliteAssemblies:
>     No input files were specified for target GenerateSatelliteAssemblies, skipping.
>     Target GenerateTargetFrameworkMonikerAttribute:
>     Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
>     Target CoreCompile:
>     Skipping target "CoreCompile" because its outputs are up-to-date.
>     Done building project "/home/martin/Downloads/fancontrol/Core/StagWare.FanControl/StagWare.FanControl.csproj".
>     The project 'ConfigEditor' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
>     The project 'DriverSetupWixAction' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
>     The project 'StagWare.Hardware' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
>     Project "/home/martin/Downloads/fancontrol/Core/NbfcProbe/NbfcProbe.csproj" (default target(s)):
>     Target PrepareForBuild:
>     Configuration: ReleaseLinux Platform: AnyCPU
>     Target ResolveAssemblyReferences:
>     /usr/lib/mono/4.5/Microsoft.Common.targets: warning : Reference 'clipr, Version=1.4.7.0, Culture=neutral, processorArchitecture=MSIL' not resolved
>     For searchpath {CandidateAssemblyFiles}
>     Warning: {CandidateAssemblyFiles} not supported currently
>     For searchpath {HintPathFromItem}
>     Considered ../../packages/clipr.1.4.7.0/lib/net35/clipr.dll, but it does not exist.
>     For searchpath {TargetFrameworkDirectory}
>     Considered target framework dir /usr/lib/mono/4.0, assembly named 'clipr' not found.
>     For searchpath {PkgConfig}
>     Considered clipr, Version=1.4.7.0, Culture=neutral, processorArchitecture=MSIL, but could not find in any pkg-config files.
>     For searchpath {GAC}
>     Considered clipr, Version=1.4.7.0, Culture=neutral, processorArchitecture=MSIL, but could not find in the GAC.
>     For searchpath {RawFileName}
>     Considered '/home/martin/Downloads/fancontrol/Core/NbfcProbe/clipr, Version=1.4.7.0, Culture=neutral, processorArchitecture=MSIL' as a file, but the file does not exist
>     For searchpath bin/ReleaseLinux/
>     Considered '/home/martin/Downloads/fancontrol/Core/NbfcProbe/bin/ReleaseLinux/clipr' as a file, but the file does not exist
>     Considered '/home/martin/Downloads/fancontrol/Core/NbfcProbe/bin/ReleaseLinux/clipr.exe' as a file, but the file does not exist
>     Considered '/home/martin/Downloads/fancontrol/Core/NbfcProbe/bin/ReleaseLinux/clipr.dll' as a file, but the file does not exist
>     Target GenerateSatelliteAssemblies:
>     No input files were specified for target GenerateSatelliteAssemblies, skipping.
>     Target GenerateTargetFrameworkMonikerAttribute:
>     Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
>     Target CoreCompile:
>     Tool /usr/bin/dmcs execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj/ReleaseLinux/ec-probe.exe CommandLineOptions/ECWriteVerb.cs CommandLineOptions/ECReadVerb.cs CommandLineOptions/ECDumpVerb.cs CommandLineOptions/CustomHelpGenerator.cs CommandLineOptions/Verbs.cs Program.cs Properties/AssemblyInfo.cs /target:exe /define:TRACE /main:NbfcProbe.Program /platform:AnyCPU /reference:/usr/lib/mono/4.0/System.dll /reference:/usr/lib/mono/4.0/System.Core.dll /reference:/home/martin/Downloads/fancontrol/Core/StagWare.FanControl/bin/Release//StagWare.FanControl.dll /warn:2
>     CommandLineOptions/ECWriteVerb.cs(1,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/ECReadVerb.cs(1,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/ECDumpVerb.cs(1,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(1,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(2,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(3,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(4,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/Verbs.cs(1,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     Program.cs(1,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(11,40): error CS0246: The type or namespace nameTriggerBase' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(11,53): error CS0246: The type or namespace name IHelpGenerator' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(25,32): error CS0115:NbfcProbe.CommandLineOptions.CustomHelpGenerator.Description' is marked as an override but no suitable property found to override
>     CommandLineOptions/CustomHelpGenerator.cs(30,32): error CS0115: NbfcProbe.CommandLineOptions.CustomHelpGenerator.Name' is marked as an override but no suitable property found to override CommandLineOptions/CustomHelpGenerator.cs(40,31): error CS0246: The type or namespace nameIParserConfig' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(71,29): error CS0246: The type or namespace name `IParserConfig' could not be found. Are you missing an assembly reference?
>     Task "Csc" execution -- FAILED
>     Done building target "CoreCompile" in project "/home/martin/Downloads/fancontrol/Core/NbfcProbe/NbfcProbe.csproj".-- FAILED
>     Done building project "/home/martin/Downloads/fancontrol/Core/NbfcProbe/NbfcProbe.csproj".-- FAILED
>     Project "/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Plugins.ECLinux/StagWare.Plugins.ECLinux.csproj" (default target(s)):
>     Target PrepareForBuild:
>     Configuration: ReleaseLinux Platform: AnyCPU
>     Target GenerateSatelliteAssemblies:
>     No input files were specified for target GenerateSatelliteAssemblies, skipping.
>     Target GenerateTargetFrameworkMonikerAttribute:
>     Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
>     Target CoreCompile:
>     Skipping target "CoreCompile" because its outputs are up-to-date.
>     Target AfterBuild:
>     Copying file from '/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Plugins.ECLinux/bin/ReleaseLinux/StagWare.Hardware.LPC.dll' to '/home/martin/Downloads/fancontrol/Linux/bin/ReleaseLinux/Plugins/StagWare.Hardware.LPC.dll'
>     Copying file from '/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Plugins.ECLinux/bin/ReleaseLinux/StagWare.Plugins.ECLinux.dll' to '/home/martin/Downloads/fancontrol/Linux/bin/ReleaseLinux/Plugins/StagWare.Plugins.ECLinux.dll'
>     Done building project "/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Plugins.ECLinux/StagWare.Plugins.ECLinux.csproj".
>     Project "/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Plugins.FSTemperatureMonitor/StagWare.Plugins.FSTemperatureMonitor.csproj" (default target(s)):
>     Target PrepareForBuild:
>     Configuration: ReleaseLinux Platform: AnyCPU
>     Target GenerateSatelliteAssemblies:
>     No input files were specified for target GenerateSatelliteAssemblies, skipping.
>     Target GenerateTargetFrameworkMonikerAttribute:
>     Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
>     Target CoreCompile:
>     Skipping target "CoreCompile" because its outputs are up-to-date.
>     Target AfterBuild:
>     Copying file from '/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Plugins.FSTemperatureMonitor/bin/ReleaseLinux/StagWare.Plugins.FSTemperatureMonitor.dll' to '/home/martin/Downloads/fancontrol/Linux/bin/ReleaseLinux/Plugins/StagWare.Plugins.FSTemperatureMonitor.dll'
>     Done building project "/home/martin/Downloads/fancontrol/Core/Plugins/StagWare.Plugins.FSTemperatureMonitor/StagWare.Plugins.FSTemperatureMonitor.csproj".
>     Task "MSBuild" execution -- FAILED
>     Done building target "Build" in project "/home/martin/Downloads/fancontrol/NoteBookFanControl.sln".-- FAILED
>     Done building project "/home/martin/Downloads/fancontrol/NoteBookFanControl.sln".-- FAILED
> 
>     Build FAILED.
> 
>     Warnings:
> 
>     /home/martin/Downloads/fancontrol/Windows/Setup/NbfcSetup/NbfcSetup.wixproj: warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
>     /home/martin/Downloads/fancontrol/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj: warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
>     /home/martin/Downloads/fancontrol/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj: warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.
> 
>     /home/martin/Downloads/fancontrol/NoteBookFanControl.sln (Build) ->
>     (Build target) ->
>     /home/martin/Downloads/fancontrol/Core/NbfcProbe/NbfcProbe.csproj (default targets) ->
>     /usr/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->
> 
>     /usr/lib/mono/4.5/Microsoft.Common.targets: warning : Reference 'clipr, Version=1.4.7.0, Culture=neutral, processorArchitecture=MSIL' not resolved
> 
>     Errors:
> 
>     /home/martin/Downloads/fancontrol/NoteBookFanControl.sln (Build) ->
>     (Build target) ->
>     /home/martin/Downloads/fancontrol/Core/NbfcProbe/NbfcProbe.csproj (default targets) ->
>     /usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
> 
>     CommandLineOptions/ECWriteVerb.cs(1,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/ECReadVerb.cs(1,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/ECDumpVerb.cs(1,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(1,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(2,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(3,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(4,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/Verbs.cs(1,7): error CS0246: The type or namespace nameclipr' could not be found. Are you missing an assembly reference?
>     Program.cs(1,7): error CS0246: The type or namespace name clipr' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(11,40): error CS0246: The type or namespace nameTriggerBase' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(11,53): error CS0246: The type or namespace name IHelpGenerator' could not be found. Are you missing an assembly reference? CommandLineOptions/CustomHelpGenerator.cs(25,32): error CS0115:NbfcProbe.CommandLineOptions.CustomHelpGenerator.Description' is marked as an override but no suitable property found to override
>     CommandLineOptions/CustomHelpGenerator.cs(30,32): error CS0115: NbfcProbe.CommandLineOptions.CustomHelpGenerator.Name' is marked as an override but no suitable property found to override CommandLineOptions/CustomHelpGenerator.cs(40,31): error CS0246: The type or namespace nameIParserConfig' could not be found. Are you missing an assembly reference?
>     CommandLineOptions/CustomHelpGenerator.cs(71,29): error CS0246: The type or namespace name `IParserConfig' could not be found. Are you missing an assembly reference?
> 
>     4 Warning(s)
>     15 Error(s)
> 
>     Time Elapsed 00:00:00.8652120

**Comment by hirschmann** [comment]
see https://github.com/hirschmann/nbfc/issues/56#issuecomment-240742293
