### ISSUE TITLE
RWEverything alternative for Linux?

### ISSUE THREAD

**Issue by bender2305** [hirschmann/nbfc#109]
Hi,

I've installed now nbfs on my elitebook 8570w with Linux Mint 17.3 using the elitebook 8760w config file which works with some minor issues (100 percent fan speed setting isn not the maximum fan speed for example). As I read about how to create a config for my own machine I was wondering if there is any ReadAndWriteEverything alternative for Linux? Since I am using only Linux on my machine I would appreciate any suggestions or must I have Windows if I want to create my own config?

**Comment by hirschmann** [comment]
NBFC comes with an [EC probing tool](https://github.com/hirschmann/nbfc/wiki/EC-probing-tool) which runs on Linux and Windows.
