### ISSUE TITLE
Asus GL552VW config

### ISSUE THREAD

**Issue by intelect** [hirschmann/nbfc#1091]
Hello! Can anyone more experience than me write a config for the ASUS ROG GL552VW. Thank you!

**Comment by rp1231** [comment]
I'll second that

**Comment by intelect** [comment]
Hey People of GitHub! I was actually waiting for some activity on this thread, and nothing happened, so I did it myself. You're welcome!

https://drive.google.com/file/d/1_-4kqemJiq6BdLHzzHOiXnL8zPa1-EYi/view?usp=sharing

**Comment by zidaniislem22** [comment]
Open the DOCUMENT TEXTE and paste it into it. # 
<?xml version="1.0"?>
<FanControlConfigV2 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NotebookModel>GL552VW</NotebookModel>
  <Author>Dylan Manley</Author>
  <EcPollInterval>300</EcPollInterval>
  <ReadWriteWords>false</ReadWriteWords>
  <CriticalTemperature>80</CriticalTemperature>
  <FanConfigurations>
    <FanConfiguration>
      <ReadRegister>151</ReadRegister>
      <WriteRegister>151</WriteRegister>
      <MinSpeedValue>0</MinSpeedValue>
      <MaxSpeedValue>8</MaxSpeedValue>
      <IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
      <MinSpeedValueRead>0</MinSpeedValueRead>
      <MaxSpeedValueRead>0</MaxSpeedValueRead>
      <ResetRequired>true</ResetRequired>
      <FanSpeedResetValue>9</FanSpeedResetValue>
      <TemperatureThresholds>
        <TemperatureThreshold>
          <UpThreshold>40</UpThreshold>
          <DownThreshold>0</DownThreshold>
          <FanSpeed>20</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>50</UpThreshold>
          <DownThreshold>40</DownThreshold>
          <FanSpeed>35</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>60</UpThreshold>
          <DownThreshold>50</DownThreshold>
          <FanSpeed>50</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>70</UpThreshold>
          <DownThreshold>60</DownThreshold>
          <FanSpeed>65</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>80</UpThreshold>
          <DownThreshold>70</DownThreshold>
          <FanSpeed>80</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>90</UpThreshold>
          <DownThreshold>85</DownThreshold>
          <FanSpeed>90</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>100</UpThreshold>
          <DownThreshold>90</DownThreshold>
          <FanSpeed>100</FanSpeed>
        </TemperatureThreshold>
      </TemperatureThresholds>
      <FanSpeedPercentageOverrides />
    </FanConfiguration>
  </FanConfigurations>
  <RegisterWriteConfigurations>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnWriteFanSpeed</WriteOccasion>
      <Register>166</Register>
      <Value>99</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>99</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
    </RegisterWriteConfiguration>
  </RegisterWriteConfigurations>
</FanControlConfigV2>
# And make it extend "XML"
