### ISSUE TITLE
I'll pay for the config. HP Gaming Pavilion Notebook PC - 15-cx0027ur.

### ISSUE THREAD

**Issue by GORILA1221** [hirschmann/nbfc#1092]
Good day.
Requires config for HP Gaming Pavilion Notebook PC - 15-cx0027ur

Cooling demand see topic views:
https://h30434.www3.hp.com/t5/Notebook-Hardware-and-Upgrade-Questions/cooler-calibration/m-p/7869188#M609799

I will pay for the creation of the config, I will provide all the necessary information up to the use of TeamViewer.

I tried to compile the config myself, but my knowledge of google translate is not enough.

I appeal to the authors of the program and to those who managed to create the config.

**Comment by webloft** [comment]
TeamViewer is not enough. You need to monitor of the fan activity - all the time.
You need to heat the CPU up with burn-in tools to see changes in the fan and identify the right registers.

Once a register in the EC is found to manually control the fan you'll ran into risk of heat damage if there is no firmware emergency recovery option of the fan. Best case the device shuts down. Worst case it will never boot again if the register isn't cleared at boot and the EC memory is permanent.

**Comment by laughingwater** [comment]
> Good day. Requires config for HP Gaming Pavilion Notebook PC - 15-cx0027ur
> 
> Cooling demand see topic views: https://h30434.www3.hp.com/t5/Notebook-Hardware-and-Upgrade-Questions/cooler-calibration/m-p/7869188#M609799
> 
> I will pay for the creation of the config, I will provide all the necessary information up to the use of TeamViewer.
> 
> I tried to compile the config myself, but my knowledge of google translate is not enough.
> 
> I appeal to the authors of the program and to those who managed to create the config.

try the HP Compaq 15-s103tx config, it worked on my HP pavilion gaming 15 dk-2xxx

also if required https://github.com/UraniumDonut/nbfc-revive/issues/27#issuecomment-967684864
