### ISSUE TITLE
Uninstaller hangs

### ISSUE THREAD

**Issue by looak** [hirschmann/nbfc#1094]
I am attempting to run the uninstaller but it hangs on "Processing: NoteBook FanControl"

**To Reproduce**
1. Install on a non-notebook machine.
2. Uninstall through "add and remove programs" in windows.

**Expected behavior**
The  application should be uninstalled fine.

**System information**
 - Windows
 - 1.6.3

**Comment by looak** [comment]
I noticed that the service never got stopped and I suspect this is what was holding on to the application and not allowing it to uninstall. I stopped it manually and had to disable it since it kept starting itself again and after going through those steps I managed to uninstall the application.

**Comment by matrix2110** [comment]
U can disable the service first manually

**Comment by canklot** [comment]
> I noticed that the service never got stopped and I suspect this is what was holding on to the application and not allowing it to uninstall. I stopped it manually and had to disable it since it kept starting itself again and after going through those steps I managed to uninstall the application.

Same here. Uninstall wasn't working. I had to open to app and click disable a lot of times to stop it. It was stuck in a loop between read only and disabled. After stopping the service I was able to uninstall it without a problem.

**Comment by salvlox** [comment]
I cant straight out stop the service; cannot arrest it cannot suspend it; wth
