### ISSUE TITLE
New version changed Asus N550JV config to the worse

### ISSUE THREAD

**Issue by Morfskorf** [hirschmann/nbfc#11]
New version changed Asus N550JV config to the worse, the only noticable thing i've found is that Max speed was set to 12 while it was 8 on ver1.1.1.19 so i reinstalled 1.1.1.19 and everything works as i should. Other than that everything is great. I love your software and i thank you for making it, both me and my laptop thanks you. much love from Sweden

**Comment by hirschmann** [comment]
I'm glad you like my work :)

[Asus N550JV.xml](../blob/ceba94a165dd31fb355bc20e9142c829334f2a8e/Configs/Asus%20N550JV.xml) has not been changed. Max. speed is still set to 8.
I can't find any problems in my code which could cause a issue like this.

Are you sure you are using the config which comes with NBFC?
