### ISSUE TITLE
Configuration triggers only after sleep

### ISSUE THREAD

**Issue by astearon** [hirschmann/nbfc#1106]
**Describe the bug**
I have repurposed for my g6 a HP ZBook 15 g4 config found on the listing here and changed the min max values so the fan correctly spins up at 100% but when trying to use the config it will not trigger any changes unless i first close the lid and set the laptop to sleep.
After wake the settings work as expected.
**To Reproduce**
Load the config and try to change the speed.
Put the laptop to sleep
Wake and try the settings again

**Expected behavior**
Setting should work first try.

**System information**
 - operating system: Win 10
 - NBFC version 1.6.3
 - i have added the config as XLSX instead of XML
[HP ZBook 15 G6.xlsx](https://github.com/hirschmann/nbfc/files/6182424/HP.ZBook.15.G6.xlsx)

Anyone has any idea why this happens?

**Comment by Techzune** [comment]
I can confirm this on the HP ZBook G6. I cannot change the fan speed until I put the laptop to sleep, then wake it up.
