### ISSUE TITLE
nbfc not controlling the fan while moving to sleep/waking up from it anymore? 

### ISSUE THREAD

**Issue by LazyLand1** [hirschmann/nbfc#1109]
Hi,
1. Thanks for creating this wonderful software!
2. This might be the wrong place to post, I apologize - I'm kinda in a hurry. 
 I just updated my Lenovo flex 5 14 (Ryzen 4500u) to the latest windows 10 version to hopefully fix my fingerprint not working while waking up from sleep. It did not work, but after disabling "allow this device to be turned off" for the fingerprint device in device manager and disabling the suspend USB in windows 10 power settings it worked. But now I have discovered that when I close the lid of my laptop to put it in sleep or open it to wake up from sleep the fan starts and pretty noisy too. It only lasts a few seconds but it's a pain in the butt. (I always have my nbfc on 0% Because the Ryzen chip is pretty power efficient and I only do school work/YouTube on it and I want and can have the silence of the fan turned off (as the temps are just fine :)) 
So, I turned the USB suspend back on but the result is still the same. Maybe it's the windows version.. IDK exactly. 
What can I do to not make the fan turn on for the 5 seconds while it wakes up from sleep and goes to sleep? Really annoying! 
Some information: 
Laptop: Lenovo flex 5 14 Ryzen 4500u 14are05
Windows version: https://prnt.sc/10ybzyb
BTW - The flex 5 is not in nbfc, but by selecting Lenovo ideapad 710s fan#1 controls the one fan in the flex 5.. Seems to be working well. Fan#2 Does nothing.

Thanks :)

**Comment by batmalin** [comment]
What happens when you disable NBFC and it wakes up?
