### ISSUE TITLE
Config Asus Zenbook UX302LA wors for Asus ROG G501JW

### ISSUE THREAD

**Issue by Hourri** [hirschmann/nbfc#111]
This .xml file in config Asus Zenbook UX302LA is working very well for my Asus ROG G501JW.

Maybe it is possible to add it in the list ? :)

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
