### ISSUE TITLE
Can you please add a stupid people warning when you first open the app. something like "READ THIS *instructions page* OR YOUR LAPTOP WILL GET PRICKED". I really underestimated how stupid I can be, I did not prick my laptop though.

### ISSUE THREAD

**Issue by RamiMikho** [hirschmann/nbfc#1110]

**Comment by jwhendy** [comment]
Out of curiosity, don't you have to take some specific actions before `nbfc` does anything? As in, installing will not change any behavior. I hear you, I also think seeing a screen with options intuitively prompts one to seek out what the options/settings do, and how to use `nbfc`. I'd never used it, had no idea what to do, started looking and saw the "first steps" link on the main github page.

Can you describe what you did so someone can address a specific concern above and beyond type-shouting at new users to "be careful"?

**Comment by RamiMikho** [comment]
apologies for being unclear, I meant when you change the profile, before you click apply it automatically tried to run it. my laptops screen went blank and I tried shutting it down from power button (held it for 12s) but it did not work, I could tell cz the backlight was still on. I had to wait for battery to die, lucky I was close to 20%. There is not technical issue with app it self, at least I don't think so cz I gave up shortly after. Just a pop up window when app is first opened with red background, white text and link to steps is all.

**Comment by jwhendy** [comment]
Ah, that's helpful. I run on linux so I have no frame of reference for the windows side, but was perusing another issue and thought I'd prompt for more info. I think this is helpful for the devs (though super new user and no idea on their typical response time). I hope it can be improved as that does sound pretty freaky!
