### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by justablob** [hirschmann/nbfc#1113]
**Describe the bug**
When running any command, nbfc just returns `Connection refused`. Tried with both sudo and no sudo. nbfc.service is definitely enabled and up, since `service nbfc status` shows it as running. Restarting the service with systemd does nothing, but starting the service manually with `nbfcservice.sh` does, and after that, nbfc works like it should. What's weird is that if you kill nbfc using `sudo killall mono`, then restart the systemd service, nbfc will keep working normally.

**To Reproduce**
1. Install nbfc on Ubuntu 20.04 following the instructions from the Wiki
2. Run nbfc, get `Connection refused`

**Expected behavior**
It should work 🤷🏻‍♂️ 

**System information**
Lenovo ThinkPad T490s
Ubuntu 20.04.02 LTS
NBFC 1.6.3.0
Mono 6.12.0.122
Log: https://hatebin.com/dvepjwtwpq
Systemd log: https://hatebin.com/upndtobjqv

**Additional context**
I'm using a slightly modified version of the T430s config, but this isn't the problem because the other ThinkPad configs result in the same issue.

There's been a few issues about the same thing but none of the solutions there fixed anything.

**Comment by mohamadali-halwani** [comment]
Can you show me the output of `ls -la /opt/nbfc` ?

**Comment by justablob** [comment]
Weirdly, since I updated to 21.04, I can't reproduce the issue myself anymore. Close?

**Comment by BachoSeven** [comment]
Sure, feel free to close the issue if it's not an issue anymore.
