### ISSUE TITLE
Add config for Lenovo Yoga C940

### ISSUE THREAD

**Issue by stefnikolaev** [hirschmann/nbfc#1119]
Hi,

Does anyone know the registers for fan control for Lenovo Yoga C940 please?

Thanks,
Stef

**Comment by owenliu66** [comment]
I figured out which EC addresses are for CPU temperature, but I can't find the fan...

**Comment by stefnikolaev** [comment]
Thanks for trying. 
I wonder whether the fan is only HW controlled internally...
