### ISSUE TITLE
A mistake in the guide "First steps" & Fail to start mono.exe "connection refused"

### ISSUE THREAD

**Issue by mohamadali-halwani** [hirschmann/nbfc#1122]
[First Steps](https://github.com/hirschmann/nbfc/wiki/First-steps)
**Describe the bug**
In this section of configuring nbfc, " (optional) Copy nbfc/Linux/nbfc into /opt/nbfc/bin/ and Add /opt/nbfc/bin to PATH, so you can call nbfc from anywhere. (Please use quotes if your command has more than one word arguments. ex: nbfc 'set -a' )"

Did you mean to copy nbfc/Linux/bin ? instead of /nbfc/Linux/nbfc ?
Because when I browsed the content of the directory /Linux I did not find a file nor a directory called `nbfc`

Here are the file content:

ls -la nbfc/Linux/
total 24
drwxr-xr-x  3 user user 4096 Apr 19 07:47 .
drwxr-xr-x 11 user user 4096 Apr 19 07:47 ..
drwxr-xr-x  3 user user 4096 Apr 19 07:47 bin
-rw-r--r--  1 user user  250 Apr 19 07:46 nbfc.service
-rwxr-xr-x  1 user user  488 Apr 19 07:46 nbfcservice.sh
-rw-r--r--  1 user user  263 Apr 19 07:46 nbfc-sleep.service

I'm using the stable version of nbfc
I thought I write this issue to warn you guys or to correct me if I did anything wrong in the process.
It might confuse some of the other newbies too, so I think it's better be corrected if it was wrong.
Thank you for your efforts
Kind Regards.
Mohamad Ali

**Comment by mohamadali-halwani** [comment]
Also, since it is optional, when I skip step 4 in Linux section and get to this part where I apply the config and start the fan control
![image](https://user-images.githubusercontent.com/68155980/115191089-4297c980-a0e9-11eb-812b-414eb755e0bc.png)
Even though the files are not contained in /opt/nbfc but in /opt/nbfc/Release/
Every time I try to run mono nbfc.exe , I get `connection refused`
Any suggestions?

**Comment by mohamadali-halwani** [comment]
@erkexzcx  sorry for bothering you sir.
You seem to be the most active contributor to this project. Can you take a look on this issue?
Kind Regards,
Mohamad Ali

**Comment by mohamadali-halwani** [comment]
Here's the service status
![image](https://user-images.githubusercontent.com/68155980/115770210-b0274c80-a3ac-11eb-9539-8d5102e2b9ad.png)

**Comment by erkexzcx** [comment]
Hi. I am no longer using NBFC and I am no longer maintaining any AUR packages.

But I am the original creator of AUR packages `nbfc` and `nbfc-git`. For example, `nbfc` package here: https://aur.archlinux.org/packages/nbfc/

In [this URL](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nbfc) you can find literally step by step instructions how to build and install NBFC. Also in [this URL](https://wiki.archlinux.org/index.php/Fan_speed_control#NBFC) you can find how to use it.

**Comment by mohamadali-halwani** [comment]
Thanks for responding.
Downloading nbfc through aur did relief me from the issues I'm facing.


Edit:
Can you tell me who is still maintaining this project ? @erkexzcx

**Comment by mohamadali-halwani** [comment]
### The guide needs to be updated.
Install the package `nbfc` from the AUR then follow these steps after installation:

`sudo systemctl enable nbfc --now`
Then You can start using it by typing `nbfc` in the command line without the .exe like the guide says. If that did not work with you and the terminal showed: Command not found, you can add it to your path like this:
`export PATH=$PATH:/opt/nbfc` But I don't think you'll need to do this if you installed the package from the AUR

Next you can choose the most suitable config file. You can find the config files in `/opt/nbfc/Configs`
After you choose the suitable config file successfully, apply it : 

`nbfc config --apply "Config file name without extension" `
` nbfc start`
` nbfc status --all`

**Comment by mohamadali-halwani** [comment]
I also made my own config file and set the fans to work in the speeds I want on the heat thresholds that specified.
It's working fine now.
Thanks for your patience and for this great tool <3
