### ISSUE TITLE
Please add a config for Asus Vivobook X509JB 

### ISSUE THREAD

**Issue by Ege56813** [hirschmann/nbfc#1128]
Hello mate. Can you please add a config for Asus VivoBook X509JB? I tried another VivoBook config but it doesnt seems to work properly. Thanks for the application appecirate it. (Sorry for broken english mate.)

**Comment by Marcarrones** [comment]
Same problem for a X409JA, no other ASUS profiles work, goes from Read Only to Disabled and doesn't show temps.
Any resources to look into creating our own profile?
