### ISSUE TITLE
HP EliteBook Folio 1040 G3

### ISSUE THREAD

**Issue by ftribrunn** [hirschmann/nbfc#113]
sry, but I hav no idea how to configure the tool for my new notebook.

the profile for HP EliteBook Folio 9470m does not work

maybe anyone would help me? :-)

thx in advance

**Comment by sandreas** [comment]
You could try to create your own config file...

Take one of the more recent config-Files for HP Elitebooks (e.g. https://github.com/hirschmann/nbfc/blob/master/Configs/HP%20EliteBook%20Folio%209470m.xml), copy it to a new File named with your Notebook Model (e.g. "HP Elitebook Folio 1040 G3.xml") and try if it works... Perhaps you need to change some of the values in the xml file itself (this is an experimental thing) or perhaps switching the order (increase value for spin down and decrease for spin up of the fan).

Before you do that, you could try to use http://rweverything.com/ for experiments with the registers.

Caution: These experiments could damage your notebook, but it is very unlikely.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
