### ISSUE TITLE
Does Not Work for HP ENVY x360 15-ee0003ca, AMD Ryzen 7 4700U

### ISSUE THREAD

**Issue by Maghsad** [hirschmann/nbfc#1131]
**Describe the bug**
It shows the CPU temperature when the "HP ENVY x360 Convertible 15-cn0xxx" profile is selected. However, it cannot read the fan speed (it says a high negative number: -10603.7%) and cannot control the fan speed.

**To Reproduce**
Install the NoteBook Fan Control
Select "HP ENVY x360 Convertible 15-cn0xxx" profile 
Select Enabled

**Expected behavior**
Can read the current Fan Speed
Can Control the fan speed

**System information**
 - Windows 10 Version 2004 (Build 19041.928)

**Comment by Maghsad** [comment]
No support or even any answers after half of a month?

**Comment by geonom** [comment]
Hey there, open source means pushing devs is not an acceptable behaviour.

For your issue, I have the same notebook and just using a different profile - in my case "HP ENVY m6 1206dx" worked perfectly well.

Spoke to soon - after having changed the Thermal Profile in the HP command center, now I am stuck with 100% fan speed with the annotation critical ;)

There is something slightly buggy with how HP handles the fan speed - I had to switch to another HP model and back to the above and now it seems to work better for some unknown reason.
