### ISSUE TITLE
hp omen 15-ek1009tx

### ISSUE THREAD

**Issue by WhymustIhaveaname** [hirschmann/nbfc#1133]
This is the newest laptop of hp up to the year 2021. It has a 3070 GPU and so it is really NOISY.

I tried to follow the steps in [How to create a NBFC config](https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config) but unfortunately failed. I tried to extract the DSDT out but failed. I tried to observe the behavior of EC regs. I get some clue but not enough. I also read carefully [Problems creating HP OMEN 15-dc00xxxx config](https://github.com/hirschmann/nbfc/issues/749) but the registers he mentioned not work for me. 

I want its fan to work constantly at 30%, which is 1800rpm. I have known that __0xb7 is the temperature of GPU__. This laptop has a "Fan always active" in BIOS. If I set 0xb7 lower the 55 decimal, the fan will work at 50% if "Fan always active" and totally turn off if not "Fan always active".

I also worked out that __0x2e and 0x2f are the current speeds in percent__, which are read-only registers and take no effect if I change them.

**Comment by WhymustIhaveaname** [comment]
I used the utils in [marhop/fanslow-probook430g2](https://github.com/marhop/fanslow-probook430g2) to control EC registers explicitly.

**Comment by kalstn007** [comment]
I badly want this too. HP control program doesn't allow user to lower the rpm below 2900 which is annoying.

**Comment by WhymustIhaveaname** [comment]
> I badly want this too. HP control program doesn't allow user to lower the rpm below 2900 which is annoying.

I wrote one for my omen here [WhymustIhaveaname/fanslow-omen-2021](https://github.com/WhymustIhaveaname/fanslow-omen-2021). It can slow the speed of fans to 40% and 45%. Although not as slow as 30% I wanted, it is much quieter.

**Comment by grayexoc** [comment]
I am a user of en-100. I found that 0x34, 0x35 are the inputable fan rpm. Nbfc for windows does not work. I know it is a problem with the openhardwremonitor plugin.
