### ISSUE TITLE
Asus ROG G752VT Help :)

### ISSUE THREAD

**Issue by SexyNippleKiller** [hirschmann/nbfc#114]
Hi. Anyone that can help me make a config for this computer? If you can help me, then i'll buy you a beer :')

**Comment by giizbrellien** [comment]
Hello SexyNippleKiller , I have used Asus ROG G752VT :). You should choose "Asus Zenbook UX32LN" for your labtop.

**Comment by RypeDub420** [comment]
I've noticed for the ROG laptops, there are only a few possibilities for the EC registers.

Like @GiiZBrelliEN said: testing another config usually works.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
