### ISSUE TITLE
HP Pavilion Gaming - 15-dk0100nf profile

### ISSUE THREAD

**Issue by thib6622** [hirschmann/nbfc#1154]
hello, notebook fan control worked with the profile of an hp pavillion 14 but since a reinstallation of notebokk fan control, nothing can control my fans. i wish someone created a profile for it

**Comment by Buiston** [comment]
hi did you find way to control your fans?
 I've same laptop model and the same problem :/

**Comment by thib6622** [comment]
yes of course with notebook fan control, use the "HP ENVY m6 1206dx" profile

**Comment by thib6622** [comment]
> hi did you find way to control your fans? I've same laptop model and the same problem :/

yes of course with notebook fan control, use the "HP ENVY m6 1206dx" profile

**Comment by Buiston** [comment]
Oh thanks. I will try it. I tried many profiles but none works. The app start doing a enable to disable loop. Thx

**Comment by thib6622** [comment]
> Oh thanks. I will try it. I tried many profiles but none works. The app start doing a enable to disable loop. Thx

that is the profile i'm currently using, i edited some settings it works perfectly. https://1drv.ms/u/s!Akb_Qsp3CKQp7AyN9FyQ3mTk9gbr?e=mcMPKk
