### ISSUE TITLE
Config for HP Pavilion 15-ec1073dx dual fans

### ISSUE THREAD

**Issue by crkatz06** [hirschmann/nbfc#1158]
**Describe the bug**
Took me forever, but I found the HP Pavilion Gaming 15-ec10xxx.xml file in the issues thread here instead of in your repository...I didn't really understand why until I downloaded it and instead of it working or detecting both fans it just detects "CPU Fan" and just runs my fans wide open. Please if there is any information you require, or if you can walk me through how to create one, I need a config .xml for HP Pavilion 15-ec1073dx gaming laptop, it has dual fans. You can email me at crkatz19862@gmail.com if you prefer. Thanks in advance.

**System information**
 - Windows 10 20H2
 - NBFC version 1.6.3
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview))

**Additional context**

**Comment by Quarterblad** [comment]
Same, 15-ec10xxx config doesn't worcing on 15-ec1064ur

**Comment by don-dada2** [comment]
me three :) HP Pavilion Gaming Laptop 15-ec2xxx
it does have the same chip, SuperIO Chip=SCH5027D, seen through speedfan.
Also even with HWmonitor i cant get acces to those 2 Fans.
