### ISSUE TITLE
ec-probe.exe dump and RWEverything show all EC values in 00

### ISSUE THREAD

**Issue by JuanMiguelPR** [hirschmann/nbfc#1180]
Hi! I have been trying to create a config file for my Asus UX534FT, but have had trouble since the begining.

I opened my laptop and could not find the EC anywhere, looked for the models of the chips I saw, but none of them where the EC.
I proceeded then to try the DSDT editor, but got the error Could not parse ACPI tables, AE_ALREADY_EXISTS.

With RWEverything I'm able to get the DSDT, but then comes the strange part for me: When I run ec-probe.exe dump or use RWEverything to see the EC values, all result in 00 and when trying to use the monitor feature of ec-probe I don't recieve any result and I'm also not able to save a report text file.

Resulting in being unable to get any clues of the registers controlling the fans speeds, even though I have a way of making them spin by loading the cpu of gpu.

Any help or idea of what can be wrong?

Thanks!

**Comment by cRoCx** [comment]
I encounter the same problem with my Asus ZenBook Duo 14 UX482.
This issue is a duplicate of #1034 btw.

**Comment by cRoCx** [comment]
Similar issues occur also in the NBFC Revive project (https://github.com/UraniumDonut/nbfc-revive/) here: https://github.com/UraniumDonut/nbfc-revive/issues/72 and here https://github.com/UraniumDonut/nbfc-revive/issues/46 .
