### ISSUE TITLE
Asus ROG GL752VW-T4016T

### ISSUE THREAD

**Issue by qwer77** [hirschmann/nbfc#119]
Hi. I don't see this (or any GL752VW model) in the config list. Anyone knows if one of the existing config would work for it? Or if it was made where I can find it?

**Comment by RypeDub420** [comment]
For any brand of computer, if there is a config for a similar model (and there are a few ROG configs) usually one or more of them will work for your laptop.

I have the G75VX and the G750J worked for me. Try testing other profiles.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
