### ISSUE TITLE
Config for Lenovo Ideapad Slim 3i

### ISSUE THREAD

**Issue by Str4u55** [hirschmann/nbfc#1194]
Can someone please add fan config for Ideapad Slim 3i? will be much appreciated.

**Comment by dumprop** [comment]
Check out my config for Lenovo Yoga Slim7 https://github.com/UraniumDonut/nbfc-revive/pull/59
But I'm not sure that it compatible with Lenovo Ideapad Slim 3i
It's impossible create config without probing

**Comment by Str4u55** [comment]
> Check out my config for Lenovo Yoga Slim7 [UraniumDonut#59](https://github.com/UraniumDonut/nbfc-revive/pull/59) But I'm not sure that it compatible with Lenovo Ideapad Slim 3i It's impossible create config without probing

Thank you very much for your reply. greatly appreciate it.
I've tried your config, but yet nbfc still unable to read the fan EC.
I know that you need probing first before creating the config, but i don't understand the instructions. If only there's someone who wants to create the tutorials in YouTube, maybe i can follow it.
But once again, thank you for your response..

**Comment by dumprop** [comment]
> > Check out my config for Lenovo Yoga Slim7 [UraniumDonut#59](https://github.com/UraniumDonut/nbfc-revive/pull/59) But I'm not sure that it compatible with Lenovo Ideapad Slim 3i It's impossible create config without probing
> 
> 
> 
> Thank you very much for your reply. greatly appreciate it.
> 
> I've tried your config, but yet nbfc still unable to read the fan EC.
> 
> I know that you need probing first before creating the config, but i don't understand the instructions. If only there's someone who wants to create the tutorials in YouTube, maybe i can follow it.
> 
> But once again, thank you for your response..

I prefer that way: dump register with disabled fan, enabled slow speed and enabled high speed 
For these purposes I use any benchmark tool (geek bench), it loads cpu (fan) very fast
And then diff them
Also you can try to provide these files for possible config generation (personally I created with one attempt, but I had near 10 samples of various states)
