### ISSUE TITLE
Support for IT8987E

### ISSUE THREAD

**Issue by LukasAV** [hirschmann/nbfc#1198]
**Is your feature request related to a problem? Please describe.**
Hi,
I am trying to control my fans on an Acer Swift 3 acer swift SF314-51.
It has an IT8987E chip. I got the relevant parts of the documentation from the ITE support:

![it9897E-1](https://user-images.githubusercontent.com/41890101/140660320-0916b4d5-889c-405c-a8fd-cd3f9a001f50.png)

![it9897E-2](https://user-images.githubusercontent.com/41890101/140660326-cdce47f2-a679-4e81-ab36-b59c183b0565.png)

They would not give me the full documenation, but I suspect it is identical to the one from [this lm-sensors issue](https://github.com/lm-sensors/lm-sensors/issues/320), [see PDF](https://github.com/lm-sensors/lm-sensors/files/6190220/IT8987_B_V0.3.1_102513.pdf).

Unfortunately all four mentioned registers 1E, 1F, 20 and 21 are always shown as 00 in ec-probe, although the fans are definitely spinning. I also could not connect the behaviour of any other registers to the fans.

Am I reading the documentation wrong? What was not quite clear to me was the mentined base address 1800. How do I set that in ec-probe? Or is this the default?
Would appreciate any help.

**Comment by yoshirinda** [comment]
> **Is your feature request related to a problem? Please describe.您的功能请求是否与问题有关？请描述。** Hi, 你好、 I am trying to control my fans on an Acer Swift 3 acer swift SF314-51.我正试图控制 Acer Swift 3 acer swift SF314-51 上的风扇。 It has an IT8987E chip. I got the relevant parts of the documentation from the ITE support: 它有一个 IT8987E 芯片。我从 ITE 支持中心获得了相关部分的文档：
>
> ![it9897E-1](https://user-images.githubusercontent.com/41890101/140660320-0916b4d5-889c-405c-a8fd-cd3f9a001f50.png)
>
> ![it9897E-2](https://user-images.githubusercontent.com/41890101/140660326-cdce47f2-a679-4e81-ab36-b59c183b0565.png)
>
> They would not give me the full documenation, but I suspect it is identical to the one from [this lm-sensors issue](https://github.com/lm-sensors/lm-sensors/issues/320), [see PDF](https://github.com/lm-sensors/lm-sensors/files/6190220/IT8987_B_V0.3.1_102513.pdf).他们没有给我完整的文档，但我怀疑它与这个 lm-sensors 问题中的文档相同，请参见 PDF。
>
> Unfortunately all four mentioned registers 1E, 1F, 20 and 21 are always shown as 00 in ec-probe, although the fans are definitely spinning. I also could not connect the behaviour of any other registers to the fans.遗憾的是，虽然风扇确实在转动，但所有四个寄存器 1E、1F、20 和 21 在 ec-probe 中始终显示为 00。我也无法将其他寄存器的行为与风扇联系起来。
>
> Am I reading the documentation wrong? What was not quite clear to me was the mentined base address 1800. How do I set that in ec-probe? Or is this the default?难道是我看错了文档？我不太清楚的是所提到的基地址 1800。如何在 ec-probe 中设置？还是默认设置？ Would appreciate any help. 希望得到帮助。

你解决这个问题了吗，我的hp pavilion14 ce0xxx也是同样的芯片，我想手动控制风扇
