### ISSUE TITLE
Config for Acer Nitro 5 AN515-51?

### ISSUE THREAD

**Issue by ZeraX7** [hirschmann/nbfc#1199]
Here's the tech info
https://www.acer.com/ac/en/IN/content/model/NH.Q2QSI.002

thanks for the hard work

**Comment by ghost** [comment]
On my AN515-52 the Acer Predator G3-572 setting works fine in Linux but I can't get it to start in Windows 10 21H1.

**Comment by itsmeshibintmz** [comment]
https://www.acer.com/ac/en/IN/content/model/NH.Q2QSI.002

the link is not working.
