### ISSUE TITLE
HP Pavilion Gaming Laptop 15-dk0xxx

### ISSUE THREAD

**Issue by Munjalnyk** [hirschmann/nbfc#1202]
please make fan profile for this laptop

**Comment by revelino01** [comment]
i've been using the HP Compaq 15-s103tx config just fine, but the fan speeds are a little bit wonky

**Comment by GZuki8** [comment]
Just use HP Notebook 15-ba010ng, or try this command in cmd.exe: _nbfc.exe config --recommend_ some of them should work fine

i have a hp pavilion gaming 15 dk1043la and its work fine with that config, check nbfc revive

**Comment by Wildchild420187** [comment]
Has anyone made a config for this particular laptop? I have the dk0056nr I have a config that, well works, but I cannot figure out how to get the fans to be able to be controlled individually. If anyone has a 2 fan config for this laptop that at least works, i can tweak it from there

**Comment by XoltgamingonYT** [comment]
> Just use HP Notebook 15-ba010ng, or try this command in cmd.exe: _nbfc.exe config --recommend_ some of them should work fine
> 
> i have a hp pavilion gaming 15 dk1043la and its work fine with that config, check nbfc revive

could you drop ur discord and send me the config profile you use for your laptop?

**Comment by GZuki8** [comment]
here is the link: https://drive.google.com/file/d/102g88mrE7DVo6FtNAUGFoSvlB4RMh4Af/view?usp=sharing

**Comment by GZuki8** [comment]
> > Just use HP Notebook 15-ba010ng, or try this command in cmd.exe: _nbfc.exe config --recommend_ some of them should work fine
> > i have a hp pavilion gaming 15 dk1043la and its work fine with that config, check nbfc revive
> 
> could you drop ur discord and send me the config profile you use for your laptop?

here: https://drive.google.com/file/d/102g88mrE7DVo6FtNAUGFoSvlB4RMh4Af/view?usp=sharing
