### ISSUE TITLE
[Success report] Config for HP Spectre x360 Convertible 15-ch0xx also works on HP Laptop 14s-fq1xxxur

### ISSUE THREAD

**Issue by nouveau-nvc0** [hirschmann/nbfc#1206]
I tested it on HP Laptop 14s-fq1002ur (Ryzen 7 5700U) on Windows 10 LTSC 2021. NBFC can correctly set fan percentage and monitor temperature.

**Comment by galaxyrun** [comment]
[Success report] HP ENVY x360 Convertible 13-ag0xxx profile also works with HP Pavilion x360 Convertible 14-cd0xxx
