### ISSUE TITLE
Stuck at a certain speed after windows startup

### ISSUE THREAD

**Issue by HoreaM** [hirschmann/nbfc#122]
So the problem is as follows:
I close the nbfc with the fan speed set on auto but sometimes (not always, I have no idea why) when I open it back the fan speed is set on 12.5%. Any idea on how to clear the cache of the program and reinstall it from scratch? I guess that will fix the issue.

**Comment by hirschmann** [comment]
This is a bug which has already been fixed. There is no release yet which includes the bug fix, but you can build NBFC yourself from the latest source: [How to build NBFC](https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC)

If you want to reset the NBFC service settings follow these steps:
1. Open the Windows services control panel (services.msc)
2. Stop _NbfcService_
3. Delete `C:\ProgramData\NbfcService\NbfcServiceSettings.xml`
4. Start _NbfcService_

**Comment by HoreaM** [comment]
So just building it and running the new version should fix this? And thanks a lot for the quick reply.

**Comment by hirschmann** [comment]
You have to uninstall the release build before installing your custom build, because I can't ensure that the setup is able to upgrade from release to any custom build.

**Comment by HoreaM** [comment]
Thanks a lot, it's fixed now.
