### ISSUE TITLE
there isnt exactly a selection for an hp pavilion 15 gaming laptop but apparently hp compaq 15-s103tx worked for these i have an i5 10th gen and when i try to use it it lists my cpu temperature as 0, the, it keeps switching from read only to disabled by itself, it lists target fan speed as auto, and cpu fan at 0 i have windows 11 and 1.6.3 and from a video of someone with a similar laptop (i5 and such) and he could control and use it perfectly i was just wondering if there was any way to fix this as this laptop has some serious heat issues and even with a cooler and a 140mm desktop case fan chilling on top the cpu will spike to 98 degrees Celsius any help would be appreciated and thank you 

### ISSUE THREAD

**Issue by Smeazyspaz** [hirschmann/nbfc#1224]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**System information**
 - operating system
 - NBFC version
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview))

**Additional context**

**Comment by laughingwater** [comment]
I don't know if this will help or not, but do what this comment says, worked for me. https://github.com/UraniumDonut/nbfc-revive/issues/27#issuecomment-967684864
