### ISSUE TITLE
Support For HP 255 G7 ( AMD RYZEN 5 2500u )

### ISSUE THREAD

**Issue by HuzefaZafar** [hirschmann/nbfc#1226]

**Comment by harceh** [comment]
I would really be glad, if there were support for the HP255 G7 (AMD RYZEN 3 2200U).

**Comment by chimcen** [comment]
This would be awesome - because i'm searching for a HP255 G8 (Ryzen 3 5300U) wich probably will be the same...

**Comment by tankcom** [comment]
> This would be awesome - because i'm searching for a HP255 G8 (Ryzen 3 5300U) wich probably will be the same...

I made one for HP 255G8 with Ryzen 7 5700U    #1256
