### ISSUE TITLE
Hp omen 15 2020 Support 

### ISSUE THREAD

**Issue by mtalhazulf** [hirschmann/nbfc#1227]
I have an XML file that works Perfectly fine for HP Omen 15  2020 - en Series. The File isn't included yet here.
@hirschmann  
[HP_OMEN_Laptop_15-en0xxx.zip](https://github.com/hirschmann/nbfc/files/8190418/HP_OMEN_Laptop_15-en0xxx.zip)

**Comment by hockeymikey** [comment]
I don't know, that xml seems very aggressive. My computer is always at 100% fan speed, while the system default is much much less

**Comment by mtalhazulf** [comment]
Yes Notebookfan control with custom Controls and It works

**Comment by hockeymikey** [comment]
What? Yes, it works but it's too aggressive like I said

**Comment by mtalhazulf** [comment]
Bro you can custom set the temperatures depending upon your use and region. I have set it to Pakistan Region as it's very hot you can edit the configuration

**Comment by hockeymikey** [comment]
@AGOT-00 Region doesn't change anything, your profile should be set to a good amount so it's cooling as much as it should depending on the temp which doesn't matter depending where you are. The fact is your profile is too aggressive.

**Comment by mtalhazulf** [comment]
> @AGOT-00 Region doesn't change anything, your profile should be set to a good amount so it's cooling as much as it should depending on the temp which doesn't matter depending where you are. The fact is your profile is too aggressive. 

It seems to keep my omen's temp around 45-52 C so its good for me😃

**Comment by hockeymikey** [comment]
@AGOT-00 Your omen would be kept cool at default settings too. The fact is you're running it too aggressive and if you like a jumbo jet in your room while you are sleeping, go for it. Most people do not.
