### ISSUE TITLE
Need Newbie help on EXACTLY how to install .xml config

### ISSUE THREAD

**Issue by FYPH2016** [hirschmann/nbfc#123]
Greetings,

I downloaded this fantastic app a year ago and got things running.  The download did NOT include a config for my Asus K501LX but I was able to use another.  

That unit had to be sent in/replaced and I'm starting all over again.  Now when I install NFC that config is missing.  However I see my K501LX is now available!  

But I have NO IDEA how to install it.  I was hoping if I download the .xml and clicked IMPORT in settings it would import.  No go.

Can someone please explain how I import it?  Or explain what I've done wrong?  

THANK YOU

**Comment by hirschmann** [comment]
Just copy the config into the NBFC configs folder.
By default, on Windows this is: `C:\Program Files (x86)\NoteBook FanControl\Configs\`

**Comment by FYPH2016** [comment]
I dragged the .xml file into the correct folder.  It was then listed in NFC.  I go to select it and I'm told "CONFIG EDITOR STOPPED WORKING".

**Comment by FYPH2016** [comment]
Update -- it will switch to other settings included with download.  Perhaps K501LX .xml is broken?

**Comment by hirschmann** [comment]
If NBFC can't load the config, it is certainly in some way corrupted.
I tried to edit the Asus [K501LX config](https://github.com/hirschmann/nbfc/blob/master/Configs/Asus%20K501LX.xml) in the config editor and it worked flawlessly.

Have you downloaded the config from this repository or somewhere else?

**Comment by FYPH2016** [comment]
I downloaded from the link on this page --

https://github.com/hirschmann/nbfc/tree/master/Configs

The result was a .xml file on the desktop

**Comment by FYPH2016** [comment]
By the way, I said earlier that a recommended setting for my unit was missing now -- despite downloading this a year later.  It turns out the setting is there -- the Asus Zenbook UX32LN.  I overlooked it because it says 'Zenbook' whereas this 15 incher is a Vivobook (or whatever).
