### ISSUE TITLE
How to choose temperature source?

### ISSUE THREAD

**Issue by Quarterblad** [hirschmann/nbfc#1238]
I have HP ec1064 with AMD 4800H.

By default all apps including NBFC read CPU temperature from this sensor (CPU Tctl/Tdie №1):
![image](https://user-images.githubusercontent.com/26858463/161400014-2aec0c74-704c-4203-93f5-50cf52c2cb3f.png)
as you can see it very astatic and generally in fact is predictive from the CPU (have high differentiate coef.) 
But we have CPU Core sensor which looks more realistic (2 left on top):
![image](https://user-images.githubusercontent.com/26858463/161400256-fb5adfd3-79fa-423d-8b22-54e312cbfd29.png)

On practice fluctuations on default CPU temperature sensors (CPU Tctl/Tdie №1) causes the fan to operate or speed up for a short period of time, what annoys.

How i can change temperature source sensor in NBFC?

**Comment by unknown10777** [comment]
Please. Take a look at Config settings and close your issue.
