### ISSUE TITLE
Asus rog g750jh

### ISSUE THREAD

**Issue by agemennon675** [hirschmann/nbfc#124]
I just take back my laptop back from the service, but my cpu fan seems to adjusted max in any usage i cant control my fans or power settings with bios i need your help

**Comment by javierdlg** [comment]
Have you tried using the Asus ROG G751JY config?

**Comment by agemennon675** [comment]
No I didnt, do you think that would work ?

**Comment by javierdlg** [comment]
You can try with that config file. If that one doesn't work then you can also try using the "Asus Zenbook UX32LN" as stated [here](https://github.com/hirschmann/nbfc/issues/114) to work with the new G752 laptops

**Comment by agemennon675** [comment]
I will try them both :) thank you very much!

**Comment by javierdlg** [comment]
Let me know how it goes, and remember to close the issue if it gets fixed!
