### ISSUE TITLE
Hp Pavilion 15 ec2xxxx

### ISSUE THREAD

**Issue by yaralicecegen** [hirschmann/nbfc#1240]
Hello i couldnt find config for this and many user have same problem also if anyone can help i can write super io chip

**Comment by mangler66** [comment]
I am also looking for a working configuration for this laptop. Super I/O Chip is SCH5027D.

**Comment by EmanDev** [comment]
I am also looking for a working config

**Comment by ewaldc** [comment]
I have a Pavilion 15-cs0xxx.  Attached is the config I created using the ec-probe tool.  The explanation on how to do it yourself is excellent, but not without risk.   The config is not perfect:

- the temperature reported by nbfc is on the high side (higher than the highest core temperature, CPU Tdie perhaps) compared to e.g. coreTemp or speedfan.  On the other hand, this is a very safe value to use and you can compensate for it in the threshold table.
- the fan speed scale is not linear (e.g. 2800 RPM is the starting speed and ~6000 is the max), hence the % fan speed is not accurate.

[HP Pavilion Laptop 15-cs0xxx.zip](https://github.com/hirschmann/nbfc/files/8935551/HP.Pavilion.Laptop.15-cs0xxx.zip)

Put it in read mode first, and observe whether the values seem correct.
