### ISSUE TITLE
Acer Aspire VN7-572G

### ISSUE THREAD

**Issue by mysticusa** [hirschmann/nbfc#125]
Hi,

could you create a config file for the Acer Aspire VN7-572G.
It's working nicely choosing the "591 V15", but i think it could be better.
And thank you so much for making that wonderful piece of software!

Best regards,

mysticusa

**Comment by hirschmann** [comment]
Hi,
thank you for your compatibility report 👍 

If it works nicely, then there is nothing to fix.
Nevertheless, I've added a Acer Aspire VN7-572G config for discoverability: 88cd09575fbc5a137cd148bfabc59521256f4d18
