### ISSUE TITLE
nothing is shown when i click at "select a config" 

### ISSUE THREAD

**Issue by badertah** [hirschmann/nbfc#1254]
nothing is shown when i click at "select a config" , its empty and i tried to reinstall it  alot of times and still not working
the picture below describes everything
![Screenshot_1](https://user-images.githubusercontent.com/76018181/167266965-85e876fa-5933-418b-a778-2aea10755ffd.png)
g

**Comment by badertah** [comment]
i am using a lite type of windows 10 pro called "atlas os" so maybe something is not enabled cuz before i switch to this windows everything was ok

**Comment by eldonburr** [comment]
I just updated Win10 and have the same problem. The update broke it. Roll back the update I guess, until it's resolved.
