### ISSUE TITLE
ASUS ROG GL552JX

### ISSUE THREAD

**Issue by rafael1998ma** [hirschmann/nbfc#1255]
![image_2022-05-12_144521034](https://user-images.githubusercontent.com/36709588/168067606-28296108-e758-4c7c-9db5-430a35c70947.png)
I'm using this configuration and it seems to work, but when I select "Enabled" on the "Fan control service status" my CPU underclocks a lot. I want to keep my fan at full throttle because I encounter heat problems within this machine, but as mentioned before the CPU underclocks and things start to work poorly. It's like when the fan is 100% power, the machine thinks temps are very high and CPU has to go chill and relax

Anybody can help?

Thanks you!

**Comment by Zireael61** [comment]
I have same problem with a different notebook, I am trying to create my own config. There is a value for my laptop which is a like threshold. I can increase my fan speed to this threshold without any underclock penalty but after that it starts to underclock cpu.

I suggest you to try to find a similar threshold for your notebook by trying all values. You can increase your fan speed to these value even if it is not 100% speed.

**Comment by rafael1998ma** [comment]
My fan goes way too slow for actually cooling especially when gaming. At full throttle my cpu just underclocks and nothing is playable. I've tried playing with the numbers in the config but nothing fits. My fan has like 4 modes i would say: chill, a tiny bit faster, a bit faster and full turbo mode.

**Comment by deulizealand** [comment]
any update about this ? did you find how to solve it ?

**Comment by rafael1998ma** [comment]
No

**Comment by deulizealand** [comment]
you still using it ? or any recommendation ?
