### ISSUE TITLE
Update to support 10th gen cpus?

### ISSUE THREAD

**Issue by TiagoRibeiro25** [hirschmann/nbfc#1258]
From what I saw , this app only supports up to 9th gen intel cpu and not above. Is it possible an update to support 10th cpus? (Comet Lake).

**Comment by cRoCx** [comment]
You might have noticed, that the author @hirschmann isn't updating this software since >2 years. You might want to try posting your issue in a fork by another person here: https://github.com/UraniumDonut/nbfc-revive/

**Comment by TiagoRibeiro25** [comment]
> You might have noticed, that the author @hirschmann isn't updating this software since >2 years. You might want to try posting your issue in a fork by another person here: https://github.com/UraniumDonut/nbfc-revive/

Thanks a lot, it's working
