### ISSUE TITLE
Software "Blinking" Controls appears and disapears.

### ISSUE THREAD

**Issue by LALAMUSIC** [hirschmann/nbfc#1260]
Hello,

The software is kind of blinking alone in WIN 10.

The controls appear and disapear and it's not possible to control the FANs.

WIN VER: 10.0.19044 
Hardware: HP ZBook Fury 15 G7 Mobile Workstation

![image](https://user-images.githubusercontent.com/63554857/170211146-ae7fc32f-5be6-424e-9da0-e703bdd39f38.png)

No button is pressed between these two images

![image](https://user-images.githubusercontent.com/63554857/170211302-07e3f702-eb35-462a-abc6-7e49ae82dbaf.png)

Thanks for your support

**Comment by TorkelE** [comment]
Hello,
I have exactly the same problem. It is on windows 10, and it is on a Hp Omen 15 laptop. Happy to provide more details.

**Comment by TorkelE** [comment]
For reference,
this: https://github.com/hirschmann/nbfc/issues/1143
and this: https://www.youtube.com/watch?v=OJXzBzPKm6o&ab_channel=ERENBULUT
both seems like reports of the same issue.
