### ISSUE TITLE
Issues with adding Asus ROG STRIX GL703GM

### ISSUE THREAD

**Issue by Universal13** [hirschmann/nbfc#1261]
First I'm no programmer of any kind but I love to tune my PCs for optimal performance.
After undervolting the CPU and Overclocking the GPU I want to set a more aggressive Fan tune or at least manually controll them.

But when I tried to use ec-probe or RWEverything I get a blank console screen or in the case of RW 0's all across.
So I cant get the needed values. So I opened some old files of my BIOS extract when I undervolted my CPU.
There I saw that for CPU Fan Speed it gives 0x39D (0x41 as 8 bit). But when I try to input the number I still get no reaction from my fans.

So I ask someone to add the model or help me do it. 

Thanks in advance!

**Comment by adrianevansas** [comment]
> 

hi. i have i7-11800h tuf17 (fx706heb)
we can cooperate
i'm also tryig to resolve my issues with temp.

**Comment by Universal13** [comment]
I sold the Asus a long time ago and got a legion 5 pro. Dont have problems now even with the stock fan curve.
