### ISSUE TITLE
Dell Inc. Dell G15 5510

### ISSUE THREAD

**Issue by mario6714** [hirschmann/nbfc#1264]
I tried use "nbfc.exe config --recommend" but none work, can help me to create a config for my model?

**Comment by babyNEKO** [comment]
厂商配套的AWCC应该可以满足需求了。

**Comment by SiddharthManthan** [comment]
Alternative to Alienware : https://github.com/T-Troll/alienfx-tools

Is there a way to integrate it to Notebook Fan Control ?

**Comment by mario6714** [comment]
I tried https://github.com/T-Troll/alienfx-tools and my antivirus say is a Trojan and crash my explorer and nothing work after tried to use, dont install that thing, i forze to shutdown my pc and the first thing to do is uninstall that thing.

**Comment by SiddharthManthan** [comment]
> I tried https://github.com/T-Troll/alienfx-tools and my antivirus say is a Trojan and crash my explorer and nothing work after tried to use, dont install that thing, i forze to shutdown my pc and the first thing to do is uninstall that thing.

It is false detection. Plus it modifies some kernel drivers so it is natural for the antivirus for marking it as Torjan. The source code is freely available for inspection. I am using it and it works perfectly. Join the discord server if you face any issues.

**Comment by mario6714** [comment]
The problem or scare thing is after that nothing work on my pc, i cant open folders, apps, nothing just after force to shutdown my pc

**Comment by mario6714** [comment]
And compared to the official Alienware Command center is better the alternative?

**Comment by mario6714** [comment]
And yes, i think like you say, "false positive" but i don't know why after i tried to use the alternative nothing work on my pc

**Comment by mario6714** [comment]
One question, i need to uninstall the official Alienware Command Center?

**Comment by SiddharthManthan** [comment]
> The problem or scare thing is after that nothing work on my pc, i cant open folders, apps, nothing just after force to shutdown my pc

I do not why this happens. It did not happen with me.

> And compared to the official Alienware Command center is better the alternative?

The issue with official Alienware Command center was that it did not apply the fan curve properly. 

> And yes, i think like you say, "false positive" but i don't know why after i tried to use the alternative nothing work on my pc

It might be some other issue. That application works fine for a lot of people.

> One question, i need to uninstall the official Alienware Command Center?

No, but it is better to uninstall it as Alienware Command Center might override the settings set by AlienFan.

You might also want to join AlienFx discord server for further help.
https://discord.gg/XU6UJbN9J5

**Comment by babyNEKO** [comment]
你可以试试这个方法：提前准备好AWCC所有的驱动程序。然后把电脑断网，卸载AWCC 。断网安装刚才下载的驱动。

**Comment by aimixsaka** [comment]
whatif i'm using linux (arch ?
