### ISSUE TITLE
Request for a config for Asus Zenbook Pro 15 UX535L

### ISSUE THREAD

**Issue by LeonRiveraXR** [hirschmann/nbfc#1267]
It would be great if anyone can make a NBFC for the Asus Zenbook Pro 15 UX535L , It runs hots often even in idle and when working it runs upto about 70'C and the fans are not having efficient rpm to cooldown 
The Asus Zenbook Pro 15 UX535L has a dual fan system
For any Spec inquiries pls contact me

*this is a brand new pc
Thank you

**Comment by aspizu** [comment]
bruh
