### ISSUE TITLE
Config for Asus TUF gaming F15

### ISSUE THREAD

**Issue by MisterGalletoide** [hirschmann/nbfc#1269]
New asus TUF gaming F15 is really hot, gaming into 90-95º

Would be good if someone have a config for this laptop, i don't like when just turn on a game and CPU goes more than 85º, and the thing is that the laptop is just new...

Thknsss everyone!!

**Comment by adrianevansas** [comment]
> New asus TUF gaming F15 is really hot, gaming into 90-95º
> 
> Would be good if someone have a config for this laptop, i don't like when just turn on a game and CPU goes more than 85º, and the thing is that the laptop is just new...
> 
> Thknsss everyone!!

have the same issue... trying to find registers... but i cannot(((
