### ISSUE TITLE
Uninstallation not possible on Windows.

### ISSUE THREAD

**Issue by ghost** [hirschmann/nbfc#1284]
**Describe the bug**
Uninstallation stuck forever, nothing solves the issue.

**To Reproduce**
1. Install nbfc
2. Uninstall nbfc

**Expected behavior**
It will never let you uninstall properly. Sometimes it works, most of the time not.

**System information**
 - Windows 10
 - NBFC 1.6.3

**Additional context**

**Comment by ArouayAb** [comment]
As a workaround I found that removing all traces from registery resolve the problem.
- Open Regedit.
- Search for notebook.
- Delete everything related to NotebookFanControl.
- Rerun the uninstall.

**Comment by ghost** [comment]
Yes, I know the workaround, but the issue is weird and irritating.

**Comment by ArouayAb** [comment]
Agreed

**Comment by ArouayAb** [comment]
On a side note It appears there is a fork which appears actively maintained, check the issue https://github.com/hirschmann/nbfc/issues/1259#issue-1244247159
I tested it and it seems like this is issue is fixed.

**Comment by ghost** [comment]
> 

Thank you so much for the fork.
