### ISSUE TITLE
support for hp elitebook 840 g1

### ISSUE THREAD

**Issue by YoshiBoi64** [hirschmann/nbfc#1289]
is there is a way to add supoort for hp elitebook 840 g1

**Comment by kocane** [comment]
Don't know if this is still relevant for you but I made something exactly for an Elitebook 840 G1 years ago.

I don't have that computer any more so I can't help.

[HP EliteBook 840 G1.txt](https://github.com/hirschmann/nbfc/files/11405259/HP.EliteBook.840.G1.txt)
