### ISSUE TITLE
gl702vm 3rd fan

### ISSUE THREAD

**Issue by vladpm** [hirschmann/nbfc#129]
Dear @hirschmann 
I have purchased new gl702vm and it goes really freaking hot.
I'm using available ROG profile's that you have in latest commit and it seems that this is working.
But I have 1 question:
This laptop have 3rd cooler: http://screencloud.net/v/h5JF
How using existing ROG profile will affect this cooler? How can I enable fan control for it?

**Comment by hirschmann** [comment]
Hard to tell from an screenshot, but I would guess the already existing configs will
a) not affect the 3rd fan at all
b) maybe affect the 3rd fan if it is somehow linked to one of the other two fans

In case of a), you could try to add a 3rd [FanConfiguration](https://github.com/hirschmann/nbfc/wiki/Fan-configuration) to one of the existing ROG configs.
Wild guess: the r/w register for the 3rd fan could be at 153.

**Comment by vladpm** [comment]
@hirschmann thanks a lot for your feedback!
Can you please suggest some user-friendly way to identify specific r/w for this 3rd fan? 
I will really appreciate that.

**Comment by hirschmann** [comment]
Unfortunately, there is no user-friendly way.
Have a look at the NBFC manual: https://onedrive.live.com/?id=6C34BD33AC55CE36%21450&cid=6C34BD33AC55CE36
It is outdated, but will hopefully give you an idea of what you have to search for.

I'm currently working on an updated "How to create a NBFC config" article. I will publish it in the NBFC wiki, once it's done.

**Comment by vladpm** [comment]
@hirschmann Thanks
It seems that 151 for cpu and 152 for gpu is working on my laptop, but I hear very strange accelerate/decelarate of one cooler (pobably first one). I hear that this cooler start to spin and then stop. It's happening very fast.

Sounds concerning. It's going away when I turning off service.
Do you have ideas?

**Comment by hirschmann** [comment]
Have you tried adding a 3rd FanConfiguration?

**Comment by vladpm** [comment]
@hirschmann only gpu and cpu
creating r/w with 153 do not provide any effect.

**Comment by Johnny008** [comment]
Hello,

Attached a profile with the 3rd Fan.
To avoid the start/stop the 3rd Fan at lower temperatures it kicks in at 60 degrees, this fan is to help out cooling the GPU.
I get maximum 85 degrees in games now no annoying sounds, PERFECT!
Thank you hirschmann for the app!

[Asus ROG GL702VM.zip](https://github.com/hirschmann/nbfc/files/762964/Asus.ROG.GL702VM.zip)

**Comment by hirschmann** [comment]
Thank you very much!
I've added your config with this commit: 5beee4cfe3e4034911d415805c654868d306b8bf
