### ISSUE TITLE
EC poll interval less than 1000ms doesn't work.

### ISSUE THREAD

**Issue by prykpryk** [hirschmann/nbfc#130]
I tried setting EC poll interval to 500ms and less and it still seems to refresh CPU temp and fan speeds at a slow 1000ms rate.

I tested EC values with RWEverything and they refresh much faster than 1Hz so it's not EC fault. Also CPU temp tested with HWiNFO refresher more often.

**Comment by hirschmann** [comment]
There are several reasons why the updated poll intervall isn't being applied (or looks like it isn't being applied):
- you have saved your changes to the config, but have not applied the updated config
- NBFC tries to filter out short temperature spikes, which might look like the temperature lags behind, compared to other monitoring tools
- the GUI gets updated only once every 3 seconds
