### ISSUE TITLE
Add Lenovo ThinkBook Plus G3 21EL

### ISSUE THREAD

**Issue by FatTonyKS** [hirschmann/nbfc#1308]
Hello everyone!

I would like to build a configuration for the following notebook:

Lenovo ThinkBook Plus G3 21EL
EC: ITE IT5571

Unfortunately I can't find a datasheet of the EC and would appreciate any help.

**Comment by FatTonyKS** [comment]
At least I have now managed to read out the DSDT:
[https://www.dropbox.com/s/1vfdr7rqpkvbzoi/DSDT.txt](url)

Has anyone of you perhaps already worked with this EC and can tell me what registers to look for?

**Comment by xz-dev** [comment]
> At least I have now managed to read out the DSDT: [https://www.dropbox.com/s/1vfdr7rqpkvbzoi/DSDT.txt](url)
> 
> Has anyone of you perhaps already worked with this EC and can tell me what registers to look for?

This item was deleted

**Comment by FatTonyKS** [comment]
Thanks for the answer! I have restored the file, so it should be downloadable again now.

**Comment by xz-dev** [comment]
For backup [DSDT.txt](https://github.com/hirschmann/nbfc/files/10098296/DSDT.txt)

**Comment by ntzb** [comment]
@FatTonyKS did you find any solution?

**Comment by FatTonyKS** [comment]
> @FatTonyKS did you find any solution?

No, and I don't own the notebook anymore.
