### ISSUE TITLE
Please add support for asus fa506iv

### ISSUE THREAD

**Issue by NightShadow1910** [hirschmann/nbfc#1323]
Had overheating problems with this laptop for a while and maybe this would help. Don't know if other model's config would help.

**Comment by adrianevansas** [comment]
i applied liquid metal. now its much better. but i would also like to resolve it. we can cooperate

**Comment by adrianevansas** [comment]
> NightShadow1910

please read 1 message upper

**Comment by NightShadow1910** [comment]
> i applied liquid metal. now its much better. but i would also like to resolve it. we can cooperate

I tried changing the thermal paste, but it didn't do much difference.

**Comment by NightShadow1910** [comment]
> i applied liquid metal. now its much better. but i would also like to resolve it. we can cooperate

I tried changing the thermal paste and pads, but it didn't do much of a difference. Any other suggestions?
