### ISSUE TITLE
NbfcService keeps restarting

### ISSUE THREAD

**Issue by TylerWDoesStuff** [hirschmann/nbfc#1326]
**Describe the bug**
NbfcService kept being restarted by Service Control Manager, making it near impossible to uninstall

**To Reproduce**
Not entirely sure, but I kept selecting incompatible configs until it crashed (since my laptop doesn't have a config) a few weeks ago repeatedly, might be the issue

**Expected behavior**
The process to not be constantly restarted in the background, and for me to be able to easily uninstall NBFC.

**System information**
 Windows 11 22H2 Build 22621.1105
 - NBFC 1.6.3
 - already uninstalled it before submitting a bug report, so directory doesn't exist
 
**Additional context**
If it helps, here's a snippet of the system log in a text file.
[log.txt](https://github.com/hirschmann/nbfc/files/10715661/log.txt)

**Comment by ghost** [comment]
Same here, any chance you solved it?

**Comment by devmet34** [comment]
I had similar issue because cpu not recognised, ryzen r5 series. Downloading the latest OpenHardwareMonitorLib.dll plugin sorted the problem.

Btw, if service loops restarting, you can disable then stop.

**Comment by KyuremBoG** [comment]
> I had similar issue because cpu not recognised, ryzen r5 series. Downloading the latest OpenHardwareMonitorLib.dll plugin sorted the problem.
> 
> Btw, if service loops restarting, you can disable then stop.

What is the latest version? And where to download? Plus I also have a constant restart of the service. Win10 ryzen 5600h
