### ISSUE TITLE
Temperature thresolds logic

### ISSUE THREAD

**Issue by sipertruk** [hirschmann/nbfc#133]
Hello,
I set the following threshold.
According to what is think is logic, I expect the fan to stay off until 50° is reach.
What I see is the following:
        -between 0° and 55° the fan is not constantly off, it starts randomly for less than half a second and stops
        -the fan starts spinning at 55° and the speed raises slowly until 50° then it stops
I am seeing that on an Asus Vivobook S301LA and Windows 10.
Am I doing something wrong ?
![rules](https://cloud.githubusercontent.com/assets/7644041/19950913/f2bd3a7c-a15a-11e6-8e39-556fdfabc566.jpg)
![basic](https://cloud.githubusercontent.com/assets/7644041/19950914/f73655ca-a15a-11e6-8b0a-550afe842bfc.jpg)

**Comment by hirschmann** [comment]
You misunderstood the logic.
With your current settings,the fan will be set to 10.2% at 55° and turned off when the temperature falls below 51°.
See https://github.com/hirschmann/nbfc/wiki/Temperature-threshold
