### ISSUE TITLE
Please make configuration for laptop Lenovo V14 G2 acl

### ISSUE THREAD

**Issue by AlexanderBarde** [hirschmann/nbfc#1330]
I will be very grateful. Because I really need it. Because my laptop heats up to 93-95 degrees, even though I bought it half a year ago

**Comment by basisbit** [comment]
maybe try the config from https://github.com/hirschmann/nbfc/pull/1339

**Comment by OmarMshMsh** [comment]
> maybe try the config from #1339

May you please make a config for (HP Gaming Pavilion - 15-cx0088ne)
I know my laptop is not using its full potential for some reason idk why 
I tried everything and now it's up to your help please :( 🙏
