### ISSUE TITLE
Laptop shut down on startup

### ISSUE THREAD

**Issue by Raigiku** [hirschmann/nbfc#1331]
**Describe the bug**
I tried a config for my hp laptop to see if this software worked, my model was not the same one from the config though. After a couple of seconds my laptop shut down and it would only start windows if I held the power button for 16-20 seconds. When it turned on it would power off automatically after 5 seconds.

**Solution**
Start windows on safe mode and DISABLE the automatic service "Notebook Fan Control" or something like that and then **UNINSTALL THIS CRAP** on the next windows restart

**Note for the creator**
ADD A POPUP SAYING TO NOT LOAD A CONFIG IF THE LAPTOP MODEL IS NOT THE SAME AS THE CONFIG LOADED. MY HEART ALMOST DROPPED AS I THOUGHT I BRICKED MY LAPTOP

**Comment by 1RONMAN** [comment]
HP Pavilion Gaming 15-ec0034ur same issue, same solution, BUT as far as I understood _**it happens when Max. speed parameter exceeds some limit**_, moving program files to another location (to make service unable to start) fixes issue too.

**Comment by pouriya09** [comment]
Really really thank you for this thread, the same happened to me, I was hysterical and thought my laptop was done for.😭😭
