### ISSUE TITLE
Temperature is not being read

### ISSUE THREAD

**Issue by Dum4G** [hirschmann/nbfc#1332]
I have a Dell Inspiron 3585 and whatever config I choose shows my temperature as 0. This isn't a problem for HWinfo, SpeedFan or any other reading tool out there. I did ec-probe and I found a register that is responsible for the temps. So the question is: how do I force nbfc to read the temp from the register I need?

**Comment by MrCheatak** [comment]
What was the solution?

**Comment by Dum4G** [comment]
@MrCheatak to use HWInfo and start it minimized on fan control window 
https://www.hwinfo.com/forum/threads/can-i-run-fan-control-at-each-startup.5197/
