### ISSUE TITLE
Lenovo Yoga 910 Configuration (Kaby lake i7 CPU support?)

### ISSUE THREAD

**Issue by zhengbli** [hirschmann/nbfc#135]
I tried to create a profile for Yoga 910 but couldn't find the read / write registers. Does nbfc currently support 7th gen i7 cpus? 
And of course it would much appreciated if some one can add a yoga 910 profile directly. Thanks.

**Comment by hirschmann** [comment]
First off: CPU support in NBFC means, it can access the temperature sensors. It has nothing to do with the EC registers.
That said - if you build NBFC from the latest source, Kaby Lake is supported.

**Comment by raifd** [comment]
I have tried a lot to solve the issue i have the Yoga 710 model with the i7 Kaby Lake and nothing works i have given up and im trying to live with the noisy fans, and it is so stupid that the fan kicks in when temp is 37-38 degrees C.

**Comment by sauerlandtreffi** [comment]
Hi,
please have a look here: https://github.com/hirschmann/nbfc/issues/145
I'm pretty sure that the 710 config could work with the 910 :-)

**Comment by zhengbli** [comment]
It seems to be partially working. It can read the fan speed, but cannot control it. 
![image](https://cloud.githubusercontent.com/assets/1171301/20609511/78d377aa-b242-11e6-82d5-7dd8df7cfcae.png)

The "target fan speed" only shows the current fan speed if set to 100% (auto)
while the "Current fan speed" is always 0

**Comment by strap8** [comment]
It would be great if someone implemented the 910. Please and thank you!

**Comment by hirschmann** [comment]
See https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
