### ISSUE TITLE
Error Program V1.6.3

### ISSUE THREAD

**Issue by MarlonPra** [hirschmann/nbfc#1365]
**Describe the bug**
It does not detect the fans and I already have the "Always Fan" activated.

**To Reproduce**

https://github.com/hirschmann/nbfc/assets/79668146/7c0d0fb0-e413-43ae-bf31-2216f91bb4ea

**Expected behavior**
It can manage my fans but it doesn't, it stays in a loop of activation and deactivation.

**System information**
 - Windows 10
 - 1.6.3
 - log files
[NbfcServiceLog.txt](https://github.com/hirschmann/nbfc/files/12648805/NbfcServiceLog.txt)
[NoteBookFanControlLog.txt](https://github.com/hirschmann/nbfc/files/12648809/NoteBookFanControlLog.txt)

**Additional context**
My PC is an HP PAVILION GAMING, 15-DK1043LA

**Comment by Oblithian** [comment]
So, I just spent a few hours trying to get mine to work, I have a different issue, but I ran into this one along the way.

If the maximum fan speed is set too low in the config (too high in decimal numbers for some computers, like mine), it will cut in and out. Pulsing the fan as opposed to running it at an impossibly low speed.

I would just run through the configuration and confirm all the values are correct.

You may want to get the Read and Write Utility from [rweverything.com](url). I found a manual for an older version here: [https://vdocument.in/notebook-fancontrol-user-manual.html?page=1](url)
