### ISSUE TITLE
Nbfc not working in arch linux

### ISSUE THREAD

**Issue by harisudarsan1** [hirschmann/nbfc#1366]
**Describe the bug**
`sudo nbfc start` gives an error : /usr/local/etc/nbfc/nbfc.json: /usr/local/etc/nbfc/nbfc.json: No such file or directory. nbfc is installed using pacman and also tried installing from source both of them are not working.

`systemctl enable nbfc.service`  gives this error : `Failed to enable unit: Unit file nbfc.service does not exist`. But I have installed nbfc-linux package for arch.

**To Reproduce**
Steps to reproduce the behavior.
- run `sudo nbfc start`
- run `systemctl enable nbfc.service`

**Expected behavior**
The nbfc start should start the service

**System information**
 - Arch linux
 - NBFC version
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview))
[log.txt](https://github.com/hirschmann/nbfc/files/12776520/log.txt)

**Comment by stm28304** [comment]
Hi, you can use arch packages from AUR (https://wiki.archlinux.org/title/Arch_User_Repository).  For me the package "nbfc" works very well.

If you install from source and have problems with "systemctl enable nbfc.service": Does the  nbfc.service-file exists in /etc/systemd/system or /usr/lib/systemd/system/? And don't forget to "systemctl daemon-reload" before enabling the service.

**Comment by vinibali** [comment]
hello @harisudarsan1! you've probably picked the nbfc-linux pacakge at Arch, which is a different repo:
https://github.com/nbfc-linux/nbfc-linux

**Comment by Petrprogs** [comment]
Same

**Comment by mrp4sten** [comment]
I have the same problem, and altenativally I dont wanna use nbfc I want to use nbfc-linux because is updated instead of nbfc package.

**Comment by mrp4sten** [comment]
I dont test it this but I think that is the obvious fix https://github.com/nbfc-linux/nbfc-linux/issues/100

**Comment by mrp4sten** [comment]
I do this:

```shell
sudo nbfc config -r
sudo nbfc config --apply "Lenovo ThinkPad Helix"
sudo nbfc start
```
