### ISSUE TITLE
Nbfc connection refused manjaro linux

### ISSUE THREAD

**Issue by Glqch404** [hirschmann/nbfc#1368]
Hello, i just installed manjaro linux, i did all the steps correctly, i build the git, i ran the build.sh, i put the services into the etc/systemd/system and the other place, also did systemctl enable nbfc.service and it worked fine, but everytime i try to use the mono nbfc.exe (command) any command, it says connection refused object reference not set to an instance of an object

**Comment by Glqch404** [comment]
Also mono nbfc.exe start  says connection refused

**Comment by xstable** [comment]
I'm also at manjaro, but installed the package via package-manager. Same error... `connection refused`

You can try: https://github.com/nbfc-linux/nbfc-linux
