### ISSUE TITLE
Need Dual fan Config For HP Pavilion Gaming 15-DK0056NR 

### ISSUE THREAD

**Issue by Wildchild420187** [hirschmann/nbfc#1370]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I have a config that will control both fans at the same time, but id really love to be able to control them individually 

**Describe the solution you'd like**
to find a config that will control each fan individually 

**Additional context**
I have a general understanding of how a config is made, but cannot figure out how to make them operate individually

**Comment by laughingwater** [comment]
Hi, i have a similar laptop (HP Pavilion Gaming 15 dk-2xxx), i currently use the HP compaq config but it only allows for fan speed control, could you please share your config to control both fans at the same time?

also for your question, i have tried finding configs but they either don't work or just control the cpu fan

**Comment by GORILA1221** [comment]
Hello, HP Gaming Pavilion Notebook PC - 15-cx0027ur configuration HP Compaq 15-s103tx only works with the processor, the GPU does not cool, I would like to take a look at your configuration.

**Comment by Wildchild420187** [comment]
yeah, i will share it, that laptop is out of comission at the moment, it will be a couple weeks until i get it going again. remind me if you dont hear back from me 

    On Monday, November 6, 2023 at 08:16:03 PM PST, laughingwater ***@***.***> wrote:  
 
 


Hi, i have a similar laptop (HP Pavilion Gaming 15 dk-2xxx), i currently use the HP compaq config but it only allows for fan speed control, could you please share your config to control both fans at the same time?

also for your question, i have tried finding configs but they either don't work or just control the cpu fan

**Comment by laughingwater** [comment]
> Hello, HP Gaming Pavilion Notebook PC - 15-cx0027ur configuration HP Compaq 15-s103tx only works with the processor, the GPU does not cool, I would like to take a look at your configuration.

i already said that its only working for the CPU fan, im trying to find configs that control the gpu fan too

**Comment by GORILA1221** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. I have a config that will control both fans at the same time, but id really love to be able to control them individually
> 
> **Describe the solution you'd like** to find a config that will control each fan individually
> 
> **Additional context** I have a general understanding of how a config is made, but cannot figure out how to make them operate individually

Hi, could you please post the configuration?

**Comment by laughingwater** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. I have a config that will control both fans at the same time, but id really love to be able to control them individually
> 
> **Describe the solution you'd like** to find a config that will control each fan individually
> 
> **Additional context** I have a general understanding of how a config is made, but cannot figure out how to make them operate individually

Hi, hope your laptop is back. Do you mind sharing the config?

**Comment by Wildchild420187** [comment]
laptop is toast. lost everytihin 
    On Monday, January 1, 2024 at 03:49:07 AM PST, laughingwater ***@***.***> wrote:  
 
 



Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. I have a config that will control both fans at the same time, but id really love to be able to control them individually

Describe the solution you'd like to find a config that will control each fan individually

Additional context I have a general understanding of how a config is made, but cannot figure out how to make them operate individually


Hi, hope your laptop is back. Do you mind sharing the config?
