### ISSUE TITLE
Gui for linux

### ISSUE THREAD

**Issue by Glqch404** [hirschmann/nbfc#1375]
the application on linux works flawlessly for me, but i hate that we need to use psensor to see the temp, i also hate how it needs to be adjusted via the terminal, i know that creating a gui for linux is very easy, but i dont have the complete knowledge to do so, so i need your help to make a gui similar to the windows's one but for linux Debian/Ubuntu

**Comment by maxcurrent420** [comment]
Seconded. Hard enough to get this to work with dual fans when there's no config for my model- a GUI would at least make it less painful.
