### ISSUE TITLE
Asus Zenbook UX360UAK

### ISSUE THREAD

**Issue by The-Buro** [hirschmann/nbfc#138]
Hey i have a problem, if i try to build this file NbfcBootstrapper.exe i get an error.

> PS C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master> ./build.ps1
> Alle in "packages.config" aufgeführten Pakete sind bereits installiert.
> Microsoft (R)-Buildmodul, Version 4.6.1586.0
> [Microsoft .NET Framework, Version 4.0.30319.42000]
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Si
> e den Schalter "/m" hinzufügen.
> Der Buildvorgang wurde am 11.11.2016 10:08:02 gestartet.
> Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\NoteBookFanControl.sln" auf Knoten "1", Build Ziel(e).
> ValidateSolutionConfiguration:
>   Die Projektmappenkonfiguration "ReleaseWindows|Any CPU" wird erstellt.
> ValidateProjects:
>   Das Projekt "StagWare.Plugins.ECLinux" ist in der Projektmappenkonfiguration "ReleaseWindows|Any CPU" nicht zum Erste
>   llen ausgewählt.
>   Das Projekt "StagWare.Plugins.FSTemperatureMonitor" ist in der Projektmappenkonfiguration "ReleaseWindows|Any CPU" ni
>   cht zum Erstellen ausgewählt.
>   Das Projekt "StagWare.Plugins.ECSysLinux" ist in der Projektmappenkonfiguration "ReleaseWindows|Any CPU" nicht zum Er
>   stellen ausgewählt.
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\NoteBookFanControl.sln" (1) erstellt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-maste
> r\Core\StagWare.FanControl\StagWare.FanControl.csproj" (2) auf Knoten "1" (Standardziele).
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj" (2) erstellt "C:\U
> sers\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.Configurations\StagWare.FanControl.Configurations.csproj" (3) auf Knoten "
> 1" (Standardziele).
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
> Das Ziel "CoreCompile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> CopyFilesToOutputDirectory:
>   StagWare.FanControl.Configurations -> C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.Configurations\bin\Release\Sta
>   gWare.FanControl.Configurations.dll
> Die Erstellung von Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.Configurations\StagWare.FanControl.Configu
> rations.csproj" ist abgeschlossen (Standardziele).
> 
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
>   C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /war
>   n:4 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFra
>   mework\v4.5\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFra
>   mework\v4.5\mscorlib.dll" /reference:C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.Configurations\bin\Release\Stag
>   Ware.FanControl.Configurations.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFr
>   amework\v4.5\System.ComponentModel.Composition.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft
>   \Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram
>   ework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\M
>   icrosoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micros
>   oft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framew
>   ork\.NETFramework\v4.5\System.Management.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Frame
>   work\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.
>   NETFramework\v4.5\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\StagWare.FanControl.
>   dll /subsystemversion:6.00 /target:library /utf8output ArithmeticMeanTemperatureFilter.cs FanControl.cs FanInformatio
>   n.cs FanSpeedManager.cs ITemperatureFilter.cs Plugins\FanControlMetadataAttribute.cs Plugins\FanControlPluginLoader.c
>   s Plugins\IEmbeddedController.cs Plugins\IFanControlPlugin.cs Plugins\IFanControlPluginMetadata.cs Plugins\ITemperatu
>   reMonitor.cs TemperatureThresholdManager.cs Properties\AssemblyInfo.cs "C:\Users\xxxxxxxxxxxx\AppData\Local\Temp\.NETFramewo
>   rk,Version=v4.5.AssemblyAttributes.cs"
> FanControl.cs(225,51): error CS0103: Der Name 'nameof' ist im aktuellen Kontext nicht vorhanden. [C:\Users\xxxxxxxxxxxx\Deskto
> p\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
> FanControl.cs(225,58): error CS0118: 'StagWare.FanControl.FanControl' ist ein(e) 'Typ', wird aber wie ein(e) 'Variable'
>  verwendet. [C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
> FanControl.cs(292,51): error CS0103: Der Name 'nameof' ist im aktuellen Kontext nicht vorhanden. [C:\Users\xxxxxxxxxxxx\Deskto
> p\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
> FanControl.cs(292,58): error CS0118: 'StagWare.FanControl.FanControl' ist ein(e) 'Typ', wird aber wie ein(e) 'Variable'
>  verwendet. [C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
> Die Erstellung des Projekts "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj" is
> t abgeschlossen (Standardziele) -- FEHLER.
> 
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\NoteBookFanControl.sln" (1) erstellt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-maste
> r\Windows\ConfigEditor\ConfigEditor.csproj" (7) auf Knoten "1" (Standardziele).
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\ConfigEditor\ConfigEditor.csproj" (7) erstellt "C:\Users\xxxxxxxxxxxx\
> Desktop\nbfc-master\Windows\StagWare.BiosInfo\StagWare.BiosInfo.csproj" (8) auf Knoten "1" (Standardziele).
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
> Das Ziel "CoreCompile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> CopyFilesToOutputDirectory:
>   StagWare.BiosInfo -> C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\StagWare.BiosInfo\bin\Release\StagWare.BiosInfo.dll
> Die Erstellung von Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\StagWare.BiosInfo\StagWare.BiosInfo.csproj" ist
> abgeschlossen (Standardziele).
> 
> MainResourcesGeneration:
> Das Ziel "MainResourcesGeneration" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell si
> nd.
> CoreResGen:
>   Es sind keine Ressourcen vorhanden, die im Hinblick auf die Quelldateien veraltet sind. Die Ressourcengenerierung wir
>   d übersprungen.
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
> Das Ziel "CoreCompile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> _CopyAppConfigFile:
> Das Ziel "_CopyAppConfigFile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> CopyFilesToOutputDirectory:
>   ConfigEditor -> C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\ConfigEditor\bin\Release\ConfigEditor.exe
> Die Erstellung von Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\ConfigEditor\ConfigEditor.csproj" ist abgeschlos
> sen (Standardziele).
> 
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\NoteBookFanControl.sln" (1) erstellt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-maste
> r\Windows\Setup\NbfcSetup\NbfcSetup.wixproj" (9) auf Knoten "1" (Standardziele).
> BeforeBuild:
>   C:\Program Files (x86)\WiX Toolset v3.10\bin\Heat.exe dir ..\..\..\Configs -cg Configs -dr ConfigsFolder -srd -var va
>   r.ConfigsDir -ag -out C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\Setup\NbfcSetup\Configs.wxs
>   Windows Installer XML Toolset Toolset Harvester version 3.10.3.3007
>   Copyright (c) .NET Foundation and contributors. All rights reserved.
> 
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\Setup\NbfcSetup\NbfcSetup.wixproj" (9) erstellt "C:\Users\xxxxxxxxxxxx
> \Desktop\nbfc-master\Core\Plugins\OpenHardwareMonitor\OpenHardwareMonitorLib.csproj" (11:2) auf Knoten "1" (Standardzie
> le).
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
> Das Ziel "CoreCompile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> CopyFilesToOutputDirectory:
>   OpenHardwareMonitorLib -> C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\Plugins\OpenHardwareMonitor\Bin\Release\OpenHardwar
>   eMonitorLib.dll
> Die Erstellung von Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\Plugins\OpenHardwareMonitor\OpenHardwareMonitorLib.
> csproj" ist abgeschlossen (Standardziele).
> 
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\Setup\NbfcSetup\NbfcSetup.wixproj" (9) erstellt "C:\Users\xxxxxxxxxxxx
> \Desktop\nbfc-master\Core\Plugins\StagWare.Hardware.LPC\StagWare.Hardware.LPC.csproj" (12:2) auf Knoten "1" (Standardzi
> ele).
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
> Das Ziel "CoreCompile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> CopyFilesToOutputDirectory:
>   StagWare.Hardware.LPC -> C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\Plugins\StagWare.Hardware.LPC\bin\Release\StagWare.H
>   ardware.LPC.dll
> Die Erstellung von Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\Plugins\StagWare.Hardware.LPC\StagWare.Hardware.LPC
> .csproj" ist abgeschlossen (Standardziele).
> 
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\Setup\NbfcSetup\NbfcSetup.wixproj" (9) erstellt "C:\Users\xxxxxxxxxxxx
> \Desktop\nbfc-master\Core\Plugins\StagWare.Hardware\StagWare.Hardware.csproj" (13:2) auf Knoten "1" (Standardziele).
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
> Das Ziel "CoreCompile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> CopyFilesToOutputDirectory:
>   StagWare.Hardware -> C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\Plugins\StagWare.Hardware\bin\Release\StagWare.Hardware.
>   dll
> Die Erstellung von Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\Plugins\StagWare.Hardware\StagWare.Hardware.csproj"
>  ist abgeschlossen (Standardziele).
> 
> Die Erstellung des Projekts "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\Setup\NbfcSetup\NbfcSetup.wixproj" ist abgeschl
> ossen (Standardziele) -- FEHLER.
> 
> Das Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\NoteBookFanControl.sln" (1) erstellt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-maste
> r\Windows\Setup\DriverSetupWixAction\DriverSetupWixAction.csproj" (17:2) auf Knoten "1" (Standardziele).
> GenerateTargetFrameworkMonikerAttribute:
> Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
> teien aktuell sind.
> CoreCompile:
> Das Ziel "CoreCompile" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> PackCustomAction:
> Das Ziel "PackCustomAction" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabedateien aktuell sind.
> CopyFilesToOutputDirectory:
>   DriverSetupWixAction -> C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\Setup\DriverSetupWixAction\bin\Release\DriverSetup
>   WixAction.dll
> Die Erstellung von Projekt "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Windows\Setup\DriverSetupWixAction\DriverSetupWixAction.
> csproj" ist abgeschlossen (Standardziele).
> 
> Die Erstellung des Projekts "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\NoteBookFanControl.sln" ist abgeschlossen, Build Ziel(e
> ) -- FEHLER.
> 
> 
> Fehler beim Buildvorgang.
> 
> "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\NoteBookFanControl.sln" (Build Ziel) (1) ->
> "C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj" (Standardziel) (2) ->
> (CoreCompile Ziel) ->
>   FanControl.cs(225,51): error CS0103: Der Name 'nameof' ist im aktuellen Kontext nicht vorhanden. [C:\Users\xxxxxxxxxxxx\Desk
> top\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
>   FanControl.cs(225,58): error CS0118: 'StagWare.FanControl.FanControl' ist ein(e) 'Typ', wird aber wie ein(e) 'Variabl
> e' verwendet. [C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
>   FanControl.cs(292,51): error CS0103: Der Name 'nameof' ist im aktuellen Kontext nicht vorhanden. [C:\Users\xxxxxxxxxxxx\Desk
> top\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
>   FanControl.cs(292,58): error CS0118: 'StagWare.FanControl.FanControl' ist ein(e) 'Typ', wird aber wie ein(e) 'Variabl
> e' verwendet. [C:\Users\xxxxxxxxxxxx\Desktop\nbfc-master\Core\StagWare.FanControl\StagWare.FanControl.csproj]
> 
>     0 Warnung(en)
>     4 Fehler
>

**Comment by hirschmann** [comment]
Seems like there is no C# 6.0 compiler installed on your system.
Install the latest .NET Framework and try to build again.

**Comment by The-Buro** [comment]
i have installed .Net Freamwork 4.6 or newer

**Comment by hirschmann** [comment]
My bad. The latest compiler isn't shipped with the framework anymore.
Please install [MS Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159) and run the build script again.

If the build still fails, try to invoke msbuild manually:
`& ${env:ProgramFiles(x86)}\MSBuild\14.0\Bin\MSBuild.exe /t:Build /p:Configuration=ReleaseWindows NoteBookFanControl.sln`

Please let me know if this worked for you. Maybe I have to fix the build script.

**Comment by The-Buro** [comment]
Ok it works very well
thank you...

**Comment by hirschmann** [comment]
Did you have to invoke msbuild manually?

**Comment by The-Buro** [comment]
i have edit the build.ps1 to this:

> $workingDir = split-path $MyInvocation.MyCommand.Path
push-location $workingDir

# download nuget if necessary
if(!(test-path .\nuget.exe)) {
	(new-object System.Net.WebClient).DownloadFile('http://nuget.org/nuget.exe', "$workingDir\nuget.exe")
}

# restore nuget packages for solution
.\nuget.exe restore

# build solution
& ${env:ProgramFiles(x86)}\MSBuild\14.0\Bin\MSBuild.exe /t:Build /p:Configuration=ReleaseWindows NoteBookFanControl.sln

pop-location

>

**Comment by hirschmann** [comment]
Thanks for the feedback! 👍 
That's exactly what I meant when I said "maybe I have to fix the build script".

The fix: 0e99514d0cd98961d5c4a7c619eebaa63e860288

**Comment by ashtonaut** [comment]
Hi @The-Buro, if you got this working, would you mind posting your configuration file for the Asus UX360UAK?

**Comment by The-Buro** [comment]
hey @ashtonaut  i use the Asus Zenbook UX32VD configuration file for my UX360UAK its work fine

**Comment by ashtonaut** [comment]
For the record, the new UX360UAK configuration file just added by @hirschmann in [this commit](https://github.com/hirschmann/nbfc/commit/346990e33846b3fb7363f4e760332ccc3ad118c3) also works on an Asus Zenbook Flip UX360UA (Skylake).

Program version 1.4.2 didn't work with this laptop, but 1.4.4 Beta works and appears to be operating as expected.

Thanks so much for this utility - I knew that the fan on this model was too aggressive (see [this review](http://www.ultrabookreview.com/11810-asus-zenbook-ux360ua/)), but this tool has fixed that issue without me having to hope for an Asus update!
