### ISSUE TITLE
My NBFC is bugged

### ISSUE THREAD

**Issue by MrDood3** [hirschmann/nbfc#1380]
I'm not sure why it's like this or whether it's working or not. My laptop is indeed the AERO 15XV8. So I don't know why it's doing this... The GPU fan is the same as well. Please help
![image](https://github.com/hirschmann/nbfc/assets/142956845/7a898d94-e7f3-4ed3-8dd4-add5e74d2d5d)

**Comment by jmbreuer** [comment]
Are you using WSL2? Someone somewhere mentioned something that this puts all of Win (and the Linux Subsystem next to it) under a Hypervisor that can get in the way of certain hardware access of the type that nbfc would want/need to perform.

Also, there's an updated version of nbfc available as a fork, might be worth a try:

https://github.com/UraniumDonut/nbfc-revive
