### ISSUE TITLE
Asus Zenbook UX330UAK

### ISSUE THREAD

**Issue by ftribrunn** [hirschmann/nbfc#139]
Hi

I can´t enable NBFC.
If I select a Profile and klick apply, the select config field keeps empty.

any suggestions?

**Comment by hirschmann** [comment]
The latest release doesn't support Kaby Lake CPUs, but you can build NBFC from source to get all the new features including Kaby Lake support. 
See: https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC

**Comment by macuser2017** [comment]
Hi Stefan,

I also have a asus zenbook ux330uak (i7 7500).
Can you do a config file to this machine?
If not, can you point me to a similar config from those preexistent in NBFC?
Thanks.

**Comment by hirschmann** [comment]
I guess this one could work: https://github.com/hirschmann/nbfc/blob/master/Configs/Asus%20Zenbook%20Flip%20UX360UAK.xml

Btw the [NBFC CLI](https://github.com/hirschmann/nbfc/wiki/Command-line-interface) is able to recommend configs:
`nbfc config --recommend`
