### ISSUE TITLE
High Latency on Acer Aspire VN7-593G V17 Nitro BE

### ISSUE THREAD

**Issue by hotbabyspace** [hirschmann/nbfc#1392]
Hello! I've been using your software for more than 6 years and it works great on my acer aspire VN7-593G  V17 Nitro BE to control the fans. I haven't found any other software that works.
I use Ableton for producing music and I have been always living with this latency issue. I also changed my audio interface because I thought it might fix the problem.
Im not very technical with computers but today I started a new troubleshooting session to fix the latency issue and I finally found out that when I disable the nbfc service, the latency is gone!
Please try and fix it! It does something with the ACPI driver, as the other people mentioned. I use the acer aspire VN7-593G  V17 Nitro BE config.

Or maybe im not using the program correctly, I don't really know how to set it up, I just have setup the temperature thresholds in a way that the fans are not constantly blasting because its so annoying when producing music. It works like a charm, my laptop is super quiet and doesn't overheat when setup properly. I haven't changed any other parameter in the program. Can you help me set it up correctly or can I provide you with information so you can fix the bug?

Thank you anyway, i can do my music with latency, but not with the fans blasting, so you have saved my life all these years.

![image](https://github.com/hirschmann/nbfc/assets/97682582/2abb2a3c-dd10-4f99-ad69-72d682a7d052)

![image](https://github.com/hirschmann/nbfc/assets/97682582/c00ee004-cbf7-45a9-8c90-1f8fbd0b22e2)

**Comment by angelokimhui** [comment]
I fixed mine by writing a powershell script that monitors temps every 500ms and using NBFC's ec-probe tool to adjust value of the fan in specific range. I think there's some optimization needed for the program itself and the service, If you are still interested, you can check my profile and the Ryzenadj repo wherein I integrated it. You can even uninstall NBFC and the ec-probe tool will still work as long as some dependency dll's are satisfied.
