### ISSUE TITLE
Can you create a configuration file for Redmi? 

### ISSUE THREAD

**Issue by PIMCN** [hirschmann/nbfc#1394]
Can you create a configuration file for Redmi? My motherboard model is Redmi G Pro 2024.Thank you very much.My e-mail is 2171855185@qq.com.

**Comment by Lord-Fec** [comment]
Can you set "enable" in your computer, my computer is RedmiBook Pro 2024, win11, but I cannot set "enable". It always varies from "disable" and "read only"

**Comment by tkkcc** [comment]
check this https://bbs.nga.cn/read.php?tid=40353224
