### ISSUE TITLE
There is not NbfcBootstrapper.exe

### ISSUE THREAD

**Issue by cappatr** [hirschmann/nbfc#14]
Running build.ps1 but there is not NbfcBootstrapper.exe) at nbfc\Windows\Setup\NbfcBootstrapper\bin\Release\ or anywhere. 
When i run build.ps1 , there are red words in black window in miliseconds so i can't read. thanks.
Win 7 Ult x64 , notebook model: hp dv5 1041et

**Comment by hirschmann** [comment]
1. If you are not familiar with powershell, please read a tutorial about powershell (e.g. [A Beginner’s Introduction to Windows PowerShell](https://blog.udemy.com/powershell-tutorial/))

2. Maybe the execution policy for powershell scripts is set to restricted. This article may help you: [15 Ways to Bypass the PowerShell Execution Policy](https://blog.netspi.com/15-ways-to-bypass-the-powershell-execution-policy/)

3. There are builds of NBFC available here: https://github.com/hirschmann/nbfc/releases
You don't need to necessarily build it yourself
