### ISSUE TITLE
SOLVED/Lenovo Yoga 710 i7- Kaby Lake 

### ISSUE THREAD

**Issue by raifd** [hirschmann/nbfc#140]
Can someone make a configuration for the new Yoga 710 because the fans are so loud even when idle and the temperature is low, i have tried for days but nothing seems to work.
Check this post in lenovo forums: https://forums.lenovo.com/t5/Lenovo-Yoga-Series-Notebooks/Yoga-710-Constant-Fan-Noise-even-when-idle/td-p/3354501

**Comment by sauerlandtreffi** [comment]
Please have a look here :-)

https://github.com/hirschmann/nbfc/issues/145

**Comment by raifd** [comment]
You are a living legend!
