### ISSUE TITLE
Problems with compiling source

### ISSUE THREAD

**Issue by sauerlandtreffi** [hirschmann/nbfc#141]
Hi all,

I experienced problems in compiling the newest version of NBFC. I installed all the needed programs as described in the Wiki. The problem is, that the powershell closes itself and I can't copy the errors.

Do you have any clue why? Could someone compile it for me and send me the setup file?

I need the newest version for my new Lenovo Yoga 710 with i7 Kaby Lake. It's annyoing loud ;-)

Thank you in advance for your help! :-)

**Comment by DerFisc** [comment]
I'm having the same issue. I could compile the program without issues a few month ago. I'm on the latest Windows 10.

**Comment by DerFisc** [comment]
> "C:\Users\michi\Downloads\nbfc-master\nbfc-master\NoteBookFanControl.sln" (Build Ziel) (1) ->
"C:\Users\michi\Downloads\nbfc-master\nbfc-master\Windows\Setup\NbfcSetup\NbfcSetup.wixproj" (Standardziel) (10) ->"C:\Users\michi\Downloads\nbfc-master\nbfc-master\Windows\NbfcClient\NbfcClient.csproj" (Standardziel) (17:2) ->"C:\Users\michi\Downloads\nbfc-master\nbfc-master\Windows\NbfcClient\yekess42.tmp_proj" (_CompileTemporaryAssembly Ziel) (19) ->(CoreCompile Ziel) ->  ViewModels\FanControllerViewModel.cs(10,43): error CS0012: Der Typ "Object" ist in einer nicht referenzierten Assembly definiert. Fügen Sie einen Verweis auf die Assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" hinzu. [C:\Users\michi\Downloads\nbfc-master\nbfc-master\Windows\NbfcClient\yekess42.tmp_proj] ViewModels\FanControllerViewModel.cs(101,30): error CS0012: Der Typ "Object" ist in einer nicht referenzierten Assembly definiert. Fügen Sie einen Verweis auf die Assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" hinzu. [C:\Users\michi\Downloads\nbfc-master\nbfc-master\Windows\NbfcClient\yekess42.tmp_proj]

That's a part of the error. There are several lines of `Der Typ "Object" ist in einer nicht referenzierten Assembly definiert. Fügen Sie einen Verweis auf die Assembly "System.Runtime ...` following.

**Comment by hirschmann** [comment]
@sauerlandtreffi 
Did you just double-click the build script? I'm not sure if this works.
Try opening a new powershell session, navigate to the NBFC source directory and run the build script.

@DerFisc
Are you sure all the required packages (see https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC)  - especially .net 4.5 - are installed on your system?

**Comment by DerFisc** [comment]
Yes, I installed WiX Toolset and the MS Build Tools. I couldn't install the .Net Package because Windows 10 already comes with a newer version.

**Comment by hirschmann** [comment]
I've updated the wiki.
Unfortunately you have to install Visual Studio (which is pretty huge) to build NBFC.

I know there is demand for the latest features, therefore I'm planning to provide beta builds regularly.

**Comment by sauerlandtreffi** [comment]
Thank you @hirschmann for your help! It worked finally with Visual Studio installed.

With the newest Build I experienced problems, that NBFC is still not able to read the temperature of my Kaby Lake Processor.

I have the latest i7 7500u in my Lenovo Yoga 710. Is this problem already known?

**Comment by hirschmann** [comment]
The NBFC service must be at least in read-only mode, otherwise it will not do anything but listen for commands.

If this doesn't work, could you please post a CPU-Z screenshot of your CPU?

**Comment by sauerlandtreffi** [comment]
Hi @hirschmann 
Yes, this was my fault, sorry. I forgot to install the new version, therefore the service didn't work. Now it works fine and is also working with the new yoga 710. 
If you want me to upload the working config file please let me know where to upload it :-)

**Comment by hirschmann** [comment]
Great to hear you've got it working :) 

If you are familiar with git, you can create a pull request.
Otherwise, please open a new issue and post the content of your config file.

**Comment by sauerlandtreffi** [comment]
I did it now and hope, that it's okay for you: https://github.com/hirschmann/nbfc/issues/145 :-)

**Comment by hirschmann** [comment]
Thanks! 👍
