### ISSUE TITLE
fan cleaning program

### ISSUE THREAD

**Issue by shinji2009** [hirschmann/nbfc#142]
hi. it will be just super great if add a fan cleaning program into application. it's like when fan 5s at 100% and 5s at minimum. and cycle it. there is such program in lenovo laptops.

**Comment by hirschmann** [comment]
NBFC gives you full control over the fans. You can set the fan to 100% for 5 seconds manually, then set it to 0%.

If you want to automate this, you can do it with a small script like this:
```powershell
while($true) { nbfc set -s 100; sleep 5; nbfc set -s 1; sleep 5 }
```

**Comment by doiiido** [comment]
Lenovo Notebooks can also spin the fans at reverse.
Your script only spins one way.
