### ISSUE TITLE
Asus UX32VD gpu fan

### ISSUE THREAD

**Issue by dimalu85** [hirschmann/nbfc#144]
Asus UX32VD doesn't see gpu(nvidia) fan info

**Comment by hirschmann** [comment]
For the UX32VD, NBFC can't control the fans independent of each other.
There is also a problem with Nvidia's Optimus technology, see https://github.com/hirschmann/nbfc/wiki/FAQ#why-does-nbfc-stop-working-when-i-start-a-game

**Comment by dimalu85** [comment]
Thanks a lot!
