### ISSUE TITLE
Solved: KabyLake / Lenovo Yoga 710

### ISSUE THREAD

**Issue by sauerlandtreffi** [hirschmann/nbfc#145]
Hi all,
I finally was able to get a working config file which works with the newest nbfc beta. Thanks a lot to @hirschmann for helping!

To support you and this project I uploaded the newest compiled NBFC beta including the config-file which is working fine with my kabylake-yoga.

http://ul.to/d3cnyaze

@hirschmann, if it's not okay that I uploaded the compiled file, I will delete it immidiately. But I think this could help the people who have those problems :-)

**Comment by hirschmann** [comment]
Thanks for the config! 👍 
I don't mind that you uploaded your own build of NBFC, yet I would recommend to use the latest official beta build: https://github.com/hirschmann/nbfc/releases/tag/1.4.4-beta

**Comment by Fred1454** [comment]
Does this only work for Kaby Lake models or would it also work for the previous generation (Skylake)?
I'm thinking about buying the following model: Lenovo Yoga 710 - 80TY0056MX, which has an i7-6500U CPU, but I'll only buy it, if the fan noise can be fixed. Hope someone can help me :-)

**Comment by Overmun** [comment]
I have tried the following with v1.5 and 1.42, but both do not work.  I am on a KabyLake machine.  

I have tried to 'import' the config (.xml file), but dont see changes to fan configuration as opposed to something like this: https://forums.lenovo.com/t5/image/serverpage/image-id/77434iC51F0A0229C7384C/image-size/large?v=v2&px=999  
Its completely blank under Temperature thresholds. This leads me to believe I am doing something wrong during the 'import' process.  

I have also tried adjusting the settings manually to be like the ones in the Kabylake config and the Yoga 11s(skylake). However, I am unable to adjust Fan Speed under the Temperature thresholds - the option for Fan Speed is stuck at 0: http://imgur.com/a/BODAK  
I am also curious as to why when I view the .XML file, there are options in there that are not visible when I try to manually do a config. 

Thus I am unable to utilise NoteBookFanControl to make any adjustments to better regulate the CPU Fan in my machine. 
I have already installed the latest BIOS which has improved the situation, and also made changes to Power Management.  

I will really appreciate it if some of my queries could be answered. Thanks.

**Comment by parkerlreed** [comment]
@sauerlandtreffi Holy crap thanks! I've had this laptop for a few months and just now noticed the fan didn't spin down on idle. I'm idling at 41C and I had to `stress` all 4 threads, play a YouTube video in Chrome, and run Quake 3 (ioquake3) just to hit 50. You have effectively made my laptop passively cooled under pretty much any load I could throw at it. :heart: 

```
  native-path:          BAT1
  vendor:               SIMPLO
  model:                PABAS0241231
  serial:               41167
  power supply:         yes
  updated:              Thu 05 Oct 2017 06:41:02 PM EDT (1 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              45.99 Wh
    energy-empty:        0 Wh
    energy-full:         54.42 Wh
    energy-full-design:  53 Wh
    energy-rate:         3.823 W
    voltage:             8.241 V
    time to empty:       12.0 hours
    percentage:          84%
    capacity:            100%
    technology:          lithium-ion
    icon-name:          'battery-full-symbolic'
  History (rate):
    1507243262    3.823    discharging
```

And you brought down my idle wattage to 3.8.
