### ISSUE TITLE
A little noob help to understand config

### ISSUE THREAD

**Issue by MadDogDean** [hirschmann/nbfc#146]
Hi,
This has saved my HP ELitebook 8560. Nothing else would control the fan - it was stuck at 40% and I could fry eggs on the touchpad.

I'm a bit lost with the configuration. The 0 - 255 registers is 0 the lowest and 255 the highest? Or is 255 Auto? Everytime I restart NBFC, the fan returns to Auto and will run at or below 40% speed. It seems that if I run my fan at a constant 90%, the laptop stays cool (and I'm almost always plugged in anyhow)

Sorry for such a question, but I appreciate any help any can give.

**Comment by hirschmann** [comment]
If you are at NBFC version 1.4.2, please upgrade to the latest beta: https://github.com/hirschmann/nbfc/releases/tag/1.4.4-beta
1.4.2 sometimes fails when saving the target fan speed and defaults to 'Auto' after a restart.

If you want to change the behavior auf 'Auto' control, then you can adjust the temperature thresholds according to your needs: https://github.com/hirschmann/nbfc/wiki/Temperature-threshold

**Comment by MadDogDean** [comment]
Thanks Stefan,
1.4.4 seems to work without any hitches and it saves the fan settings correctly. I'll be sure to mention your NBFC on a few other forums - somehow nobody seems to be able to resolve fan control issues on a number of HP Elitebooks ;)
