### ISSUE TITLE
Mac OS Porting

### ISSUE THREAD

**Issue by thefiredragon** [hirschmann/nbfc#147]
Hey @all,
Could it possible to port the nbfc application to MacOS?

There are lots of people they build a hackintosh, 
It would be great if there is a way to port this.
Not all people know to handle acpi programming on macOS (like me)
to import this to the dsdt that mac os can handle the fan.

This is not really a issue but could help more people, 
But thanks for the great work here,
David

**Comment by hirschmann** [comment]
Technically it would be possible, but I don't have a OSX device to test on.

**Comment by hirschmann** [comment]
Technically it would be possible, but I don't have a OSX device to test on.
