### ISSUE TITLE
Please Help me Lenovo İP510 15ISK CONFİG?

### ISSUE THREAD

**Issue by onir272** [hirschmann/nbfc#148]
Lenovo idepad 510-15ISK Anybody help me?

**Comment by onir272** [comment]
up

**Comment by onir272** [comment]
UP UPPPPPPPPPPPPPPPPPPPPPP

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
