### ISSUE TITLE
Lenovo Yoga 710 - Sometimes fan doesn't stop

### ISSUE THREAD

**Issue by garceri** [hirschmann/nbfc#151]
This is very weird, been using NBFC with the suggested configuration for the Yoga 710 with great success, yet it looks like something else (driver/sofware) is racing for control of the fan, sometimes the temperature goes as low as 40C yet the fan seems to be stuck at around 60%, no amount of tweaking in NBFC seems to stop it, runs like that for a while then all of sudden the fan goes quiet again.
Anyone has an idea about what may be going on ?
![nbfc- speedfan](https://cloud.githubusercontent.com/assets/10517648/20908649/0385c402-bb35-11e6-8c00-12b78b23a755.PNG)

**Comment by trifasi** [comment]
Same here..

Lenovo 710 15 IKB

**Comment by pythianarceri** [comment]
Update:
Not only the fan seems to be stuck sometimes, when it does it's like something else is trying to control it, and if for example, you try to force the speed to 100% in NBFC the "unknown" other software piece tries to lower it, resulting in the fan going in a fast/slow loop every few seconds.

**Comment by duguyushu** [comment]
same for Lenovo miix 720

**Comment by Boom-Hacker** [comment]
this maybe is acpi force controlling
