### ISSUE TITLE
Can someone do Lenovo Y700-17isk configuration please?

### ISSUE THREAD

**Issue by karamba2016** [hirschmann/nbfc#152]
Lenovo Y700-17 with latest bios:  CPU temp 35 C, GPU 36 C and fans are always loud - second speed level (around 40dB). First Fan speed level (33dB) is used only when the CPU temp is less than 32-33 C. All users have the same problem - the fans are so loud even when idle and the temperature is very low. Please help

when I launched RW-Everything  I get: 

Type:Embedded Controller: 0066,0062
Width:01
00=00 01=01 02=00 03=00 04=00 05=00 06=15 07=01 
08=00 09=00 0A=00 0B=00 0C=00 0D=22 0E=23 0F=00 
10=00 11=00 12=80 13=00 14=05 15=00 16=20 17=01 
18=00 19=01 1A=04 1B=00 1C=00 1D=00 1E=00 1F=00 
20=00 21=00 22=00 23=00 24=00 25=00 26=00 27=00 
28=00 29=00 2A=00 2B=00 2C=00 2D=00 2E=00 2F=80 
30=00 31=00 32=00 33=00 34=00 35=00 36=00 37=00 
38=04 39=00 3A=00 3B=00 3C=00 3D=00 3E=00 3F=00 
40=00 41=00 42=00 43=A0 44=00 45=00 46=00 47=00 
48=00 49=00 4A=00 4B=00 4C=00 4D=00 4E=00 4F=00 
50=00 51=00 52=00 53=0B 54=00 55=00 56=22 57=00 
58=00 59=00 5A=00 5B=00 5C=00 5D=00 5E=00 5F=00 
60=00 61=00 62=00 63=00 64=00 65=00 66=00 67=00 
68=00 69=00 6A=00 6B=00 6C=00 6D=00 6E=00 6F=00 
70=00 71=00 72=00 73=00 74=00 75=00 76=00 77=00 
78=00 79=00 7A=00 7B=00 7C=00 7D=00 7E=00 7F=00 
80=00 81=00 82=00 83=00 84=08 85=00 86=00 87=00 
88=E0 89=00 8A=80 8B=01 8C=00 8D=00 8E=00 8F=53 
90=4D 91=50 92=00 93=31 94=31 95=00 96=00 97=00 
98=4C 99=31 9A=34 9B=4D 9C=34 9D=50 9E=32 9F=33 
A0=00 A1=00 A2=00 A3=83 A4=80 A5=00 A6=00 A7=61 
A8=64 A9=00 AA=00 AB=00 AC=64 AD=25 AE=00 AF=F0 
B0=22 B1=00 B2=00 B3=00 B4=23 B5=00 B6=00 B7=00 
B8=02 B9=11 BA=00 BB=00 BC=00 BD=24 BE=01 BF=00 
C0=71 C1=00 C2=88 C3=17 C4=AB C5=2D C6=64 C7=40 
C8=D0 C9=39 CA=70 CB=17 CC=88 CD=17 CE=5F CF=01 
D0=00 D1=00 D2=00 D3=00 D4=00 D5=00 D6=00 D7=1C 
D8=00 D9=00 DA=00 DB=00 DC=00 DD=00 DE=00 DF=00 
E0=00 E1=00 E2=1A E3=00 E4=00 E5=00 E6=00 E7=00 
E8=00 E9=00 EA=00 EB=00 EC=00 ED=00 EE=00 EF=00 
F0=03 F1=00 F2=00 F3=00 F4=9A F5=48 F6=00 F7=00 
F8=00 F9=00 FA=00 FB=00 FC=00 FD=00 FE=12 FF=00

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
