### ISSUE TITLE
Cannot select a config item from list

### ISSUE THREAD

**Issue by webloft** [hirschmann/nbfc#156]
The configuration items in the main app (select config) are gone after using a pre-defined configuration the first time.

How can I resolve this?
I have tried uninstalling, removing files per hand from %APPDATA%\Roaming and deleting registry values.

Version 1.5.0
Windows 7 x64 w/o SP1
Net. Framework 4.5

**Comment by hirschmann** [comment]
Sounds like the NBFC service crashed.

This should resolve the problem:
1. Stop the service (via services.msc)
2. Delete `%programdata%\NbfcService`
3. Start the service

If it happens again, please look in the Windows event log for NoteBookFanControlService Errors.

To list all NBFC service errors, run this via Windows Powershell:
```powershell
Get-WinEvent -ProviderName NoteBookFanControlService | 
? { $_.Level -le 2 } | 
% { "$($_.TimeCreated)`r`n$($_.Message)`r`n" }
```

**Comment by webloft** [comment]
Hmm. Seems like that it cannot read sensor data from my AMD APU (E2-7110)?

```
Failed to access CPU temperature sensors(s).

   at StagWare.Hardware.HardwareMonitor.InitializeCpuSensors()
   at StagWare.Hardware.HardwareMonitor.get_CpuTemperatures()
   at StagWare.Plugins.Generic.CpuTemperatureMonitor.GetTemperature()
   at StagWare.FanControl.FanControl.TimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCa
llback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

Is there are a way to switch to GPU sensor?

**Comment by hirschmann** [comment]
You can't switch to the GPU sensor because Windows services can't access the GPU (because of session 0  isolation).

I've added support for the AMD Puma CPU architecture: 5dda7a974b38deb9e830678350a14176bafcbcbe
If you want to test it, you can download the build artifact: https://ci.appveyor.com/project/hirschmann/nbfc/build/artifacts

**Comment by webloft** [comment]
Confirmed. Reads the correct temp value and doesn't crash anymore. Thank you!
