### ISSUE TITLE
Can't build master on Fedora 23

### ISSUE THREAD

**Issue by Astreos** [hirschmann/nbfc#158]
Hi !

I have tried to build the master on Fedora 23, but errors occured :
https://gist.github.com/Astreos/a6b9cbc8bee9bfd18b5533900ce305ee

However, everything is okay for the 1.4.4-beta version.
Any idea ?

Thanks for the project by the way !

**Comment by hirschmann** [comment]
Could be a bug in the mono c# compiler. Try to update mono.
If this doesn't help, open the solution in MonoDevelop, open the build configuration and disable the test projects which fails to build.

**Comment by Astreos** [comment]
My mono version seems to be the latest (mono 4.4.2-1, I have just upgraded to Fedora 25).
So I have followed what you have suggested, and it works well now, thanks a lot ! :) 

Thanks you for your work !

**Comment by hirschmann** [comment]
I've implemented a workaround: 92325ba70bf5c0b8b867054862da9a32f532d375

**Comment by beledouxdenis** [comment]
Just a little notification that I came across the same issue, and your workaround solved it.

Of course, I had to build the master branch while I was trying to build the stable 1.5.0, but well, at least my fan is silent now :D.

Thank you very much :). 

I am quite astonished such a project works for both Windows and Linux, and uses the latest technologies (I appreciate the use of `systemd` for the linux service :D). 

I took the liberty to refer your project on this Youtube video, which was the first hit I got when I searched for a solution to my noisy Asus UX360UAK laptop fan.

Keep up the good work !

**Comment by iPadGuy** [comment]
The workaround worked.  Thanks!

There is no `nbfc/Linux/bin/ReleaseLinux/` folder, as mentioned in the [First Steps(https://github.com/hirschmann/nbfc/wiki/First-steps).

The NBFC CLI utility reports the following:

> The method or operation is not implemented.
> Object reference not set to an instance of an object

So, I have no way of configuring or checking the fan status.

Oh well...
