### ISSUE TITLE
Y510p configuration ?

### ISSUE THREAD

**Issue by elobaba** [hirschmann/nbfc#16]
Hallo hirschmann,

Since i bought my lenovo Y510p it is getting a bit hot (78°-82°) I cleaned it already and removed the accumulator but it didn't changed the temperature in cause of the fan wich turns slow even in games the fan is really quiet.

so I would be happy about a Lenovo Y510p configuration to turn the fan up

your sincerely elobaba.

Thanks for the great support I also use NBFC for my old medion p6630

**Comment by hirschmann** [comment]
Please have a look at issue #5

**Comment by hirschmann** [comment]
https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests
