### ISSUE TITLE
Comile error on ubuntu 16.04

### ISSUE THREAD

**Issue by embeddedprojects** [hirschmann/nbfc#161]
after calling build.sh I got this errors:

Errors:

/home/sauterbe/Downloads/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/sauterbe/Downloads/nbfc/Tests/StagWare.FanControl.Tests/StagWare.FanControl.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	FanControlTests.cs(52,66): error CS8082: An argument to nameof operator cannot include sub-expression
	FanControlTests.cs(97,66): error CS8082: An argument to nameof operator cannot include sub-expression
	FanControlTests.cs(193,62): error CS8082: An argument to nameof operator cannot include sub-expression

**Comment by hirschmann** [comment]
Duplicate of #158
