### ISSUE TITLE
How can I load easily a config after each reboot without write the command again under Linux ?

### ISSUE THREAD

**Issue by kevincaradant** [hirschmann/nbfc#163]
Hi

When I reboot the computer, my config seems to be lost

Is it a way to force it to works after a reboot ?

I'm under Ubuntu 16.10 64 bits

At the begin, it works and some minutes after, the fan starts again and nbfc.exe status give me : `connection failed.` The service seems to be stopped and I have to start it again at the hand ... 
Any idea ? 

Thank you 

This is the problem:
`sudo service nbfc status`
![image](https://cloud.githubusercontent.com/assets/6093175/21689193/e41cae3e-d36f-11e6-8469-43874c62e728.png)

```
sudo service nbfc start
sudo service nbfc status
```

![image](https://cloud.githubusercontent.com/assets/6093175/21689275/2440798c-d370-11e6-8272-a5d0432159d5.png)

**Comment by kevincaradant** [comment]
OK the problem was the command : `nbfc.exe status`. When I start it with the current user, I get the good info the first time and the fan starts just after that, I rewrited `nbfc.exe status`, I get `connection refused`. So the service crash apparently just after to write in the terminal nbfc.exe status. 

It's a bug I guess ?

**Comment by hirschmann** [comment]
I can't reproduce this error. Does it occur after every reboot?

Until this problem is solved, you can try to fix it by configuring the service to restart on failure.
Add this line to the [Service] section of the _nbfc.service_ file:
`Restart=on-failure`

**Comment by kevincaradant** [comment]
Yes,  it happens after each reboot (4 reboots) , (4 fails). I created a workaround with a new service which call my sh script and inside it I added some commands and I added the command  `service nbfc start` in more.  That's seems to work even if it's not really good as answer but in my case it's not a problem.  

If you need more information,  tell me where I have to look because I don't know where to search ')

**Comment by hirschmann** [comment]
I fixed the error from your screenshot with 13d7c44e11b3743c962bf2b3275cdd7374efb51f
You can build NBFC from the latest sources if you want to test it.

**Comment by kevincaradant** [comment]
Ah perfect, In fact NBFC has never work correctly with me before because I had only 0 or 100% fanspeed ( critical temp). The different steps was ignored :/

Now everything works without any workaround

Thank you :)

**Comment by kevincaradant** [comment]
Sorry my mistake. Today the bug is here again.

CF:
![image](https://cloud.githubusercontent.com/assets/6093175/22340719/b45dd01c-e3ee-11e6-924d-aee59f374b89.png)

![image](https://cloud.githubusercontent.com/assets/6093175/22340766/d72eb78c-e3ee-11e6-8d47-51808d2f9772.png)


I don't know why today :(

**Comment by hirschmann** [comment]
Looks like NBFC times out when trying to access either the EC or the temperature sensors.
Have you tried the workaround I posted in https://github.com/hirschmann/nbfc/issues/163#issuecomment-270992604 yet?

**Comment by kevincaradant** [comment]
Indeed, I forgot your workaround after the new installation. 
It works, I can see the service failed and just after restart itself and become "activated"
It's like if the service wants to start before to have the OS ready.

**Comment by hirschmann** [comment]
I think it's more like the service tries to start before the hardware (probably the EC) is ready.
The solution to this problem is to retry starting the service, so I will implement the solution from #163

Thanks for helping me to solve this problem :)

**Comment by kevincaradant** [comment]
You're welcome :).  It's perfect and very very useful this NBFC. I let you to close this issue when you think it's necessary

**Comment by jpick** [comment]
Hello hirschmann,
hello kevincaradant,

I think I have a similar problem. I cannot start the nbfc service under my linux distro.
I have an Asus UX410 running under Fedora 25.

I've build nbfc like that :
$ git clone --depth 1 https://github.com/hirschmann/nbfc.git
$ mozroots --import --sync
$ nuget restore
$ xbuild /t:Build /p:Configuration=ReleaseLinux NoteBookFanControl.sln

$ su -
# cd /opt
# cp -r /home/jp/nbfc/Linux/bin/ReleaseLinux nbfc
# cp /home/jp/nbfc/Linux/nbfc*.service /etc/systemd/system/
# cp /home/jp/Asus\ Zenbook\ UX410UAK.xml nbfc/Configs/

But I cannot start the service !
I get the same error message as kevincaradant :

# systemctl start nbfc
# systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since ven. 2017-01-27 18:46:57 CET; 1s ago
  Process: 7250 ExecStart=/opt/nbfc/start-nbfcservice.sh (code=exited, status=0/SUCCESS)
 Main PID: 7253 (code=exited, status=1/FAILURE)

janv. 27 18:46:56 asus.intra.pick.fr systemd[1]: Starting NoteBook FanControl service...
janv. 27 18:46:56 asus.intra.pick.fr systemd[1]: nbfc.service: PID file /run/nbfc.pid not readable (yet?) after start: No such file or directory
janv. 27 18:46:56 asus.intra.pick.fr systemd[1]: Started NoteBook FanControl service.
janv. 27 18:46:57 asus.intra.pick.fr mono[7253]: NbfcService: Exception has been thrown by the target of an invocation.
janv. 27 18:46:57 asus.intra.pick.fr mono[7253]: NbfcService: Object reference not set to an instance of an object
janv. 27 18:46:57 asus.intra.pick.fr systemd[1]: nbfc.service: Main process exited, code=exited, status=1/FAILURE
janv. 27 18:46:57 asus.intra.pick.fr systemd[1]: nbfc.service: Unit entered failed state.
janv. 27 18:46:57 asus.intra.pick.fr systemd[1]: nbfc.service: Failed with result 'exit-code'.

Any idea ?
What is the meaning of the message "NbfcService: Exception has been thrown by the target of an invocation" ?

Thank you,

**Comment by kevincaradant** [comment]
Hi

Interesting, we have the same computer.
I don't know what this means. As mentioned before, it's maybe the hardware which is not completely ready when nbfc service wants start but a good workaround is simply to do:
https://github.com/hirschmann/nbfc/issues/163#issuecomment-270992604

this line in the service file located in 
`/etc/systemd/system/nbfc.service`


And you have to get this:
```
[Unit]
Description=NoteBook FanControl service

[Service]
ExecStart=/opt/nbfc/start-nbfcservice.sh
Type=forking
Restart=on-failure
PIDFile=/run/nbfc.pid
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
```

Let me know if the fix propsed works

**Comment by hirschmann** [comment]
@jpick
Thats's not the same error. You haven't selected a config, that's why the service refuses to start.
Also, you haven't enabled the service, which means it will not start automatically.

See https://github.com/hirschmann/nbfc/wiki/First-steps, steps 3 and 5.

**Comment by kevincaradant** [comment]
Ok so my bad. forgot my answer @jpick :)

**Comment by jpick** [comment]
I just try to add "Restart=on-failure" but without succes.
The nbfc.service start :
```
# systemctl start nbfc
# systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: disabled)
   Active: active (running) since ven. 2017-01-27 19:09:07 CET; 83ms ago
  Process: 7716 ExecStart=/opt/nbfc/start-nbfcservice.sh (code=exited, status=0/SUCCESS)
 Main PID: 7719 (mono)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/nbfc.service
           └─7719 /usr/bin/mono /usr/lib/mono/4.5/mono-service.exe -m:NbfcService /opt/nbfc/NbfcService.exe -l:/run/nbfc.pid

janv. 27 19:09:07 asus.intra.pick.fr systemd[1]: Starting NoteBook FanControl service...
janv. 27 19:09:07 asus.intra.pick.fr systemd[1]: nbfc.service: PID file /run/nbfc.pid not readable (yet?) after start: No such file or directory
janv. 27 19:09:07 asus.intra.pick.fr systemd[1]: Started NoteBook FanControl service.
```
but 5 seconds after, it fail with another error message :
```
# systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit-hit) since ven. 2017-01-27 19:09:08 CET; 1s ago
  Process: 7716 ExecStart=/opt/nbfc/start-nbfcservice.sh (code=exited, status=0/SUCCESS)
 Main PID: 7719 (code=exited, status=1/FAILURE)

janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: nbfc.service: Unit entered failed state.
janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: nbfc.service: Failed with result 'exit-code'.
janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: nbfc.service: Service hold-off time over, scheduling restart.
janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: Stopped NoteBook FanControl service.
janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: nbfc.service: Start request repeated too quickly.
janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: Failed to start NoteBook FanControl service.
janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: nbfc.service: Unit entered failed state.
janv. 27 19:09:08 asus.intra.pick.fr systemd[1]: nbfc.service: Failed with result 'start-limit-hit'.
```

**Comment by kevincaradant** [comment]
@jpick , Do you have follow the link from here: https://github.com/hirschmann/nbfc/issues/163#issuecomment-275731993

**Comment by jpick** [comment]
@hirschmann, I forget to mention I had enabled the service.

Even if I reenable the service :
```
# systemctl enable nbfc --now
# mono nbfc.exe config -a "Asus Zenbook UX410UAK"
```

I still get the same error :
```
# systemctl start nbfc
[root@asus nbfc]# systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: disabled)
   Active: active (running) since ven. 2017-01-27 19:21:22 CET; 16ms ago
  Process: 7903 ExecStart=/opt/nbfc/start-nbfcservice.sh (code=exited, status=0/SUCCESS)
 Main PID: 7906 (mono)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/nbfc.service
           └─7906 /usr/bin/mono /usr/lib/mono/4.5/mono-service.exe -m:NbfcService /opt/nbfc/NbfcService.exe -l:/run/nbfc.pid

janv. 27 19:21:22 asus.intra.pick.fr systemd[1]: Starting NoteBook FanControl service...
janv. 27 19:21:22 asus.intra.pick.fr systemd[1]: nbfc.service: PID file /run/nbfc.pid not readable (yet?) after start: No such file or directory
janv. 27 19:21:22 asus.intra.pick.fr systemd[1]: Started NoteBook FanControl service.

# systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: disabled)
   Active: activating (start) since ven. 2017-01-27 19:21:23 CET; 1ms ago
 Main PID: 7916 (code=exited, status=1/FAILURE); Control PID: 7923 (start-nbfcservi)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/nbfc.service
           └─7923 /bin/bash /opt/nbfc/start-nbfcservice.sh

janv. 27 19:21:23 asus.intra.pick.fr systemd[1]: Starting NoteBook FanControl service...

# systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit-hit) since ven. 2017-01-27 19:21:24 CET; 3s ago
  Process: 7923 ExecStart=/opt/nbfc/start-nbfcservice.sh (code=exited, status=0/SUCCESS)
 Main PID: 7926 (code=exited, status=1/FAILURE)

janv. 27 19:21:23 asus.intra.pick.fr systemd[1]: nbfc.service: Failed with result 'exit-code'.
janv. 27 19:21:24 asus.intra.pick.fr systemd[1]: nbfc.service: Service hold-off time over, scheduling restart.
janv. 27 19:21:24 asus.intra.pick.fr systemd[1]: Stopped NoteBook FanControl service.
janv. 27 19:21:24 asus.intra.pick.fr systemd[1]: nbfc.service: Start request repeated too quickly.
janv. 27 19:21:24 asus.intra.pick.fr systemd[1]: Failed to start NoteBook FanControl service.
janv. 27 19:21:24 asus.intra.pick.fr systemd[1]: nbfc.service: Unit entered failed state.
janv. 27 19:21:24 asus.intra.pick.fr systemd[1]: nbfc.service: Failed with result 'start-limit-hit'.
```

**Comment by jpick** [comment]
Oups, I found my issue. There was a typo in my .xml configuration file !

```
$ mono /opt/nbfc/nbfc.exe status
Service enabled		: True
Read-only		: False
Selected config name	: Asus Zenbook UX410UAK
Temperature		: 35

Fan display name	: Fan #1
Auto control enabled	: True
Critical mode enabled	: False
Current fan speed	: 0.00
Target fan speed	: 0.00
Fan speed steps		: 10
```

Sorry again for the confusion.

**Comment by jpick** [comment]
@hirschmann : I suggest to add in the [First steps](https://github.com/hirschmann/nbfc/wiki/First-steps) wiki page a mention of the location of the main configuration file `/etc/NbfcService/NbfcServiceSettings.xml`.

It takes me two hours to understand (thanks to strace) that my mono-service was loading the wrong Configs/.xml file.  :-)

**Comment by hirschmann** [comment]
Good idea. Maybe it's somewhat exaggerated, but I have created an overview of important files and dirs, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview
:)

**Comment by kevincaradant** [comment]
No it's perfect.  I lost time to get every files as you mentioned in the new wiki page.  So it's really a good idea :)

**Comment by jpick** [comment]
Thank you hirschmann !

**Comment by hirschmann** [comment]
Enabled restart on failure: 47e6bcdd5338bf33e534044b82baaf5173cdf6c5
