### ISSUE TITLE
Lenovo ideapad z570

### ISSUE THREAD

**Issue by grkn137** [hirschmann/nbfc#164]
hi
need Lenovo Ideapad z570 and g570 notebook fan control settings
im using ideapad500s option now but im not sure this option looking not true
if u can make this settings i will very grateful
thanks

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
