### ISSUE TITLE
Read and write doesn't exist any more

### ISSUE THREAD

**Issue by JacMac** [hirschmann/nbfc#167]
the link in the manual lead to an empty page and i need to know of an alternative to read and write because my laptop doesn't have a  config

**Comment by hirschmann** [comment]
You can use [ec-probe](https://github.com/hirschmann/nbfc/wiki/EC-probing-tool) instead.

**Comment by dude-sam** [comment]
is it possible to write to IO space ? the system im working on changes the fan speed by writing to a register in the IO space. Thank you
