### ISSUE TITLE
HP Elitebook 755 G2

### ISSUE THREAD

**Issue by hjjy1005** [hirschmann/nbfc#168]
I've downloaded your app, and tried to find my laptop, but there wasn't among the lists.
I tried all of HP laptops that were listed, and at least waited for 5 seconds each to see if it works, but the fan didn't get slowed down at all.
If there's any other config that might work on my laptop, please let me know.. 
Or, if you could add the config for my laptop, I would appreciate it very much.
I've been spending my whole day to find a single software that can control the fan, but it's really hard.
Please help me.. I desperately need it ASAP..
Thank you,

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
