### ISSUE TITLE
Razer Blade late 2016 (GTX1060) config file for inclusion

### ISSUE THREAD

**Issue by hokasu** [hirschmann/nbfc#171]
This is a config file put together by a few guys on the[ notebookreview forum](http://forum.notebookreview.com/threads/razer-blade-2016-fan-control-success.792655/page-4) 
and I thought it would make sense to add to your repository. I don't have push access, so I've attached it. I've had to change the extension to txt as XML files aren't allowed to be attached.
[Razer Blade GTX1060 xml.txt](https://github.com/hirschmann/nbfc/files/706352/Razer.Blade.GTX1060.xml.txt)

I'm sure it could be improved on, but as it stands it is a massive improvement on the laptop's usual behaviour and means those who would usually be driven crazy by 50% fans when the cpu is 30 degrees can use their computer.

**Comment by hirschmann** [comment]
Is this config stable? Or does it cause battery issues and random shutdowns like some other Razer configs?

**Comment by hokasu** [comment]
This one hasn't caused me any problems yet, but I've only been using it for
a couple of days. Once I've tested it more thoroughly I'll let you know.

**Comment by genghisbong** [comment]
@hokasu 
It's not actually normal behavior. The fans spinning at 50%+ on idle is a known issue with the new Razer Blade. A lot of people have been complaining about it.

@hirschmann 

It causes random shutdowns for me. It's a shame that there isn't a great solution to the Razer Blade fan issue. Without NBFC, the fans spin at 50% even on idle. A lot of people have been complaining about it since November and Razer has been ignoring it.

**Comment by genghisbong** [comment]
@hirschmann
It causes random shutdowns for me. It's a shame that there isn't a great solution to the Razer Blade fan issue. People have been complaining about it since November and Razer has been ignoring it.

**Comment by hokasu** [comment]
I've found the same problems as others when on battery power. When plugged in it works well.

**Comment by hirschmann** [comment]
Well, random shutdowns are intolerable, so I can't add this config to the repo.
Anyway, thanks for your effort.

**Comment by github-account1111** [comment]
> @hirschmann It causes random shutdowns for me. It's a shame that there isn't a great solution to the Razer Blade fan issue. People have been complaining about it since November and Razer has been ignoring it.

What fan issue?
Are you saying the laptop shuts down on its own when on battery even without nbfc?
