### ISSUE TITLE
asus g74sx

### ISSUE THREAD

**Issue by posydon** [hirschmann/nbfc#173]
Hey what configuration to use asus g74sx

**Comment by RypeDub420** [comment]
Try any of the other ROG configs. I have an ASUS G75VX and one of them worked for me. My registers were 151 for CPU and 152 for GPU.

**Comment by hirschmann** [comment]
Let NBFC recommend a config: `nbfc.exe config  --recommend`

Also see [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by posydon** [comment]
Hey. I have a laptop Asus G74Sx and want to create a config. Chip IT8572E 1124-AXA DCEBVB. The cooling system is cleared. What parameters need to be taken from the datasheet for the config?
