### ISSUE TITLE
ASUS K501UX - on battery mode

### ISSUE THREAD

**Issue by keresztesizoli** [hirschmann/nbfc#174]
Hi,

is there somebody who experiences lagging on battery mode, too?
There is no problem at all while charging my notebook, but on battery mode it's the opposite.

What do I need to configure to eliminate this problem?

Thx

**Comment by etemplar** [comment]
Check out windows task manager while notebook is lagging.

Do you see "System Interrupts" process highloading cpu?

My k501ux was terribly slow on battery too until I've upgraded wifi adapter driver to newer version (surprisingly). System interrupts' process was starting to take too much cpu after couple of minutes of intense browsing on wifi.
I switched adapter to driver version 10.0.0.345.
