### ISSUE TITLE
NBFC 1.5.0 / Asus UX51VZ: Service Switches to "read only" after standby

### ISSUE THREAD

**Issue by juepi** [hirschmann/nbfc#175]
Hardware: ASUS UX51VZA (original, unmodified NBFC config)
OS: Win10 x64 v1607
NBFC: 1.5.0 (updated from 1.4.2)

Problem:
Sometimes after waking up the notebook from STD, NBFC service switches itself to "read only", leading to a running CPU fan. After manually switching the service to "Enabled" in the NBFC GUI, everything is fine.

Workaround:
Downgraded to version 1.4.2 where this problem does not exist.

**Comment by hirschmann** [comment]
It's ok if the service switches itself to 'read only' before standby/hibernate, but it should actually restore the previous state after waking up from standby/hibernate.

Could you please post the service's event log entries for the last week:
```powershell
Get-EventLog -LogName "Application" -Source "NoteBookFanControlService" -After $(Get-Date).AddDays(-7) | select TimeGenerated, Message
```

**Comment by juepi** [comment]
Hello Stefan,

Attached the requested info (CSV format):
[nbfc-events.zip](https://github.com/hirschmann/nbfc/files/736246/nbfc-events.zip)

I've extended the time range to -10 days, as i've downgraded to 1.4.2 7 days ago (when i filed the bug). I've been running 1.5.0 a few days before that when i've sometimes experienced this problem (not always i think).

yours,
Juergen

**Comment by hirschmann** [comment]
Thanks for the log.
Looks like you encounter the same error 1.4.2 as well, but it's not noticeable because unlike 1.5, 1.4.2 doesn't switch to read-only mode before standby/hibernate.

I couldn't reproduce this bug on my system and I haven't figured out why it happens yet.
Since 1.4.2 works fine for you, just stay at that version until the bug is fixed.

**Comment by juepi** [comment]
Hi Stefan,

I've interpreted the logs the same way :)
Will stay on 1.4.2, as mentioned, works perfectly well for me!

thanks,
Juergen

**Comment by plikojim** [comment]
Hello to all,
I was writing by reading this interesting post and this program I thought would solve my problem asus UX51VZ
the fans always work 100% I tried versions 1.4.2 1.5 and beta 1.5.3 but the speed remains unchanged.
I can not do other tests apart from a possible downvolt that I would not do if possible
Thanks for your help
Ps Italian language :)

**Comment by juepi** [comment]
Hello Plikojim,

This sounds like  a hardware defect to me. Even without NBFC the fans in my UX51VZ were practiallcy never spinning at 100% (they were always running, but at low speeds). I assume an defective EC would also explain why NBFC is not working..

Yours,
Juergen

**Comment by plikojim** [comment]
so there's nothing left that downvolt I think ...
other solutions?
I just replaced display 400 € :(

**Comment by juepi** [comment]
To be honest, i have no idea what you mean with "downvolt"..
if you think of placing a resistor in the fan's power cable, i think this is not a proper solution, as the fans cannot spin at the required speed if your notebook is under heavy load, thus your CPU / GPU will probably overheat.

Maybe you should check BIOS settings and also see if you can upgrade the BIOS (this also often re-flashs the EC afaik). Also make sure that you have the ASUS ATK software package installed, i think this one also has something to do with the EC.
AND of course, check that your CPU is idle. My ASUS Smart Gesture bullshit software sometimes hangs and causes 100% CPU load, in which case the fans also spin up of course ;)

hth,
Juergen
