### ISSUE TITLE
Temperature thresholds

### ISSUE THREAD

**Issue by Juan6306** [hirschmann/nbfc#177]
Dear Geoff, 

What are temperatures Up Threshold and Down Threshold when I edit a fan config. For example, one of your config was set: 
- Up Threshold = 60C, Down Threshold = 48C => Fan Speed = 10%
- Up Threshold = 63C, Down Threshold = 55C => Fan Speed = 20%

Why these 2 temperature ranges are overlapped?

Thanks!!!

**Comment by hirschmann** [comment]
I've added an example to the TemperatureThreshold wiki page: https://github.com/hirschmann/nbfc/wiki/Temperature-threshold#example

Hope this clarifies how the thresholds work.
