### ISSUE TITLE
New (14. Nov) Lenovo Ideapad 500s config not working

### ISSUE THREAD

**Issue by DerFisc** [hirschmann/nbfc#179]
Hi there,
the new Lenovo Ideapad 500s config from the commit 
eec7c090b7d444a346eaf32583667e40f124694d (14. Nov)
is not working for my Lenovo Ideapad 500s-13ISK.

The temp is correct but the fan speed is displaying 183,5% without actually changing or taking over the system fan speed control. It has no visible effect at all.

The config file from before the commit is working as expected for me, so i took that in the meantime.

I'm not sure if this also applies to other 500s variants.

Greetings and thanks for your great work
Michael

**Comment by hirschmann** [comment]
I've added a config for the Ideapad 500S-13ISK and renamed the current 500S config to 500S-14ISK: 7c19c5c1d521c65dfd89c0609cb79c9f40f49df3
