### ISSUE TITLE
Lenovo Z70-80 support

### ISSUE THREAD

**Issue by Brodigdy** [hirschmann/nbfc#180]
Hi. Could You add please config for Lenovo Z70-80? It has the same specs as the Lenovo U31-70 (same processor and chipset), i see correct temperatures and fan speed on Lenovo U31-70 preset, but i can't set desired fan speed, it's just not working. Could You help me please? :) Thanks, and sorry for my english.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
