### ISSUE TITLE
nbfc triggers tons of pcieport errors in syslog

### ISSUE THREAD

**Issue by andaag** [hirschmann/nbfc#181]
System: Asus K501UX running ubuntu 16.04.

```
jan. 29 20:50:17 kevin kernel: pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
jan. 29 20:50:17 kevin kernel: pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
jan. 29 20:50:17 kevin kernel: pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
jan. 29 20:50:17 kevin kernel: pcieport 0000:00:1c.5:    [ 0] Receiver Error 
```

I get these continously in the system log. And the fan is off. If I disable the service the fan comes back on instantly. I've tried ramping up the cpu a little bit to see if it turns on, but it doesn't seem to be doing it at all. I haven't put too much pressure on the system though.

**Comment by hirschmann** [comment]
Are you sure this is caused by nbfc?
Seems more like a driver problem, see http://askubuntu.com/questions/748078/nvidia-geforce-930m-driver-and-pci-bus-error
