### ISSUE TITLE
lenovo 710s

### ISSUE THREAD

**Issue by Vikerules** [hirschmann/nbfc#183]
i got the lenovo 710s-13ikb model=80VQ

cant find it in the latest version. i cant use this in school without annoying people because of this stupid fan noise. please help! :(((

**Comment by Plasmatree** [comment]
Here is the NBFC config file I created for the Leovo 710s. It has a steeper response and the fans switch off faster as the temperature drops. 
Surfing is now fanless.

https://www.file-upload.net/download-12295597/LENOVO710s.xml.html

Please mind I am using throttlestop with the 710s, which lowers power consumption and thus temperature (and improves gaming performance. It actually makes the difference between "almost" and "perfect" gamecube emulation! ;) ). 
Keep an eye on your temps and feel free to adjust the fanspeeds to your needs!

**Comment by MenschA** [comment]
Got my 710S today (with Skylake, not Kabylake) and it works perfectly fine. 
THANKS!

**Comment by Vikerules** [comment]
doesnt work, literally nothing happens when i use that config

**Comment by Plasmatree** [comment]
Ah, 13ikb is the kabylake model?
The config is based on a skylake model. Seems like Kabylake needs a different config then. 

Have you tried to make your own file? My guess is that there is just some kind of offset in the EC values. The whole prcedure is nicely explained in [here](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjL8uDygoDSAhWnJMAKHR0NC1gQFggcMAA&url=http%3A%2F%2Fforum.notebookreview.com%2Fattachments%2Fnotebook-fancontrol-user-manual-pdf.105862%2F&usg=AFQjCNEaVvuhgJRXMsfD9mGsxMWj7oJDJQ&cad=rja), page 4-6. It's even kind of fun! :)

**Comment by Vikerules** [comment]
ok so as i was about to get ready to try and make my own config file i noticed the fan wasent making any noise at all so i checked my temps and what kind of config file was active at the time and it was the one you linked above. now, magically out of the blue the config file you linked works 100% on my model. i dont know what i did or how i did it but it now works! thank you so much. this config file needs to get more exposure

**Comment by hirschmann** [comment]
I agree, this config needs to get more exposure for sure.
Therefore I've added it to the repo: 6eb7fdbcefdcf2637c2e74378d8af312eb81910d

Thank you very much @Plasmatree! 👍

**Comment by StigguLePetit** [comment]
It worked thanks mate! CPU tempeture is between 40 and 45°C while surfing. Is this a problem for the processor? i have the i7 7200U version.
