### ISSUE TITLE
Asus UX52VS issue

### ISSUE THREAD

**Issue by 123456x** [hirschmann/nbfc#19]
Hi. I have a major problem with NBFC. I have had the fan of my notebook Asus "zenbook" UX52VS going crazy, it was starting and stopping several times in several minutes. So I have installed NBFC, and boy did it screw up my computer. Without even realizing that there is no control with this program for my model, the program completely took over the fan control. As it does  not support my model, I have uninstalled it, however, my fan doesn't work at all now, my GPU is constantly crashing, even my Windows media player is lagging as the fan is not working. I have reinstalled the program and set fan on another Asus model, to run at 100%, then everything is fine and the computer is not crashing. Once I again unistall the NBFC, fan again loses all the functionality. Can I go back to my default settings? There are no fan settings in BIOS. Can I somehow recall what the NBFC done to my computer? Should I send it to Asus experts to re-do all this damage that this program done to my notebook?

**Comment by hirschmann** [comment]
Remove the battery (if possible)  and press and hold the power-button for some seconds.
If that doesn't work, read the manual of your notebook. There must be a way to reset it.
