### ISSUE TITLE
finer fan control speed % ?

### ISSUE THREAD

**Issue by d-theo** [hirschmann/nbfc#190]
Hi,

Everything works well expect than i can only set 0, 25%, 50% or 100% fan speed. Even If i edit the xml file by myself to put like 15%, the nbfc tells me that my current fan speed is 0% and target is 15% so nothing happen
Is that a problem with my configuration ?

**Comment by hirschmann** [comment]
Yes, it's a problem with your config.

The number of availalbe fan speed steps (%) depends on what you have set for _MinSpeedValue_ and _MaxSpeedValue_, see https://github.com/hirschmann/nbfc/wiki/Basic-fan-configuration#minspeedvalue

**Comment by d-theo** [comment]
thank you for your answer, I assumed with MinSpeedValue=0 and MaxSpeedValue=100 it would work but it looks like I don't understand the documentation correctly. Now the display is indeed correct but doesn't match the actual speed of the fan

**Comment by hirschmann** [comment]
Some notebooks have a "fan always on" BIOS-setting which prevents the fan from stopping.
Also some ECs refuse to stop the fan if the temperature is over a certain threshold.

You can work around the latter by faking the temperature like this (see _RegisterWriteConfigurations_): https://github.com/hirschmann/nbfc/blob/master/Configs/HP%20ProBook%206465b.xml

**Comment by d-theo** [comment]
Oh sorry, I meant that I seems that the lowest RPM I can get (beside being off) is 2000 whatever _FanSpeed_ / _MinSpeedValue_ / _MaxSpeedValue_ I set if _FanSpeed_ > 0.
For now I set the _FanSpeed_ to 0 until 65° but I wished that I could set my fan to something like 1000 RPM to avoid some extra CPU heat.

Anyway your software deserve a beer ;)

**Comment by hirschmann** [comment]
Ok, well, min. RPM is indeed a hardware limitation, so there is not much you can do about it besides installing a better fan.

I'm glad you like NBFC anyway :)
