### ISSUE TITLE
Acer V5-552G - no GPU-Temp

### ISSUE THREAD

**Issue by Benman2785** [hirschmann/nbfc#193]
Hi, i have Acer V5-552G (A10 5757m + HD 8750m)

i use the config of Acer Aspire V5-572G and it works - but it only shows me CPU-Temp and not GPU-Temp

is there any way to fix this?

**Comment by hirschmann** [comment]
On Windows the NBFC service can't access the GPU because of Windows security restrictions (session 0 isolation).

**Comment by hirschmann** [comment]
see #203
