### ISSUE TITLE
ASUS K450JF

### ISSUE THREAD

**Issue by electecnickmk** [hirschmann/nbfc#195]
Hi guys I come from thailand. alright my ploblem is my notebook(K450JF) not found in notebooklist . I try to select the notebook that i think is most similar but it still not work. how can i do? 
PS. Sorry if my language is not good

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
