### ISSUE TITLE
Using NBFC on ultracompacts?

### ISSUE THREAD

**Issue by lozoliref** [hirschmann/nbfc#197]
Hi.

Your software is brilliant. Would it be possible to use it for small desktops as well? I'm thinking mostly of ultracompacts like the Asus Vivomini UN65U and Intel NUC where you can't replace fans etc. easily.

**Comment by hirschmann** [comment]
I don't own a ultracompact, so I can't test it myself. You could try it out yourself (and please let me know if it works :))
