### ISSUE TITLE
Gui doesn´t open any more

### ISSUE THREAD

**Issue by Fragy1** [hirschmann/nbfc#198]
Hi, I have the Acer Aspire VN17 Nitro BE. I used NBFC for a while, but suddenly the gui is away and doesn´t open anymore. Pls help, because my Gpu reached temperatures over 100 degrees and all games i want to play are unplayable.

**Comment by hirschmann** [comment]
NBFC works fine even without the GUI client. 
You could either use the command line interface to control NBFC: https://github.com/hirschmann/nbfc/wiki/Command-line-interface
or delete the GUI settings and try to start the GUI again: 
https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by RypeDub420** [comment]
Try using Revo Uninstaller Pro to remove the program and all registry entries. The free trial will accomplish this.

Then reinstall as admin AND run the shortcut as admin.

**Comment by hirschmann** [comment]
Uninstalling and then reinstalling software to solve a problem is - in my opinion - a bad idea, because event if it works afterwards, you don't know what went wrong in the first place.
Using 3rd party tools like Revo Uninstaller to uninstall software is a even worse idea, because it is hard to track down what it does (maybe it fucks up something) and you still don't know why it actually solved your problem (if it does).

I really recommend to have a look at the GUI client's settings file:
https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

If it is corrupted, please post the file content here, so I can find out what went wrong.
Then delete the settings file and restart the GUI.

**Comment by Fragy1** [comment]
After deleting the file and restarting it works, but i dont know how to post the broken file here

**Comment by hirschmann** [comment]
Just open the file in any file editor and copy&paste the content here.

**Comment by Fragy1** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <NbfcClient.Properties.Settings>
            <setting name="UpgradeRequired" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="TrayIconForegroundColor" serializeAs="String">
                <value>#FFFFFFFF</value>
            </setting>
            <setting name="WindowHeight" serializeAs="String">
                <value>421</value>
            </setting>
            <setting name="WindowWidth" serializeAs="String">

**Comment by Fragy1** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <NbfcClient.Properties.Settings>
            <setting name="UpgradeRequired" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="TrayIconForegroundColor" serializeAs="String">
                <value>#FFFFFFFF</value>
            </setting>
            <setting name="WindowHeight" serializeAs="String">
                <value>421</value>
            </setting>
            <setting name="WindowWidth" serializeAs="String">`

**Comment by hirschmann** [comment]
Thank you. Obviously, only half of the settings were saved to disk. I will look into this.

**Comment by BenStuart** [comment]
Fyi I also have a Nitro Black Edition (VN7-591G), I faced what seems to be the same issue. One fate filled day I opened the application then attempted to select the config from the drop-down box and the drop-down was empty.

Probably doesn't help but my config outlined below.

`<?xml version="1.0"?>
<FanControlConfigV2 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NotebookModel>Aspire VN7-591G</NotebookModel>
  <Author>JL</Author>
  <EcPollInterval>3000</EcPollInterval>
  <ReadWriteWords>false</ReadWriteWords>
  <CriticalTemperature>80</CriticalTemperature>
  <FanConfigurations>
    <FanConfiguration>
      <ReadRegister>149</ReadRegister>
      <WriteRegister>148</WriteRegister>
      <MinSpeedValue>255</MinSpeedValue>
      <MaxSpeedValue>98</MaxSpeedValue>
      <ResetRequired>true</ResetRequired>
      <FanSpeedResetValue>255</FanSpeedResetValue>
      <FanDisplayName>Left fan</FanDisplayName>
      <TemperatureThresholds>
        <TemperatureThreshold>
          <UpThreshold>0</UpThreshold>
          <DownThreshold>0</DownThreshold>
          <FanSpeed>0</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>66</UpThreshold>
          <DownThreshold>59</DownThreshold>
          <FanSpeed>10.191083</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>68</UpThreshold>
          <DownThreshold>63</DownThreshold>
          <FanSpeed>32.4840775</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>71</UpThreshold>
          <DownThreshold>67</DownThreshold>
          <FanSpeed>100</FanSpeed>
        </TemperatureThreshold>
      </TemperatureThresholds>
      <FanSpeedPercentageOverrides />
    </FanConfiguration>
    <FanConfiguration>
      <ReadRegister>152</ReadRegister>
      <WriteRegister>151</WriteRegister>
      <MinSpeedValue>255</MinSpeedValue>
      <MaxSpeedValue>98</MaxSpeedValue>
      <ResetRequired>true</ResetRequired>
      <FanSpeedResetValue>255</FanSpeedResetValue>
      <FanDisplayName>Right fan</FanDisplayName>
      <TemperatureThresholds>
        <TemperatureThreshold>
          <UpThreshold>0</UpThreshold>
          <DownThreshold>0</DownThreshold>
          <FanSpeed>0</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>66</UpThreshold>
          <DownThreshold>58</DownThreshold>
          <FanSpeed>10.191083</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>70</UpThreshold>
          <DownThreshold>60</DownThreshold>
          <FanSpeed>30.5732479</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>71</UpThreshold>
          <DownThreshold>67</DownThreshold>
          <FanSpeed>80.891716</FanSpeed>
        </TemperatureThreshold>
      </TemperatureThresholds>
      <FanSpeedPercentageOverrides />
    </FanConfiguration>
  </FanConfigurations>
  <RegisterWriteConfigurations>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnInitialization</WriteOccasion>
      <Register>147</Register>
      <Value>20</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>4</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
      <Description>Set EC to manual control</Description>
    </RegisterWriteConfiguration>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnInitialization</WriteOccasion>
      <Register>150</Register>
      <Value>20</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>4</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
    </RegisterWriteConfiguration>
  </RegisterWriteConfigurations>
</FanControlConfigV2>`

**Comment by hirschmann** [comment]
Give the latest beta a try. It already includes a improved settings system.
There will also be automatic settings backups in the next stable release.
