### ISSUE TITLE
Help! Is anyone available to make a config of new Dell XPS 15 9560?

### ISSUE THREAD

**Issue by hwf442073199** [hirschmann/nbfc#201]
I bought this dell xps 15 9560 a couple days ago and the fan speed issue is bothering me. It is loud even just web browsing. I hope someone could make its config which helps xps owner a lot!

**Comment by RypeDub420** [comment]
Have you tested the XPS M1530 config?

Also, read here: https://github.com/hirschmann/nbfc/wiki/EC-probing-tool

**Comment by mqudsi** [comment]
The M1530 profile does not work for the 9560 (neither read nor write).

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by makedir** [comment]
So is the 9560 not supported? That would be bad news.

**Comment by makedir** [comment]
@mqudsi did you test making a config for the 9560?
