### ISSUE TITLE
Lenovo IdeaPad Y580 Config

### ISSUE THREAD

**Issue by Dimon1358** [hirschmann/nbfc#204]
Hi, I've found a working config for Lenovo Y580 made by user nicknamed IL_DECAMERON from techinferno web site.

[Lenovo IdeaPad Y580.zip](https://github.com/hirschmann/nbfc/files/872133/Lenovo.IdeaPad.Y580.zip)

**Comment by hirschmann** [comment]
Thank you very much for the config.
Have you tested the config on your notebook? If yes, is it working without any problems?

**Comment by Dimon1358** [comment]
Yes, it works fine, but Lenovo laptops do have a fan speed limiter. It means that you can't reach 100% fan speed (it's limited on 85,7%), limiter turns off only when you use dust cleaner in lenovo energy utility.

**Comment by hirschmann** [comment]
I've added the config: 28e4c59c1bbbbf34d1680f6477dd09df746083f6
