### ISSUE TITLE
All fields empty, 0°C

### ISSUE THREAD

**Issue by M1st3rN0b0d7** [hirschmann/nbfc#207]
Hi,

I have an Asus N550JV and v1.5.0 of NoteBook Fan Control.
Everytime I reboot my computer, I have this problem :

![screen shot 04-02-17 at 07 52 pm](https://cloud.githubusercontent.com/assets/23179122/24589637/34c755e8-17de-11e7-8769-246845ed2d87.PNG)

And the only thing I can do to make it work again is use the "repair" option.

Thanks.

**Comment by hirschmann** [comment]
Looks like the service isn't running.
Please post a log: https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by ajayyy** [comment]
You just have to restart the service from the task manager.

![image](https://user-images.githubusercontent.com/12688112/27756911-b18ae53c-5dc9-11e7-85c1-f8b61f953ca4.png)

I have to do it everytime I restart my computer.
