### ISSUE TITLE
Data for Lenovo 710s Plus?

### ISSUE THREAD

**Issue by Janoosch** [hirschmann/nbfc#208]
Hey guys,
I absolutely love this program, but the optimal config for my notebook is missing.
Could smb please creat it for me or help me to create it??
Would be awesome!
It´s this laptop: https://www.amazon.de/gp/product/B01MY6EEDK/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1  the 512gb version!
 
Edit: The existing config by Florian for the normal 710S doesnt seem to work for me.
My fans wont turn off, even if my laptop is at 40 degrees celsius..
Janoosch

**Comment by Vilo176** [comment]
I'm trying too to make a suitable config file for 710S+.

As far as I understand it, 710S+ has only one fan, and its speed value can be read at offset 06.
Min value is 00, max seams to be near 64 (decimal).

But I can't find any "Write Register" offset.
Offsets 05 and 07 values are always 00, and writing something to them do not cause anything.
I'm stuck ...

**Comment by Vilo176** [comment]
Good news : "Lenovo Yoga 710" config works fine with 710S+ ;-)

**Comment by Vilo176** [comment]
Yoga 710 works, but is not optimal.
I've tuned the original file to suit 710S and my own needs.

[Lenovo IdeaPad 710S plus.xml.txt](https://github.com/hirschmann/nbfc/files/1063824/Lenovo.IdeaPad.710S.plus.xml.txt)

**Comment by MikkelCph** [comment]
Ppoys: to use a config you must save the .xml file in the configs-folder on your machine (e.g. C:\Program Files (x86)\Notebook FanControl\Configs). Then find the config in the NBFC app.
