### ISSUE TITLE
Is it safe to just uninstall NBFC?

### ISSUE THREAD

**Issue by davidgitgud** [hirschmann/nbfc#209]
Hi, I have installed NBFC and applied a profile but decided that I want to go back to the default(factory) fan settings. How would I go about doing this? Are there any extra steps or do I just uninstall it from windows normally?

Thanks :)

EDIT: Just curious, is NBFC actually controlling fans when read-only is checked or do I have to enable it?
![image](https://cloud.githubusercontent.com/assets/25834518/24821882/0d512f40-1ba6-11e7-9980-6eac5412ba95.png)

**Comment by hirschmann** [comment]
NBFC **doesn't** control the fans if it is in read-only mode. You have to enable it.
If you want to restore factory defaults, just uninstall NBFC. The setup/uninstaller will rollback all changes. You don't have to take any extra steps.
If the setup fails to restore the factory settings, please follow these instructions: https://github.com/hirschmann/nbfc/wiki/FAQ#is-there-a-way-to-reset-my-notebook-if-something-went-wrong
