### ISSUE TITLE
How can I adjust min speed of the fan?

### ISSUE THREAD

**Issue by maihoanglai** [hirschmann/nbfc#210]
I tried many ways to config the min speed of laptop fan but I couldn't. My laptop just have 4 speeds at: 25%, 50%, 75% and 100%. And at 25% the speed about 4000 rpm and It's really noise even If the laptop was not running any load and the temp was about 40 - 45 oC. Can you show me how to decrease the min of the speed to about 2000 rpm or 3000 rpm? I also tried to config the temp threshold to 10% but when It was at 10% the fan didn't run. By the way, my laptop model is Asus K501UB. Looking forward to hearing from you soon. Thank you.

**Comment by cdosorio** [comment]
Those 4 speeds are the only availables in the "Target fan speed" slider of main screen? In my laptop (an Asus too) the values availables are 0%, 12.5% 25% and so on, so I copied those values to a config file, and finally got a silent laptop when just using the browser.

**Comment by maihoanglai** [comment]
Yes. 4 speeds are the only availables. But I don't have 12.5% like you. I just have from 25% and at this point the fant reach at 4000rpm. Can you show me how to add 12.5% to the "Target fan speed"?

**Comment by cdosorio** [comment]
I guess that those available values are queried by nbfc to some registry in the laptop, then displayed in the slider. If that is the case, I hope someone else can clarify us if is possible to add 0%.

**Comment by maihoanglai** [comment]
I'm sorry for your misunderstanding. I provided missing information. I got 0% too but my problem is my laptop usually either 0% (0rpm) or 25% (4000rpm). When I try to set > 0% and < 25% and the fan does not run. I just want to decrease the speed to 2000rpm or 3000rpm because 4000rpm is too noise.

**Comment by hirschmann** [comment]
See https://github.com/hirschmann/nbfc/wiki/Basic-fan-configuration#minspeedvalue
and
https://github.com/hirschmann/nbfc/wiki/Probe-the-EC%27s-registers

**Comment by maihoanglai** [comment]
I'm sorry but my problem is that no matter how my computer is set up It just either 0% = 0 rpm or higher than 0% (0.1% ~ 100%) and it always run from 4000 rpm. I haven't seen it lower than 4000 rpm(2000rpm, 3000rpm...) So even if I don't use the computer It always run at least 4000 rpm. Anyone can help?

**Comment by maihoanglai** [comment]
I'm sorry but can I write negative number as fan speed?

**Comment by barisasli** [comment]
Plz help me where i can change laptop fan speed 3000rpm always just browsing on internet new laptop 2 month old
