### ISSUE TITLE
how can I donate? When I click in the program it crashes.

### ISSUE THREAD

**Issue by sarciccio5674** [hirschmann/nbfc#211]
I'm using fan control on my asus n76vz and it works really good. in the program there's the link about donating but it crashes the program. how can i donate to the original developer?

thanks

marco

**Comment by hirschmann** [comment]
I'm glad you like nbfc :)
I couldn't reproduce this error. Is there any kind of error message before the program crashes?

Anyway, you can donate via this [paypal donation link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=HUALCC9HY9MKC).

**Comment by sarciccio5674** [comment]
no error at all :)

thanks

2017-04-11 13:16 GMT+02:00 Stefan Hirschmann <notifications@github.com>:

**Comment by 48296** [comment]
@sarciccio5674 Hey, What configuration do you use on your n76VZ ?

**Comment by sarciccio5674** [comment]
@48296 I just selected Asus N56VZ the 15" version and it's ok
