### ISSUE TITLE
Issues after updating to Windows 10 Creators Update

### ISSUE THREAD

**Issue by techrosis** [hirschmann/nbfc#215]
Fan control seems to still be working, however if you hover the mouse over the temperature notification in the taskbar it disappears/crashes.  This means you can not right-click to reopen the UI.  Tried completely reinstalling nbfc but still the same results.  Checking it from cli shows the service is running fine and the fans seem to still work as set via the profile.

**Comment by hirschmann** [comment]
I couldn't reproduce this error on Windows 10 (with creators update installed).
Have you checked if the NotebookFanControl process is still running when this happens?
Wild guess: maybe Windows just hides the NBFC tray icon.

**Comment by techrosis** [comment]
Yes, the process is still running.  I always have my taskbar notifications set to show all icons (don't want anything sneaking in down there hehe).  When it happens, the process is still running in task manager as well as from command line if you do the nbfc status check thing.  Very strange indeed.  The only way I can get it to work is to log out and log back in (which closes all tasks and fires them back up).  I've learned to just be aware of my mouse pointer and not hover over the number hehe.

**Comment by b0xBR** [comment]
Hi hirschmann!

I'm also having this same issue. I did a clean install with w10 x64 Creators Update and after configured for the first time NBFC, the UI couldn't be opened again.

**Comment by hirschmann** [comment]
Please try this:
- uninstall NBFC
- delete the GUI settings, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview
- install the latest nightly build: https://ci.appveyor.com/project/hirschmann/nbfc/build/artifacts

**Comment by techrosis** [comment]
Just tried it.  Same results :(

**Comment by b0xBR** [comment]
I also tried and got the same results. =(

**Comment by Erriez** [comment]
Starting the "NoteBook FanControl Service" displays: "Error: 1067: The process terminated unexpectedly." on my brand new HP Pavilion 17-ab240nd with Windows 10 Creators Update. I'd like to add support for this notebook. The issue reported above seems to be related to the service which cannot be started.

My Event Log displays: 
```
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: NbfcService.exe
P2: 1.3.0.0
P3: 585520de
P4: StagWare.Hardware
P5: 1.0.0.0
P6: 585520e1
P7: c
P8: 60
P9: System.PlatformNotSupported
P10: 

...
```

I've the following behavior when starting NoteBookFanControl.exe installed from the setup: 
* GUI comes up. 
* Click the Browse button, no configs available. (As reported earlier) 
When I start the NbfcClient debugger from source and click the Browse button, it displays in SelectConfigViewModel.cs line 84: 

`if (this.availableConfigs == null)
{
	this.availableConfigs = new ObservableCollection<string>(client.GetConfigNames());
}`

> ArgumentNullException was unhandled by user code
An exception of type 'System.ArgumentNullException' occurred in System.dll but was not handled in user code

So there is a difference in behavior between the release and in the debugger.

> System.PlatformNotSupported

Maybe related to StagWare.FanControl | FanCtonrol.cs | 
`throw new PlatformNotSupportedException(`

Any ideas how to fix the service?

**Comment by hirschmann** [comment]
No, your issue is not related:

> Problem signature:
P1: NbfcService.exe
P2: 1.3.0.0
P3: 585520de
P4: StagWare.Hardware
P5: 1.0.0.0
P6: 585520e1
P7: c
P8: 60
**P9: System.PlatformNotSupported**
P10: 

Your notebook is not supported. Please upgrade your NBFC version, see #213

**Comment by hirschmann** [comment]
@techrosis @b0xBR 
I can't solve this issue without error logs, but unfortunately, the client application doesn't log anything (mea culpa).
I'll implement logging and let you know when I'm done.

**Comment by Erriez** [comment]
Now it works perfect! This is what I've done:
- Previous 1.5.0 installation removed
- Reboot
- Files removed:
```
Install directory 	C:\Program Files (x86)\NoteBook FanControl\
Configs directory 	C:\Program Files (x86)\NoteBook FanControl\Configs\
Service settings 	C:\ProgramData\NbfcService\
GUI client settings 	%userprofile%\AppData\Roaming\StagWare\
```
- 1.5.1 installed as you suggested:
> Your notebook is not supported. Please upgrade your NBFC version, see #213
- Service is started correctly.

Thanks for your help.

**Comment by hirschmann** [comment]
@techrosis @b0xBR
I've slightly improved taskbar icon related code and added logging support.
Please check out the latest nightly:
https://ci.appveyor.com/project/hirschmann/nbfc/build/95/artifacts

Logs will be created at `%appdata%\NbfcClient\`

Note: upgrading from one nightly build could fail. It is recommended to uninstall the previous build before installing the latest nightly.

**Comment by b0xBR** [comment]
@hirschmann.
I uninstalled the previous nightly and installed the new one, cleaned all folders as explained above etc. 
Do I have to enable this logging? Because It's not creating any %appdata%\NbfcClient folder.
Also, the GUI doesn't even pop up now.

**Comment by hirschmann** [comment]
In nightly build 95 a library is missing.
It's included in build 96: https://ci.appveyor.com/project/hirschmann/nbfc/build/96/artifacts

**Comment by b0xBR** [comment]
First log.

AssemblyVersion: 1.4.3.0

Timestamp	Level	Message	Exception	Callsite	Stacktrace
2017-04-23 00:58:19.4611	INFO	App start		NbfcClient.App..ctor	App.Main => App..ctor
2017-04-23 00:58:19.8115	WARN	Attempt to call a service method failed	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Object reference not defined for a instance of object. (The fail detail is equal to ExceptionDetail, probably created by IncludeExceptionDetailInFaults=true, which value is:
System.NullReferenceException: Object reference not defined for instance of object.
   in StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   in SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   in System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   in System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   in System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   in System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   in System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.Services.FanControlClient.CallServiceMethod	SimpleIoc.DoGetService => Delegate.DynamicInvokeImpl => RuntimeMethodInfo.UnsafeInvokeInternal => RuntimeMethodHandle.InvokeMethod => SimpleIoc.MakeInstance => RuntimeConstructorInfo.Invoke => RuntimeMethodHandle.InvokeMethod => MainViewModel..ctor => FanControlClient.GetFanControlInfo => FanControlClient.CallServiceMethod

**Comment by hirschmann** [comment]
Did the error occur when this log was created?
I see nothing which would make the task bar icon disappear.

**Comment by b0xBR** [comment]
@hirschmann yeap, the error occured when I opened the app for the first time.

**Comment by hirschmann** [comment]
Ok, new build which logs more stuff: https://ci.appveyor.com/project/hirschmann/nbfc/build/100/artifacts

**Comment by b0xBR** [comment]
new log.

AssemblyVersion: 1.4.3.0

Timestamp	Level	Message	Exception	Callsite	Stacktrace
2017-04-23 19:13:27.4497	INFO	App start		NbfcClient.App..ctor	App.Main => App..ctor
2017-04-23 19:13:27.8090	DEBUG	A first chance exception occurred	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.App+<>c.<.ctor>b__1_1	FanControlClient.CallServiceMethod => <>c__DisplayClass16_0.<GetFanControlInfo>b__0 => IFanControlService.GetFanControlInfo => RealProxy.PrivateInvoke => ServiceChannelProxy.Invoke => ServiceChannelProxy.InvokeService => ServiceChannel.Call => ServiceChannel.HandleReply => ServiceChannel.ThrowIfFaultUnderstood => <>c.<.ctor>b__1_1
2017-04-23 19:13:27.8090	DEBUG	A first chance exception occurred	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.App+<>c.<.ctor>b__1_1	RuntimeConstructorInfo.Invoke => RuntimeMethodHandle.InvokeMethod => MainViewModel..ctor => FanControlClient.GetFanControlInfo => FanControlClient.CallServiceMethod => <>c__DisplayClass16_0.<GetFanControlInfo>b__0 => IFanControlService.GetFanControlInfo => RealProxy.PrivateInvoke => RealProxy.HandleReturnMessage => <>c.<.ctor>b__1_1
2017-04-23 19:13:27.8247	WARN	Attempt to call a service method failed	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.Services.FanControlClient.CallServiceMethod	SimpleIoc.DoGetService => Delegate.DynamicInvokeImpl => RuntimeMethodInfo.UnsafeInvokeInternal => RuntimeMethodHandle.InvokeMethod => SimpleIoc.MakeInstance => RuntimeConstructorInfo.Invoke => RuntimeMethodHandle.InvokeMethod => MainViewModel..ctor => FanControlClient.GetFanControlInfo => FanControlClient.CallServiceMethod
2017-04-23 19:13:30.6208	DEBUG	A first chance exception occurred	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.App+<>c.<.ctor>b__1_1	FanControlClient.CallServiceMethod => <>c__DisplayClass16_0.<GetFanControlInfo>b__0 => IFanControlService.GetFanControlInfo => RealProxy.PrivateInvoke => ServiceChannelProxy.Invoke => ServiceChannelProxy.InvokeService => ServiceChannel.Call => ServiceChannel.HandleReply => ServiceChannel.ThrowIfFaultUnderstood => <>c.<.ctor>b__1_1
2017-04-23 19:13:30.6208	DEBUG	A first chance exception occurred	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.App+<>c.<.ctor>b__1_1	ExceptionWrapper.InternalRealCall => DispatcherTimer.FireTick => FanControlClient.timer_Tick => FanControlClient.GetFanControlInfo => FanControlClient.CallServiceMethod => <>c__DisplayClass16_0.<GetFanControlInfo>b__0 => IFanControlService.GetFanControlInfo => RealProxy.PrivateInvoke => RealProxy.HandleReturnMessage => <>c.<.ctor>b__1_1
2017-04-23 19:13:30.6364	WARN	Attempt to call a service method failed	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.Services.FanControlClient.CallServiceMethod	ExecutionContext.Run => ExecutionContext.Run => ExecutionContext.RunInternal => DispatcherOperation.InvokeImpl => ExceptionWrapper.TryCatchWhen => ExceptionWrapper.InternalRealCall => DispatcherTimer.FireTick => FanControlClient.timer_Tick => FanControlClient.GetFanControlInfo => FanControlClient.CallServiceMethod
2017-04-23 19:13:33.6909	DEBUG	A first chance exception occurred	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.App+<>c.<.ctor>b__1_1	FanControlClient.CallServiceMethod => <>c__DisplayClass16_0.<GetFanControlInfo>b__0 => IFanControlService.GetFanControlInfo => RealProxy.PrivateInvoke => ServiceChannelProxy.Invoke => ServiceChannelProxy.InvokeService => ServiceChannel.Call => ServiceChannel.HandleReply => ServiceChannel.ThrowIfFaultUnderstood => <>c.<.ctor>b__1_1
2017-04-23 19:13:33.6969	DEBUG	A first chance exception occurred	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.App+<>c.<.ctor>b__1_1	ExceptionWrapper.InternalRealCall => DispatcherTimer.FireTick => FanControlClient.timer_Tick => FanControlClient.GetFanControlInfo => FanControlClient.CallServiceMethod => <>c__DisplayClass16_0.<GetFanControlInfo>b__0 => IFanControlService.GetFanControlInfo => RealProxy.PrivateInvoke => RealProxy.HandleReturnMessage => <>c.<.ctor>b__1_1
2017-04-23 19:13:33.6969	WARN	Attempt to call a service method failed	"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Referência de objeto não definida para uma instância de um objeto. (O Detalhe da Falha é igual a ExceptionDetail, provavelmente criado por IncludeExceptionDetailInFaults=true, cujo valor é:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em StagWare.FanControl.Service.FanControlService.GetFanControlInfo()
   em SyncInvokeGetFanControlInfo(Object , Object[] , Object[] )
   em System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   em System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   em System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))."	NbfcClient.Services.FanControlClient.CallServiceMethod	ExecutionContext.Run => ExecutionContext.Run => ExecutionContext.RunInternal => DispatcherOperation.InvokeImpl => ExceptionWrapper.TryCatchWhen => ExceptionWrapper.InternalRealCall => DispatcherTimer.FireTick => FanControlClient.timer_Tick => FanControlClient.GetFanControlInfo => FanControlClient.CallServiceMethod

**Comment by hirschmann** [comment]
I moved the log into a file because it was unreadable the way you posted it.
The log still doesn't contain any errors. From my perspective it seems like this isn't a bug in NbfcClient.

**Comment by b0xBR** [comment]
@hirschmann 
I simply formatted once again my machine (ASUS ROG G751JT) and after installed the latest nightly build, it opened GUI successfully. After configured and restarted OS, the GUI crashes again. Maybe the problem isn't the GUI itself, but the tray icon?

**Comment by techrosis** [comment]
OMG I found the fix!!  At least on my machine.  I was running the stable version of MSI afterburner which uses rivertuner statics server.  While trying to figure out why reshade setup wouldn't working someone in that forum said there was a beta version of rivatuner that changed the application hooks.  I updated it and low and behold it fixed my reshade issues as well as the gui for notebook fan control heheh

Here's the link if anyone else is having this issue and also running MSI afterburner:
http://office.guru3d.com/afterburner/RTSSSetup700Beta17.rar

**Comment by JoergPeterHahn** [comment]
![grafik](https://user-images.githubusercontent.com/27731730/36415871-afd51bd8-1627-11e8-82ca-ea702212506d.png)
Hi, I have a Lenovo Yoga 710-14|KB, Model 80V4, which should be supported, and the fan control seems to work well. But after rebooting some icons on the task bar do not show up.
