### ISSUE TITLE
Lenovo Miix 720 - Noise fan

### ISSUE THREAD

**Issue by xxskorpion88xx** [hirschmann/nbfc#226]
Hi 

On lenovo miix 720 the problem is the same of lenovo 710.

Config file of 710 miix help only to detect temp value but do not help to adjust anything.
Please add a config file for lenovo Miix 720

**Comment by Sursodd** [comment]
I have the same issue. A config file for the "Miix 720" would be great.

**Comment by Sursodd** [comment]
Hi, 

I've tested some of the configs and the one for the "Lenovo Yoga 3 14" affects my fan. Maybe this config can be modified for the Miix 720.

**Comment by duguyushu** [comment]
Hi, I need that too. I have tried using rw everything to find out the write register, but it seems that 3 register is related with the fan, and I don't which one should be the write register.

**Comment by duguyushu** [comment]
I have use one register and successfully control the fan speed. However, it seems that the notebook fancontrol service conflicts with system ACPI, and the ACPI service tries to access EC, mostly fails, and sometimes success. Even though I set EC pull interval to minimum 100ms, the fan will be sudden start and stop for a very short time, looks like it is suddenly started by ACPI and quickly stopped by fan control. Does this problem appear on other notebooks? Is there any solutions?

**Comment by maihoanglai** [comment]
Maybe I got the same problem with you on Asus K501UB. If the CPU temp is higher than 40oC It keeps spin 4000rpm or higher even I don't use any weight application. I don't know how to set It to 2000 or 3000. This sound drives me crazy.

**Comment by int3ks** [comment]
same problem here. does anyone know what tries to restart the fan ? is this the bios the EC controller itself or an acpi device on windows??? anyway to stop this? it sounds like a defectiy harddisk! i dont like this sound :(

**Comment by chrismin13** [comment]
Any updates on this? I'm considering getting a Miix 720 to replace my Surface Pro 4 since I'm afraid it'll start flickering. Is the fan really that annoying? Does NBFC work, or is the clicking sound still there? Thanks.
