### ISSUE TITLE
ACER SWIFT 3 SF314-51-37QT

### ISSUE THREAD

**Issue by Shisukor** [hirschmann/nbfc#229]
Hello,
my english is not the best so ignore my mistakes.
I have a little issue with my acer swift 3. Could you please insert my Model into the programm ?
I´ve seen a lot of guys using it but my acer is not in the list....

Hoping you read this.

Thanks for doing this !!!

**Comment by parzt** [comment]
Same problem here.

The Swift 3 makes an annoying whistling sound even when little performance is needed.

**Comment by idkfaaa** [comment]
Hi, not only the Acer Swift 3 - I have the same Problem with my Acer Swift 5 - really annoying fan sound and I could not handlt eh nbfc configuration for it. I think if there would be a configuration for the swift 3 / 5 we could use it for both modells. there are a lot of users in the amazon forums having the same issues with this series (swift 3 / 5).
Would be awesome to have a nbfc configuration.

**Comment by Shisukor** [comment]
I think i got it for the Swift 3 !
Just try the Acer Espire E1-772. For me it works most of the time, but when i play a game it doesnt work. I think caus it gets really hot.

Tell me if it works.
