### ISSUE TITLE
Any option for Pavilion DV7 7070sw?

### ISSUE THREAD

**Issue by VersusVes** [hirschmann/nbfc#230]
Hello everyone and thanks for help in advance. I already tried HP Pavilion DV6 that is similar but without any effect.

**Comment by smtrejo** [comment]
Check issues https://github.com/hirschmann/nbfc/issues/247 and https://github.com/hirschmann/nbfc/issues/246 and https://github.com/hirschmann/nbfc/issues/137

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
