### ISSUE TITLE
Lenovo Yoga 720-13IKB

### ISSUE THREAD

**Issue by joost14** [hirschmann/nbfc#232]
Hi, 

I've seen the config for the yoga 710, are you willing to add the config for the yoga 720 too? 
I don't think the configs will be much different (Not for me to say), so i hope you are willling to add the laptop in the next update.

Thank you in advance !

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
