### ISSUE TITLE
NBFC 1.5.0 is shutting down my laptop randomly

### ISSUE THREAD

**Issue by deathnoise** [hirschmann/nbfc#234]
..without showing any information, whatsoever. And by that I don't mean the Windows restart. What I mean is that it literally switches off my laptop, instantly (power off), after some random time. It doesn't matter if I'm gaming or if the laptop is idling on the Windows desktop. It might be a couple of minutes, an hour or a day and then, suddenly, it goes off.

After going back to the 1.4.2 version of NBFC everything works just fine. No restarts for more than a week, now.

I've got Asus G751JT, with Haswell 4720HQ processor.

**Comment by hirschmann** [comment]
Please post a NBFC service log, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by deathnoise** [comment]
It's even worse with the newest (beta) version. I've got a shutdown just after 10 minutes from the time I've installed the NBFC.

There is nothing in the logs.

But I've got this in the Event Log, before the shutdown:
http://i.imgur.com/J1LY15k.png

**Comment by hirschmann** [comment]
Random shutdowns are usually caused by an incompatible config (the G751JT is not officially supported), or incompatibilities with other software, see https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc

**Comment by deathnoise** [comment]
I've been able to solve the problem. I've got VOLTGROUND profile for nbfc.
It turns out that the EcPollInterval has been set to a wrong value. It's been set to "300" for the original configuration. After rising it to "600" everything works great, even with the newest version of NBFC. So - there is nothing wrong with your software.

I've found some useful information on asus rog forums:

> Then I have tried setting it to minimum, which means 100ms. But this isn't good either because writing too often in the EC Table left me with some weird values written all over the registers. These values can make your notebook act weird, and I have some personal exampleslike: the fans start bursting into full speed, the battery led starts blinking orange, the battery is not detected, the notebook goes into sleep mode by random, or the battery capacity isn't showing correctly. Most of these problems are repaired by resetting the Embedded Controller by pressing and holding the power button for 10 secs until the battery led shuts off and starts again. Now, after I have found what did cause some of the biggest troubles I have found that a Poll Interval of 500ms is just right to avoid any of them. 

Except that 500ms value didnt work for me, either.. But 600 works OK.
So the problem has been solved, thanks :)

https://rog.asus.com/forum/showthread.php?58501-Making-of-quot-Official-NotebookFanControl-G751JY-Profile-quot
