### ISSUE TITLE
NBFC 1.5.0 nbfcservice cannot start (1067)

### ISSUE THREAD

**Issue by an94baller** [hirschmann/nbfc#235]
Notebookfancontrol service will stop running, cannot be started no matter what.

Only a clean uninstall using revo uninstaller will fix the problem.

Using cmd "net start nbfcservice" will result in error 1067.

Problem can be triggered by trying to select a notebook profile and loading them. After a few seconds the program will crash due to nbfcservice crashing. 

The next time you try to run, the program will not work correctly due to nbfcservice refusing to work.

Thanks in advance.

Razer Blade 14 2017 Kaby Lake 7700HQ/GTX1060 6G

**Comment by hirschmann** [comment]
Please post a NBFC service log, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview
