### ISSUE TITLE
nbfc causing APCI "event 13" Error  (HP elitbook 8770w + windows 10)

### ISSUE THREAD

**Issue by rezpower** [hirschmann/nbfc#239]
This was happening before creators update, but not a real issue. I have been using nbfc for long now and 
the error was nothing to worry about. Now I am getting a ton of the same error coming up is system log.
I updated to latest version tonight and the problem is still here. If I uninstall problem is gone! Can you help
me figure out what is causing the error and eventually a way to fix it?

**Comment by hirschmann** [comment]
These ACPI errors occur because NBFC accesses the EC directly instead of evaluating ACPI methods via the Windows ACPI driver. This is kind of a hack, but unfortunately on many notebooks the only way to control the fan(s).

As long as NBFC doesn't cause any negative side effects, you can safely ignore those error messages.

**Comment by rezpower** [comment]
Thanks a lot for the fast reply. Yes, the ACPI error was something I was totally ignoring for a long time as it did not have any negative side effect. But after the windows creators update my laptop keyboard randomly stops working and non of the keys work anymore. Even restarting the laptop dose not solve the problem. I have to shutdown the computer and turn in back on and it works again and the ACPI errors have jumped from few ( accruing in a distant manner) , to a lot of them (10's or 20's successive ones).

**Comment by deathnoise** [comment]
try to raise the EcPollInterval by 100 in your XML NBFC profile, over and over again until the problem is gone..

**Comment by rezpower** [comment]
Thanks a lot for the reply. I did change the EcPollInterval value my 100 ms and went up and down from the original 3000 value to as low as 300 and up to 4000. the changes made some change to the amount of errors I was getting and in some cases there were no errors at all at least on startup. But as soon as I run games or cpu intensive software (for which i need  nbfc) erros come back and at some point the keyboard become non functional and the only solution to fix it is to turn off pc and turn it back on.

I still really hope that someone will find a solution as without nbfc my notebook run very hot and I'm sure it will be damaged soon as it happened before using nbfc. (had to replace the motherboard)
