### ISSUE TITLE
Linux service is disabled

### ISSUE THREAD

**Issue by AndersStigsson** [hirschmann/nbfc#24]
After going through your steps and checking the status I just get 

Service enabled		: False
Selected config name	: 
Temperature		: 0

Could not get fan info because the service is disabled

And I've tried both through the shell script and by doing mono nbfc.exe start

Any clues?

**Comment by hirschmann** [comment]
Looks like no config has been applied, so the service refuses to start.

It should work if you follow those steps:
1. Start the daemon as root: `su start-nbfcservice.sh`
2. Apply a config: `nbfc.exe -config -a "name of the config file for your notebook (without extension! (.xml))"`
3. Start the NBFC service `nbfc.exe start`

**Comment by AndersStigsson** [comment]
Works great now, don't know what the difference to what I did earlier is, but I'm happy it works!

**Comment by aaronspring** [comment]
I use Ubuntu 16.04. I use NBFC since more than a year on my Lenovo Yoga 13 running windows os and appreciate the program a lot.

I am facing a similar problem, however also the fix here above doesnt help me.

`aaron@aaron-Lenovo-IdeaPad-Yoga-13:/opt/nbfc$ mono nbfc.exe status`
`Service enabled		: False
Selected config name	: 
Temperature		: 0
Could not get fan info because the service is disabled`

Also I cannot apply the config file, Lenovo Yoga 13 2191 in my case.

`nbfc.service is running: systemctl status nbfc`
```
nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: enabled)
   Active: active (running) since So 2016-08-28 22:01:19 CEST; 5min ago
  Process: 21090 ExecStart=/opt/nbfc/start-nbfcservice.sh (code=exited, status=0/SUCCESS)
 Main PID: 21094 (mono)
   CGroup: /system.slice/nbfc.service
           └─21094 /usr/bin/mono /usr/lib/mono/4.5/mono-service.exe -m:NbfcService /opt/nbfc/NbfcService.exe -l:/run/nbfc.pid
Aug 28 22:01:19 aaron-Lenovo-IdeaPad-Yoga-13 systemd[1]: Starting NoteBook FanControl service...
Aug 28 22:01:19 aaron-Lenovo-IdeaPad-Yoga-13 systemd[1]: nbfc.service: PID file /run/nbfc.pid not readable (yet?) after start: No such file or
Aug 28 22:01:19 aaron-Lenovo-IdeaPad-Yoga-13 systemd[1]: Started NoteBook FanControl service.
Aug 28 22:01:20 aaron-Lenovo-IdeaPad-Yoga-13 mono[21094]: NbfcService: Service NoteBookFanControlService started
```

Any clues?

**Comment by hirschmann** [comment]
NBFC was unable to load a compatible EC plugin on Ubuntu 16.04. This bug has been fixed with 08598e2201a5c23e312ac0ba67587dea11188f8f

Just compile NBFC from the latest sources.

**Comment by aaronspring** [comment]
Thank. Now I get further I think. 
Got this new version. 
in /opt/nbfc/
`mono nbfc.exe config --apply "Lenovo Yoga 13 2191"
mono nbfc.exe start
>> Failure has occurred while loading a type.
mono nbfc.exe status
>> Could not load type 'StagWare.FanControl.FanInformation' from assembly 'StagWare.FanControl, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null'.
`
Any idea? I found a folder StagWare.FanControl in Core and in there the FanInformation.cs but couldnt resolve the issue.

**Comment by hirschmann** [comment]
I can't reproduce this error. I built NBFC from the latest sources on Ubuntu 16.04 and it works without any problems.
Is there a 'StagWare.FanControl.dll' in /opt/nbfc?

**Comment by aaronspring** [comment]
yes, there is.
`
aaron@aaron-Lenovo-IdeaPad-Yoga-13:/opt/nbfc$ ls -all
total 220
drwxr-xr-x 4 root root  4096 Sep 22 21:56 .
drwxr-xr-x 4 root root  4096 Sep 22 22:20 ..
-rw-r--r-- 1 root root 69120 Sep 22 21:54 clipr.dll
drwxr-xr-x 2 root root  4096 Sep 22 21:55 Configs
-rwxr-xr-x 1 root root 11264 Sep 22 21:54 ec-probe.exe
-rwxr-xr-x 1 root root 21504 Sep 22 21:54 nbfc.exe
-rw-r--r-- 1 root root   770 Sep 22 21:54 nbfc.exe.config
-rwxr-xr-x 1 root root  6656 Sep 22 21:54 NbfcService.exe
-rw-r--r-- 1 root root  1075 Sep 22 21:54 NbfcService.exe.config
drwxr-xr-x 2 root root  4096 Sep 22 21:56 Plugins
-rwxr-xr-x 1 root root 25600 Sep 22 21:54 StagWare.FanControl.Configurations.dll
-rwxr-xr-x 1 root root 25088 Sep 22 21:54 StagWare.FanControl.dll
-rwxr-xr-x 1 root root 17408 Sep 22 21:54 StagWare.FanControl.Service.dll
-rwxr-xr-x 1 root root    95 Sep 22 21:54 start-nbfcservice.sh
-rwxr-xr-x 1 root root    39 Sep 22 21:54 stop-nbfcservice.sh
`

**Comment by hirschmann** [comment]
I still can't reproduce this error.

Please remove everything related to nbfc from your system and then follow those 2 guides:
* [How to build NBFC](https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC)
* [First steps](https://github.com/hirschmann/nbfc/wiki/First-steps)

**Comment by aaronspring** [comment]
Now it works.

Danke dir. Sau geiles Programm !!!
