### ISSUE TITLE
ASUS ZenBook UX510UW

### ISSUE THREAD

**Issue by pawurb** [hirschmann/nbfc#240]
Hello. Is there a chance of adding config for ASUS ZenBook UX510UW ? I was wondering if it would be safe to use config for Asus K501UX on this model ? I don't have much experience with your program so far.

If not then I can be of any help providing details, profile stats etc. of UX510UW if you need it to create config.

**Comment by hirschmann** [comment]
You can give the Asus K501UX cofnig a try. Btw. NBFC can recommend configs: `nbfc.exe config --recommend`

See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
