### ISSUE TITLE
ThinkPad T460p

### ISSUE THREAD

**Issue by sz4b0lcs** [hirschmann/nbfc#241]
Hi! Does anybody have any idea what config would match with this machine?
I've tried all the Lenovo ones, but nothing's even close.

Or if anybody has the knowledge, could you please help me creating a config?

Thanks a lot!

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
