### ISSUE TITLE
Please fix this issue in the next version

### ISSUE THREAD

**Issue by NavidDanesh** [hirschmann/nbfc#242]
Sometimes when I rapidly hover the cursor over NBFC tray icon, the pop up box appears on the top left corner of the screen and doesn't fade for several minutes even by opening or closing the main NBFC window.
(Tested on Windows 10 pro x64 creators update)
Thanks for your great job.
![shot](https://cloud.githubusercontent.com/assets/27695915/26282464/2ea4ee18-3e27-11e7-8219-e15afd161afa.jpg)

**Comment by hirschmann** [comment]
Maybe this is related to https://github.com/hirschmann/nbfc/issues/215#issuecomment-303531820
