### ISSUE TITLE
Can someone make profile for Sony Vaio VPCF1* all users of this model would be thankful.

### ISSUE THREAD

**Issue by hernanisilvaa** [hirschmann/nbfc#244]
Hi 

Many people may know this laptop series  Sony Vaio Vpcf1* from suffering of fan noise, a little search in google for vpcf1* fan noise, and theres a lot, i mean a lot of people complaning about the fan noise.

If someone could make a profile for this model would be wonderfull.

I dont know what files people need to this but i am glad to help whatever you need to do this.

Thank you 

Sorry for the bad english.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
