### ISSUE TITLE
auto setting with min & max

### ISSUE THREAD

**Issue by JorisDebonnet** [hirschmann/nbfc#245]
First of all: fantastic work! I should have found this a year ago... 

Now, I was wondering whether an auto setting with a min and/or max value is available. Right now I can either set the fan(s) to either Auto, or to a specific percentage. Is it possible to make it 'Auto' within a certain range? For example: prevent it from dropping below 10% or from going above 70%?

**Comment by hirschmann** [comment]
I'm glad you like NBFC :)

Of course it's possible to adjust the 'auto'-behavior according to your needs. After all, that's what NBFC is all about. Just edit the temperature thresholds in the config you're currently using, see https://github.com/hirschmann/nbfc/wiki/Temperature-threshold

**Comment by JorisDebonnet** [comment]
Aha, great, thanks for the pointer!
