### ISSUE TITLE
Latest version is not working on an Asus Ux31a

### ISSUE THREAD

**Issue by shunyata0** [hirschmann/nbfc#25]
Hi,

I just downloaded your app to help tone down the constant fan noise on my Asus Ux31a. The application starts perfectly and loads the proper configuration. The issue is that despite being able to change the target fan speed setting, and having the current fan speed bar reflect this change, the fan speed does not actually change; it runs constantly at a high setting despite CPU temp only reading at 42 degrees Celsius. I can set the target fan speed to any increment on the slider, from 0% incrementally all the way to 100%, with no change in actual fan speed. I tried running the program in administrative mode to see if that would make a difference but it did not. Perhaps this a hardware issue on my machine.

Thanks for you time and effort in making this great application,

R.H.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
