### ISSUE TITLE
Please add a Profile for: ASUS ZenBook UX501VW

### ISSUE THREAD

**Issue by TheGITofTeo997** [hirschmann/nbfc#253]
Could you please add a configuration for the ASUS ZenBook UX501VW, it is a shame that this great tool doesn't have it since it has all the other ZenBook series models. Thanks to this tool the notebook can get better temps so it would be great to add a specific configuration for that model too.

Thanks in advance

**Comment by Sacharpie** [comment]
I think it is the same as the G501JW :)

**Comment by TheGITofTeo997** [comment]
oh thanks @Sacharpie, but i am using like UX301 or something like that ahhaha, let me try the one you said!

**Comment by hirschmann** [comment]
Please let me know if the G501JW config also works for the UX301.

In case it doesn't, have a look at https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
