### ISSUE TITLE
Current Fan Speed - Negative Value

### ISSUE THREAD

**Issue by MatthewPortman** [hirschmann/nbfc#255]
Hi,

I hope I'm not missing something but I've been unable to get nbfc to change the fan speed on my laptop. It's an HP Pavilion dv6 so I've been using the configuration file for it. 

I've attempted to manually set the fan speed and also let it sit on auto to no avail. I'm very new to Linux so I apologize if I'm missing anything crucial! 

Thanks

Here's the terminal readout after messing around with it a little bit:

> /opt/nbfc#

> mono nbfc.exe set -s 100
> /opt/nbfc# mono nbfc.exe status -a
> Service enabled		: True
> Read-only		: False
> Selected config name	: HP Pavilion dv6
> Temperature		: 75
> 
> Fan display name	: Fan #1
> Auto control enabled	: False
> Critical mode enabled	: False
> Current fan speed	: -64.29
> Target fan speed	: 100.00
> Fan speed steps		: 14
> 
> /opt/nbfc# mono nbfc.exe set -a
> /opt/nbfc# mono nbfc.exe status -a
> Service enabled		: True
> Read-only		: False
> Selected config name	: HP Pavilion dv6
> Temperature		: 81
> 
> Fan display name	: Fan #1
> Auto control enabled	: True
> Critical mode enabled	: False
> Current fan speed	: -64.29
> Target fan speed	: 20.00
> Fan speed steps		: 14

**Comment by shanemeagher** [comment]
Using 1.5.3-beta release, I'm having a similar issue under Windows 10 on a HP Pavilion DV6-3042tx. The 'HP Pavilion dv6' config is selected.

When switching to Read-only mode, the fan speed displays a negative. It seems to work okay when set to Enabled though with the correct fan speed displayed and the fan reacting to manual changes.

![image](https://user-images.githubusercontent.com/2144292/29167145-d7b210e4-7dfb-11e7-80c2-6967373c1154.png)
![image](https://user-images.githubusercontent.com/2144292/29167122-c5a6a7b6-7dfb-11e7-9393-b8f0cd75536f.png)

If more info is needed, let me know what logs / commands to run.

**Comment by hirschmann** [comment]
There are many different HP Pavilion dv6 models.
If none of the configs which come with NBFC works, try to create one yourself: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by EuphoriaCelestial** [comment]
It show negative number on my HP ZBook 15 too, when the laptop is cool and fan not running (or not run fast, because I cant hear noise and cant feel air-flow comes out)

**Comment by RubenNL** [comment]
For anyone else finding this: This might be because the BIOS option "fan always on when charger is plugged in" is on. You might want to try to disable it.
