### ISSUE TITLE
Can you please provide a config for Asus Zenbook UX310UQ.xml

### ISSUE THREAD

**Issue by Neohiro79** [hirschmann/nbfc#257]
That would be awesome!

**Comment by Neohiro79** [comment]
Here the link:

https://www.asus.com/de/Laptops/ASUS-Zenbook-UX310UQ/

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
