### ISSUE TITLE
Please, Add Configuration for Asus Zenbook UX330UA

### ISSUE THREAD

**Issue by Gianca90** [hirschmann/nbfc#259]
Hello!

Right now I'm using the profile of the ux360ua, but the change of the fan speed is slow... I think is because there's no dedicated profile/configuration for my laptop (UX330UA).

The fan of this notebook is very noisy and too aggressive... your Notebook Fan Control is wonderful for this problem!

If you need some files or other thing to make a configuration/profile for the UX330UA, feel free to contact me!

P.s. I'm on Windows 10

https://www.asus.com/us/Laptops/ASUS-ZenBook-UX330UA/

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
