### ISSUE TITLE
Temperature discrepancy on Asus G1Sn

### ISSUE THREAD

**Issue by jesse-git** [hirschmann/nbfc#26]
The temperature shown in NBFC is always ~5°C cooler than what is reported elsewhere. I regularly monitor temperature in Speedfan (looking at the lowest value between "Core 0" and "Core 1") and RightMark CPU Clock Utility. These 2 programs both agree on temperature. NBFC temperature does not seem to correspond to any temperature shown in Speedfan.

Able and willing to do any test, as long as it doesn't destroy my laptop :)

**Comment by jesse-git** [comment]
Open Hardware Monitor has the same dependency, but agrees with all other programs on all other sensors. My CPU is Core 2 Duo T7500.
Open Hardware Monitor reports TjMax of 95C. Intel's [spec page](http://ark.intel.com/products/29761/Intel-Core2-Duo-Processor-T7500-4M-Cache-2_20-GHz-800-MHz-FSB) says 100C. Is this the reason? Why the discrepancy?

**Comment by hirschmann** [comment]
There are two steppings of the Core 2 Duo T7500: E1 and G0
OpenHardwareMonitorLib does not recognize the E1 stepping and defaults to 95°C Tjmax.

Fixed it: 64c2133057deb74485ba459b8e60541fec463dc0
