### ISSUE TITLE
Notebook Fan control causes high dpc latency windows 10 and lag on games

### ISSUE THREAD

**Issue by edneyhelene** [hirschmann/nbfc#260]
Hello friend! Acer F5-573g-59aj  windows 10 x64 creators!

Your software works amazingly to controll fan with my notebook model, i do use 471g profile and works great!

The problem is: When i do turn it on it causes hugh fps drops on my games and on latencymon i can see that the acpi driver latency goes to the moon when its turned on!

Can u please fix it and save me? haha your software is the only one that works with my notebook model  i think and i would love to be able to use it without having these issues.

Its not my laptop problem or any other thing, i tried many many methods, formated, im also TI tech and wasnt able to fix it ... 

If you do need more information please let me know!

**Comment by edneyhelene** [comment]
Infos of the system!

[f5-573g-59aj dxdiag.txt](https://github.com/hirschmann/nbfc/files/1064840/f5-573g-59aj.dxdiag.txt)
[HWMonitorf5-573-59aj.txt](https://github.com/hirschmann/nbfc/files/1064841/HWMonitorf5-573-59aj.txt)

**Comment by hirschmann** [comment]
You could try to increase the poll interval in your config or disable NBFC during gaming.
I guess the config you've selected is not 100% compatible to your notebook and writes to registers which trigger ACPI-events. That could be the reason why you see an increased ACPI-driver latency.

I doubt I can help much with this problem. On my system, latencymon show no problem at all, even if I set the poll interval as low as 100ms.

**Comment by edneyhelene** [comment]
Can you please so write a config that is full compatible with my laptop model?

I have no reason to use it while not in game...the main reason i use it is to low temperature while playing only.

**Comment by hirschmann** [comment]
Sorry, but no. I have neither access to an Acer F5-573g-59aj, nor any knowledge about it.

**Comment by edneyhelene** [comment]
no problem, can u please tell me how do i make one  and test it? i will test it myself just need to understand how to do it hehehhe and insert the proper values =DD

**Comment by hirschmann** [comment]
I can't explain it in a few sentences, but currently I'm working on a tutorial about how to create a NBFC config. I will publish it in the NBFC Wiki when it's done.

In the meantime you can read the (outdated) NBFC user manual: https://1drv.ms/b/s!AjbOVawzvTRshCHgDRKhhzanSsRS

**Comment by edneyhelene** [comment]
No problem my friend, i just am note able to find wich values change because lots of em change and i cant identify the one i need =( any tips?

**Comment by hirschmann** [comment]
have a look at the brand new tutorial: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by edneyhelene** [comment]
Thank you so much! The dsdt method looks great im trying it right now =DD

**Comment by edneyhelene** [comment]
In my case what i found is this:
  OperationRegion (VERM, EmbeddedControl, Zero, 0xFF)
            Field (VERM, ByteAcc, NoLock, Preserve)
            {
                LNPS,   8
            }
            OperationRegion (ERAM, SystemMemory, 0xFE708500, 0x0100)
            Field (ERAM, ByteAcc, NoLock, Preserve)
            {
                ECTM,   8, 
                Offset (0x04), 
                CMCM,   8, 
                CMD1,   8, 
                CMD2,   8, 
                CMD3,   8, 
                Offset (0x18), 
                SMPR,   8, 
                SMST,   8, 
                SMAD,   8, 
                SMCM,   8, 
                SMD0,   256, 
                BCNT,   8, 
                SMAA,   8, 
                BATD,   16, 
                ACDF,   1, 
                Offset (0x41), 
                    ,   1, 
                APBF,   1, 
                    ,   3, 
                FLS4,   1, 
                Offset (0x42), 
                FLS3,   1, 
                    ,   1, 
                S0EF,   1, 
                    ,   4, 
                PECE,   1, 
                    ,   1, 
                LMAT,   1, 
                Offset (0x45), 
                ECPF,   8, 
                Offset (0x48), 
                KBBL,   1, 
                    ,   1, 
                RFST,   1, 
                Offset (0x49), 
                ERCT,   8, 
                Offset (0x4B), 
                TBLV,   8, 
                ARCD,   1, 
                    ,   3, 
                DOCK,   1, 
                LANC,   1, 
                LIDT,   1, 
                CRTS,   1, 
                Offset (0x4E), 
                TJMX,   3, 
                    ,   1, 
                VGAF,   1, 
                EDTS,   1, 
                Offset (0x53), 
                DOFF,   8, 
                Offset (0x58), 
                CTMP,   8, 
                RG59,   8, 
                Offset (0x60), 
                WLAN,   1, 
                BLTH,   1, 
                ST3G,   1, 
                CPLE,   1, 
                    ,   1, 
                ED3G,   1, 
                WLST,   1, 
                BLTS,   1, 
                    ,   1, 
                DPBL,   1, 
                    ,   4, 
                NIWM,   1, 
                TOHP,   1, 
                Offset (0x63), 
                WLPH,   1, 
                BBST,   1, 
                ODST,   1, 
                GPSW,   1, 
                Offset (0x64), 
                Offset (0x70), 
                BTMD,   8, 
                MBTS,   1, 
                MBTF,   1, 
                    ,   1, 
                MFCF,   1, 
                    ,   2, 
                MBDX,   1, 
                MBAD,   1, 
                MBTC,   1, 
                    ,   4, 
                MBPC,   1, 
                Offset (0x77), 
                BA1C,   8, 
                MCYC,   16, 
                MTMP,   16, 
                MDAT,   16, 
                MCUR,   16, 
                MBRM,   16, 
                MBVG,   16, 
                BHVC,   16, 
                BLVC,   16, 
                LFCC,   16, 
                BTSN,   16, 
                BTDC,   16, 
                BTDV,   16, 
                BTMN,   8, 
                Offset (0xBB), 
                TARU,   8, 
                TARN,   8, 
                TARD,   8, 
                Offset (0xC0), 
                ROMD,   8, 
                Offset (0xD0), 
                EBPL,   1, 
                    ,   1, 
                    ,   1, 
                TPRD,   1, 
                Offset (0xD1), 
                    ,   1, 
                ECS4,   1, 
                ECS3,   1, 
                RFAT,   1, 
                OSW8,   1, 
                WOLF,   1, 
                WOWL,   1, 
                Offset (0xD5), 
                ECDY,   8, 
                DBPL,   8, 
                CPTS,   8
            }
            Scope (\_SB)
            {


Question: what does these paths means? 8 is the cicle? so the frdc is the first? 0x04? or 0x18? im trying to understand the logical here hehehehe

**Comment by hirschmann** [comment]
The only thing relevant for you is EmbeddedControl space (EC registers), because this is how NBFC controls the fan.
I don't know what you mean by FRDC. There is no FRDC in the code you've posted.
The numbers next to the field names tell you how many bits are reserved for each field.

**Comment by edneyhelene** [comment]
i dont know anything else hahahahaa!

By the way here it is my config, please add it to the official software. Its working great.
http://www.mediafire.com/file/7jazu8fp395yy45/Acer_Aspire_F5-573G.xml

**Comment by hirschmann** [comment]
So, did you solve the latency problem?

**Comment by edneyhelene** [comment]
Nope it did not, you need to fix it in the software code and test with latencymon ....im sorry.

**Comment by hirschmann** [comment]
As far as I know, the latency problem exists only on your system. This seems not to be related to NBFC itself, but either to your system or the config you're using. Therefore I can't fix it.

I also can't add a config to the official repo wich causes fps drops and other latency problems, sorry.

**Comment by edneyhelene** [comment]
Its not the config that causes drops and problems, its your software...more users have the same problem...i have more than 3 friends with the same problem when they do use your software. cheers.

**Comment by hirschmann** [comment]
Could you please tell me which notebooks and which configs they are using?

**Comment by edneyhelene** [comment]
As far as i know they are all acer users using 471g config.

**Comment by hirschmann** [comment]
Are they all using the 471g config on an Acer Aspire E5-471G, or on unsupported Acer notebooks?
In case they are all using an Acer Aspire E5-471G, I think I have to drop support for the Acer Aspire E5-471G. I can't fix this issue because I can't reproduce it on my system.

**Comment by edneyhelene** [comment]
thats sad =(  acer sucks.

**Comment by hirschmann** [comment]
I've removed the config:  c20c4dd
Thanks for the bug report!

**Comment by 000masa000** [comment]
Hello, I recently started using notebook fan control on my HP Studio G5 x360 laptop (2018, i7 8850, 32 GB RAM, 2TB SSD) and it has been a joy to finally have the fans behaving quietly! I was using the config you provide for a HP Studio G3 since it was the one that came up, and is cinceivably close; then I slightly edited the response to temperatures and it works well on my machine. However, I am working with low latency audio and multiple applications (I am a composer) and was finding some occasional glitches in audio, so I checked LatencyMon only to find spikes of up to 3.5 ms in ACPI.sys. When I deactivate notebook fan control they go away (max 400 µs). It occurs also in read-only mode. I guess the config needs some tweaking to overcome this problem, and I hope you might have some advice how to proceed? Here is my config. Best, Marc Sabat masa@plainsound.org


<?xml version="1.0"?>
<FanControlConfigV2 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NotebookModel>HP ZBook Studio G5 x360</NotebookModel>
  <Author>Marc Sabat</Author>
  <EcPollInterval>1000</EcPollInterval>
  <ReadWriteWords>false</ReadWriteWords>
  <CriticalTemperature>85</CriticalTemperature>
  <FanConfigurations>
    <FanConfiguration>
      <ReadRegister>46</ReadRegister>
      <WriteRegister>47</WriteRegister>
      <MinSpeedValue>88</MinSpeedValue>
      <MaxSpeedValue>46</MaxSpeedValue>
      <IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
      <MinSpeedValueRead>0</MinSpeedValueRead>
      <MaxSpeedValueRead>0</MaxSpeedValueRead>
      <ResetRequired>true</ResetRequired>
      <FanSpeedResetValue>255</FanSpeedResetValue>a
      <FanDisplayName>CPU fan 1</FanDisplayName>
      <TemperatureThresholds>
        <TemperatureThreshold>
          <UpThreshold>50</UpThreshold>
          <DownThreshold>0</DownThreshold>
          <FanSpeed>2.38095236</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>70</UpThreshold>
          <DownThreshold>65</DownThreshold>
          <FanSpeed>21.4285717</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>74</UpThreshold>
          <DownThreshold>70</DownThreshold>
          <FanSpeed>35.7142868</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>77</UpThreshold>
          <DownThreshold>74</DownThreshold>
          <FanSpeed>61.9047623</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>80</UpThreshold>
          <DownThreshold>77</DownThreshold>
          <FanSpeed>100</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>65</UpThreshold>
          <DownThreshold>60</DownThreshold>
          <FanSpeed>9.523809</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>60</UpThreshold>
          <DownThreshold>50</DownThreshold>
          <FanSpeed>4.76190472</FanSpeed>
        </TemperatureThreshold>
      </TemperatureThresholds>
      <FanSpeedPercentageOverrides>
        <FanSpeedPercentageOverride>
          <FanSpeedPercentage>0</FanSpeedPercentage>
          <FanSpeedValue>255</FanSpeedValue>
          <TargetOperation>ReadWrite</TargetOperation>
        </FanSpeedPercentageOverride>
      </FanSpeedPercentageOverrides>
    </FanConfiguration>
    <FanConfiguration>
      <ReadRegister>53</ReadRegister>
      <WriteRegister>54</WriteRegister>
      <MinSpeedValue>88</MinSpeedValue>
      <MaxSpeedValue>46</MaxSpeedValue>
      <IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
      <MinSpeedValueRead>0</MinSpeedValueRead>
      <MaxSpeedValueRead>0</MaxSpeedValueRead>
      <ResetRequired>true</ResetRequired>
      <FanSpeedResetValue>255</FanSpeedResetValue>
      <FanDisplayName>CPU fan 2</FanDisplayName>
      <TemperatureThresholds>
        <TemperatureThreshold>
          <UpThreshold>50</UpThreshold>
          <DownThreshold>0</DownThreshold>
          <FanSpeed>2.38095236</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>70</UpThreshold>
          <DownThreshold>65</DownThreshold>
          <FanSpeed>21.4285717</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>74</UpThreshold>
          <DownThreshold>70</DownThreshold>
          <FanSpeed>35.7142868</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>77</UpThreshold>
          <DownThreshold>74</DownThreshold>
          <FanSpeed>61.9047623</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>80</UpThreshold>
          <DownThreshold>77</DownThreshold>
          <FanSpeed>100</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>60</UpThreshold>
          <DownThreshold>50</DownThreshold>
          <FanSpeed>4.76190472</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>65</UpThreshold>
          <DownThreshold>60</DownThreshold>
          <FanSpeed>9.523809</FanSpeed>
        </TemperatureThreshold>
      </TemperatureThresholds>
      <FanSpeedPercentageOverrides>
        <FanSpeedPercentageOverride>
          <FanSpeedPercentage>0</FanSpeedPercentage>
          <FanSpeedValue>255</FanSpeedValue>
          <TargetOperation>ReadWrite</TargetOperation>
        </FanSpeedPercentageOverride>
      </FanSpeedPercentageOverrides>
    </FanConfiguration>
  </FanConfigurations>
  <RegisterWriteConfigurations>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnInitialization</WriteOccasion>
      <Register>34</Register>
      <Value>1</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>1</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
      <Description>Select thermal zone</Description>
    </RegisterWriteConfiguration>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnInitialization</WriteOccasion>
      <Register>38</Register>
      <Value>28</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>0</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
      <Description>Fake thermal zone temperature</Description>
    </RegisterWriteConfiguration>
  </RegisterWriteConfigurations>
</FanControlConfigV2>

**Comment by hotbabyspace** [comment]
Hello! I've been using your software for more than 5 years and it works great on my acer aspire VN7-593G to control the fans. I haven't found any other software that works.
I use Ableton for producing music and I have been always living with this latency issue. I also changed my audio interface because I thought it might fix the problem. 
Im not very technical with computers but today I started a new troubleshooting session to fix the latency issue and I finally found out that when I disable the nbfc service, the latency is gone!
Please try and fix it! It does something with the ACPI driver, as the other people mentioned. I use the acer aspire VN7-593G config.

Or maybe im not using it correctly, I dont really know how to set it up, I just have setup the temperature thresholds in a way that the fans are not constantly blasting because its so annoying when producing music. it works like a charm, my laptop is super quiet and doesnt overheat when setup properly. I havent changed any other parameter in the program. Can you help me set it up correctly or can I provide you with information so you can fix the bug?

Thank you anyway, i can do my music with latency, but not with the fans blasting, so you have saved my life all these years.
