### ISSUE TITLE
Faint crackling sound when fan speed at 0%?

### ISSUE THREAD

**Issue by kohanyirobert** [hirschmann/nbfc#261]
I have an ASUS UX410UA and I'm using nbfc 1.5.3-beta (2e86ddd) with [this config](https://github.com/hirschmann/nbfc/blob/master/Configs/Asus%20Zenbook%20UX410UQ.xml).

Everything seems to work. I can rev up and down the fan.

However. If I turn off the fan (0%) I can still hear a very faint crackle from my notebook. The notebook itself shouldn't have any moving parts aside from the fan on the CPU. It only has a CPU, no GPU. It's an Intel Core i5-7200U, Kaby Lake. It has a SanDisk SSD and that's all.

What could be the source of the faint crackle, is this expected? The fan isn't actually stopped just slowed down to a really low speed?

**Comment by cdarken** [comment]
I have the same laptop, but with the i7 cpu. The noise is coil whine.

**Comment by kohanyirobert** [comment]
Hmm, good to know :) Never heard coil whine before because the fans in my computers were so loud :)
