### ISSUE TITLE
Please add config for lenovo ideapad Z500

### ISSUE THREAD

**Issue by donkeyale** [hirschmann/nbfc#262]
I tried all the lenovo ideapad configs 
and they didint worked

Thank you

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by Soberia** [comment]
You can use [Lenovo IdeaPad Z500 Fan Controller](https://github.com/Soberia/Lenovo-IdeaPad-Z500-Fan-Controller)
