### ISSUE TITLE
Building latest master fails

### ISSUE THREAD

**Issue by cdarken** [hirschmann/nbfc#264]
I get these errors:
```
ConfigManager.cs(72,19): error CS1525: Unexpected symbol 'throw'
ConfigManager.cs(74,19): error CS1525: Unexpected symbol 'throw'
ConfigManager.cs(76,19): error CS1525: Unexpected symbol 'throw'
```
I'm on Ubuntu 16.04. Is my mono version too old?

**Comment by hirschmann** [comment]
yes

**Comment by cdarken** [comment]
I need at least 4.2.5, right? `mono --version` returns 4.2.1

**Comment by cdarken** [comment]
Ok. Installed latest version, with instructions from [here](http://www.mono-project.com/download/#download-lin), it compiled ok. But how do I run it? :smile:

**Comment by cdarken** [comment]
I'll try to follow the wiki instructions. Thanks.
