### ISSUE TITLE
nbfc doesn't obey me

### ISSUE THREAD

**Issue by brunocechet** [hirschmann/nbfc#268]
I'm on Acer Aspire E5-573, but using the Aspire E5-731 config.
My fan is crazy, take a look at this:

brunocechet@brunocechet-Aspire-E5-573 /opt/nbfc $ /usr/bin/mono /opt/nbfc/nbfc.exe status
Service enabled	        : True
Read-only		        : False
Selected config name	: Acer Aspire E5-731
Temperature		        : 39

Fan display name	        : Fan #1
Auto control enabled	: False
Critical mode enabled	: False
Current fan speed	        : 14.29
Target fan speed	        : 0.00
Fan speed steps		: 7

By the way, I guess the fan speed is incorrect, because the noise is so much annoying.
There is anything that I could do ?

**Comment by hirschmann** [comment]
You could try some of the other configs.
Have a look at `nbfc.exe config --recommend`
