### ISSUE TITLE
Asus Pro B9440

### ISSUE THREAD

**Issue by mushweed** [hirschmann/nbfc#275]
This lovely laptop has a super loud fan. Please add aconfig.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by mushweed** [comment]
Hey, i just checked the tutorial and got several dumps and logs, but i cant figure out any pattern, as described in the tutorial. Ist there any other way to find the ec?
