### ISSUE TITLE
Conflict with RivaTuner Statistics Server

### ISSUE THREAD

**Issue by Jonas1312** [hirschmann/nbfc#277]
NBFC Client crashes when loading RivaTuner Statistics Server, NBFC Server keeps running.

**Comment by Jonas1312** [comment]
Fixed using RivaTuner Statistics Server v7.0.0

**Comment by hirschmann** [comment]
Thanks for the info. I've already added RivaTuner Statistics Server to the known incompatibilities list: https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc
