### ISSUE TITLE
HELP PLS!

### ISSUE THREAD

**Issue by WildBiker1952** [hirschmann/nbfc#279]
Thank you for your wonderful & excellent program!
I didn't keep track of which particular download worked just fine on my Acer Aspire 7741.
I had to reset the laptop.
Now I can't find the NBFC that had the profile for the 7741.
Directions to the correct one would be gratefully received.
Many thanks.

**Comment by hirschmann** [comment]
The config is still available: https://github.com/hirschmann/nbfc/blob/master/Configs/Acer%20Aspire%207741G.xml

The config should be included in all releases since 1.3.4.
I recommend to use the latest release: https://github.com/hirschmann/nbfc/releases

**Comment by WildBiker1952** [comment]
Hello Stefan,
NBFC only has Acer Aspire 7741G in profiles.
But only a ram increase in the G.
However. NBFC works 100% fine for 2-3 days.
Then drops the profile. 
Starts at times but shows the -2***** temp & doesn't switch the fan up & down anymore?
![nbfc fault](https://user-images.githubusercontent.com/29748357/29514411-1902d8a8-8671-11e7-9c01-451875a7dff2.jpg)

HELP! Please!
Many thanks.

**Comment by hirschmann** [comment]
Obviously, NBFC can't access the hardware. This is usually caused by other tools which are interferring with NBFC. See https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc
