### ISSUE TITLE
Could you add support for the Dell XPS12 (9Q33) haswell notebook?

### ISSUE THREAD

**Issue by jcwrks** [hirschmann/nbfc#28]
First I would like to thank you. I've been using nbfc on my Yoga 13 for a few years now, and it has resolved the noisy fan issue.

However I have scoured Google for a way to silence the Dell XPS12 (9Q33) haswell notebook and there is no solution. Is there any chance that you could add support for this exceptional notebook?

**Comment by hirschmann** [comment]
See #5

**Comment by hirschmann** [comment]
https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests

**Comment by hirschmann** [comment]
https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests
