### ISSUE TITLE
NBFC with Dell Precision 5510/5520, XPS 9550/9560?

### ISSUE THREAD

**Issue by kascana** [hirschmann/nbfc#280]
Could someone tell me whether NBFC can somehow control the fans of newer Dell laptops such as Dell Precision 5510/5520 and Dell XPS 9550/9560 under Windows? If this is not possible, I would be grateful for a brief explanation and any alternative solutions.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
If you can't get NBFC to work, try [i8kfan](https://www.diefer.de/i8kfan/) or [speedfan](http://www.almico.com/speedfan.php).
