### ISSUE TITLE
It *was* an issue ... now works fine

### ISSUE THREAD

**Issue by DavidNelsonNM** [hirschmann/nbfc#281]
Thought I'd post this in case someone else ran into it. Originally, I installed FanControl but it was acting weird - commands like config wouldn't work, it didn't recognize the downloaded GL702VM file. The reinstall got worse. It would stall at the Windows service part, giving me a lot of errors in the event log. Reboots, uninstalls, repair, run as admin, nothing worked.

So I downloaded the 1.5.3 beta instead. And wow - not only did it work but it pulled the GL702VM config without me telling it to. (To be clear, I had copied into the local Configs folder already.) And I can see ALL THREE FANS. And control them. This is a big deal cause one of the 2 CPU fans refused to spin - all day I've been trying, running games, careful air cleaning, etc. Once NBFC saw it, it took off.

The laptop had been running hot lately, and would periodically shutdown or hibernate out of the blue. Now I know the fan works it just needed convincing. So bless your heart, from one IT to another. I started with an issue and end with a kudo. (I even joined Github just to say so!)

**Comment by hirschmann** [comment]
Thanks for the positive feedback.
I'm glad to hear the latest version solved your problems.
