### ISSUE TITLE
Please Add a Profile for HP Compaq nw9440 Mobile Workstation

### ISSUE THREAD

**Issue by mafry** [hirschmann/nbfc#283]
Could you please add a configuration for the HP Compaq nw9440 Mobile Workstation, it is a shame that this great tool doesn't have it since it has a lot of other series models. Thanks to this tool I can get my fan to work, after over 18mths of the fan failing to ramp up and shutting down due to overheat, so it would be great to add a specific configuration for that model too. I am currently using the profile for the HP Compaq 6735s Turion X2 RM-72.

Thanks in advance

**Comment by kkarankb** [comment]
If these settings are working for you then just use them.Or you can adjust your max and min speed properly using http://rweverything.phpnet.us/bin/RwV1.5.2.zip
click on EC tab
Change value of  215 register in EC table for which speed is min and max (try hearing fan sound).
http://forum.notebookreview.com/attachments/notebook-fancontrol-user-manual-pdf.105862/
Try this guide You already know the register offset is 215 so skip that searching part.

**Comment by mafry** [comment]
Hi kkarankb,
Thanks for the reply. While I am happy to use the current setting, not being a coder myself, I am not completely sure that the settings for the HP Compaq 6735s Turion X2 RM-72 are absolutely correct for the HP Compaq nw9440 Mobile WS. So it would be good if they could be verified. If any info is required from me, just let me know. Also, thank you for the link to rweverthing, it looks to be very powerful software with a great potential to stuff things up if you get it wrong.

**Comment by hirschmann** [comment]
As long as you don't experience any negative side effects, the config is fine for your notebook.
Please let me know if you are still satisfied with the HP Compaq 6735s Turion X2 RM-72 config.
If it works without problems, I could add a config for the HP Compaq nw9440.

**Comment by mafry** [comment]
Hello Stefan,

I have been using this config for about 2 weeks now and it’s working well without any negative side effects. This

has solved a huge problem with this notebook. I thank you for your expertise.

 

mafry

**Comment by kkarankb** [comment]
I would still recommend testing max speed it might be running slower that its full speed :)

**Comment by hirschmann** [comment]
I've added a config file for the HP Compaq nw9440: 8ff4bde669dbd08f87b811d2f0ff1287e39a2a77
