### ISSUE TITLE
1.5.3-beta infected?  Jiangmin:TrojanDropper.Agent.chbq

### ISSUE THREAD

**Issue by Logic-Elliven** [hirschmann/nbfc#284]
https://www.virustotal.com/en/file/b3431e81fa5c5547bb7498854a01741c119136fad86abfc038c88969de64db40/analysis/1499353299/
Probably a false positive and I know how lazy AV devs can be the bane of one's life, but there's the issue...

**Comment by hirschmann** [comment]
Detection ratio: | 1 / 62

It's a false positive.
The setup is capable of downloading (and installing) the .NET Framework 4.5 if required. Maybe some AVs assume this is malicious behavior.

**Comment by Logic-Elliven** [comment]
Yep. Deduced as much.
If one in over 60 AV apps thinks it's infected, who's most likely right; the one flagging it, or the 60 that aren't..?
I downloaded it and am using it.  
Wish there was a profile for a Asus N53SV though.
