### ISSUE TITLE
HP Pavilion G4

### ISSUE THREAD

**Issue by DJBaped** [hirschmann/nbfc#286]
Hi,

Would you please kindly add configuration for HP Pavilion G4?
It would save this old fighter from the heat and I might buy you a beer.
Thank you.

Regards,

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by hotchpocker** [comment]
See Contributing guidelines: Config requests
