### ISSUE TITLE
Please add config for "Lenovo Thinkpad E540"

### ISSUE THREAD

**Issue by xiaomatty** [hirschmann/nbfc#287]
First of all, I like your work and nice that someone is actually trying to do something about all the laptops out there overheating. 

I have a Lenovo E540 which is running at medium fan speed constantly even though temps are 60 or 95 degrees: I have tried anything and nothings seems to work. 

Hope you can help.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
