### ISSUE TITLE
[Linux] Can't get it to work

### ISSUE THREAD

**Issue by avently** [hirschmann/nbfc#288]
Hello. I built version 1.5.0 on Linux. 
Then i do this: "sudo cp all-files-under-LinuxRelease /opt/nbfc -r".
Then i copied "*.service" files to /etc/systemd/system.
Then sudo systemctl enable nbfc --now
/opt/nbfc/nbfc.exe status:
Connection refused

sudo systemctl restart nbfc.service:
Job for nbfc.service failed because a timeout was exceeded.
See "systemctl status nbfc.service" and "journalctl -xe" for details.

июл 12 14:34:43 linux sudo[32243]:  avently : TTY=pts/2 ; PWD=/home/avently/Desktop/nbfc-1.5.0/nbfc ; USER=root ; COMMAND=/usr/bin/systemctl restart nbfc.servi
июл 12 14:34:43 linux sudo[32243]: pam_unix(sudo:session): session opened for user root by (uid=0)
июл 12 14:34:43 linux systemd[1]: Starting NoteBook FanControl service...
-- Subject: Начинается запуск юнита nbfc.service
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Начат процесс запуска юнита nbfc.service.
июл 12 14:34:43 linux systemd[1]: nbfc.service: PID file /run/nbfc.pid not readable (yet?) after start: No such file or directory
июл 12 14:34:45 linux mono[32252]: NbfcService: Service NoteBookFanControlService started
июл 12 14:36:13 linux systemd[1]: nbfc.service: Start operation timed out. Terminating.
июл 12 14:36:13 linux mono[32252]: NbfcService: Stopping service NoteBookFanControlService
июл 12 14:36:13 linux systemd[1]: Failed to start NoteBook FanControl service.
-- Subject: Ошибка юнита nbfc.service
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Произошел сбой юнита nbfc.service.
-- 
-- Результат: failed.
июл 12 14:36:13 linux systemd[1]: nbfc.service: Unit entered failed state.
июл 12 14:36:13 linux sudo[32243]: pam_unix(sudo:session): session closed for user root
июл 12 14:36:13 linux systemd[1]: nbfc.service: Failed with result 'timeout'.

What i'm doing wrong?
I have Manjaro x64.

**Comment by hirschmann** [comment]
Please update to the latest beta (1.5.3). It has better logging support.
Then try to start the service. If it fails again, please upload the log file which should be at `/etc/NbfcService/`, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by avently** [comment]
@hirschmann 
i read nbfc.service and found this:
/opt/nbfc/nbfcservice.sh start

But this file (nbfcservice.sh) is not located in ReleaseLinux. It's located in Linux dir with *.service files. That's why service couldn't start. It couldn't find this file, right? I copied nbfcservice.sh to /opt/nbfc and service have been started succesfully. 
But i can't control fan speed... Even on Windows with NBFC. Fan works good without any helper apps until i start to build something huge like Chromium:) 
Anyway, thank you. The problem was with this file and a lack of docs or my intention to details.

**Comment by suyashmahar** [comment]
I had the same problem and had to manually copy the script to /opt/nbfc
