### ISSUE TITLE
Config for HP OMEN 15-ax050nf

### ISSUE THREAD

**Issue by Kx38** [hirschmann/nbfc#289]
Hi  ,

There's a HP OMEN 15 config , but it's for the old one .
Can you add the config for the HP OMEN 15-ax050nf ? When i use the one saved in the program , the fan speed is @ 129% but in reality it's turning @ like 25%-30% ..

Thanks for the program anyway =)

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
