### ISSUE TITLE
could you add config for ASUS K43S?

### ISSUE THREAD

**Issue by erclair** [hirschmann/nbfc#29]
Thank you for this incredible software, since on my laptop speedfan is not working and I got some heating problem.

However, can you add config for ASUS K43S, since I only see for other ASUS series (I didn't quite understand the concept for adding on my own)

**Comment by hirschmann** [comment]
See #5

**Comment by hirschmann** [comment]
https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests
