### ISSUE TITLE
Please add Asus Zenbook UX430UA config

### ISSUE THREAD

**Issue by ZheniaFIT** [hirschmann/nbfc#290]
I think its quite similar to ux410 which already exists

**Comment by Marmeladenbrot** [comment]
Just use the "Asus Zenbook Flip UX360UAK" like described everywhere on the internet. Works perfect with my UX430UQ.

**Comment by hirschmann** [comment]
I've added a config file for the Asus Zenbook UX430UA: 8ff4bde669dbd08f87b811d2f0ff1287e39a2a77
Thanks @Marmeladenbrot for the hint. 👍
