### ISSUE TITLE
Asus K501UB too noisy

### ISSUE THREAD

**Issue by maihoanglai** [hirschmann/nbfc#291]
Hello, 

I'm using Asus K501UB. Everything is perfect except one thing. The fan is very noisy. 
If the CPU temp is higher than 40oC then the fan always keep running around 4000rpm or higher. 
If CPU is lower than 40oC then Its stop. 
Even I just use some light software like word, excel or listen to music It alway keeps running. 
I don't understand why It cannot running below 4000rpm like 2000rpm or 3000 rpm...
K501UB does not have its own profile config file so I am temporary using K501LX profile. 

Does anyone know to set my laptop fan to 2000rpm or 3000rpm or something?

Thanks.

![image](https://user-images.githubusercontent.com/6018147/28243609-7f21ca3a-6a0c-11e7-971a-72a782bf2416.png)

**Comment by kkarankb** [comment]
Why don't you try editing this config and reducing min speed by some amount :)

**Comment by maihoanglai** [comment]
@kkarankb Thank for your reply. But I don't know to reducing the min speed of my fan. Could you show me how to do this? I have tried many times but I have failed to reduce the speed.

**Comment by kkarankb** [comment]
okay u can contact me through email kkarankb@gmail.com

**Comment by kkarankb** [comment]
min value is already at 0. Does anyone has any idea what is the problem.....

**Comment by hirschmann** [comment]
Could be a hardware-firmware limitation. If this is the case, there is not much you can do about it.
