### ISSUE TITLE
Add config for: HP ProBook 6455b

### ISSUE THREAD

**Issue by KirraBu** [hirschmann/nbfc#293]
Could you please add a configuration for the HP ProBook 6455b. I am using Ubuntu. In this OS on my model notebook fan working in minimum when temp < 70~75 and max when temp ~80 degrees. Using you program (config HP ProBook 4720s )can regulate temperature, but working non always correct.

**Comment by KirraBu** [comment]
Using [comment kkarankb](https://github.com/hirschmann/nbfc/issues/283) create config for my laptop. Working great :) Thanks for you work
[HP ProBook 6455b.zip](https://github.com/hirschmann/nbfc/files/1158453/HP.ProBook.6455b.zip)

**Comment by hirschmann** [comment]
Thank you very much for your config.
Could you please explain why you've added the [fan speed overrides](https://github.com/hirschmann/nbfc/wiki/Fan-speed-percentage-override)?

**Comment by KirraBu** [comment]
I using exist config for HP Probook 4720s. Fan speed overrides not needed, and I dont find it on config.
That's new version of config (change temperature thresholds) 
[HP ProBook 6455b.zip](https://github.com/hirschmann/nbfc/files/1168399/HP.ProBook.6455b.zip)

**Comment by hirschmann** [comment]
Thank you very much, I've added your config to the repo: f1ad260e45ed0ccdfed02d032dfe164e4ae1e0ec
