### ISSUE TITLE
Profile / hotkeys

### ISSUE THREAD

**Issue by kocane** [hirschmann/nbfc#298]
Hello

Any possibility for maybe getting profiles that can be set accordingly for AC/DC or perhaps toggled with hotkeys?

Again wanna thank you for making this program and making my Elitebook 840 g1 bearable to use ;)

Also, sorry if this isn't the place for suggestions :/

**Comment by Kaan88** [comment]
A way to enable NBFC when a certain .exe is started would be nice too.

**Comment by hirschmann** [comment]
It's possible to automate NBFC using the [NBFC CLI](https://github.com/hirschmann/nbfc/wiki/Command-line-interface) and tools like e.g. the windows task scheduler or eventghost
