### ISSUE TITLE
pls create an asus zenbook ux430UQ profile

### ISSUE THREAD

**Issue by EwoutxD** [hirschmann/nbfc#299]
Hi, i bought the asus zenbook ux430UQ, but im not happy with the fact that the fans are constantly active. i searched internet and thay said that i need to use the zenbook flip profile. I did this, but i noticed that with some heavy tasks, my notebook was getting really hot. I would like to have that there is a good profile for my asus zenbook ux430UQ, i would love the have that the fans start working at a temperature of +- 45 degrees celcius, and not at 60 degrees celcius such as in the zenbook flip profile.
PS: i first tryed to do it myself, but im not that good in all this 'programming'.

Thank you to everyone that could help me!!

**Comment by hirschmann** [comment]
Open the config editor and adjust the temperature thresholds according to your needs: https://github.com/hirschmann/nbfc/wiki/Temperature-threshold
