### ISSUE TITLE
Profile for Acer VX5-591G (VX15)

### ISSUE THREAD

**Issue by dziubekr6** [hirschmann/nbfc#300]
Hi,

Is ther any chance to get profile for Acer VX5-591G (VX15)? :) I was trying to use one for VN7 BE, bo for some reason it doesn`t seem to work. Generaly 1.50 version doesn`t seem to see this laptop at all.

Thank you

Regards

Mike

EDIT:

I have checked 1.5.3 version and it sees the laptop but non of Acer profiles work with this VX15 model.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
