### ISSUE TITLE
cannot run nbfc.exe, command not found

### ISSUE THREAD

**Issue by danielee0707** [hirschmann/nbfc#302]
Hi. I am totally new to linux and trying to get nbfc to work. I have already build and copied nbfc, but when I call nbfc.exe from command line, it says command not found. Is there anything that I missed? I'm using ubuntu 16.04. Please help.
![screenshot from 2017-08-01 11-53-11](https://user-images.githubusercontent.com/25728357/28842230-af7ebc22-76b1-11e7-88ff-0b7c2dcb7a18.png)

**Comment by hirschmann** [comment]
Try `mono ./nbfc.exe status

**Comment by KirraBu** [comment]
read this
[https://blog.briantruscott.com/how-to-enable-laptop-fan-in-linux-with-nbfc/](https://blog.briantruscott.com/how-to-enable-laptop-fan-in-linux-with-nbfc/)

**Comment by yusufsaid71** [comment]
Last time I could install thanks to this article, but now it won't load. Does anyone has the content saved somewhere?  https://blog.briantruscott.com/how-to-enable-laptop-fan-in-linux-with-nbfc/

I copied files to opt\nbfc.  The command "systemctl enable nbfc --now" does not work. When I try to set config it says "Connection refused". 

I use Ubuntu 18.04.
