### ISSUE TITLE
Forget profiles

### ISSUE THREAD

**Issue by LizzAcoreX** [hirschmann/nbfc#304]
After the PC rebootet, NBFC forget all Profiles.
Idk where they saved, but after a reboot they forget all profiles and i cant import them.

I have to run the Setup and repair the installation.

Kind regards

**Comment by LizzAcoreX** [comment]
PC:
Intel i7 (6700HQ), 16 GB RAM, no SSD yet, GTX 960

**Comment by hirschmann** [comment]
This could be a known incompatibility with a certain version of Rivatuner statistics server which comes with MSI Afterburner.
If Rivatuner statistics server is installed on your system, update it.

In case your issue still persists, follow the contributing guidelines: https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#issues

**Comment by Revolave** [comment]
Hello LizzAcoreX, did you able to get rid of your problem?

I have the same problem. There are no other programs installed that might conflict with NBFC. I have installed 1.5.3 Beta, but the problem still persists.

I'm using Acer V17 V791G with Windows 10 x64.

**Comment by hirschmann** [comment]
@Revolave
Please attach a service log.

**Comment by saiva1** [comment]
Hello hirschmann!

I have this problem too. I have clean install Windows 10 and there are no other programs installed (like Rivatuner, MSI Afterburner, etc). This problem only if I have install 1.5.3 BETA. When I uninstall 1.5.3. BETA and install 1.5.0 then this problem isn't observed. If I uninstall 1.5.0 and install 1.5.3 BETA again - the problem arises again.
In attach three log files.

Kind regards.

[NbfcServiceLog.txt](https://github.com/hirschmann/nbfc/files/1364581/NbfcServiceLog.txt)
[NoteBookFanControlLog.txt](https://github.com/hirschmann/nbfc/files/1364582/NoteBookFanControlLog.txt)
[SrvLog.txt](https://github.com/hirschmann/nbfc/files/1364583/SrvLog.txt)

**Comment by hirschmann** [comment]
Thanks for the logs!

Some of the latest nightly builds (appveyor) didn't include a required assembly (System.IO.Abstractions.dll).
I fixed this issue with commit 6f808506974faff2238aef6e5f59b0e1ef8fde22
Give nightly build 140 a try.

**Comment by saiva1** [comment]
Hello hirschmann!

After installation build 140 the above-named problem disappeared.

Thanks for fix it!

Close this issue.
