### ISSUE TITLE
Asus k501ux Right Fan Not Running

### ISSUE THREAD

**Issue by danielee0707** [hirschmann/nbfc#306]
Hi. My os is Ubuntu 16.04, with kernal 4.10. I installed nbfc by following the installation guide but the right fan seems not running. I tested it by setting speed to 50. I have tried using nvidia driver for dedicated gpu (950m) as well as disabling it to use only the integrated intel gpu, but still could not get it to work. It worked when I was using Windows 10 on the same machine several weeks ago.
![screenshot from 2017-08-04 13-18-26](https://user-images.githubusercontent.com/25728357/28985669-7a280e20-7918-11e7-8522-ce0c1e560071.png)

**Comment by hirschmann** [comment]
have you tried to set the speed of the right fan to 100%?
The right fan has only 1 step, which means there are only 2 valid speed settings: 0% and 100%

**Comment by danielee0707** [comment]
That makes sense. Thank you!
