### ISSUE TITLE
Sony Vaio Flip SVF14N works for SVF13N

### ISSUE THREAD

**Issue by Starkside** [hirschmann/nbfc#307]
Don't know where else to put this.

There is a config file (SVF14N1C5E (2).txt) uploaded in a reply within Issue No. 182 (courtesy of Houseman2001, as I understand).

The config file is duly attached for your attention, just rename to *.xml file extention
[NBFC config - SVF14N1C5E.txt](https://github.com/hirschmann/nbfc/files/1202629/NBFC.config.-.SVF14N1C5E.txt)
. It works for both VAIO SVF 14N1C5E and for VAIO SVF 13N 190X

Hope this helps fellow Vaio users.

**Comment by hirschmann** [comment]
Thank you for the information!
I've added the configs:
5ea8e29b4d78c21b87e4efae87cc7de6cadf7ab9
917077f8b812832a98ba026322a6e162581bb737
