### ISSUE TITLE
"EC initialization timed out."

### ISSUE THREAD

**Issue by ggDropbear** [hirschmann/nbfc#31]
Running Linux version, using Asus N550JV config on same computer. After working before on this computer yesterday, today it will only give a "EC initialization timed out." when attempting to start the service using "mono nbfc.exe start". Restarted computer, still won't work.

A further issue: due to how command line's work, I had to put an underscore in "Asus_N550JV.xml" in the Configs folder, and need to put in a similar underscore in when I use "mono nbfc.exe config -a Asus_N550JV". 

EDIT: Found the problem, it'll only accept "sudo bash start-nbfcservice.sh" as the startup, not a simple "./start-nbfcservice.sh". Odd, but it seems to be working now...

**Comment by hirschmann** [comment]
NBFC requries root privileges to access the EC.
Actually `start-nbfcservice.sh` and `stop-nbfcservice.sh` are intended to be used in systemd units.
I will add scripts to install/uninstall (=create/delete systemd unit) NBFC on linux.

You can pass config names which include spaces by surrounding them with quotes, e.g. `nbfc.exe load "Asus N550JV"`.
