### ISSUE TITLE
Request for Yoga 720-13IKB

### ISSUE THREAD

**Issue by h0tt5auc3** [hirschmann/nbfc#311]
This laptop has a ridiculously loud fan. If you could please find support for it that would be amazing. Many forums exist for this laptop and how to solve the problem, but right now the profile of yours that was found to work either has then fan at 0%, or 100% when reaching critical temps, no in between. Thank you in advance!

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
