### ISSUE TITLE
Problem when installing nbfc on Ubuntu 16.04

### ISSUE THREAD

**Issue by chrisnopa** [hirschmann/nbfc#312]
Hi man,

First of all, thanks a lot for your job. This soft works great on Windows ! And here we are with my problem:  Im on dual boot Windows/Ubuntu and i tried to install nbfc in order to reduce fan noise on my Asus K501UX. I followed every step but Im still stucked in the process  :( 

Everytime I try to set a new config I  get the following error message : *Cannot open assembly 'nbfc.exe': No such file or directory.*
That being said, I tried a to fix this by myself, but with no success so far... 
If u have a quick tip or any idea, that would be great !!

Cheers

**Comment by hirschmann** [comment]
Probably the same issue as #302
