### ISSUE TITLE
NBFC not working at all (v1.5.0)

### ISSUE THREAD

**Issue by WikisCY** [hirschmann/nbfc#313]
Hello,

I have an Acer Aspire VN7-791G V17 Nitro Black Edition, which already has its own configuration in NBFC.

My issue is that my temperature & fan speed values are wrong and moving the cursors left and/or right does not do anything. I have attached a screenshot to show exactly what I mean.

I hope I did not miss anything obvious.

![untitled](https://user-images.githubusercontent.com/30929684/29214508-4d5f71c4-7eb0-11e7-9c0f-3455e1debd83.jpg)

**Comment by hirschmann** [comment]
Obviously, NBFC isn't able to access your notebook's hardware.
This could be caused by third party hardware monitoring tools which could interfere with NBFC: https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc

**Comment by WikisCY** [comment]
I already read that and I have MSI installed but not running while NBFC is open.

**Comment by hirschmann** [comment]
Try to upgrade to the latest version of afterburner and riva tuner statistics server.
If this doesn't solve the problem, try to uninstall afterburner and riva tuner statistics server altogether.

**Comment by WikisCY** [comment]
I was about to try that and it seemed to have been fixed by itself.

Thank you for your help.
