### ISSUE TITLE
1.5 not building on debian 9

### ISSUE THREAD

**Issue by debianuser-3b** [hirschmann/nbfc#314]
I'm using debian 9 (stable)

If I run build.sh with version 1.4.2 I get the Linux/bin/ReleaseLinux/ directory, not the same with version 1.5.
Doing the same with version 1.5.0 there will be no such directory (only 5 files in nbfc-X/Linux: continue-nbfcservice.sh  nbfc.service  nbfc-sleep.service  pause-nbfcservice.sh  start-nbfcservice.sh  stop-nbfcservice.sh).
On the system nuget.exe 2.86 is installed. Though, I downloaded nuget.exe 4.1 to nbfc-1.5.0/ => same result.

**Comment by hirschmann** [comment]
1.5 has some build issues on Linux.
Try to build master or 1.5.3 instead.

**Comment by debianuser-3b** [comment]
Thanks -- tried it and it worked. 

The docs are somewhat confusing. I did the following the nbfc-1.5.3 directory:

1.  sh build.sh
2. cp -a  Linux/bin/Release/ /opt/nfbc
3. cd /opt/nfbc/
4. sh nbfcservice.sh start
5. mono nbfc.exe config -r 
=> recommended config
6. mono nbfc.exe config apply "Asus Zenbook UX51VZA"
7. mono nbfc.exe start -e
8. mono nbfc.exe status -a

Service enabled         : True
Read-only               : False
Selected config name    : Asus Zenbook UX51VZA
Temperature             : 37
# Temperature: 37 appears to be correct (according to sensors)
Fan display name        : Fan #1
Auto control enabled    : True
Critical mode enabled   : False
Current fan speed       : 0.00
Target fan speed        : 0.00
Fan speed steps         : 8


*****
I don't know whether the config is stored in any file.
Didn't yet try automatic start up via sysctl-

**Comment by hirschmann** [comment]
To find out where NBFC stores settings files, logs, etc. have a look at: https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

If you tell me what you find confusing about the wiki, I'll try to improve it. :)

**Comment by debianuser-3b** [comment]
Maybe I was also a bit confused. But I was missing "sh nbfcservice.sh start" (received many error messegages from nbfc.exe).
