### ISSUE TITLE
ASUS Zenbook UX3410UA

### ISSUE THREAD

**Issue by TomTom72** [hirschmann/nbfc#315]
Hi, i have this ASUS Zenbook UX3410UA. 
In the BIOS it is named as UX410UAK.
I tried all ASUS profiles for this Laptop, but the fan is still running like a jet.
Can anyone help me with this issue? I'm not a programmer, just a user...
Thanks for your help

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
