### ISSUE TITLE
Add config for Asus Vivobook S15 S510

### ISSUE THREAD

**Issue by Boxfender** [hirschmann/nbfc#317]
Hello,

Would it be possible to add a config for the Asus Vivobook S15 S510?

I'm currently using the config for Asus Vivobook S400CA, but I really have no idea whether that is an okay alternative config. Any advise?

Thanks

**Comment by hirschmann** [comment]
If the Vivobook S400CA config is working without problems on your notebook, there is no reason to be worried.
It's quite usual that similar notebook models share some parts including the EC which is responsible for controlling the fan(s).

**Comment by hirschmann** [comment]
The Vivobook S400CA config starts the fan only if the temperature rises above 65 degree.

**Comment by brettndm** [comment]
Thank you for giving me peace of mind  :)
