### ISSUE TITLE
Stuck with config creation for Alienware R4 17 GTX 1080 7820HK

### ISSUE THREAD

**Issue by alexkyse1** [hirschmann/nbfc#318]
Hi there, I'm trying to create my config for my laptop mentioned above, but once I create it, and I apply it, the system automatically checks the fan control status to disabled. Is this caused by the EC's registers?

I've tried to run the following command "nbfc.exe config --recommend" with admin rights but it appears the error that the reference of the object is not instantiated. I believe that is a bug, trying to process the code with a non inicializated variable..

![image](https://user-images.githubusercontent.com/10980733/29494610-5b45a448-85ae-11e7-94cd-8f488981b37e.png)

Anyone could help me please?

I'm stuck there... Thank you so much!

Have a great day!

**Comment by hirschmann** [comment]
The --recommend option is not working because the NBFC service is not running on your system.
Try to start the NBFC service via _services.msc_.
If the service refuses to start, please attach a service log file: https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by alexkyse1** [comment]
Service refuses to start due sensor temperature access deny.
[log.txt](https://github.com/hirschmann/nbfc/files/1249379/log.txt)

**Comment by hirschmann** [comment]
Please upgrade to the latest beta (1.5.3).
The version you are using doesn't support your CPU.
