### ISSUE TITLE
[Linux] "Could not load file or assembly or one of its dependencies" when trying to use nbfc.exe

### ISSUE THREAD

**Issue by lapineige** [hirschmann/nbfc#319]
Hello

I followed the How to install in the wiki, and the article referenced here #302.

But I'm still locked with this error, when trying to use nbfc.exe
> Could not load file or assembly or one of its dependencies.

nbfcservice.sh seems to work, at least for starting it.

**Comment by hirschmann** [comment]
The issue is probably caused by a missing file.
Are you sure you've copied all the files to `/opt/nbfc/` like described in the NBFC wiki?
