### ISSUE TITLE
Alternative to "RW-Everything"-Tool? Trying to create Dell Latitude E6430 Config.

### ISSUE THREAD

**Issue by TobiasKi** [hirschmann/nbfc#32]
Hello, after searching a long time for any tool to tweak my fan on a Dell Latitude E6430 I found your tool. Unfortunately I have to create my own config. The problem is: RW-Everything is not starting the EC Tab. It starts a lot of others but that one is not working. I tried to install and start the tool with admin privileges and also from windows 8.1 safe mode. I didn't work. I couldn't find an RW-Everything alternative as well. Any ideas?

**Comment by hirschmann** [comment]
You could use `nbfc-probe` instead. It's a commandline tool which comes with NBFC.
It's not included in release 1.3.4, so you have to build NBFC yourself (see readme), or wait until the next official release.

**Comment by TobiasKi** [comment]
Hi, I downloaded the current version now and I can not find nbfc-probe. I guess u mean ec-probe? When I am using this and execute "ec-probe dumb" in the terminal as an Admin I just get sorted numbers as an output: 
00: 00 00 00 00 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
10: 10 11 12 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F
20: 20 21 22 23 24 25 26 27 28 29 2A 2B 2C 2D 2E 2F
30: 30 31 32 33 34 35 36 37 38 39 3A 3B 3C 3D 3E 3F
40: 40 41 42 43 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F
50: 50 51 52 53 54 55 56 57 58 59 5A 5B 5C 5D 5E 5F
60: 60 61 62 63 64 65 66 67 68 69 6A 6B 6C 6D 6E 6F
70: 70 71 72 73 74 75 76 77 78 79 7A 7B 7C 7D 7E 7F
80: 80 81 82 83 84 85 86 87 88 89 8A 8B 8C 8D 8E 8F
90: 90 91 92 93 94 95 96 97 98 99 9A 9B 9C 9D 9E 9F
A0: A0 A1 A2 A3 A4 A5 A6 A7 A8 A9 AA AB AC AD AE AF
B0: B0 B1 B2 B3 B4 B5 B6 B7 B8 B9 BA BB BC BD BE BF
C0: C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 CA CB CC CD CE CF
D0: D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 DA DB DC DD DE DF
E0: E0 E1 E2 E3 E4 E5 E6 E7 E8 E9 EA EB EC ED EE EF
F0: F0 F1 F2 F3 F4 F5 F6 F7 F8 F9 FA FB FC FD FE FF

When I use it as normal user (no admin), all values are 0. What could possibly be wrong here?

**Comment by hirschmann** [comment]
The method how NBFC controls the fans does not work for some Dell notebooks.
Unfortunately it looks like yours is one of those models. :(

**Comment by TobiasKi** [comment]
With the fix of issue #64 I can build NoteBookFanControl.exe.
However, if I try to execute ecprobe.exe as an admin in the cmd with the command 
"ecprobe.exe dump > dump.txt"
 I get the error message: Can not resolve Path "C:\NFCProbe\BIN\RELASE\PLUGINS". I am wondering: Why is it expecting a pluging folder in this destination. As fas as I can see, there is no Plugin folder in the master branch, so I copied the Plugin subfolder from the core folder to the requested destination. Then I get the error: "Object reference not set to an instance of an object."

**Comment by hirschmann** [comment]
ec-dump cannot run on its own. It requires NBFC to be installed properly because it relies on the same plugins as the NBFC service. Furthermore, on Windows the setup needs to install a driver in order to access the hardware.

If the build succeeded, run the setup: `nbfc\Windows\Setup\NbfcBootstrapper\bin\Release\NbfcBootstrapper.exe`

**Comment by TobiasKi** [comment]
I downloaded the current master-branch, executed build1.ps successfully, installed NoteBookFanControl from nbfc-master\Windows\Setup\NbfcBootstrapper\bin\Release\NbfcBootstrapper.exe and then executed ec-probe with nbfc-master\nbfc-master\Core\NbfcProbe\bin\Release\ec-probe.exe dump dump.txt while NoteBookFanControl was even running.

It is still saying that the Path nbfc-master\core\nbfcprobe\bin\release\plugins can not be resolved.

**Comment by hirschmann** [comment]
Still the same problem.
You need to run the ec-probe executable in the NBFC install directory, which is by default `C:\Program Files (x86)\NoteBook FanControl\ec-probe.exe`

**Comment by TobiasKi** [comment]
okay, thanks. The execution is working now. Unfortunately I still only get the nonsense results which I listed above in the December post. So I guess my Dell notebook really seems to be one of the notebooks that can not be run with NoteBookFanControl.
