### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by JT230781** [hirschmann/nbfc#320]
Hello, let me start by saying great job!!!
However I think the command line parameters are not working...
I currently use task scheduler to start the app when I log on and
It would be great if the app could be started without the UI being displayed...
Hope you get the time to fix this small issue...
Thanks in advance!

**Comment by hirschmann** [comment]
I'm glad you like NBFC :)

The NBFC GUI client supports only one parameter: _-tray_
It works as expected and sends the app to the system tray.

If you don't want to see the GUI at all (not even in the tray), don't start it at all. The service runs perfectly fine without any client attached.

Also, the GUI client has a built-in autostart option.
I guess you use the task scheduler to start the client with elevated privileges, but that's not necessary. The client is able to connect to the service from any user session.

**Comment by JT230781** [comment]
Hello hirschmann,
Thanks for the quick reply!
I tried using /tray and /auto as stated in the manual but it wasn't working. I'll try -tray later on and report back!

Also nice to know that the service can run without a client attached but
I do prefer seeing cpu temp in the tray.

**Comment by hirschmann** [comment]
The old manual (.pdf) is outdated.
Refer to the NBFc wiki instead: https://github.com/hirschmann/nbfc/wiki

**Comment by JT230781** [comment]
Ah I see,
Tested it and it works as expected! :100: 
Thanks for the info and keep up the good work!!! :) :1st_place_medal:
