### ISSUE TITLE
Current fanspeed = 220%?

### ISSUE THREAD

**Issue by MWSIT** [hirschmann/nbfc#325]
Hi All together,

I use NBFC on 2 HP Elitebook Folio 9470m with the standard profile... On 1 notebook all is working fine with V1.5.0 since a longer time. But on the other 1 I see abnormal things: The actual CPU temp. is 54 degree and the current fanspeed is 220%??? But I don't hear the fan and I see this since the last windows 10 update... See screenshot:

![currentfanspeed](https://user-images.githubusercontent.com/31412070/29778648-5fa3e564-8c10-11e7-8a4c-b8f05f033f11.PNG)

I checked all settings with the other HP 9470m, all settings are the same. I tried the update to 1.5.3 already with no effect...

What can I do?

Daniel

**Comment by hirschmann** [comment]
Do both notebooks have the same BIOS version?

You could try to read the [read register](https://github.com/hirschmann/nbfc/wiki/Basic-fan-configuration#readregister) via [ec-probe](https://github.com/hirschmann/nbfc/wiki/EC-probing-tool) when this display bug occurs and add a [fan speed override](https://github.com/hirschmann/nbfc/wiki/Fan-speed-percentage-override) for the returned value.
