### ISSUE TITLE
nbfc not started after systemctl

### ISSUE THREAD

**Issue by danielee0707** [hirschmann/nbfc#327]
Hi. My system is Arch Linux. I followed the build and install step and used systemctl to enable the service. But it seems nbfc didn't start. Did I miss anything? It worked on Ubuntu though.
![screenshot_20170831_184136](https://user-images.githubusercontent.com/25728357/29952153-6d6756ae-8e7c-11e7-9678-79f74e3ba0a1.png)
![screenshot_20170831_185323](https://user-images.githubusercontent.com/25728357/29952394-ef639068-8e7d-11e7-97ee-37c19648504e.png)

**Comment by hirschmann** [comment]
You have to select a config, otherwise the service can't start.

**Comment by danielee0707** [comment]
oh, right! how come I forgot that, hahaha
