### ISSUE TITLE
Please config for Acer Aspire E5-572G-35CG

### ISSUE THREAD

**Issue by JohnnyTheReaper** [hirschmann/nbfc#328]
Hi there,

Can you please add a config for Acer Aspire E5-572G-35CG. It's fan is so slow and i have fps problems in many games because of overheating. I clear it inside every 2 month and I change it's thermal paste as well. The problem isn't the dust but because it's fan runs from what I hear at only 70% of its speed. People who designed this notebook faild so bad at fan configuration. I can even pay for a config for this notebook if possible but just please do it.
Note : When I was updating the BIOS, fan was spinning extremely! It was like 100% of it's max speed,  so i know it can do better.

Many thanks !

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
