### ISSUE TITLE
ASUS ROG G53SX

### ISSUE THREAD

**Issue by flexbrane** [hirschmann/nbfc#33]
Hello,
Thanks a lot for this software, just awesome ! 
I just have a question about it : with my ASUS ROG G53SX, I use the ROG G751JY profile, and it works ! But I just can control the CPU FAN, and not the GPU FAN. Do you know if it's possible, or of not, can you explain to me why ?
Thanks again :-)

**Comment by flexbrane** [comment]
I found the correct values !

For those who have an ASUS ROG G53SX, and wanted to control their GPU FAN and their CPU FAN I give you the write values.

Create (or edit) a (new) config, and add a "Fan configuration" with : 
- Read Register : 152
- Write Register : 152
- Min Speed : 0
- Max Speed : 6
- Reset on edit : YES
- Reset Value : 1

It's works !

**Comment by flexbrane** [comment]
Some help to add to NBFC the GPU temperature? Others soft can see it, but NBFC doesn't. So it control the gpu fan based on the cpu temperature.. Not the best!

**Comment by hirschmann** [comment]
Good job.

On Windows, services do not have access to the GPU. Since NBFC runs as a service, it can't read the GPU temperature.
Currently I don't know of a good solution for this limitation, sorry.

**Comment by flexbrane** [comment]
Thank you for this explaination !

I hope one day you will find a solution :-)

**Comment by RypeDub420** [comment]
Could you fork this project @flexbrane and upload your config so @hirschmann can add it eventually in the main build? I wanna see more gaming configurations in this program :D

I have an ASUS G75VX and I'm working on getting mine approved. I did the same thing as you lol

A LOT of the ASUS ROG laptops (or any series within ASUS) share the same EC registers. I just hate seeing a bunch of lower powered machines having way more profiles lol

**Comment by RypeDub420** [comment]
I was thinking of making a new issue on the windows not having access to GPU temps like you said, so that issues like this one can be auto merged and closed.

What do you think?

**Comment by flexbrane** [comment]
Good idea.

I am creating a new pull request for my Asus G53SX.

**Comment by RypeDub420** [comment]
And I'll make a new Issue for the generic issue with Windows having issues reading GPU temperatures, so that these similar issues can be closed and merged into the new one.
