### ISSUE TITLE
Acer Aspire F5-771G Config disappeared?

### ISSUE THREAD

**Issue by moschlen** [hirschmann/nbfc#330]
I just re-installed nfbc 1.5.0 but can´tt find the Config for the Acer Aspire F5-771G anymore.
I´m pretty sure I didn´t set it up myself - I´m a fan control dummy.
Or am I just confused?

Before uninstalling:
![acer aspire f5 771g](https://user-images.githubusercontent.com/31743468/30179932-819b5124-940e-11e7-926e-b4a9bee935c8.png)

Re-Installed Version:
![re-installed 1 5 0](https://user-images.githubusercontent.com/31743468/30180329-d5717f84-940f-11e7-91ec-37f8982eb907.png)

**Comment by hirschmann** [comment]
I don't know where you got this config from. NBFC never shipped with a config for the Aspire F5-771G.
