### ISSUE TITLE
Could not load a  plugin which implements StagWare.FanControl.Plugins.IEmbeddedController

### ISSUE THREAD

**Issue by iguerendiain** [hirschmann/nbfc#331]
***OS:*** Budgie Remix (Ubuntu 16.04.3 LTS)
***Problem:*** Service do not starts.

***What I did:***

- Build with latest version of Mono

- Started the service via systemctl

***Output of "nbfc.exe status -a"***
`Service enabled         : False
Read-only               : False
Selected config name    : Asus Zenbook UX310UAK
Temperature             : 0`

***Output of "nbfc.exe start -e" or "nbfc.exe start -r"***
`Could not load a  plugin which implements StagWare.FanControl.Plugins.IEmbeddedController`

**Comment by i5o** [comment]
Same error on Manjaro
```
[ignacio@cat ~]$ sudo nbfc config -a "Acer Aspire VN7-572G V15 Nitro BE"
Could not load a  plugin which implements StagWare.FanControl.Plugins.ITemperatureMonitor
[ignacio@cat ~]$ 
```

**Comment by reikdas** [comment]
I get the same error on Manjaro. 
```
[reik@reik-msi ~]$ sudo nbfc config -a "Packard Bell Easynote TJ65"
Could not load a  plugin which implements StagWare.FanControl.Plugins.ITemperatureMonitor
```
