### ISSUE TITLE
GUI for Linux

### ISSUE THREAD

**Issue by sweet90** [hirschmann/nbfc#335]
is there some gui for nbfc on linux? :(

**Comment by hirschmann** [comment]
There is no GUI Client for Linux and currently I don't plan to create one either.
Please use the CLI instead: https://github.com/hirschmann/nbfc/wiki/Command-line-interface

With that said, if someone wants to create a Linux client for NBFC and has questions about how to do it, feel free to ask me.
Basically you have to consume the NBFC WCF service: https://github.com/hirschmann/nbfc/tree/master/Core/StagWare.FanControl.Service
