### ISSUE TITLE
HP BC200 Fan Problem you can create config file ?

### ISSUE THREAD

**Issue by Yalcinx** [hirschmann/nbfc#336]
Hi I am using a laptop of HP Pavilion bc200 series, the second fan of this laptop works at low rpm, but not at all speeds can be 3000+ rpm for the first fan and 200 rpm for the second fan. I can adjust the speed of the first fan with the hp 17 ab240 nd in the notebook fan control but I could not find the proper value for the second fan Can we run the second fan?

**Comment by Yalcinx** [comment]
This problem exists in dual-fan hp models.

For example

https://h30434.www3.hp.com/t5/Notebook-Hardware-and-Upgrade-Questions/HP-Pavilion-15-BC023TX-fan-slower/td-p/5784851

https://h30434.www3.hp.com/t5/Gaming-Notebooks/hp-omen-fans-normal-speed/td-p/5999137


Can this problem be solved with your program?

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
