### ISSUE TITLE
Build failing on ubuntu 16.04

### ISSUE THREAD

**Issue by voidcase** [hirschmann/nbfc#337]
mono-complete is up to date (according to apt-get). This is the output from the build script:

~/repos/nbfc ~/repos/nbfc
MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
All packages listed in packages.config are already installed.
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 9/19/2017 7:07:17 PM.
__________________________________________________
/home/isak/repos/nbfc/Windows/Setup/NbfcSetup/NbfcSetup.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/isak/repos/nbfc/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/isak/repos/nbfc/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.
Project "/home/isak/repos/nbfc/NoteBookFanControl.sln" (Build target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "ReleaseLinux|Any CPU".
	Target Build:
		Project "/home/isak/repos/nbfc/Core/Plugins/StagWare.Hardware.LPC/StagWare.Hardware.LPC.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/home/isak/repos/nbfc/Core/Plugins/StagWare.Hardware.LPC/StagWare.Hardware.LPC.csproj".
		Project "/home/isak/repos/nbfc/Core/StagWare.BiosInfo/StagWare.BiosInfo.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/home/isak/repos/nbfc/Core/StagWare.BiosInfo/StagWare.BiosInfo.csproj".
		Project "/home/isak/repos/nbfc/Core/StagWare.Settings/StagWare.Settings.csproj" (default target(s)):
/home/isak/repos/nbfc/Core/StagWare.Settings/StagWare.Settings.csproj:  warning : Project has unknown ToolsVersion '15.0'. Using the default tools version '4.0' instead.
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/home/isak/repos/nbfc/Core/StagWare.Settings/StagWare.Settings.csproj".
		The project 'OpenHardwareMonitorLib' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
		Project "/home/isak/repos/nbfc/Core/StagWare.Configurations/StagWare.FanControl.Configurations.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/home/isak/repos/nbfc/Core/StagWare.Configurations/StagWare.FanControl.Configurations.csproj".
		The project 'DriverSetupWixAction' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
		The project 'StagWare.Hardware' is disabled for solution configuration 'ReleaseLinux|Any CPU'.
		Project "/home/isak/repos/nbfc/Core/StagWare.FanControl/StagWare.FanControl.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/home/isak/repos/nbfc/Core/StagWare.FanControl/StagWare.FanControl.csproj".
		Project "/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj" (default target(s)):
/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj:  warning : Project has unknown ToolsVersion '15.0'. Using the default tools version '4.0' instead.
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GetFrameworkPaths:
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.5.2' not supported by this toolset (ToolsVersion: 4.0).
			Target GetReferenceAssemblyPaths:
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.5.2'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
				Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj/Release/StagWare.FanControl.Configurations.Tests.dll ConfigManagerTests.cs ConfigsTests.cs ExtensionMethods/StringExtensionMethodsTests.cs FanControlConfigManagerTests.cs Properties/AssemblyInfo.cs /target:library /define:TRACE /nostdlib /reference:../../packages/FakeItEasy.3.3.2/lib/net40/FakeItEasy.dll /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:../../packages/System.IO.Abstractions.2.0.0.144/lib/net40/System.IO.Abstractions.dll /reference:../../packages/System.IO.Abstractions.TestingHelpers.2.0.0.143/lib/net40/System.IO.Abstractions.TestingHelpers.dll /reference:/usr/lib/mono/gac/System.Xml.Linq/4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll /reference:/usr/lib/mono/gac/System.Data.DataSetExtensions/4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/gac/Microsoft.CSharp/4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll /reference:/usr/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll /reference:/usr/lib/mono/gac/System.Net.Http/4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll /reference:/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll /reference:../../packages/xunit.abstractions.2.0.1/lib/net35/xunit.abstractions.dll /reference:../../packages/xunit.assert.2.2.0/lib/netstandard1.1/xunit.assert.dll /reference:../../packages/xunit.extensibility.core.2.2.0/lib/netstandard1.1/xunit.core.dll /reference:../../packages/xunit.extensibility.execution.2.2.0/lib/net452/xunit.execution.desktop.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /reference:/home/isak/repos/nbfc/Core/StagWare.Configurations/bin/Release//StagWare.FanControl.Configurations.dll /warn:4
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj".-- FAILED
		Done building project "/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/isak/repos/nbfc/NoteBookFanControl.sln".-- FAILED
Done building project "/home/isak/repos/nbfc/NoteBookFanControl.sln".-- FAILED

Build FAILED.

Warnings:

/home/isak/repos/nbfc/Windows/Setup/NbfcSetup/NbfcSetup.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/isak/repos/nbfc/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/isak/repos/nbfc/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.

/home/isak/repos/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/isak/repos/nbfc/Core/StagWare.Settings/StagWare.Settings.csproj (default targets) ->

	/home/isak/repos/nbfc/Core/StagWare.Settings/StagWare.Settings.csproj:  warning : Project has unknown ToolsVersion '15.0'. Using the default tools version '4.0' instead.

/home/isak/repos/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj (default targets) ->

	/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj:  warning : Project has unknown ToolsVersion '15.0'. Using the default tools version '4.0' instead.

/home/isak/repos/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (GetFrameworkPaths target) ->

	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.5.2' not supported by this toolset (ToolsVersion: 4.0).

/home/isak/repos/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.5.2'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.

Errors:

/home/isak/repos/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/isak/repos/nbfc/Tests/StagWare.FanControl.Configurations.Tests/StagWare.FanControl.Configurations.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	CSC: error CS0518: The predefined type `System.Object' is not defined or imported
	CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
	CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
	CSC: error CS0518: The predefined type `System.Single' is not defined or imported
	CSC: error CS0518: The predefined type `System.Double' is not defined or imported
	CSC: error CS0518: The predefined type `System.Char' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
	CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
	CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
	CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
	CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
	CSC: error CS0518: The predefined type `System.String' is not defined or imported
	CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
	CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
	CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
	CSC: error CS0518: The predefined type `System.Void' is not defined or imported
	CSC: error CS0518: The predefined type `System.Array' is not defined or imported
	CSC: error CS0518: The predefined type `System.Type' is not defined or imported
	CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
	CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
	CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
	CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
	CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
	CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
	CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
	CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

	 7 Warning(s)
	 31 Error(s)

Time Elapsed 00:00:01.4024070
~/repos/nbfc

**Comment by hirschmann** [comment]
The mono version in the Ubuntu 16.04 repo is too old.
Either upgrade your distro, or upgrade the mono repo on your system: http://www.mono-project.com/download/#download-lin-ubuntu
