### ISSUE TITLE
UX310UA config work with UX410UA

### ISSUE THREAD

**Issue by N121V** [hirschmann/nbfc#339]
Does the Asus UX310UA config work with the UX410UA?
I want to buy the UX410UA (not UQ) but I read that the fan can be loud during light/normal workloads.
Because I don't have it in my possession I can't test it so I wanted to ask if any of you know if it will work.
The 310UA and 410UA are basically the same laptop with some small upgrades so I think it should work but I don't know for sure.

**Comment by Jonas1312** [comment]
You can use the UX410UQ file, it will work with the UX410UA
