### ISSUE TITLE
MSI GT60 0NE 414

### ISSUE THREAD

**Issue by magnapeccatrix** [hirschmann/nbfc#34]
Hi guys 

Could you please help me to set this program up with my GT60? 

If you tell me what information is necessary, I am going to post it here.

Thank you and I am looking forward for a reply soon!

**Comment by magnapeccatrix** [comment]
There is a turbo fan button on laptop but I am using HDMI output so lid is always closed behind my external monitor so it is really frustating to set it max by messing all my work desk.

I am really looking forward for a profile on my laptop.

Could you connect my laptop through TeamViewer and gather necessary info for creating profile?

Thank you.

**Comment by TobiasKi** [comment]
Try this: #32

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by ivanjaros** [comment]
I Have MSI GE60 and the fan drives me nuts. It constantly goes up and down/hi-low. Unfortunately the nbfc.exe config --recommend yields nothing and so far none of the pre-set configs work. Most likely an issue on firmware level :(

**Comment by magnapeccatrix** [comment]
Wow it's been years and I still think owner will not care. Your best bet is to work your way out by finding values and creating your own laptop's profile. I disassembled my laptop many times that also worths a try if you haven't.

**Comment by chuxubank** [comment]
@ivanjaros You should try Dragon Center.

**Comment by ivanjaros** [comment]
@chuxubank Didn't work. I found firmware patch from msi from 2013 but it does not apply to win 10.
So far I got lucky and found a thread on msi forums and a solution that uses Fan Tools + RWeverything. It works like a charm but it has to be run manually after every time a pc is woken up or restarted. Better than nothing. That fan is exactly like the Chinese water torture.

**Comment by chuxubank** [comment]
@ivanjaros 
Try this [Dragon Center](http://download-cn.msi.com/uti_exe/nb/DragonCenterv1.2.1804.1201_1.2.1804.1201_0xc3de01cd.zip). 
It works perfect on my MSI GP62.
