### ISSUE TITLE
UX430uq

### ISSUE THREAD

**Issue by Elziebelzie** [hirschmann/nbfc#342]
My fan is unbearably loud on my ASUS UX430uq but I cannot find a version that works for this notebook model. Will settings for another model work at all? Or will you consider making a version that works?
Thanks :)

**Comment by Jonas1312** [comment]
Please try the UX410UQ configuration with NBFC 1.5.0
[https://raw.githubusercontent.com/hirschmann/nbfc/master/Configs/Asus%20Zenbook%20UX410UQ.xml](url)

**Comment by Elziebelzie** [comment]
Hi there, 
I have been using the ux410UQ version and it does allow me to turn the fans off and on but that is all, if they are on at '12.5%' it sounds the same as at 100%. This is still helpful as it allows me to turn it off when in a quiet room but is there anything I can do to make it work for low fan speeds? Thank you!

**Comment by hirschmann** [comment]
You could try some of the existing configs. Usually it's a good idea to start with the configs NBFC recommends: `nbfc.exe config --recommend` (see https://github.com/hirschmann/nbfc/wiki/Command-line-interface#commands).
If this doesn't help, read this guide to get a clue of how to adapt a config file to your notebook: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by erkexzcx** [comment]
Hi,

I am Arch Linux user and AUR packages **nbfc** and **nbfc-git** maintainer. I am also using this notebook and NBFC works amazing with **UX410UQ** profile.

I also noticed, that fan is spinning _nearly_ all the time. In order to fix it, I slightly modified **UX410UQ** profile. Just edit profile `Asus Zenbook UX410UQ.xml` and paste the following content:
```
<?xml version="1.0"?>
<FanControlConfigV2 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NotebookModel>ASUSTeK COMPUTER INC. UX410UQK</NotebookModel>
  <Author>xant1, jws, jonas1312</Author>
  <EcPollInterval>300</EcPollInterval>
  <ReadWriteWords>false</ReadWriteWords>
  <CriticalTemperature>75</CriticalTemperature>
  <FanConfigurations>
    <FanConfiguration>
      <ReadRegister>151</ReadRegister>
      <WriteRegister>151</WriteRegister>
      <MinSpeedValue>0</MinSpeedValue>
      <MaxSpeedValue>8</MaxSpeedValue>
      <IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
      <MinSpeedValueRead>0</MinSpeedValueRead>
      <MaxSpeedValueRead>0</MaxSpeedValueRead>
      <ResetRequired>true</ResetRequired>
      <FanSpeedResetValue>9</FanSpeedResetValue>
      <TemperatureThresholds>
        <TemperatureThreshold>
          <UpThreshold>0</UpThreshold>
          <DownThreshold>0</DownThreshold>
          <FanSpeed>0</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>53</UpThreshold>
          <DownThreshold>43</DownThreshold>
          <FanSpeed>25</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>68</UpThreshold>
          <DownThreshold>58</DownThreshold>
          <FanSpeed>50</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>74</UpThreshold>
          <DownThreshold>65</DownThreshold>
          <FanSpeed>75</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>80</UpThreshold>
          <DownThreshold>72</DownThreshold>
          <FanSpeed>100</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>45</UpThreshold>
          <DownThreshold>40</DownThreshold>
          <FanSpeed>12.5</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>60</UpThreshold>
          <DownThreshold>51</DownThreshold>
          <FanSpeed>37.5</FanSpeed>
        </TemperatureThreshold>
      </TemperatureThresholds>
      <FanSpeedPercentageOverrides />
    </FanConfiguration>
  </FanConfigurations>
  <RegisterWriteConfigurations>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnWriteFanSpeed</WriteOccasion>
      <Register>160</Register>
      <Value>10</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>10</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
    </RegisterWriteConfiguration>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnWriteFanSpeed</WriteOccasion>
      <Register>166</Register>
      <Value>10</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>10</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
    </RegisterWriteConfiguration>
  </RegisterWriteConfigurations>
</FanControlConfigV2>
```
And now for the most of the time fan is completely stopped and starts spinning when required. Also tested on heavy load - works just fine.

**Comment by hirschmann** [comment]
@erkexzcx 
It would be nice if you could create a pull request for the updated config.
Also, thank you for maintaining AUR packages for NBFC :) 👍

**Comment by Jonas1312** [comment]
I'm the creator of the UX410UQ xml config and the current version works fine for me, my laptop is always between 38°C and 41°C, but you can pull yours no problem

**Comment by erkexzcx** [comment]
@hirschmann - this is pure gold, that you managed to port this app to Linux. What I am not happy that it does not run nativelly (talking about C or C++), but under mono.

Anyway, i never had a chance to perform pull request. I will check once I have time and do it :) Also, I will need to update this config, because what I did is i increased a single temp value number (but it works). :)

**Comment by erkexzcx** [comment]
Created pull request. Please check and let me know.
