### ISSUE TITLE
HP Pavilion DV6 Turbo Boost does not work

### ISSUE THREAD

**Issue by steam3d** [hirschmann/nbfc#343]
with HP Pavilion DV6 laptops only config HP Pavilion dv6 6190 works. When you turn on the config, Turbo Boost is disabled. Аnd does not turn on (Turbo Boost) until you turn off the config and restart the laptop.
How do I fix this?

**Comment by OakSorcerer** [comment]
Same problem, but i have dv7 6153er. It seems to work, bit under heavy load it resets cpu speed to stock.
