### ISSUE TITLE
No config is working for ASUS ROG GL552VX Model

### ISSUE THREAD

**Issue by THEBOSS619** [hirschmann/nbfc#345]
I have tried all type of asus rog models and non of them works... also I tried the nbfc.exe config --recommend thingy and it shows other ASUS model but still it doesn't work!

I hope to consider this and I'm ready to help if there is anything specific you want in order to find a solution for this... thank you :)

**Comment by hirschmann** [comment]
Have a look at https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by THEBOSS619** [comment]
I will try my best really.. I believe that doing it is above my limit to find those MB documents, registers ,etc... 

anyway.. thank you.

**Comment by THEBOSS619** [comment]
Bump...
