### ISSUE TITLE
Add config for Asus Vivobook X202E

### ISSUE THREAD

**Issue by saiva1** [hirschmann/nbfc#346]
Hello,

I'm using ASUS Vivobook X202E.
Would it be possible to add in the NBFC a config for the ASUS Vivobook X202E?

I'm currently using the config for ASUS Zenbook UX31A, but this config isn't working correctly. For example, Fan speed changes in itself, nor with manually setup nor automatically.

Big thanks!

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
