### ISSUE TITLE
No NoteBook FanControl main folder.

### ISSUE THREAD

**Issue by VariousBlue** [hirschmann/nbfc#348]
I cant use nbfc at all, i tried so many times but it doesn't work. I manage to install it but there's no main folder, no exe or anything. Help please? im using Lenovo U41.

Im so frustrated because my laptop keep lagging.

**Comment by hirschmann** [comment]
Have you looked at the right spot? Have a look at: https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

Has your anti-virus disrupted the NBFC installer, or deleted any files?

**Comment by VariousBlue** [comment]
I have, my antivirus is not disrupting it. It happened 2 days ago when i opened up NBFC and the config option is empty. I decided to repair it but it doesnt work (usually it works), so i have to uninstall and reinnstall it again,  but this time the NBFC didn't work,  even theres no NBFC main folder.

Here what happen when i try to install it again
![nbfc](https://user-images.githubusercontent.com/32294144/30962136-d85b9bda-a472-11e7-932e-a4f36af3d409.png)

**Comment by hirschmann** [comment]
Try to uninstall NBFC via the Windows control panel and then install the latest NBFC beta (1.5.3)

**Comment by VariousBlue** [comment]
I tried so many times, still the sam. Heres the service log.
![error](https://user-images.githubusercontent.com/32294144/31080567-3df885be-a7b3-11e7-8a62-e6e00926f84a.png)

**Comment by hirschmann** [comment]
1. Start a powershell instance **as Administrator**
2. List all installed versions of NBFC:
```powershell
Get-WmiObject -Class "Win32_Product" | where {$_.Name -match "NoteBook FanControl"}
```
3. Save the ouput of the command from step 2 somewhere, so you can post it here afterwards
4. Uninstall all installed NBFC versions:
```powershell
Get-WmiObject -Class "Win32_Product"|where {$_.Name -match "NoteBook FanControl"}| % { $_.Uninstall() }
```
5. Run the command from step 2 again. It shouldn't output anything.
6. Download the setup here: https://github.com/hirschmann/nbfc/releases/tag/1.5.3-beta to make sure you have a clean installer
7. Run the downloaded setup as Administrator
8. If the setup fails, it will point you to a log file. Post this log file here.

If these steps don't help you, then I can't tell you what went wrong and you probably have to restore a Windows Restore Point or a backup.
