### ISSUE TITLE
Fujitsu Lifebook E754

### ISSUE THREAD

**Issue by Bulli** [hirschmann/nbfc#35]
How could i find out the correct register for the fan control?
This notebook has a fan control from the early 80's. It turns at 52°C the fan on, and at 48°C off. This results in a 20 sek off, 10 sek on cycle. Really annoying!

If you help me i buy you a beer! ;)

**Comment by keven1239** [comment]
did you found the problem..... I have the same problem. I sent vial canada post my laptop to Fujitsu repair center. 40 day later. I received my laptop with the same problem. grrrrrrrrrrr.

**Comment by Bulli** [comment]
the fujitsu technician was three times at our company to solve the problem. he replaced the mainboard, the fan and made a bios update. no change. he sent a ticket to fujitsu headquarter but he thinks it works „normal“.

**Comment by keven1239** [comment]
And..... Finally, the problem still not solved???????

For, me, The first time a technician change the mother board like you,not solved
After that, I shipped my laptop to Fujitsu and they did nothing, to ship me back the laptop. They said, ''We test with Hwmonitor and prime 95, and the fan work great with CPU.''
They don't open any application.... 40 day for that. today, I'm very frustrate about that.. :\

**Comment by Bulli** [comment]
The problem ist still not solved. If i hit F5 on a website the fan goes up for few seconds. I gave up, its my company computer…
Fujitsu means its working like normal.

Sometimes i run a cpu toast on one core. Then the fan makes a constant noise which i can fade out.




**Comment by hirschmann** [comment]
See https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
