### ISSUE TITLE
Installed, but all configurations disappeared - drop down box is blank

### ISSUE THREAD

**Issue by Curls100** [hirschmann/nbfc#350]
I installed successfully & could see all the configurations (for various computers) in the  "selected config" drop down box.  

So, I looked around, tried to use & change a configuration.  Next time I opened, there are NO configurations. The drop down box is blank.  Click 3 dots next to it, & that drop down box to edit is blank too.

I uninstalled NBFC without trouble. I reinstalled, and the boxes are still blank.

There must be a profile or data file somewhere or setting or something in regedit, that I need to find & delete.  But where, what is it?

Using Windows 10 64bit, Lenovo Yoga 720 15".  

Thanks!

**Comment by hirschmann** [comment]
You have probably somehow corrupted the service settings.
To solve your problem:
1. stop the NBFC service via services.msc
2. delete the service settings, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview
3. start the NBFC service via services.msc

**Comment by Curls100** [comment]
Thanks for the info!

I tried & the first "selected config" is still blank. Clicking on .... gives a window w/list I can select from & edit.  But apply, doesn't bring it forward to the first page with "selected config".

I tried unstalling through control panel. Deleting all the places with files.  (None of them were removed with uninstall.)  I reinstalled & it's same blank 1st page, config on 2nd page.

As soon as I try to edit anything, that 2nd page turns blank too again.

Notably on first page... for disabled, enable & a 3rd option (not remembering the word).  Disabled is selected by default.  I can not click on the other two options.

Since this notebook is not on the list of configs, I'm assuming I can use one of the others like the Yoga 2, and maybe adjust when the fans start that way.  If not, then this program won't help me.  I'm trying to get the fans to go on more at lower temps.

Any suggestions.  Is there a regedit that I should delete too before reinstalling?

Thanks!

**Comment by hirschmann** [comment]
Please uninstall NBFC via the Windows control panel and the install the latest beta (1.5.3).
Then, try to reproduce the error and post a NBFC service log: https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview#windows

**Comment by ajayyy** [comment]
For me I have to sometimes go to the task manager, and go to the services tab and right click on NBFC service, and click start. This will start the service and fix everything. Try that. @Curls100

**Comment by valcrystlachrymose** [comment]
i have the same issue on asus vivobook x441N, 
i tried to load other vivobook setting, then this happen.
should i try the beta version?

**Comment by ajayyy** [comment]
@valcrystlachrymose Did you try what I said in the previous comment?
