### ISSUE TITLE
Real fan behaviour doesn't follow Fan/temperature config. Asus UX310UA

### ISSUE THREAD

**Issue by orianhc06** [hirschmann/nbfc#354]
Thanks for creating this!
I have tried it on my UX310UA (with the original config file), where the fan is supposed to work at 28% above 45c, but even at 47-48c the fan is still at 0%.
Any tips on how to solve this?

**Comment by moklys** [comment]
I use the UX510UX laptop and I chose the Asus Zenbuk UX51VZA configuration.

**Comment by hirschmann** [comment]
@orianhc06
According to the UX310UA, the fan will start at 60C, not at 45C.
See https://github.com/hirschmann/nbfc/wiki/Temperature-threshold#example
