### ISSUE TITLE
This is a very good - I use the UX510UX laptop and I chose the Asus Zenbuk UX51VZA configuration.

### ISSUE THREAD

**Issue by moklys** [hirschmann/nbfc#355]
Hi,
This is a very-very good program! :)))))
I use the UX510UX laptop and I chose the Asus Zenbuk UX51VZA configuration.
I'm not a rich man. I took the laptop on credit.
**How much money to transfer for you, so as not to offend you?**
I really helped the program :)
Thank you!!!

**Comment by hirschmann** [comment]
I'm glad you like NBFC :)
Actually, you don't have to donate any money. I'm also glad about every nice message I get :D

**Comment by hirschmann** [comment]
![nbfc](https://user-images.githubusercontent.com/11175604/31864852-3ed0160c-b765-11e7-9d9e-5ccd3080c929.png)

**Comment by moklys** [comment]
Ok, The money went :))

**Comment by hirschmann** [comment]
Thank you very much! ❤️

**Comment by gothicx** [comment]
Hi! I can confirm that it works fine on the ux510ux. It's a shame that Asus doesn't provide a Quite FAN software. Thank you.

**Comment by moklys** [comment]
I am very happy :)
