### ISSUE TITLE
HP Model 17-x037cl has no config but works with HP OMEN Notebook PC 15 config

### ISSUE THREAD

**Issue by BluePhoenix175** [hirschmann/nbfc#357]
1.5.3 Beta
as the title says the OMEN config works somewhat i set target fan speed to 0.0% and the fan shut off, at 3.5% the fan starts again but continues the "pulsing fan"  (low speed - high speed - low speed - high speed - high speed - low speed....) as this is the only software that i have found that at least turns the annoying thing off im ecstatic

**Comment by hirschmann** [comment]
Thanks for the info. 👍 
Because of the "pulsing fan" problems, I will not add a 17-x037cl config to the repo for now.

**Comment by BluePhoenix175** [comment]
the "pulsing fan" is the reason i was looking for something to control the fan. i have found [forum posts](https://h30434.www3.hp.com/t5/Business-Notebooks/HP-Probook-650-G2-Fan-is-constantly-ramping-up-and-down/td-p/5575143) describing the problem across multiple HP models. this software(config) does allow me to turn the fan on and operate normally IF the computer is getting hot once it crosses the temp threshold, and then goes back to pulsing once cooled off, and i use the software to shut the annoying thing off again till it gets hot.
