### ISSUE TITLE
Lenovo U310 Configuration

### ISSUE THREAD

**Issue by SohJianke** [hirschmann/nbfc#359]
Dear Sir,

Hi @hirschmann. I have been a fan of your Notebook FanControl Application for a long time. This the only application that works for my Lenovo U310 Laptop due to Lenovo restrictions. I have been using other Lenovo Laptop configurations on your Application for the past few years and would like a dedicated one for my Lenovo U310. Hope to hear from you soon.

Best regards,
Soh Jianke
Lenovo U310 User

**Comment by hirschmann** [comment]
You could create a config for the U310 (based on the config you're currently using) yourself.
See https://github.com/hirschmann/nbfc/wiki/Structure-of-a-NBFC-config-file

As soon as you have created a working config, just create a pull request or upload it here and I will review it and add it to the repo.
