### ISSUE TITLE
Interferes with touchpad

### ISSUE THREAD

**Issue by lfuser** [hirschmann/nbfc#36]
Hi,
after a lot of testing I have undoubtedly concluded that NFC interferes with the touchpad on my laptop, causing it to constantly hang for short periods of time.

Laptop is an Asus K501LX-EB71. I'm using ASUS Zenbook UX32LN config.
I've tested it on Windows 7, 8 and 10, with all different touchpad drivers available I could find (this issue has been really annoying me, so I've already tried all workarounds I could imagine haha).

Disabling the NFC Service makes it work normally again. It's like day and night. I simply can't use the notebook touchpad with the NFC Service active. USB mouses aren't affected by this.

Let me know if you need any further information or testing.
Thanks for the hard work!

**Comment by hirschmann** [comment]
Sounds like the UX32LN config requires some adjustments to work properly on your notebook.
The first thing you should test is, if the touchpad also hangs if NBFC does not write anything to the EC registers (read only). With the latest release (1.3.4) this is not possible.

But I plan to release a new version tomorrow which comes with a EC probing tool, so please be patient :)

**Comment by hirschmann** [comment]
With NBFC version 1.4.2 you can do the following:
1. Stop the NBFC service
2. Start powershell (as Admin)
3. Navigate to the NBFC install directory
4. Paste this little script into powershell:
```powershell
while($true) { ./ec-probe read 151; sleep 1 }
```
(reads every second from register 151)
5. Check if the touchpad shows strange behavior
6. You can stop the script via `ctrl + c` afterwards

**Comment by RedGoblinz** [comment]
Hi, thank you so much for your app, really made the laptop fan better for me. However I have a similar problem as the OP.

I did what you said, for both 151 and 152, intervals 1s, 0.5s and 0.1s. All scenarios cause the touchpad to stutter. I realized when the reading is delayed, the touchpad stutters.

**Comment by goa48** [comment]
I have the same issue. A fix would be greatly appreciated.

**Comment by hirschmann** [comment]
I'm sorry, but I can't fix this issue. Because it is not even possible to read EC registers without interfering with the touch pad, I don't think I can make NBFC work properly on your notebook.
