### ISSUE TITLE
not working with all apps

### ISSUE THREAD

**Issue by MariusFilho** [hirschmann/nbfc#364]
Hi all, 
I`ve made a profile for the NBFC to reach 100% at certain temperatures but It does not work all the time.
When I play CSGO it works perfect. I can hear/fell the fan speed increasing as its supposed to be BUT when I play Overwatch, for exemple, it does not work and I got pretty much high temps on GPU.
Does any had any problem like this before?

**Comment by hirschmann** [comment]
Currently NBFC uses the CPU temperature as reference temperature for controlling the fan(s).
I know this can be an issue. I have explained why there is no easy fix for this problem here: #203
