### ISSUE TITLE
NBFC is not running my Fan

### ISSUE THREAD

**Issue by eduquezada** [hirschmann/nbfc#365]
Hi guys, I were regulary using your program.
It was good, i could manage the speed as I needed but:
- Now my fan is not moving, even if I put it in 100% of speed

(I downloaded NBFC, b'cos my zenbook had a really noisy fan, but now its all the opposite)

Thanks!
![problem](https://user-images.githubusercontent.com/33166913/32128564-25f51eb8-bb55-11e7-8524-0b819180faa0.jpg)

**Comment by hirschmann** [comment]
Try this:
https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc

or this:
https://github.com/hirschmann/nbfc/wiki/FAQ#is-there-a-way-to-reset-my-notebook-if-something-went-wrong
