### ISSUE TITLE
Cannot choose a config - dropdown empty

### ISSUE THREAD

**Issue by AndrejTelle** [hirschmann/nbfc#367]
After installing nbfc on windows 10, opening the programm, clicking the "..." button to select a config, the dropdown in the popup is empty. So I cannot select my notebook.

![2017-10-29_20h56_27](https://user-images.githubusercontent.com/195394/32147699-a7c1bbc6-bceb-11e7-9655-61398b511b6c.png)

I have all configs in the Configs folder.

Tried reinstalling already.

My notebook is supported, too.

**Comment by hirschmann** [comment]
Looks like the NBFC service is not running.
Please post a service log here (see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview)

**Comment by AndrejTelle** [comment]
![image](https://user-images.githubusercontent.com/195394/32297666-1f7e32b4-bf50-11e7-8166-4e1a1b34bc56.png)
do you mean this?

**Comment by hirschmann** [comment]
The NBFC service doesn't start on your system, because it can't access the CPU temperature sensors.
this is usually caused by other software which interferes (e.g. anti virus or other hardware monitoring tools), see https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc

**Comment by AndrejTelle** [comment]
I installed the 1.5.3 beta and now it seems to work as expected. Fans and temperature seem to be correctly detected

**Comment by AndrejTelle** [comment]
Hi Stefan, 
is there any way I can support your project nbfc with a donation? It really helped me out a lot and I would love to give back :)

**Comment by hirschmann** [comment]
Hi Andrej, I'm glad you got NBFC to work on your notebook :)

If you want to donate, you can click the link on the NBFC client:
![31864852-3ed0160c-b765-11e7-9d9e-5ccd3080c929](https://user-images.githubusercontent.com/11175604/32633831-66252ed4-c5a9-11e7-9582-015ce86cf4c1.png)

In case the link on the client doesn't work, this is the direct link:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HUALCC9HY9MKC

**Comment by AndrejTelle** [comment]
nice - enjoy your beers :D

On Thu, Nov 9, 2017 at 11:57 PM, Stefan Hirschmann <notifications@github.com

**Comment by hirschmann** [comment]
Thank you very much! 🍺
