### ISSUE TITLE
Need help after the cloning step (Linux)

### ISSUE THREAD

**Issue by htt-duong93** [hirschmann/nbfc#368]
I'm currently trying to install NBFC on my ubuntu laptop while following the steps in this blog : https://blog.briantruscott.com/how-to-enable-laptop-fan-in-linux-with-nbfc/

Under the "Downloading NBFC" section, I'm trying to clone the /opt/directory with the exact command line but i get the following error message : 
"bash: cd: /opt/nbfc: No such file or directory"

Are there any solutions for this?

**Comment by GreyWorks** [comment]
Seems to me there is a text formatting problem on that page.
Have you tried to directly clone it to the /opt directory (not /opt/directrory) with that command?
It should clone to /opt/nbfc.

**Comment by Kyuuren** [comment]
You're right.... rookie mistake. I am new to Linux distributions so I didn't notice the mistake. However when I do the next step -> " sudo sh build.sh " the terminal sends me a message that displays : 
" build.sh: 10: build.sh: Syntax error: "}" unexpected "

Basically, the terminal doesn't download the rest of the files for me.

**Comment by GreyWorks** [comment]
No problem. Everyone using Linux was a rookie sometime. I think i can help here, too :)
Roaming around the closed issues i found #324.
It points to [a stackoverflow post](https://askubuntu.com/questions/834853/ubuntu-bash-functions-syntax-error-or-unexpected)

Basic TLDR: 
Make the file executable if it isn't already:
`chmod +x build.sh`
Then run it like `sudo ./build.sh` instead of `sudo sh build.sh`

Hope that helps.

**Comment by Kyuuren** [comment]
Awesome thanks! I have the service up and running, however I only have one final step before I can get the service to fully run properly on start-up...
I followed everything correctly in the blog, but I can't get the last instruction executed properly : 
"sudo sh nbfc.sh"

I made the file executable and then ran the exact way you showed me and this error appears : 
"./nbfc.sh: 8: ./nbfc.sh: Syntax error: newline unexpected"

**Comment by hirschmann** [comment]
@Kyuuren there is a tutorial on how to run NBFC on Linux in the NBFC wiki: https://github.com/hirschmann/nbfc/wiki/First-steps#linux
