### ISSUE TITLE
Speed resets to auto after resuming windows from sleep

### ISSUE THREAD

**Issue by Kryptoxic** [hirschmann/nbfc#37]
I have checked the box for the fan control service to be enabled but the fan still resets to auto whenever I put the laptop to sleep and resume windows afterwards. It's really annoying that I have to keep resetting the fan speed to auto especially when I have to put my laptop to sleep whenever I change classes. I have confirmed that the service is setup to run automatically in services.msc. I'm currently running an Asus G56JR and Windows 10 Home. Help is much appreciated.

**Comment by hirschmann** [comment]
Actually NBFC re-initializes the EC after standby to prevent the behavior you described.
Which config do you use?

**Comment by Kryptoxic** [comment]
I use the N56JR profile for my G56JR. It always runs the fan at 100% which I set it to at every startup or resume without me changing anything when I was on Windows 8.1. After upgrading to 10, it keeps resetting to Auto and I have to set it to 100% manually.

**Comment by Kryptoxic** [comment]
As of the latest release, the issue is still happening for me.

**Comment by hirschmann** [comment]
Fixed by 8b50977ed817b78cbc4c17c67a7bba72325ff520
Sorry that it took so long.
