### ISSUE TITLE
Add longer description field to configs

### ISSUE THREAD

**Issue by sladiri** [hirschmann/nbfc#370]
It could be useful if there was a description text available for a config. This way the author could make it easier for users to choose between multiple configs for the same model. One detail that would be useful is how a config changes the fan curve compared to the stock curve.

**Comment by hirschmann** [comment]
Thanks for the suggestion. I will add a comment field in the next release.

**Comment by sladiri** [comment]
I thought of it when I read the contribution guidelines for config files. The discription about related (base-)configs could be included maybe.
