### ISSUE TITLE
Support for double fan Vivobook Pro N580VD 

### ISSUE THREAD

**Issue by Ensyell** [hirschmann/nbfc#372]
Hi,
I have an Asus N580VD and I found the configuration for Asus UX51VZA works very well with this computer. The problem I have is that this configuration affects only one of the two fans of this PC, the left one. 
Can you tell me if it is possible to affect the second fan in the configuration?
Thank you.

**Comment by Ensyell** [comment]
Hi, I figured it out and I created a configuration for this PC. I tried it and it works in all conditions: idle, internet, video playing and gaming. Thank you.

**Comment by lullabyX** [comment]
> Hi, I figured it out and I created a configuration for this PC. I tried it and it works in all conditions: idle, internet, video playing and gaming. Thank you.

Hi, could you share how you did it? My N580GD is overheating and the fan is not spinning to full speed. I'm guessing N580VD's configuration should work on N580GD.

**Comment by eidan99** [comment]
i need that too,i have a n580vd,and it still shows me 0% current fan speed
