### ISSUE TITLE
Adjusts fan speed down, but not back up

### ISSUE THREAD

**Issue by fogeshan** [hirschmann/nbfc#375]
I'm using the supplied config for a Lenovo Yoga 2 13 notebook.

NBFC can control the fan speed, but after automatically adjusting the fan speed down, it doesn't adjust it back up when the CPU warms up. 

In the supplied config the low fan speed is 0, so it effectively turns off the fan and never turns it back on.

**Comment by hirschmann** [comment]
The Lenovo Yoga 2 13 config which is shipped with NBFC should turn the fan on at 57C.
If you don't like the predefined temperature thresholds you can adjust them, see https://github.com/hirschmann/nbfc/wiki/Temperature-threshold
