### ISSUE TITLE
Beim Aspire Vx 5 591g läuft es nicht

### ISSUE THREAD

**Issue by scgock** [hirschmann/nbfc#376]
Hallo!! Ich benutze ein Aspire Vx5 591g und habe das Tool ausprobiert,krieg es nicht zum laufen.habe ähnliche configs ausprobiert die gehen aber nicht.bei älteren Notebooks die ich hatte lief alles ohne Probleme.weiss Jemand ein Rat?

**Comment by hirschmann** [comment]
For support in German, post in this thread: https://www.computerbase.de/forum/showthread.php?t=1070494
