### ISSUE TITLE
Couldn't reinstall NBFC if I accidentally deleted files in Package Cache

### ISSUE THREAD

**Issue by xponen** [hirschmann/nbfc#379]
When NbfcSetup.msi is missing then I couldn't provide the missing file to proceed in Installer. I know it is really weird/rare thing to happen, but when I'm reverting from Window 10 Fall Creator upgrade the file is missing from Package Cache (at least for me) and I have no way to re-install NBFC properly with Installer.

**Comment by xponen** [comment]
Ops, nevermind, nobody should worry about his. I fixed it myself. I manually removed Uninstall entry of programs by editing registry and the now Nbfc reinstalled just fine.

**Comment by Cartesson** [comment]
I have the same issue, how can I solve it? In my case I did a rollback from a version of windows and can't install it again.
