### ISSUE TITLE
mozroots is depricated

### ISSUE THREAD

**Issue by mateli** [hirschmann/nbfc#380]
On Fedora 26 mozroots does zilch in getting nbfc to build. This however worked:
cert-sync /etc/pki/tls/certs/ca-bundle.crt

Also "dnf install nuget" pulled in the neccessary dependencies. The installed nuget was to old but the dependencies seems to work.

**Comment by hirschmann** [comment]
I relied on mozroots because in contrast to cert-sync it is available on older distros.
But since it is deprecated for some time now, I guess it's time to switch to cert-sync.

I've updated the build script: ee3e2f8f185d4194f4452329ad667eef949b7943
