### ISSUE TITLE
"Connection refused" is the only result of running a command

### ISSUE THREAD

**Issue by jamerst** [hirschmann/nbfc#383]
Every argument apart from --version seems to just output "Connection refused". Some commands such as listing config files also output an object reference error. but that's probably just due to problems caused by the initial connection refusal.

I'm running version 1.5.2.0 (according to --version, the zip file is named 1.5.3-beta) on Linux Mint 18.2.

The binary I'm using is the prebuilt binary posted in another issue because I was having problems building it myself - there were many errors regarding types not being defined even though I do have mono-complete installed.

**Comment by miker** [comment]
Did you start nbfc, and load a compatible config?

How are you actually issuing the commands?

**Comment by jamerst** [comment]
I am unable to either start or load a config at all. Using either start or config just outputs "Connection refused". I did add nbfc as a service, but I can't check the status as the status option also does the same.

I'm just running the commands in terminal.

**Comment by hirschmann** [comment]
Check if the nbfc service is running: `systemctl status nbfc`
Also please post logs, otherwise I can't help you. See https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by jamerst** [comment]
I've found what the problem was. The directory structure under /opt/nbfc was incorrect, so the service was unable to start. It seems to be working fine now, thanks anyway.
