### ISSUE TITLE
Please HELP!!!!!!!  ASUS GL552VW

### ISSUE THREAD

**Issue by UltraPogi** [hirschmann/nbfc#384]
Can someone please write a config for ASUS GL552VW? I'm clueless & none of the available profiles work.  ;(

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by UltraPogi** [comment]
What the heck, why did you close the case? You power tripping moderator? 

I read the tutorial & don't feel comfortable making my own NBFC config, I don't wanna damage my laptop in the process.
