### ISSUE TITLE
Add support for Clevo-based systems

### ISSUE THREAD

**Issue by Brainiarc7** [hirschmann/nbfc#385]
Some tools, such as the clevo-xsm-wmi package already offer this support, and it would be good to extend it to this package.

**Comment by hirschmann** [comment]
As far as I can see clevo-xsm-wmi only offers read support, but no write support: https://github.com/rafaelgieschke/clevo-xsm-wmi/blob/3d83230a2fd785fd2f0087e50d9cfae84d310e60/module/clevo-xsm-wmi.c#L1199

But you could give it a try and create a NBFC config with the following settings:
ReadWriteWords: true
ReadRegister: 208
WriteRegister: 208

**Comment by Brainiarc7** [comment]
I'll give it a try.

**Comment by Brainiarc7** [comment]
@cyberpunkbln , no.

I now use [Tuxedo's fan control utility](https://github.com/tuxedocomputers/tuxedo-fan-control).
