### ISSUE TITLE
Asus N552VW

### ISSUE THREAD

**Issue by travelj** [hirschmann/nbfc#386]
Would it be possible to add a configuration for the following model to your pull-down menu: Asus N552VW?

In the meantime, which of the existing configurations in version 1.5.0 should I use for my Asus N552VW? For example, is the existing configuration for Asus N550JV appropriate also for Asus N552VW?

Many thanks for your help!

**Comment by hirschmann** [comment]
You could just try if one of the existing configs works for your notebook.

Also:
> Before creating a new issue, give the configs recommended by NBFC a try: `nbfc.exe config --recommend` (for further information, have a look at the NBFC command line interface)

See https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests
