### ISSUE TITLE
force single instance 

### ISSUE THREAD

**Issue by BluePhoenix175** [hirschmann/nbfc#395]
just a suggestion for improvements. i have pined the program to the taskbar for convenience but because when minimized it runs in the background(hidden icons by the clock) and the icon on the taskbar no longer shows it as "active" i was clicking the icon to "open the minimized" program and opening a new instance of the program instead at one point i had 6 instances of the program running at once. it would be nice if clicking the icon opens the minimized window that is already running or just opens a new one and closes the old one.
Thanks

**Comment by hirschmann** [comment]
You can drag the NBFC notify icon onto the taskbar tray to pin it there, so it doesn't get hidden.
Actually, it's intended behavior that users are able to open multiple instances of the NBFC client application.
But I'll consider implementing an optional "single instance mode".

**Comment by ghost** [comment]
Any chance to implement this? I keep opening it from the Start menu instead of the tray icon out of habit, and it's a bit annoying. Not sure what exactly having multiple instances of the GUI open achieves.
