### ISSUE TITLE
Linux build fails with latest commits

### ISSUE THREAD

**Issue by erkexzcx** [hirschmann/nbfc#397]
See https://travis-ci.org/hirschmann/nbfc - it fails too!

**Comment by hirschmann** [comment]
Sorry. 
It's fixed now: ad890030ac774441c62e8b9fe779a21b8141daa1

I didn't know there is also a nbfc-git AUR package. From now on I will only push stables, betas and hotfixes to the master branch.

**Comment by erkexzcx** [comment]
This is amazing! Thanks a lot!
