### ISSUE TITLE
Fujitsu Lifebook E554

### ISSUE THREAD

**Issue by obefritz** [hirschmann/nbfc#4]
Hello,
could I find a config file for the Fujitsu Lifebook E554 (FJNB281) anywhere?
Thanks in advance for any hint!
Regards,
obefritz

**Comment by hirschmann** [comment]
I'm sorry, but I can't help you with that.
This is not an issue with NBFC itself.

**Comment by DiMA6pEyc** [comment]
GENERAL
Packaged Quantity1
ManufacturerFujitsu
PROCESSOR / CHIPSET
CPUIntel Core i5 (4th Gen) 4210M / 2.6 GHz
Max Turbo Speed3.2 GHz
Number of CoresDual-Core
CacheL3 - 3 MB
64-bit ComputingYes
Chipset TypeMobile Intel HM86 Express
FeaturesIntel Turbo Boost Technology 2.0
CACHE MEMORY
TypeL3 cache
Installed Size3 MB
RAM
Memory Speed1600 MHz
Memory Specification CompliancePC3-12800
Configuration Features1 x 4 GB
TechnologyDDR3L SDRAM
Installed Size4 GB
Rated Memory Speed1600 MHz
STORAGE
InterfaceSerial ATA-300
Optical DriveDVD±RW (±R DL) / DVD-RAM removable
MEMORY
Max Supported Size16 GB
TechnologyDDR3L SDRAM
Speed1600 MHz / PC3-12800
Slots Qty2
Empty Slots1
ENVIRONMENTAL PARAMETERS
Humidity Range Operating20 - 80%
DISPLAY
LCD Backlight TechnologyLED backlight
Resolution1366 x 768 (HD)
Widescreen DisplayYes
Monitor Featuresanti-glare, compound
TypeLED
Diagonal Size (metric)39.6 cm
Display Resolution AbbreviationHD
HARD DRIVE
Spindle Speed5400 rpm
TypeHDD
Capacity320 GB
AUDIO & VIDEO
Graphics ProcessorIntel HD Graphics 4600
Memory Allocation Technologyshared video memory (UMA)
Integrated WebcamYes
SoundStereo speakers, stereo microphone
Audio CodecRealtek ALC3233
INPUT
Typekeyboard, touchpad
Localization & LayoutUS
Featuresspill-resistant
COMMUNICATIONS
Wireless Protocol802.11b/g/n, Bluetooth 4.0
Wireless ControllerIntel Wireless-N 7260
Wired ProtocolGigabit Ethernet
OPTICAL STORAGE
Drive TypeDVD SuperMulti
TypeDVD±RW (±R DL) / DVD-RAM
Form Factorremovable
PROCESSOR
CPU TypeCore i5
Processor Numberi5-4210M
Generation4
ManufacturerIntel
Clock Speed2.6 GHz
CARD READER
Typecard reader
Supported Flash MemorySD Memory Card
BATTERY
Capacity63 Wh
Cells6-cell
Technologylithium ion
Run Time (Up To)8.5 hour(s)
AC ADAPTER
InputAC 120/230 V (50/60 Hz)
Output65 Watt, 19 V, 3.42 A
CONNECTIONS & EXPANSION
Expansion Bays1 x Modular Bay
InterfacesHeadphone output
Microphone input
3 x USB 3.0
VGA
DisplayPort
LAN
Dock
Memory Card ReaderYes (SD Card)
HEADER
BrandFujitsu
Product LineFujitsu LIFEBOOK
ModelE554
Packaged Quantity1
CompatibilityPC
NETWORKING
Data Link ProtocolBluetooth 4.0, Ethernet, Fast Ethernet, Gigabit Ethernet, IEEE 802.11b, IEEE 802.11g, IEEE 802.11n
Ethernet Controller(s)Realtek RTL8111G
Wireless NICIntel Wireless-N 7260
MISCELLANEOUS
Features1 USB 3.0 with Anytime USB Charge, administrator password, hard drive password, system password
Compliant StandardsCB, FCC Part 15 B, FCC Part 15 C, FCC Part 15 E, ICES-003 Class B, RSS-210, UL, cUL
Included Accessoriespower adapter
Theft/Intrusion Protectionsecurity lock slot (cable lock sold separately)
Security Slot TypeKensington security slot
MONITOR
Diagonal Size15.6 in
SYSTEM
Notebook Typenotebook
PlatformWindows
Hard Drive Capacity320 GB
DockableYes
DIMENSIONS & WEIGHT
Width14.7 in
Depth9.8 in
Height1.2 in
MANUFACTURER WARRANTY
Type3 years warranty
MAINBOARD
Chipset TypeMobile Intel HM86 Express
ENVIRONMENTAL STANDARDS
ENERGY STAR CertifiedYes
PHYSICAL CHARACTERISTICS
Weight4.85 lbs
POWER
Min Operating Temperature41 °F
Max Operating Temperature95 °F
OPERATING SYSTEM / SOFTWARE
OS Provided: TypeWindows 8.1 64-bit Edition
TypeAdobe Reader, Anytime USB Charge Utility, CyberLink MakeDisc, CyberLink PowerDirector, CyberLink Youcam, Cyberlink PowerDVD, DTS Boost, ExpressCache, Fujitsu Disc Burning Utility, Fujitsu Display Manager, Fujitsu HotKey Utility, Fujitsu Mobility Center, Intel Wireless Display, LifeBook Application Panel, McAfee Multi Access (60 days trial), Microsoft Office 2013 (Trial), Power Saving Utility, Roxio Creator
VIDEO OUTPUT
Graphics ProcessorIntel HD Graphics 4600
Graphics Processor SeriesIntel HD Graphics
VIDEO MEMORY
Memory Allocation Technologyshared video memory (UMA)
NOTEBOOK CAMERA
Integrated WebcamYes
INPUT DEVICE
Numeric KeypadYes
EXPANSION BAYS
Total Qty1
SERVICE & SUPPORT
Type3 years warranty
SERVICE & SUPPORT DETAILS
Typelimited warranty
Full Contract Period3 yearsGENERAL
ManufacturerFujitsu
