### ISSUE TITLE
Asus Zenbook UX430UA NBFC not working

### ISSUE THREAD

**Issue by GTRONICK** [hirschmann/nbfc#404]
First of all, Thanks for this awesome tool, and your excellent work on this. 
I have applied the recommended **Asus Zenbook UX430UA** config, but when the temperature thresholds are reached, the fan is not being activated. Manual speed set works, enable and disable the service works, everything seems to work, but the fan is not being activated. 

I'm using **ArchLinux**, and `Linux 4.14.4-1-ARCH #1 SMP PREEMPT`. with **LXDE**.
I have also tried modifying the config file, reducing the thresholds by 10, for example:

(Before)

```
<TemperatureThreshold>
          <UpThreshold>62</UpThreshold>
          <DownThreshold>47</DownThreshold>
          <FanSpeed>12.5</FanSpeed>
</TemperatureThreshold>
```

(After)
```
<TemperatureThreshold>
          <UpThreshold>52</UpThreshold>
          <DownThreshold>37</DownThreshold>
          <FanSpeed>12.5</FanSpeed>
</TemperatureThreshold>
```
However, the laptop reach the 41+°C and the fan is still stopped.
```
[gtronick@gtronick ~]$ nbfc status -a
Service enabled		: True
Read-only		: False
Selected config name	: Asus Zenbook UX430UA
Temperature		: 41

Fan display name	: Fan #1
Auto control enabled	: True
Critical mode enabled	: False
Current fan speed	: 0.00
Target fan speed	: 0.00
Fan speed steps		: 8
```

Thanks in advance.

**Comment by hirschmann** [comment]
Your threshold (after) would be selected if the temperature is at 52 degree (or higher).

I tried to explain how the thresholds work in the NBFC wiki: https://github.com/hirschmann/nbfc/wiki/Temperature-threshold#example
Hopefully this makes things clearer :)

**Comment by GTRONICK** [comment]
Perfect!. I have modified the default config a little, because the default initial threshold is near the 60°C, so I think, 52 is perfect for my Linux configuration. Now it is working like a charm!. Thanks a lot and keep going on this awesome project.
