### ISSUE TITLE
Yoga 720 - Fan control settings 

### ISSUE THREAD

**Issue by maverickuv** [hirschmann/nbfc#415]
Hi Team - first, thanks for building this good software.
I found that we do not have direct support for Yoga 720, so I chose the recommended Yoga 2 13. But I have quick ques regarding the settings - 
I have options to choose target fan speed - Auto or any specific percentage. What is the difference?
1. If I select Auto, will that automatically set the speed based on CPU temperature? And will that only start the fan when required? - 
**At times**, when set to auto, I see it displays,
Target fan speed = Auto, Current fan speed = 0%
And If I set a Target fan speed say = 87.5%, **all the time** it displays 
Target fan speed = 87.5%, Current fan speed = 87.5%
2. Does that mean that now the fan is always ON at 87.5% speed?
3. Also, if the laptop gets heated generally, what's the best target fan speed?

Pls help.

Thanks

**Comment by antonsundberg** [comment]
Im wondering the same.
