### ISSUE TITLE
Lenovo Ideapad 320-15ABR

### ISSUE THREAD

**Issue by vasilisraptis** [hirschmann/nbfc#418]
Could please someone help with the fan configuration of Lenovo Ideapad 320-15ABR (AMD A10)?
It's a brand new laptop but I am very disappointed and frustrated because it's so noisy..thanks in advance!

**Comment by gfanini** [comment]
I cannot adjust fan speed on Lenovo ideapad 320-15ABR too, it is AMD A10 family F model 5
I enclose the dsdt from the Lenovo bios of December 2018, is anyone able to interpret which are fan read write registers ?

[lenovo ideapad 32015ABR dsdt EC0 new.txt](https://github.com/hirschmann/nbfc/files/3101630/lenovo.ideapad.32015ABR.dsdt.EC0.new.txt)
