### ISSUE TITLE
Asus Ux430unr

### ISSUE THREAD

**Issue by wolfik85** [hirschmann/nbfc#422]
Help! Could anybody set a proper configuration code for this notebook- it's terrible loud even  on idle - cpu temp.is about 36" and fan goes all the Time on 12,5% or more.. i though about using config for other ux430 but mine has different  cpu nad gpu (i7 8550 nad mx150) so I think it won't work properly...  Heeelllp, Hilfe,  Ayudar, Aiutare, Pomocy....;)

**Comment by nikil511** [comment]
I have the same laptop and bellow 40C fan is off.
I suggest you upgrade bios, nvidia, intel drivers
For the config file, following should work fine
https://github.com/hirschmann/nbfc/blob/master/Configs/Asus%20Zenbook%20UX430UQ.xml

**Comment by erkexzcx** [comment]
https://github.com/hirschmann/nbfc/tree/master/Configs we have configs for UX430* and UX530* models. Maybe one of them works for you? Can this issue be closed?

**Comment by erkexzcx** [comment]
UX430* and UX530* were released at the same time and shares identical hardware (just size factor is different - 14" and 15.6".
