### ISSUE TITLE
Acer Predator Helios 300 (PH317-51-586M)

### ISSUE THREAD

**Issue by jedi93** [hirschmann/nbfc#428]
I want to request a config (or help creating a config) for the Acer Predator Helios 300 (PH317-51-586M). It **should** have an ENE KB9022Q-D chip. I already tried probing, but the only thing I could find was that 0x21 and 0x22 get the left/right fan to MAX and back to normal (probably the PredatorSense "MAX" setting), I can't control them other than that.

Can someone help?

P.S: I treid the recommended configs already, didn't work...

**Comment by Noisrevid** [comment]
Run the command line program inside the NBFC folder:  "ec-probe dump" and paste what it shows.    I have a newer Asus laptop and NBFC reads all registers as zeros..  so perhaps we have an issue where these newer ECs are not supported properly, even though we can use other utilities to modify registers fine.

**Comment by jedi93** [comment]
00: 02 63 02 21 06 00 00 44 0F 1E 01 01 01 00 00 02
10: 00 00 00 83 07 F8 07 00 00 00 00 00 00 00 00 00
20: 48 10 04 00 00 00 00 00 00 00 27 00 00 00 00 00
30: 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 FF
60: 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
90: 4C 47 43 34 42 38 4B 43 43 43 43 43 34 42 38 4B
A0: 00 00 00 C6 E1 00 00 61 64 00 00 08 64 2C 00 7C
B0: 2B 00 1C 27 29 00 00 00 00 0A 00 4D 88 52 11 10
C0: 83 00 E4 0C 00 BE 13 42 60 3B 94 0C E4 0C 64 01
D0: 00 00 00 00 00 A9 EE 1C 00 00 09 15 00 00 E0 00
E0: 00 00 00 80 10 85 10 83 10 89 10 87 43 E4 0C 00
F0: 43 50 00 00 C2 4A 00 00 84 00 00 00 00 00 00 00

**Comment by Noisrevid** [comment]
Looks like you should be able to use NBFC just fine honestly..    Sounds like your profile isn't set up correctly in NBFC otherwise..   Edit another Acer profile to match the read and write registers and see what happens.

**Comment by chandradeepdey** [comment]
@jedi93 I have made a pull request for my Predator Helios 300 G3-572, try if the config works. I have the same ene KB9022Q D chip.
