### ISSUE TITLE
GL702VM third fan problem?

### ISSUE THREAD

**Issue by 1tteco** [hirschmann/nbfc#429]
Hi. First post here.

Having a problem with gl702vm third fan. Installed and managed to get the 702 config working. It did control all of the 3 fans great, allthough the third boost fan did occur some random stops. Still, all of the 3 worked fine at games. Actually, heard that third fan for the first time in use!

Well, after a reboot, the third fan wont run. When I set it to 100%, I can hear some sort of coil whine and the fan trying to accelerate. Sometimes spins for a half a second, other times a quarter of a second, then waits a couple of second. Actually, can hear cpu fan doing random stops when idling (12.5%) also.

What might be causing these problems? THANKS

**Comment by ghalibhunjul** [comment]
hello..
i have the same issue as you. i controlled the 3rd fan for once then it stopped responding tot he program after a reboot.. i even ehar some weird noise when not gaming(idel))... if u have any solution please inform me
