### ISSUE TITLE
#100 isn't fixed for me

### ISSUE THREAD

**Issue by goose121** [hirschmann/nbfc#436]
Per the title, I am experiencing the same issue described in #100 on the latest commit. I'm running Artix Linux, not Ubuntu, bot otherwise the symptoms are the same, and the solution of deleting `/opt/nbfc/Plugins/StagWare.Plugins.ECSysLinux.dll` works, although I don't need to copy the other DLLs, as they are already in the `Plugins` directory.

EDIT: I'm on an ASUS Zenbook UX430UQ, in case that matters

**Comment by harlows** [comment]
The same solution worked for me with Antergos Linux on an ASUS UX310UA.

**Comment by GTRONICK** [comment]
This worked for me on ASUS UX430UA

**Comment by Imkerix** [comment]
Worked on a Fujitsu Lifebook E8420 running Arch Linux as well

**Comment by Magentium-Chris** [comment]
This may be old, but confirmed this worked for me. ArchLinux on the Asus UX430UA, same as the UQ but the UQ has a dedicated GPU.

**Comment by erkexzcx** [comment]
I am trying to summarize what we have: https://wiki.archlinux.org/index.php/Fan_speed_control#Troubleshooting
