### ISSUE TITLE
Config for ASUS K401UQ

### ISSUE THREAD

**Issue by qtvafi** [hirschmann/nbfc#437]
Is it possible to get a config for ASUS k401uq?

**Comment by vafajj** [comment]
[ASUSTeK COMPUTER INC. K401UQK.zip](https://github.com/hirschmann/nbfc/files/1866695/ASUSTeK.COMPUTER.INC.K401UQK.zip)
use this. i've made it.

**Comment by qtvafi** [comment]
Thanks.
I Will try it within a few data


A domingo, 1 de abr de 2018, 23:52, vafajj <notifications@github.com>
escreveu:
