### ISSUE TITLE
How to read out the configs for new laptops

### ISSUE THREAD

**Issue by melistik** [hirschmann/nbfc#44]
Hi,

I like your app and want to configure my laptop that is not within the preconfigured list.
How do I know which settings I need to set for reading, writing, fanspeed and so on.
I've got a **Acer Aspire E5-573** - Can I check my configuration or is there a way to proof if another config for example _Acer Aspire E5-731_ is working correctly on my machine...

Thanks and best regards

**Comment by hirschmann** [comment]
Well, you could give the Acer Aspire E5-731 config a try and see if it works.

If it doesn't, then you could read the (outdated) [NBFC user manual](https://onedrive.live.com/?id=6C34BD33AC55CE36!450&cid=6C34BD33AC55CE36).

I'm currently working on a [NBF Wiki](https://github.com/hirschmann/nbfc/wiki).
I'll add an updated "how to create a NBFC config"-article pretty soon.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
