### ISSUE TITLE
HP ZBook G4 - 0% ignored. 

### ISSUE THREAD

**Issue by Cnordbo** [hirschmann/nbfc#445]
Version: 1.5.3-beta
Profile: HP ZBook 15
Computer: HP Zbook Studio G4

State: "Set Target Fan Speed to **Auto**"

Expected behavior: 
Current fan speed to hit Target fan speed value (0.0%)

Actual Behavior: 
Fan speed "stuck" at 55%. 

Additional notes: 
Im using NBFC because there is some sort of bug with this laptop that makes the fan speed go constantly at  a minimum of 55%. 
Changing the Target Fan Speed to anything but **Auto**, will reduce \ increase the fan speed. 

After a bit of further investigation, it seems that the issue is related to **0,0%**. If auto tries to set any other value, then it will reduce\ increase the fan speed. 
This can also be triggered by just setting Target Fan Speed to 0,0% manually.

**Comment by mbrand** [comment]
I'm having the same issue,. If it's set to 0.0% the notebooks default fan speeds seem to apply.

**Comment by pressRtowin** [comment]
Isn't the Studio G4 a dual fan device? The ZBook 15 profile isn't configured for that. I modded the ZBook Studio G3 profile for my ZBook 17 G4 and it's working fine. Make sure you don't have the setting to keep the fan always enabled on AC in the UEFI as that interferes with NBFC.

**Comment by ben75020** [comment]
I'm running an HP ZBook G3 17, and noticed the same behavior. If I set the first fan to 0%, the fan will start and work like there is no NBFC enabled. Setting the first fan to 1% then it remains to 1%.
The second fan (which is in my profile) can be at 0% and there is no worry.

This is a Linux NBFC 1.5.2 running on Fedora 27.

**Comment by DerChiller** [comment]
Iam using the configuration file "HP Z-Book 15" on a HP-Z-Book G4 and its not working really correct.
The problem is that in the read-only Mode the current fan speed is a negative value. When iam enable the service (Auto) and the fans starts to run in the target value, its more louder as without fancontrol. I testet it manually and set the target speed to the minimum value 2,5%, but the fan is so loud like running with 80%. Do you know how i can solve this issue?

**Comment by Cnordbo** [comment]
DerChiller, Iknow there is a "Emergency" mode in the software (i believe its labeled when it enters this mode) - which meens that you can set it to 0%, but it will automatically go up to 80-100% as long as the CPU temperature is too high. Maybe thats whats kicking in ?

**Comment by Palpi75** [comment]
@pressRtowin  could you please share the profile you modded for you´re G4 because i have a dual fan G3 so i think it should work and my problem now is just one fan manualy controlled

**Comment by datony2019** [comment]
@Palpi75, did pressRtowin share his G4 NBFC profile with You and did it work perfectly then ? I recently bought a ZBook 17 G4 and would be very happy about the NBFC profile for this ZBook 17 G4 (upgraded the firmware to 1.25 but didn' t help in anyway).

**Comment by pressRtowin** [comment]
@Palpi75 @datony2019 sorry I never got around to this. I'll try to remember later today when I get home.

**Comment by datony2019** [comment]
@pressRtowin, just awaiting the result of Your investigation then. Would be great due to Your post from
May 1st 2018. Thanks amill in advance.

**Comment by pressRtowin** [comment]
Here's my current profile. I don't really use the auto fan control feature so you may have to edit those values. I really only use it to keep my fans cranked up to max, but I've just reedited this profile to make sure the min/max ranges are correct as well as the reset values. I had to change the extension to txt to upload here so just make sure you set it back to xml.
[HP ZBook 17 G4.txt](https://github.com/hirschmann/nbfc/files/2826106/HP.ZBook.17.G4.txt)

**Comment by datony2019** [comment]
Great for ZBook 17 G4 users as to agree. I suppose You posted already to @hirschmann concerning Your famous profile adding to ZBook 17 G4 so that he will integrate it to NBFC ? My 17 G4 is qiet now (fans at 33,3 %). Thanks amill for Your help !!!

**Comment by suddenelfilio** [comment]
this works wonders for the zbook x360 15 g5 as well thanks!
