### ISSUE TITLE
Request: Config for ASUS GL703VM

### ISSUE THREAD

**Issue by bfnk** [hirschmann/nbfc#446]
Hello,

I am having trouble getting NFC to work with my GL703 ASUS laptop. It's a newer model and the profile for GL702 does not work on it. In fact, that profile crashes the application and it then becomes basically unusable until reinstall. In one case, even that did not help and I had to delete the profile from the config editor, then re-install again.

If anyone has managed to create a usable profile for GL703, please share. :) 

Thank you!

**Comment by namar0x0309** [comment]
+1 on this.

**Comment by namar0x0309** [comment]
ec-probe
line 40
changing value in parenthesis 

enabled overboost
00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
10: 00 00 55 AA 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 00 00 00 00 00 00 00 00 07 14 F1 00
40: 00 02 14 60 43 00 00 00 BC 0F (58) 42 00 00 00 00
50: 00 00 00 00 00 00 00 00 2A 06 00 00 81 01 C0 08
60: 00 00 00 F1 00 04 38 04 30 04 90 10 BC 0F 00 00
70: 00 03 10 40 00 60 3B 64 E6 0B 00 00 00 00 00 00
80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
90: 00 00 00 00 00 00 08 08 08 08 00 00 00 00 00 00
A0: 0A 00 00 00 00 00 0A 00 00 00 00 00 0A 00 00 00
B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
C0: 00 00 00 00 00 26 00 00 00 00 00 32 00 00 9A 02
D0: 47 4C 35 30 33 34 32 00 00 00 00 00 00 00 00 07
E0: 54 4B 02 00 01 11 00 00 00 00 00 00 00 00 00 00
F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00


enabled silent mode
00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
10: 00 00 55 AA 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 00 00 00 00 00 00 00 00 07 14 F1 00
40: 00 02 14 60 43 00 00 00 BC 0F (58) 42 00 00 00 00
50: 00 00 00 00 00 00 00 00 2E 06 00 00 81 01 80 08
60: 00 00 00 F1 00 04 3B 04 18 04 90 10 BC 0F 00 00
70: 00 03 10 40 00 60 3B 64 E5 0B 00 00 00 00 00 00
80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
90: 00 00 00 00 00 00 08 08 08 08 00 00 00 00 00 00
A0: 0A 00 00 00 00 00 0A 00 00 00 00 00 0A 00 00 00
B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
C0: 00 00 00 00 00 27 00 00 00 00 00 32 00 00 9A 02
D0: 47 4C 35 30 33 34 32 00 00 00 00 00 00 00 00 07
E0: 54 4B 02 00 01 11 00 00 00 00 00 00 00 00 00 00
F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

silent mode
00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
10: 00 00 55 AA 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 00 00 00 00 00 00 00 00 07 14 F1 00
40: 00 02 14 60 43 00 00 00 BC 0F (57) 42 00 00 00 00
50: 00 00 00 00 00 00 00 00 2F 06 00 00 81 01 80 08
60: 00 00 00 F1 00 04 2C 04 43 04 90 10 BC 0F 00 00
70: 00 03 10 40 00 60 3B 64 E6 0B 00 00 00 00 00 00
80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
90: 00 00 00 00 00 00 08 08 08 08 00 00 00 00 00 00
A0: 0A 00 00 00 00 00 0A 00 00 00 00 00 0A 00 00 00
B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
C0: 00 00 00 00 00 26 00 00 00 00 00 32 00 00 9A 02
D0: 47 4C 35 30 33 34 32 00 00 00 00 00 00 00 00 07
E0: 54 4B 02 00 01 11 00 00 00 00 00 00 00 00 00 00
F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
