### ISSUE TITLE
Request: Config for Lenovo Flex 5 / Yoga 520

### ISSUE THREAD

**Issue by adatum** [hirschmann/nbfc#447]
There is no config for the Lenovo Flex 5 / Yoga 520 (same model, different name in different markets). One of the configs partly works (Yoga 510, I think), but not fully. 

If someone could figure it out for this model, it would be appreciated!

**Comment by ondrackajan** [comment]
Any luck with the profile? Or maybe have you find a better way to control your fan speed?

**Comment by adatum** [comment]
No. I found the default fan control is working well enough for now, after updating the BIOS and enabling quiet mode, and also uninstalling some bloatware. Specifically, since removing Lenovo App Installer, the laptop has become silent at idle. 

A nbfc profile would still be better for more control.

**Comment by ondrackajan** [comment]
Quiet mode is limiting CPU power as far as I know. :/
Why not to create a nbfc profile ourselves?
I have already started looking into it, but have peoblem to identify EC chip. Could you maybe help me with that?

**Comment by adatum** [comment]
It's actually not my computer; I set it up for someone else. If you have something (hopefully safe) that you'd want me to try on it, I could probably do that. Otherwise, I don't have constant access to the machine to experiment on it.

**Comment by tahaygun** [comment]
Hello, Did you find a solution @ondrackajan? And may I ask you which config file is works on Yoga 520?

**Comment by cpharlok** [comment]
Hi, I have also a Yoga 520 and I still find the quiet mode a bit annoying, so I want to use notebook fan contorl app. Now I am trying with 510 profile but seems to do nothing. Any luck finding the nbfc profile?

**Comment by ondrackajan** [comment]
Hi, no. :/ I was unable to find it. I have also tried to create it myself
but it was taking too much time...

If you find anything that could help, let me know. It's annoying. There is
just spike in cpu usage but fans start spinning like crazy.

**Comment by tahaygun** [comment]
Guys I think I changed something in my embedded controller, now tempreture is like a crazy, it goes from 50 to 70 in a second. Could you send a picture of your embedded controller please, so I can fix it maybe..

And I found the ports for changing fan speed, but it is not allowed on ec.. When I change it, nothing changes. We have just one port for closing fan completly which is 176(you can try yoga 2(13) for it.  )

**Comment by cpharlok** [comment]
I have been experimenting with the yoga 2 (13) and only the fan disconnect seems to work, not the fan speed control. I will try several profiles.

**Comment by ondrackajan** [comment]
There is probably uniqe EC so nothing will work. :/ And I have tried to
look for that EC but unsuccessfully.

**Comment by cpharlok** [comment]
When I use Manjaro Linux, it's much more silent, even using KDE (which is a desktop heavier than other options).

**Comment by ondrackajan** [comment]
Windows is full of automatic shit that causes CPU usage -> higher temps ->
fans.

**Comment by cpharlok** [comment]
Yes, I know, but monitoring the temperature, at same degrees, the fan is more silent in linux than windows. Or the temperature monitor show different values, or the fan control is acting different. For example, at 53 C, the fan is noisy in Windows, while in Linux is barely audible. The cpu load shows more spikes in Windows, while in Linux is a bit higher but with no spikes, more stable. In general, Linux works more quietly, fans activate less and quiet.

**Comment by cpharlok** [comment]
Oh by the way, I have turned on the BIOS quiet fan option.

**Comment by ondrackajan** [comment]
That's cool! Have you found a way to control it directly?

**Comment by cpharlok** [comment]
Unfortunately no. I have taken another approach to silent the laptop: decrease the background process to a minimum, disabling services and tweaking the system. Now I feel it more silent. If someone happens to get the values we need to direct control, that would be superb
