### ISSUE TITLE
Configuration of Asus zenbook UX310UQ

### ISSUE THREAD

**Issue by antonioalt** [hirschmann/nbfc#449]
I recently bought this notebook and the fans are always on, even when I turn on the PC. They turn off when the CPU temperature is at 31 degrees... I would like to turn them off under 35-40 degrees if it's possible. Please help me! Thanks for your attention (and sorry for my bad english).

**Comment by antonioalt** [comment]
heeeeelp me please

**Comment by Semmy7** [comment]
There is a config for you model. Install program, select config and set "enable" in main window. It's very easy.

**Comment by antonioalt** [comment]
My model is zenbook UX310UQ (or UX310UQK, it's the same)
![config](https://user-images.githubusercontent.com/36794803/40132402-fa98545c-593c-11e8-8473-93fbcc9120a0.jpg)
I don't find it here... I don't know if the UX310UA model has the same characteristic as mine.
Could I activate the ux310ua? 
Anyway, thanks for the answer :)

**Comment by Semmy7** [comment]
Yes,  select ux310ua and it will work!
