### ISSUE TITLE
"File Descriptor does not support writing" with latest Arch Linux kernel

### ISSUE THREAD

**Issue by erkexzcx** [hirschmann/nbfc#453]
See this image below. Installed latest version of NBFC from Github (using AUR package: [nbfc-git](https://aur.archlinux.org/packages/nbfc-git/), which I maintain by myself).

The issue itself is seem to be related to the latest Linux kernel, because on current [linux-lts 4.14.22-1](https://www.archlinux.org/packages/core/x86_64/linux-lts/) the NBFC works without problems (just had to downgrade ncurses due to #451 issue).

![image](https://user-images.githubusercontent.com/5955795/36894599-9613a9ae-1e14-11e8-8967-7abb39b4af00.png)

**Comment by 0140454** [comment]
Hi,

My ArchLinux kernel is linux-ck 4.15.13-1.
After adding kernel parameter ```ec_sys.write_support=1```, I can modify EC register.
Do you have tried adding this kernel parameter?

**Comment by Optiligence** [comment]
https://github.com/hirschmann/nbfc/issues/100

**Comment by erkexzcx** [comment]
@0140454 superb! Updated arch wiki accordingly. The issue can be closed!

**Comment by erkexzcx** [comment]
I am trying to summarize what we have: https://wiki.archlinux.org/index.php/Fan_speed_control#Troubleshooting
