### ISSUE TITLE
Config for Lenovo 720s 13-IKBR 8250u

### ISSUE THREAD

**Issue by vitas13** [hirschmann/nbfc#457]
Hello,
I'm trying to create my own config file for this laptop and i'm stuck on probing registers.
Here is mine 2 min dump form prime95:
0x00: 00,                                                                                    0A,0A
0x06: 2E,30,2E,30,            2D,2A,   29,27,            26,27,25,28,2A,29,27,28,27,   25,24,00,00
0x07: 00,                                                                                       21
0x0D: 2D,               2C,         2B,         2A,            29,2A,   29,               28,00,28
0x0E: 32,         33,32,      31,      30,               2F,      30,31,      30,      2F,2E,28,28
0x0F: 00,                                                                                    2D,2D
0x12: 80,                                                                                    00,00
0x13: 00,                                                                                       80
0x14: 05,                                                                                    00,00

This model has two fans. I think 0x06 and 0x07 is first fan and 0x0D and  0x0E is second fan, but writing to this registers don't do anything.
Maybe manual changing for EC is disabled. Someone was trying luck with this model?

**Comment by shobullus** [comment]
Any progres? Got the same notebook and the same fan problem. No preset seems to work.

**Comment by vitas13** [comment]
For my no progress so far. I think writing to the EC registers is disabeld.
Don't upgrade to the newest bios, it brakes turbo mode and as you say you are stuck at 1.5 Ghz.
You can always downgrade to old one, just turn on flash back function in bios.

**Comment by okh1** [comment]
About the turbo issue: I'm on BIOS 6CMN18WW and the problem is present. However, it's not a problem of turbo but of speed shift, which is disabled. The problem is solved if you enable speedshift in Throttlestop.

**Comment by Lixy13** [comment]
hi there! any progress since April? I'm struggling to make a working config..

**Comment by taralloc** [comment]
Is it working?
