### ISSUE TITLE
ASUS X542UQ

### ISSUE THREAD

**Issue by mongooseleon** [hirschmann/nbfc#458]
Нашел регистр 151 - отвечает за обороты. Не могу остановить полностью через короткое время пытается снова завестись. Если кто настраивал, скажите как регистр овечает за полную остановку или какой число в регистре 151 отвечает за остановку .

**Comment by doteroargentino** [comment]
I don't understand russian but I'm having trouble with my fan noise aswell so if anyone could help with a configuration file for asus X542UQ I'd be grateful
