### ISSUE TITLE
Lenovo Ideapad 320S 13IKB

### ISSUE THREAD

**Issue by englscream** [hirschmann/nbfc#459]
Hello,

i'm trying to get a working config for the Lenovo Ideapad 320S 13IKB.
The two fans are always spinning - even in idle.
In the DSDT i found one interesting name "CFAN", but no registers to it.
Then I used ec-probe. In the picture attached the fan was getting louder at 0xCA with value 0F.
It was quieter at 0xCA with value 0C.
I think it could be 0xCA and 0xCE but no fan shows a reaction.
Any help is really appreciated.
Thanks in advance.

[DSDT.txt](https://github.com/hirschmann/nbfc/files/1808873/DSDT.txt)
![test1 loud louder quiet](https://user-images.githubusercontent.com/37244268/37373128-8bee58d4-2715-11e8-8d18-916a967ebfac.PNG)

**Comment by tamas2001** [comment]
Hello
I would like to add some more info:
- Linux e-pad 4.15.13-1-MANJARO #1 SMP PREEMPT Sun Mar 25 19:51:07 UTC 2018 x86_64 GNU/Linux
- ssdt files
[dsdt-ssdt-ideapad320s-13ikb.tar.gz](https://github.com/hirschmann/nbfc/files/1860363/dsdt-ssdt-ideapad320s-13ikb.tar.gz)
- Acpi error during boot
[acpi_errors.txt](https://github.com/hirschmann/nbfc/files/1860391/acpi_errors.txt)
if there is anything else required to check/collect kindly let me know.

Thanks

**Comment by g-provost** [comment]
Without any surprise same exact ACPI errors listed by @tamas2001 under Ubuntu with 
4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mapagm** [comment]
Any news regarding configuration for this laptop? In my case fan is running constantly even on idle :/
