### ISSUE TITLE
Intermittently coming up empty after sleep

### ISSUE THREAD

**Issue by iamjaydear** [hirschmann/nbfc#46]
A few times lately I have noticed that after resuming from sleep the NBFC taskbar icon is showing 0 degrees, which would be nice if it was true :)  In the NBFC window the Selected config is empty. It is possible to select one, but it won't stick - it just goes empty again. Also, in this fault condition, the 'Fan control service enabled' box cannot be ticked and no fans are listed below it.

Unfortunately, if I don't notice the taskbar icon before starting a VidCoder job (a very processor-intensive process) and wandering away, the temperature goes sky high, the job goes really s-l-o-w and the laptop feels like it's going to melt! I've tried closing NBFC and also killing it with Process Explorer and then restarting it, but it still comes up empty. NBFC only restarts properly during a machine restart.

NBFC v1.3.4 in 'Auto', Asus N550JV, Win 8.1, VidCoder v1.5.33.0 (another GitHub project)

![Uploading NBFC01.jpg…]()

**Comment by hirschmann** [comment]
Are there any errors in the WIndows event log if you search for "NoteBookFanControlService" (event source)?

**Comment by iamjaydear** [comment]
Yes, heaps. Most of them are like NBFC3 in attached zip file.

**Comment by hirschmann** [comment]
There is no attached zip file.
Could you please upload it somwhere and send me the link?

**Comment by iamjaydear** [comment]
I wonder why GitHub invites us to attach files and then just complain that something went terribly wrong? Anyhow, here's a link... http://s000.tinyupload.com/?file_id=96517857362578830829

**Comment by hirschmann** [comment]
Thank you!
Looks like NBFC can't access the hardware after standby.

Does this happen everytime the system resumes from standby?
If yes, could you please stop the service before standby and restart it afterwards?

Do you use any other hardware monitoring tools which might interfere with NBFC?

**Comment by iamjaydear** [comment]
OK. I don't use any h/w monitoring tools as far as I know, but I have been using Imdisk to have half of my RAM as an 8GB ramdisk and yesterday I altered the settings to use dynamic memory. In the evening I went to check on a long encode and saw the dreaded 0 degrees icon in the taskbar. NBFC's control panel was blank/empty. The fan was still running, so I killed NBFC in process explorer and it kept running, so I guess it was under the control of the ASUS driver. Do you think Imdisk is the problem? I have uninstalled Imdisk today to see if NBFC stays normal. 

"Does this happen everytime the system resumes from standby?" No, not every time. This latest time is the first I have ever been aware of it happening whilst the machine is running and in use. 
Events logs at http://s000.tinyupload.com/?file_id=10497134893713420899

**Comment by iamjaydear** [comment]
It's some 24 hours since I uninstalled Imdisk. The machine was 'sleeping' overnight and when I woke it this morning NBFC was running OK. I have been using the machine on and off today and NBFC is still OK.

**Comment by hirschmann** [comment]
Ok, thanks for the feedback.
I'll mention in the NBFC wiki that lmdisk can cause trouble in conjunction with NBFC.

**Comment by iamjaydear** [comment]
Just an FYI... It's been several days now without a cold restart and NBFC is still OK.
