### ISSUE TITLE
Request: Yoga 520

### ISSUE THREAD

**Issue by tahaygun** [hirschmann/nbfc#462]
Hello,

Thank you so much for your help. I bought a new computer and when I click on folders my fan starts making noise even tempreture is 40°. Could you please make a config file for yoga 520? Thanks a lot.

**Comment by RevoArma3** [comment]
Same here, I'd much appreciate a config for the Lenovo Yoga 520.

**Comment by tahaygun** [comment]
I did everything Today but I think we are not allowed to change Fan speed by EC. Yoga 2 is partially works because it turns on/off fans,  nothing changes.

**Comment by jskov9850** [comment]
Did you ever find a fix?
