### ISSUE TITLE
How to build NBFC on Linux

### ISSUE THREAD

**Issue by freekvh** [hirschmann/nbfc#467]
The [first steps](https://github.com/hirschmann/nbfc/wiki/First-steps) for Linux starts with "After you have built NBFC, copy the files from nbfc/Linux/bin/ReleaseLinux/ to /opt/nbfc/"... but, how does one build NBFC?

**Comment by chthonic7** [comment]
[How-to-build-NBFC](https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC) presumably
