### ISSUE TITLE
Lenovo Y50-70 (20378)

### ISSUE THREAD

**Issue by Bumcha** [hirschmann/nbfc#468]
Hi hirschmann,

I found out about your software looking for a way to control the fans of certain laptops and i would like for you to add mine which is a Lenovo Y50-70 Model 20378.

I read the FAQs and everything that i need to do to create a new profile for my laptop reading the EC and stuff but i'm not good at those kinds of reading numbers like the matrix but i'm going to try when i get home, just in case i fail... what do you need from me/laptop to be able to create a fan profile for my laptop?

My model specifications:
CPU: 2.6GHz Intel Core i7-4720HQ (quad-core, 6MB cache, up to 3.6GHz with Turbo Boost)
Graphics: Nvidia GeForce GTX 960M (4GB GDDR5 RAM); Intel HD Graphics 4600.
RAM: 16GB DDR3L (2x 8GB, 1,600MHz)
Screen: 15.6-inch, 1920 x 1080 FHD, LED anti-glare backlight.
Storage: 1TB HDD (5,400 rpm with an 8GB SSD cache)

**Comment by StKob** [comment]
I've extracted dsdt from y50-70. Unfortunately I'm unable to figure it out based on this. [https://gist.github.com/StKob/d8bc8b6ef97401cf781c4f519dc41199](url)
