### ISSUE TITLE
Statusbar Icon on Linux Arch (Mate)

### ISSUE THREAD

**Issue by solnyshok** [hirschmann/nbfc#47]
Using nbfc on Linux (hp 2560p). As I dual boot it with Windows, I use xml config created and edited under Windows GUI. 

First of all, big thanks for what is already done and working. Just wanted to ask if there is supposed to be any GUI or statusbar icon while service is running? Or is it only possible to see service state via: "#mono nbfc status -a"?

**Comment by hirschmann** [comment]
Currently there is no GUI client for Linux and I don't plan to create one.
Instead I will improve the CLI client because it works on Linux as well as on Windows.
