### ISSUE TITLE
"Object reference not set to an instance of an object" Zenbook 430 Linux

### ISSUE THREAD

**Issue by SalatgurkenJoe** [hirschmann/nbfc#471]
I cant set my config for the Asus Zenbook 430, i get the error message "Object reference not set to an instance of an object" on Manjaro Linux. 
This is the first time i see this message, after setting up my manjaro lately. Before reinstalling it, it worked fine all the time. Is this a known bug?

**Comment by SalatgurkenJoe** [comment]
edit:
I downloaded the development version from the AUR nbfc-git  1.5.3.r68.g41dad9e-1 and it works fine. No problems at all.

**Comment by rgcv** [comment]
Sorry for the necrobump, but this still appears to be an issue.

On Arch kernel 5.3.8-arch1-1
nbfc-git 1.6.3.r20.g537e9b2

```sh
$ nbfc config -r
Connection refused
Object reference not set to an instance of an obejct
```
