### ISSUE TITLE
Request: Add Asus Zenbook UX331 (UN)

### ISSUE THREAD

**Issue by PennyLook** [hirschmann/nbfc#474]
Could you add configuration for Asus Zenbook UX331UN?

**Comment by swatgoss** [comment]
Hi,

I just ordered a UX331UN computer, it will be delivered in a few days and i'm willing to edit a profile for that laptop.
I also have many other laptops that i would love to see supported by this software, is there a documentation for tinkering and finding the right ports/registers to take control of fans ?

**Comment by swatgoss** [comment]
Hi back,

Just tested the 1.6.3 release with the Asus Zenbook UX31A profile and i can confirm it seems to work, for now i can force my "main" (only) fan speed up and down.

The latency of the effective fan speed changes is in tens of seconds though (mostly to ensure smooth acoustic transitions) so don't be surprised if it doesnt change the instant you set it to 100% target fan speed.

After a few minutes of playing around with nbfc 1.6.3 i didnt see any strange behavior.
