### ISSUE TITLE
Request: Add Acer Aspire VX5 591G

### ISSUE THREAD

**Issue by Esquilax91** [hirschmann/nbfc#475]
Could you add configuration for Acer Aspire VX5 591G?
Thanks in advance.

**Comment by priatnaadnyana** [comment]
yes, requesting for it too

**Comment by jaspi72** [comment]
YEAH, I WANT IT TOO. My primary nvidia 1050 stopped working and fans yelling full apeed so PLEASE ! ! !

**Comment by IFlarious** [comment]
Yes. I need it too ! Since mine was i7-7700HQ equipped with GTX1050Ti, why does Acer doesn't provide any fan boost software like the CoolBoost or PredatorSense technology within this 'gaming laptop'. Ridiculous Acer

**Comment by edr0k** [comment]
I need that too! Anyone with a solution ?

**Comment by Esquilax91** [comment]
I find this temporaly solution [https://youtu.be/-2eoWrpZwcI](url), the problem is that when you want to lower the power of the fan, it does not work well and it is solved by restarting the laptop only. This happens because it is not the corresponding model configuration. But since nobody has another solution, for as long as you can apply this.

(Sorry for my bad english)

**Comment by Esquilax91** [comment]
@hirschmann you have a idea how to fix this problem in the config?

**Comment by WR5Solutions** [comment]
@hirschmann It will be done?
