### ISSUE TITLE
Help with starting the service

### ISSUE THREAD

**Issue by daktei** [hirschmann/nbfc#477]
Hello everyone.I am new to Linux and struggling with getting everything to work. I've followed all the steps and enabled the service through "systemctl enable nbfc --now". But I keep getting an error when starting it or applying a config.
I get the following error;
 nbfc.exe config --apply "Asus Zenbook UX310UA"
EC initialization failed: Could not acquire EC lock
OR
nbfc.exe start -e
EC initialization failed: Could not acquire EC lock
Thank you everyone for your time.

**Comment by Gele-CZ** [comment]
Duplicite with #472
