### ISSUE TITLE
Lenovo IdeaPad 320 171KB

### ISSUE THREAD

**Issue by bastrou** [hirschmann/nbfc#479]
Yes its noisy. 

I found TEMP read I found FAN read but I cant find FAN write 
![temp3](https://user-images.githubusercontent.com/32610582/39673077-615c1996-513e-11e8-9372-780c8fbf05e5.PNG)
But I cant find the FAN write

**Comment by bastrou** [comment]
Look the photo before the fan starts
![just_a_frame_before](https://user-images.githubusercontent.com/32610582/39911402-f05997ae-5503-11e8-99e5-7b4a6beac228.jpg)
and here at 06 shows the fan that starts
![whe_the_fan_kicks](https://user-images.githubusercontent.com/32610582/39911420-02b55744-5504-11e8-97f0-6e0c1ac81721.jpg)
there is no register that shows triggering the fan
Any suggestions?

**Comment by bastrou** [comment]
I found fan READ in DSDT any idea where WRITE can be?
![dsdt](https://user-images.githubusercontent.com/32610582/40161331-1d4820c8-59b9-11e8-860a-c5a754cc0897.PNG)

**Comment by danielstuart14** [comment]
Check that out: https://github.com/hirschmann/nbfc/issues/419#issuecomment-386849671

**Comment by bastrou** [comment]
Thank you for that, but I didn't find something that it could be useful for my laptop. I saw that we have similar bios. I am trying to find what put EC in manual mode. I also found than in battery mode that is quieter registry 193 shows 01 and some numbers show up in 208-211.

**Comment by Koenees** [comment]
Did you find a solution? i  have the lenovo 330s and the fan...... geez. starts and stops. at 40c. its loud, id like to make it start at 55c.

**Comment by bastrou** [comment]
No I didn't.
The solution that I found for the present is to disable Turbo using TORNADO software. Just that.
