### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by kaliduss** [hirschmann/nbfc#480]
hi!
I have tried to build both latest and 1.5.0 versions on linux mint 18.3 xfce, without success.
any help will be appreciated as im kinda new to this and still have to learn.
im banging my head with the wall because nbfc is literally the only  program that works for my toaster(asus x202 similar) in windows, but i would prefer to use it under linux...
thanks !
https://gist.github.com/kaliduss/81fc4c5d296c7d9572a99991c0f64526

**Comment by hirschmann** [comment]
Seems like the mono version on your system is too old.
If this is the latest version in your distro's repositories, follow this guide to update it to the latest stable version mono: http://www.mono-project.com/download/stable/#download-lin-ubuntu

**Comment by kaliduss** [comment]
switched to lubuntu, update mono as instructed in the wiki you posted...and it works. i could kiss you! thanks^^
