### ISSUE TITLE
config for Lenovo Legion Y520-15IKBN ?

### ISSUE THREAD

**Issue by burkifaso** [hirschmann/nbfc#498]
hello I need config for lenovo y520, maybe someone has ? or can I try to use profile from similiar laptop from list ? which one will be good for this laptop ? thx

**Comment by Zorsselsson** [comment]
I guess the same confing might work for y720 as well. None of the other Lenovo configs worked for me.

**Comment by 5l1v3r1** [comment]
> 

same here and still looking the fans kick in under any circumtances, even i changed the fans and applied liquid metal thermal paste but the result is same.
