### ISSUE TITLE
Acer v3 471g support

### ISSUE THREAD

**Issue by 4evermaat** [hirschmann/nbfc#50]
I am trying to detect my laptop fan.  Can someone please advice?

I tried SpeedFan but it doesn't detect anything.  Notebook FanControl 1.4.2 does not have my laptop listed.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
