### ISSUE TITLE
 Current Fan Speed Negative Value

### ISSUE THREAD

**Issue by DerChiller** [hirschmann/nbfc#501]
Hello,

iam using the configuration file "HP Z-Book 15" on a HP-Z-Book G4 and its not working really correct.
The problem is that in the read-only Mode the current fan speed is a negative value. When iam enable the service (Auto) and the fans starts to run in the target value, its more louder as without fancontrol. I testet it manually and set the target speed to the minimum value 2,5%, but the fan is so loud like running with 80%.

**Comment by ben75020** [comment]
Hello

I'm using a ZBOOK G3 17" and here is my file, can you try it ? 


[HP_Zbook_17_G3_Ben.txt](https://github.com/hirschmann/nbfc/files/2128959/HP_Zbook_17_G3_Ben.txt)

**Comment by DerChiller** [comment]
Hey Ben,

this is a config-file for the HP ZBook Studio G3, i have a normal Z-Book G4 without "Studio".
As far as i know, the Studio has more as one fan.

**Comment by ben75020** [comment]
I'm using this file on a Zbook G3 non studio, that has two fans. 
If you look at the configuration file, you'll notice two fans. 
Did you tried the file sent ?

**Comment by DerChiller** [comment]
Hello Ben,

works much better, but why is e.g. on fan 2 at 70 degrees 0% fan speed?
Why is the EC Pool interval at 1000? For the other Z-Book configuration, the value is always 3000.
