### ISSUE TITLE
Asus UX310UQ option

### ISSUE THREAD

**Issue by ghost** [hirschmann/nbfc#502]
Can you add options for ASUS UX310UQ?

**Comment by antonioalt** [comment]
https://github.com/hirschmann/nbfc/issues/449
They answer me that the configuration for ux301ua could be the same... Anyway, after the bios update I didn't need it anymore. It could be a solution, download it from here: https://www.asus.com/it/Laptops/ASUS-Zenbook-UX310UQ/HelpDesk_BIOS/
