### ISSUE TITLE
Lenovo G580 missing

### ISSUE THREAD

**Issue by 3Domse3** [hirschmann/nbfc#508]
Could you add the config for Lenovo G580?

**Comment by AdibSadman** [comment]
Not to be a sore thumb or anything but the Acer Aspire VX5-591G also needs the config. I still cant figure out how Acer has not implemented fan control this laptop. @hirschmann @mattconsto

**Comment by genock241094** [comment]
Please add the configuration for the laptop Lenovo G505s processor AMD A-10 is very warm.PS thanks in advance.
