### ISSUE TITLE
Fans on Asus RoG GL502VS do not respect speed currently set

### ISSUE THREAD

**Issue by saravanabalagi** [hirschmann/nbfc#510]
The fans don't seem to respect the speeds set (manually or auto)

For example, if the CPU fan is set to 12.5% it spins as if it's at 100% and when I increase the value in the slider it does make no difference. This might make us think the slider isn't working at all, but it does stop the fans when set to 0.

Here's the config I'm using (I found this on RoG forums): 
[Asus ROG GL502VS.zip](https://github.com/hirschmann/nbfc/files/2165758/Asus.ROG.GL502VS.zip)

Also I am so forced to use nbfc because the fans in RoG GL502VS go crazy all the time even when I have nothing running. nbfc seems to set the right temperatures, but the fans don't respect the speed, they acting as if it's a boolean: on or off :/

What's wrong?

**Comment by katanakiwi** [comment]
Have you tried changing the 
      <MinSpeedValue>0</MinSpeedValue>
      <MaxSpeedValue>8</MaxSpeedValue>
values to see what effect it has?

**Comment by zekedran** [comment]
Yes, I believe it's there.
![image](https://user-images.githubusercontent.com/8567893/43035062-65a99568-8ce0-11e8-884a-645486840165.png)
![image](https://user-images.githubusercontent.com/8567893/43035064-7aa497ec-8ce0-11e8-868b-b5e3a1c9bcea.png)
![image](https://user-images.githubusercontent.com/8567893/43035066-804cd7ae-8ce0-11e8-87f3-e467c540985e.png)

**Comment by zekedran** [comment]
Yes I did, but the problem seems weird. Looks like 0 is the minimum and 8 is the maximum. However, I can't understand why fans keep spinning at full speed oftentimes, but spin just right rarely (which is how I guess the 0-8 is right)

**Comment by saravanabalagi** [comment]
After carefully inspecting for several days, I finally found that this issue was due to a manufacturing defect in the fan. After replacing the fans, they do indeed spin at the right speeds. The fan defect has been reported by many GL502 and GL702 laptop users, although not all of the users seem to experience the issue. The issue will stand closed.
