### ISSUE TITLE
HP ZBook G3 17 only able to control 1 fan

### ISSUE THREAD

**Issue by Palpi75** [hirschmann/nbfc#518]
yea so i want to know if there is someone that has a fan profile for my G3 dual fan setup G4 profile should work too i need to find someway to put the other fan go faster because my guadro m5000m and intel i7 6820hq is running 70-90 celcius and gpu thermal throttle in some games or productive work.

**Comment by DerChiller** [comment]
Hey Palpi75,

i have a HP Z-Book G4 and i use the profile from ben75020, which you will find here: https://github.com/hirschmann/nbfc/issues/501#issuecomment-399562219
With this profile, it is possible to control both fans independently.

I modified the profile a little bit. If you want, i can send it to you per mail.

**Comment by Palpi75** [comment]
@DerChiller  yes you can send your profile to my email wich is nikop.peteri@gamil.com

**Comment by DerChiller** [comment]
Realy gamil.com?

**Comment by DerChiller** [comment]
Mail is out. Pls report if its works.

**Comment by Palpi75** [comment]
@DerChiller yes it wroked fine exactly as intended thank you.
