### ISSUE TITLE
Asus B400A

### ISSUE THREAD

**Issue by Rwhorst22** [hirschmann/nbfc#52]
I have an Asus B400a ultrabook with 2 fans, one for cpu and one for gpu.  And I've been able to use the Asus Zenbook UX32LN config but was wondering if there is a place where I can request a certain model to be added to the config list.  Is there a request form or something similar I can fill out?  Thanks in advance

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
