### ISSUE TITLE
Lenovo IdeaPad 520s 14IKB

### ISSUE THREAD

**Issue by arthurprs** [hirschmann/nbfc#521]
After several days I ended up with the attached config, the register addresses are ok (the scale is a bit off but that can be fixed).

My problem is that it is constantly fighting the crazy standard controller which will dial the fan close to max as soon as the processor reaches 50C or something like that.

Any ideas how to fix it?

[Lenovo Ideapad 520s-14.xml.zip](https://github.com/hirschmann/nbfc/files/2224787/Lenovo.Ideapad.520s-14.xml.zip)

**Comment by romannebesny** [comment]
ok, looks like this path
Load and apply a config: nbfc.exe config -a "HP ProBook 6465b"
The config name is the filename without extension.

**Comment by arthurprs** [comment]
Update: DSDT editor wasn't able to parse the acpi, but RWEverything was.

I think I'm a competent software developer but I spend hours at that ACPI file and found nothing useful :cry:
