### ISSUE TITLE
hp dv5 configuration

### ISSUE THREAD

**Issue by Mellimalo** [hirschmann/nbfc#523]
Hi all, I am resolving a new configuration for hp dv5 1000 series. I know that Write register is 177 (B2 hex) like dv6 model, and read register is the same, but i have a doubt.

For dv5 model, the lower fan speed is value 14hex, then it continuous with 9, A, B, C, D, E, F, 10, 11, 12 and fastest is value 13. I don't know how the lowest value is at the end of the serie 9,A,B... instead of be in 9 or 8.

For read mode, if i write 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D in register 177, I can see the speeds of the fan in the current fan speed label of nbfc software, that correspond with 0%, 7,7%, 15,4%, 23,1%, 30,8%, 38,5%, 46,2%, 53,8%, 61,5%, 69,2%, 76,9%, 84,6%, 92,3%, 100%

I don`t know how to configure the config file for this model, i think i have to configure fan speed overrides por all values in read mode and write mode, or use the "use different min/max speed for read operations" checkbox, and create a new line in temperature threshold for each speed of the fan.

I'm trying to do that but with bad results.

Anyone who help me please??? this dv5 model is very bad with the fan control, with nbfc i notice it could be much better.

Thanks in advance!!!

**Comment by Mellimalo** [comment]
I Have just configure a file that works very well on my laptop. The temperature hols stable about 35-50 degrees. I don´t stop the fan, instead of that, i use the second lower speed who is very silent (more silent as the first speed). The laptop works very silent at lower temperatures betweeen 35-65 degrees. From 70 to 80 degrees i use all the power of the fan, but quickly the temperature down a lot.

I have modified the HP PAVILION DV6 config file, changing de temperature thresholds and min and max speeds.

With nbfc my laptop works very well, is fantastic! compared to bios, that always holds de fan very hard at lower temperatures, very noisy. If I compare the two modes, the temperature is the same, but the silent is a big difference.

[HP Pavilion dv5 1000 series INTEL CPU.zip](https://github.com/hirschmann/nbfc/files/2236155/HP.Pavilion.dv5.1000.series.INTEL.CPU.zip)

**Comment by erkexzcx** [comment]
Not quite sure of what you are asking, but if you are stating that you found everything, just don't know how to create configuration file, then you need to figure out how to create config file and create it. If you are on Linux, then there is no GUI for that. I use both platforms and I highly recommend using Windows for that. It's fairly easy to do it on Windows since there is graphical config editor.
