### ISSUE TITLE
Add HP EliteBook 2570p Configuration. (Re-use 2560p config, no modifications needed.)

### ISSUE THREAD

**Issue by DebexeL** [hirschmann/nbfc#524]
I have this specific laptop, I'm currently using HP EliteBook 2560p configuration with it. It fully works, so you can just copy 2560p config as 2570p config. No modifications to the config needed, other than the name. :D That shouldn't be hard? :)

Maybe I should have made a pull request with the 2560p config re-used.. Oh well, what's done is done.

**Comment by erkexzcx** [comment]
Please do it yourself and create pull request.
