### ISSUE TITLE
Edit Config File

### ISSUE THREAD

**Issue by kenerly** [hirschmann/nbfc#53]
Can I edit a existing config file to match what is needed for my Dell Latitude E6420?

If so where could I find the correct settings to change for the E6420?

Thanks

**Comment by TobiasKi** [comment]
I am trying to get a E6430 to work...

**Comment by TobiasKi** [comment]
you might want to have a look at this : #32

**Comment by RypeDub420** [comment]
Most of the time you can go into the Configs folder and copy-n-paste, then rename to your laptop, using another similar computer's config.

For instance: I have the ASUS ROG G75VX but NBFC doesn't come with a config, so I copied the ASUS ROG G751J or whatever's config, renamed it to my laptop, and now I'm working on getting it added.

Please update this ticket when you guys test some other E6 or even any other latitude E profiles, then fork this project, upload your config and let's get this added to the official build :D

**Comment by hirschmann** [comment]
https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
