### ISSUE TITLE
[Feature Request] Gnome Extension for NBFC

### ISSUE THREAD

**Issue by mumrau** [hirschmann/nbfc#531]
Hello,

I'm about to talk about somehting I truly am inexperienced about in terms of development of both nbfc (the bridge with mono and such under Linux systems) and gnome extensions.
Would somebody knowing the domain would be able to implement a gnome extension with an appindicator that provides the same interface as under Windows for exemple?

I think that would be a great feature but I might be unaware of the real possibilities in term of implementaion.
Anyway, thanks in advance!

Regards !

PS: I might have missed a previous issue referencing this because of the multiple terms and technologies usable for such an indicator.

**Comment by erkexzcx** [comment]
Would be great if you rewrite NBFC in C language for max performance.

**Comment by Mumrau** [comment]
Don't get me wrong please. 
Anyone can pick this issue and I believe that if anybody implemented something, he'll be ready to share it over this issue and give people the opportunity to use/enhance his work.

This level of contempt is honestly misplaced.

**Comment by hirschmann** [comment]
I'm not that familiar with Gnome and I'm not a fan of desktop environment specific solutions, so I won't create a Gnome Extension for NBFC myself.
But I'm willing to support anyone who wants to work on this task.

In fact, I'm planning to add a REST API to the nbfc service. This would make it easier to access the service from a non-dotnet frontend (e.g. a web app, a conky script, etc.)

**Comment by Mumrau** [comment]
Oh that sounds awesome!
That would indeed largely broaden the possibilites, looking forward to it, I'm sure a lot of people (including me, but not for the Gnome Extension) will make a great use of that.

Looking forward to it.

**Comment by mumrau** [comment]
I still believe this could be good. Please go away stale bot!

**Comment by erkexzcx** [comment]
**Highly disagree** that his would be good idea.

Linux has a **fragmentation problem**, and that is **exactly what you are asking for**. Aren't there any other standardized applets that work the same between different DE/WM?
