### ISSUE TITLE
Can I use Hexadecimals?

### ISSUE THREAD

**Issue by virgiltu** [hirschmann/nbfc#534]
Hello,

I am trying to create a profile for google chormebooks. However I am running into a wall. The EC code shows hexadecimals not integer. Even after I put them It did not seem to work. Am I doing something wrong. 

This is the Fan controller from the bios. 
https://chromium.googlesource.com/chromiumos/platform/ec/+/factory-1235.B/host_interface/ec_command.h

`

/* Thermal and fan */
--
  | EC_COMMAND_THERMAL_CMD = 0x20,
  | EC_COMMAND_THERMAL_CMD_MASK = 0xf0,
  | EC_COMMAND_THERMAL_GET_CURRENT_FAN_RPM = 0x21,
  | EC_COMMAND_THERMAL_GET_TARGET_FAN_RPM = 0x22,
  | EC_COMMAND_THERMAL_SET_TARGET_FAN_RPM = 0x23,
  | EC_COMMAND_THERMAL_READ_SENSOR = 0x24,
  | EC_COMMAND_THERMAL_SET_ALARM_RANGE = 0x25,
  | /* TODO: PECI? */

`

This was my configuration 

```
`<FanDisplayName>CPU fan</FanDisplayName>
<WriteRegister>47</WriteRegister>
<ReadRegister>46</ReadRegister>
<MinSpeedValue>88</MinSpeedValue>
<MaxSpeedValue>48</MaxSpeedValue>
<IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
<MinSpeedValueRead>0</MinSpeedValueRead>
<MaxSpeedValueRead>0</MaxSpeedValueRead>
<ResetRequired>true</ResetRequired>
<FanSpeedResetValue>255</FanSpeedResetValue>`
```

**Comment by erkexzcx** [comment]
Use google searches like "0x24 to decimal" and "191 to hex":

Like this - it is handy:
![image](https://user-images.githubusercontent.com/5955795/44006824-5ecb7134-9e93-11e8-9d5b-6eee5241ee03.png)
