### ISSUE TITLE
ec-probe monitor does not work on Linux (list goes downwards)

### ISSUE THREAD

**Issue by erkexzcx** [hirschmann/nbfc#535]
![screenshot_2018-08-13_00-56-16](https://user-images.githubusercontent.com/5955795/44006850-b883fde0-9e93-11e8-840a-001035adf108.png)

**Comment by hirschmann** [comment]
I need some more info to reproduce this error. Which shell are you using? Have you tried a different shell? Have you tried disabling stuff like e.g. powerline?

**Comment by erkexzcx** [comment]
1. Both BASH and ZSH produce the same issue.
2. **ec-probe dump** works without issues.
3. **ec-probe read 0xXX** works without issues.
4. **ec-probe write 0xXX** works without issues.

I have not used ec-probe on linux in the past at all. I am currently using my own maintained [nbfc-git](https://aur.archlinux.org/packages/nbfc-git/) package from AUR (for Arch Linux).

Because _everything else_ seem to work just fine, I assume this needs to be fixed in code. Let me know if there is anything you would like me to provide.

P.S. You can check [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nbfc-git) if needed.

**Comment by hirschmann** [comment]
The last time I tested it, it worked fine in bash for Manjaro and Ubuntu.
I will try to reproduce the issue with your AUR package.

**Comment by erkexzcx** [comment]
That's my bad. I've fixed this issue now: https://aur.archlinux.org/packages/nbfc-git/

**Comment by erkexzcx** [comment]
I created #537 as a result of this issue :) Thanks for your help, hirschmann!
