### ISSUE TITLE
Switching to LibreHardwareMonitor for more support ?

### ISSUE THREAD

**Issue by dan-and** [hirschmann/nbfc#536]
Hi @hirschmann,

Have you thought about switch to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor ? 
It would allow much more support on CPUs (i.e. AMD Ryzen) and is far more active in development. 

We are nearly before getting a Config for the Ryzen based Envy X360, but we are missing the cpu temperature support.

**Comment by hirschmann** [comment]
Yes, I have actually planned to switch to LibreHardwareMonitor as base for NBFC plugins for Windows.
I just haven't had enough time yet to port some of the changes I made to my fork of OHM back to LHM.
