### ISSUE TITLE
NBFC-Acer VN7-792 Config won´t apply

### ISSUE THREAD

**Issue by vickoxy** [hirschmann/nbfc#54]
Hi, thanks for your work on this Fan Control. 
I tried to apply VN7-792g V17 (i have Nvidia GTX950M) Config file, but it gives me error message : "Notebook Fan Control funktioniert nicht mehr...". So i load the the file for V15 (Aspire VN7 591 V15 Nitro) and it seems to work, but not sure if stable. I am new to windows (used for years MacOS and Linux), so would appreciate some simple how-to problem solving...
Thanks

**Comment by hirschmann** [comment]
If it works without any negative side effects, you can assume it's stable.
