### ISSUE TITLE
Looking for Asus UX490UAR i7 8550U CPU

### ISSUE THREAD

**Issue by christianbernardi** [hirschmann/nbfc#542]
applying codes for UX430UA but not sure it's working correctly

**Comment by erkexzcx** [comment]
Do you mean it doesn't work? Try my configured "Asus Zenbook UX430UQ" config and see if this works better to you. I've spent a lot of time perfecting it.

**Comment by christianbernardi** [comment]
Thank you for Your answer Erikas,

It works but I thought it was a better solution to use a customized parameters for the CPU config of the specific pc.. UA490UX.

Anyway I am using yours for the 430 and for the moment works fine.

Do you know why the cpu goes to 84 89C at pc start up??

 

Thank you.

Christian

**Comment by erkexzcx** [comment]
christianbernardi,

If it works, then just leave it as it is. Of course creating and submitting pull request would be the best thing you can do for the community.

Also there is no such thing as "_customized parameters for the CPU config of the specific pc_" - we are dealing with Embeeded Controller's registers. If my config works for you, that means your EC registers are the same as mine's, so you don't have to change anything in the config.

And I don't know why CPU gets so hot at startup. Maybe update BIOS then? And you mean laptop startup, not NBFC startup?

**Comment by christianbernardi** [comment]
Thank you for your answers.
I mean pc start up..
NBFC works perfectly.

Thanks
Christian.
⁣Sent from TypeApp ​

**Comment by adamvlasak** [comment]
I can confirm it's working for Asus Zenbook UX490UAR 👍 Thank you erkexzcx.

**Comment by christianbernardi** [comment]
I managed to install Asus "quiet fan" software.. dramatically changes ux490ua..

⁣Sent from TypeApp ​
