### ISSUE TITLE
Asus GL552jx

### ISSUE THREAD

**Issue by Schrdingr** [hirschmann/nbfc#544]
Can you support the Asus Rog GL552JX? I really want to Change my Fan Speed but haven't been able to do so.

**Comment by r4wn4k** [comment]
![nbfc](https://user-images.githubusercontent.com/42183551/44585595-b36a7480-a7ce-11e8-9b98-10ea55b038f0.jpg)

Just use the asus g501jw's config and edit the write register as shown in the pic. I have asus x550jx red and black edition which is hardware wise similiar to your asus gl552jx. Mine works perfectly so your's should work as well.

**Comment by Schrdingr** [comment]
Thank you!

**Comment by rafael1998ma** [comment]
Hi. If I choose to select "Enabled" so that my fan will be at full throttle, my CPU underclocks a lot. Any idea how to fix this?
