### ISSUE TITLE
Fan Support for Asus TUF FX504

### ISSUE THREAD

**Issue by Radu27** [hirschmann/nbfc#549]
Please add fan support for Asus TUF FX504. It would be great! Thank you!

**Comment by r4wn4k** [comment]
Doesn't it have fan overboost option in ROG gaming centre? Also,is it fx504gd or ge or gm?

**Comment by Radu27** [comment]
It's FX504GE and you can't select fans rotations, you have only three options: silent, balanced or overboost that are based on fan noise

**Comment by erkexzcx** [comment]
If there is at least one app to at least a bit manipulate fan speed, then it's easier than ever to create a working NBFC config for that. See similar models or debug at your own.

**Comment by Schwarzschild13** [comment]
why isn't the hotkey for overboost not working on my asus tuf fx504?

**Comment by XuSlone** [comment]
gl504gm  has the same problem, the fan is crazy and i can't control it by the gaming center.

**Comment by Davoodeh** [comment]
I tried creating the config with 0 knowledge of hardware of having any idea what I'm doing and I think you can guess where it led.

All I could find on the internet was this https://wiki.archlinux.org/index.php/Laptop/ASUS
"For Fan Speed Control (silent,balance,overboost) as in Windows, use ec-probe tool(see nbfc git) and write to register 0x5e the value (0x80,0x40,0xC0) correspondingly."
I cannot actually confirm if it works or not tho I don't have mine is on the shelf for now.

Unfortunately, my computer has a fan problem and it's always in high usage + makes a lot of noise so I cannot probe
That is why I need a hand in here in hope of being able to lock the fans on maximum capacity so I can actually it with a better performance like when I had it new.
