### ISSUE TITLE
Acer Aspire V3-551

### ISSUE THREAD

**Issue by GregoryGHarding** [hirschmann/nbfc#55]
anyone have any luck with a profile for this model? cant find ANYTHING! Bios doesn't watch GPU heat only CPU so i have a constant shut down while gaming.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Comment by fordcars** [comment]
For anybody experiencing the same problem, [this script](https://github.com/neduard/acer_5750G_fan_maximiser) has worked for me (to control the fan on the Acer Aspire V3-551).
