### ISSUE TITLE
Acer Aspire 5 A515 51G Support

### ISSUE THREAD

**Issue by Nashismo** [hirschmann/nbfc#550]
I need to use your fan control on my Acer Aspire 5 A515 51G Notebook but I don't see any profiles that match it.

It has an i5 8250u CPU.

Do you know any profile that could work with my Notebook? If not, could you add support for the Aspire 5 Notebooks?

Maybe a new beta of the program could help? Is been more than a year and maybe by releasing a new beta there could be coffe lake support.

If you have any solution for my problem I am all ear!

(I need your program so much, because my fan goes to sleep and then start and is driving me nuts)

Thank you, and I await your feedback!

Ignacio Hidalgo.

**Comment by cymug** [comment]
Try the Acer Aspire E5-471G profile

**Comment by ANR2ME** [comment]
I'm looking forward to this also since i have Aspire A615-51G which is basically a special edition of A515-51G since they shared the same user manual.

Based on one of the screenshot in this review it seems A515-51G is using ENE KB9022Q D https://www.ultrabookreview.com/15876-acer-aspire-5-a515-51-review/
But i couldn't find the datasheet on the internet other than ENE KB9012 which said to be similar (unconfirmed).

Even after reading KB9012 datasheet i still don't know how to use those info to be used in config file >.< LOL

**Comment by weter11** [comment]
I have A517-51G and on a motherboard installed the same KB9022Q D. I'm also tried to understand where are stored fan mode and fan speed and what values change fan from auto to manual or fullspeed. On me old Lenovo G565 I found a value that turns off the fan, but not manual mode. Lets hope someone do that with KB9022Q, I tried to change different values and I will try, but at this moment without any lucky.

**Comment by hakkikaancaliskan** [comment]
+1 for this issue

**Comment by amaterasushen** [comment]
+1 for this issue

**Comment by rohitghali** [comment]
+1 for this issue.

**Comment by oppalla** [comment]
passing through the same situation.. want to control my fan but until now its not possible.

**Comment by erdemiri** [comment]
[kb9022.pdf](https://github.com/hirschmann/nbfc/files/6137364/kb9022.pdf)

I have an Acer a515 51g model laptop. It uses the same motherboard. If anyone can manage to make a fan control file, can they send me the config file?

**Comment by siddharthbawa** [comment]
Did anyone found a work around for this?

**Comment by thinun** [comment]
I'm having the same problem ☹️

**Comment by quelsy** [comment]
Maybe if install modified bios than some hidden settings will be unlocked, including fan control.

**Comment by ghost** [comment]
> Maybe if install modified bios than some hidden settings will be unlocked, including fan control.

I have the BIOS unlocked and the fan control doesn't work. So it is not possible to change the curves.

**Comment by oppalla** [comment]
It would be very nice to have a working config for this laptop. It has a lifetime of I believe more than 3~5 years yet.

**Comment by oppalla** [comment]
It would be very nice to have a working config for this laptop. It has a lifetime of I believe more than 3~5 years yet.
@hirschmann

**Comment by siddharthbawa** [comment]
> > Maybe if install modified bios than some hidden settings will be unlocked, including fan control.
> 
> I have the BIOS unlocked and the fan control doesn't work. So it is not possible to change the curves.

Are there any useful options after unlocking the bios? i was thinking to unlock the bios to see if theirs any option to increase the tdp limit of cpu which is set for 15w.    
Also i finally bought a deepcooler notebook external fan to keep it running cool, i have overclocked the GPU and added extra ram and ssd which adds to more heat. I have the back panel half opened to improve the air flow. Works good.

**Comment by ghost** [comment]
> > > Maybe if install modified bios than some hidden settings will be unlocked, including fan control.
> > 
> > 
> > I have the BIOS unlocked and the fan control doesn't work. So it is not possible to change the curves.
> 
> Are there any useful options after unlocking the bios? i was thinking to unlock the bios to see if theirs any option to increase the tdp limit of cpu which is set for 15w.
> Also i finally bought a deepcooler notebook external fan to keep it running cool, i have overclocked the GPU and added extra ram and ssd which adds to more heat. I have the back panel half opened to improve the air flow. Works good.

I can send you my BIOS. But you will lose your Windows key once you install it. To install the modified BIOS you would need an EPROM + Clip soic8 programmer.

I haven't found any other way to change the fan curves. I increased the processor TDP but it only works for a few seconds.
