### ISSUE TITLE
Hp Pavilion 15 config request

### ISSUE THREAD

**Issue by mrhameed** [hirschmann/nbfc#551]
Hi , I really need a config file for my laptop, its getting hard to use it because of the overheating problems 
my model number is 5CD4472CDT (HP Pavilion Notebook - 15-p105ne) .

**Comment by dan-and** [comment]
Have you tried the envy x360 15-cn0000 config for a test?

**Comment by mrhameed** [comment]
Yes , I have tried that it gives negative value of current  fan speed , not working .

**Comment by dan-and** [comment]
But you can manually turn on and off the fan if you try 0 to 100 % in 10 steps?

**Comment by mrhameed** [comment]
I've just tried that now didn't do any thing to the fan 0 to 100 and backward nothing .
