### ISSUE TITLE
Lenovo Yoga 530 (i3-8130u)

### ISSUE THREAD

**Issue by Alootje** [hirschmann/nbfc#552]
I'm trying to create a config file for a Lenovo Yoga 530 i3-8130u, 8GB RM, 256GB SSD (specific version: Lenovo Yoga 530-14IKB (81EK00HVMH))
I tried to follow the guide step by step however I get stuck at the 'verify findings' step (ec-probe write 0x2F 50, https://github.com/hirschmann/nbfc/wiki/Probe-the-EC%27s-registers)

I'm unable to find the readregister and writeregister.

Attached some files which I generated along the way:

- DSDT via  RWEverything*: [Entire_DSDT.txt](https://github.com/hirschmann/nbfc/files/2350072/Entire_DSDT.txt)
- Result of ec-probe.exe monitor --clearly**: [ec-probe.exe monitor --clearly.txt](https://github.com/hirschmann/nbfc/files/2350073/ec-probe.exe.monitor.--clearly.txt)
- Result of ec-probe.exe dump: [ec-probe.exe dump.txt](https://github.com/hirschmann/nbfc/files/2350075/ec-probe.exe.dump.txt)

*: DSDT editor gave error: Could not parse ACPI tables, AE_ALREADY_EXISTS
**: Including info when Prime started/stopped and wait time (see lines 1, 130, 235)

By the way, according this image the laptop has two fans: https://tweakers.net/i/2d5DMN5MU15mNdXVfAslteEZ8o0=/x800/filters:strip_icc()/i/2002128853.jpeg?f=imagegallery

Could someone point me into the right direction?

Thanks in advance!

**Comment by erkexzcx** [comment]
Before giving up on this - read all this discussion :D https://github.com/hirschmann/nbfc/issues/526 You will find lots of information, but after all - we were unable to make it.
