### ISSUE TITLE
Help for config HP Pavillon Power 15 cb028nf

### ISSUE THREAD

**Issue by Cherryblue** [hirschmann/nbfc#553]
Hello,

First, congratulation for making this kind of software, it really is needed and is a godly gift :).

I'm an IT engineer trying to configure my girlfriend's new laptop (I believe a funny background is essential :)).

I did succeed in getting my DSDT, "temperature" is mentionned twice within lines 21597 and 21604.
So I kinda got a starting point, but I'm at a loss for making the config with that :).

[DSDT - HP Pavilion Power 15 cb028nf.txt](https://github.com/hirschmann/nbfc/files/2357855/DSDT.-.HP.Pavilion.Power.15.cb028nf.txt)

Any help on how to proceed any further? If I can create it, I hope to share it to help anyone with these new HP laptop series.

Thanks a lot guys!

**Comment by dan-and** [comment]
Could you be so kind and copy out the elements you are mentioning ? 

Also give the ec-probe.exe a try. It is straight forward to figure out which register are used for what if you observe the HP cooling in action.

**Comment by cvkogz** [comment]
Hello

I tried ec-probe.exe, but i could find only cpu fan's register. GPU, i couldnt find.

I have very few knowledge, but a IT Engineer, i think, can find this.

Waiting for good news!!

**Comment by Cherryblue** [comment]
Good to know people are waiting for this, HP default cooling rules really are shitty..

Well I'm no embarked developer, I used to develop high level software.

Anyway, I need this too, so I'll be trying hard to build one config, but I need time.
My girlfriend just broke her knee, so it's not helping :D.

@cvkogz could you share what you found on the cpu register?

**Comment by cvkogz** [comment]
Hello again

I cant remember exactly now but you can accelerate the cpu fan and you can see which register is changing. 

I could just check that register. I couldnt find gpu one.

**Comment by cvkogz** [comment]
"HP Pavilion 17-ab240nd" this config works with cpu fan. So you can grab the cpu register from that.

**Comment by Cherryblue** [comment]
Hi,

Reading this software F.A.Q, it appears it cannot control fans when the laptop is equipped with Nvidia Optimus technology, and has the dedicated graphic card running.

This, is really a pain for me :(.
My girlfriend's laptop has a 1050ti, and I also needed to control the fans when playing.

**Comment by cvkogz** [comment]
:/

**Comment by Cherryblue** [comment]
Hi,

So I didn't like to back off, I tried to at least change fan speed when optimus/nvidia not used.
The indicated profile "HP Pavilion 17-ab240nd" didn't work for me. Not sure why.

I then tried to find my informations using ec-probe as indicated on the wiki.

This is what I found so far:

**Temperature readings:
0x47
0x59**

Value example: 2C,2D   ,2E      ,2F,30      ,31      ,32   ,33      ,34   ,35      ,36   ,37
The two of them are really close in term of values, makes sense.

At 70°C Celsius, fan activates
Waiting enough time? (like 30s to 1 min)
**0x58 0 : stops fan**

Value Example: 0x58: ...,00         ,40,00                              ,40   ,00         ,40   ,00         ,40,00   ,40,00,40,00      ,40,00,40,00

But well, I cannot make it go faster. I can only stop it when it makes noise, a certain duration after.
Moreover the values don't add up... Why would it go like 40 and then 00 and then 40 again, when the cpu is still hot (45°C+).

Anyone has a guess about what i'm playing with for it to stop the fan? Thanks in advance

**Comment by evolon98** [comment]
Hi all,
I had tried the "HP Pavilion 17-ab240nd" config file and successfully raise the speed of CPU fan.
But the config was unable to raise the speed of cpu fan to 100%
I tried to modify the maximum fan speed in config editor but the result is that bios mistakenly judge the cpu temperature and thermal shutdown occurs whenever i got log into windows.
Anyone have the solution for this problem?

**Comment by Cherryblue** [comment]
I'm not one to stop at this, so I'm still trying time to time:
![image](https://user-images.githubusercontent.com/29195828/51700643-f8116a80-200f-11e9-883a-d5fcd7d496e1.png)

Any help from someone knowledgeable on notebook fan control would be really appreciated ;).

Evolon, had the same problem by playing with register, currently not anymore it seems, I stayed pushed on button power for like 1 minute none stop with the laptop shut down.

**Comment by evolon98** [comment]
> I'm not one to stop at this, so I'm still trying time to time:
> ![image](https://user-images.githubusercontent.com/29195828/51700643-f8116a80-200f-11e9-883a-d5fcd7d496e1.png)
> 
> Any help from someone knowledgeable on notebook fan control would be really appreciated ;).
> 
> Evolon, had the same problem by playing with register, currently not anymore it seems, I stayed pushed on button power for like 1 minute none stop with the laptop shut down.

![Screenshot (20)](https://user-images.githubusercontent.com/46209828/60315941-3f26d180-999b-11e9-9827-da74f1b646a7.png)

![批注 2019-06-28 114958](https://user-images.githubusercontent.com/46209828/60315959-4ea61a80-999b-11e9-8fc2-d814227e17e6.jpg)

CherryBlue, I'm now using the config file"HP Pavilion 17-ab240nd", but edited to the values like the picture above, and it managed to trick the system that the cpu is 95 degrees and turn the fan to higher speed.

But the thing is it seems like it can only boost up one of the fan.

**Comment by pwnerandy** [comment]
@evolon98 do you have any issues with that config? Other than not being able to boost the GPU fan. (I don't think you are able to at all)

I have an OMEN by HP Laptop 17-an0xx and the HP pavilion 17 config works for me and controls the fan perfectly. but I am getting thermal shutdown hibernations (in event viewer it reads as Kernel Power event 88) randomly even when the fan/NBFC is running at a lower speed and temps are in the 40s-50s.

I cannot for the life of me figure out how to stop my computer from hibernating with this Kernel Power event 88 shutdown.

**Comment by evolon98** [comment]
@pwnerandy For Pavilion 15-cb the heatsink for cpu and gpu is linked and i found out that i can control all of the fan.
The issue you getting is the same here for me, but it usually occur when temp around 60~70

**Comment by pwnerandy** [comment]
So you were able to figure out how to increase the GPU fan speed? That's interesting.

I hope there is some sort of workaround or fix that can be found to stop the thermal shutdown error. 

are you getting the same event # in your system log? kernel power event 88?

**Comment by evolon98** [comment]
What I mean is that for this model, the two fan is not separate as cpu and gpu fan, so when the temperature gets hot enough both fans will increase their speed.

Yes the same event.

**Comment by Cherryblue** [comment]
> 
> 
> What I mean is that for this model, the two fan is not separate as cpu and gpu fan, so when the temperature gets hot enough both fans will increase their speed.
> 
> Yes the same event.

Hi Evolon,

I'm back at it since my girlfriend continues to have random crash because of thermal maxed.
I really need to get this fan working; I read what you did, but it didn't work for me.

- First of all can you confirm what is your notebook model? Yours may be different from one.
- By modifying HP Pavilion 17-ab240nd and changing the values as you showed on your screenshots, I do not get the fan working:

![image](https://user-images.githubusercontent.com/29195828/63953798-4db86480-ca82-11e9-8220-e5e65d087532.png)
![image](https://user-images.githubusercontent.com/29195828/63953853-66c11580-ca82-11e9-9913-0b8e75fb1ef4.png)

Do you see any error on my side which might explain why it doesn't work for me?

Thanks in advance for your help mate.

**Comment by Cherryblue** [comment]
OK guys, I decided to try every HP existing profile in this software, and it worked.
I'm stupid as to not having tried that earlier.

The one working for me was HP Pavillon 17. (not the one with a ID after 17).
**I'm currently modifying it for correct fan max RPM and temperature curve, then I'll look to submit it the correct way :).**

Thanks a lot for everything Evolon.

**Comment by evolon98** [comment]
Guys it's me again.
After the last post, i discovered that calibrating the battery solved the overheat problem and improved lot of battery life. (Instructions here:https://support.hp.com/ph-en/document/c04700771, under the "calibrating the battery manually")
Now, the cpu temperature stays under 45 degree on battery and 70 for plugged in and the keyboard area always stay cool (even NBFC is turned off).
Also, I followed the steps here for more battery life:http://forum.notebookreview.com/threads/guide-improving-battery-life-on-windows-enabling-deeper-c-states.815602/

Hope this is helping.

**Comment by quevon24** [comment]
> OK guys, I decided to try every HP existing profile in this software, and it worked. I'm stupid as to not having tried that earlier.
> 
> The one working for me was HP Pavillon 17. (not the one with a ID after 17). **I'm currently modifying it for correct fan max RPM and temperature curve, then I'll look to submit it the correct way :).**
> 
> Thanks a lot for everything Evolon.

> OK guys, I decided to try every HP existing profile in this software, and it worked. I'm stupid as to not having tried that earlier.
> 
> The one working for me was HP Pavillon 17. (not the one with a ID after 17). **I'm currently modifying it for correct fan max RPM and temperature curve, then I'll look to submit it the correct way :).**
> 
> Thanks a lot for everything Evolon.

Do you still remember what the full name of the profile is? or do you still have the profile? or what are the registers to control CPU fans? i have a similar model but with i5 7300hq and i want to control the fan speed
