### ISSUE TITLE
ec-probe monitor not working in linux

### ISSUE THREAD

**Issue by Mitsukaritas** [hirschmann/nbfc#554]
I'm trying to make a config file for Lenovo Legion Y520, and whenever I run `ec-probe monitor` it returns
`Could not load EC plugin. Try to run ec-probe with elevated privileges.`
The problem is, I tried it with sudo, as well as `sudo su -` on gnome terminal, and as root in tty.
I'm currently running Arch Linux 4.18

**Comment by erkexzcx** [comment]
read this: https://wiki.archlinux.org/index.php/Fan_speed_control#NBFC

**Comment by Mitsukaritas** [comment]
Already did to install it, and it says nothing about my error, but I did reinstall arch for dual booting with windows, maybe this time it wants to work... I still find it weird that even by loging in with root ec-probe returns that error message

**Comment by erkexzcx** [comment]
Mine is working fine on the latest `linux` kernel available from stable repositories. All I did was delete this file:

```
# mv /opt/nbfc/Plugins/StagWare.Plugins.ECSysLinux.dll /opt/nbfc/Plugins/StagWare.Plugins.ECSysLinux.dll.old
```
And restart NBFC services.

Try to restart from Linux to Linux without dual boots - maybe Windows does something?

Also - install `nbfc-git` rather than `nbfc`. I no longer update `nbfc` just because...I don't remember - I think latest NBFC release is simply not working on Linux (#558)

**Comment by erkexzcx** [comment]
The command is `sudo su` then `ec-probe monitor`?

Also, you might be interested to try this out: http://linuxbsdos.com/2016/06/05/how-to-disable-fast-startup-in-windows-10/ (might be related I guess).

**Comment by erkexzcx** [comment]
Umm then what nbfc version did you install? If you are using `nbfc` rather than `nbfc-git` - install `nbfc-git` and try again. Let me know how it goes.

**Comment by Mitsukaritas** [comment]
I used nbfc-git, can't try right now as I'm away frome my home with no wifi, and I've already abused too much my cellphone's mobile data.

As soon as I get usable wifi I'll try again and update with my results

**Comment by Mitsukaritas** [comment]
So, after reinstalling arch linux and then NBFC it now works... so yeah... thanks :p

**Comment by 5l1v3r1** [comment]
> So, after reinstalling arch linux and then NBFC it now works... so yeah... thanks :p

can you please share the config file for y520?
