### ISSUE TITLE
Please help create config for Acer ES1-533

### ISSUE THREAD

**Issue by danil1petrov** [hirschmann/nbfc#555]
I have Acer ES1-533 with Debian, one fan and "ene KB9012" EC. No configs for my laptop, but Acer Aspire V3-571G config turns on my fan very loud. This config change 0xBD register. Any value except 0x13 for this register turns my fan very loud on fixed speed.

I turn on cpu stress test and run monitor. I turn off stress test and after 00 fan spin with low speed.

![image](https://user-images.githubusercontent.com/41929985/45268306-ac0bc200-b482-11e8-865c-11119444ec2b.png)
Сhanging all values from the ec-probe monitor does not do a result.

Only changing 0xBD register from 0x13 do a high fan speed.
I run the monitor on low fan speed, and after change 0xBD register to 0x14 value fan fix on high speed. After 0x13 fan spin again on low speed.
![image](https://user-images.githubusercontent.com/41929985/45268349-90ed8200-b483-11e8-9df4-4f79c8ca5bc2.png)
I do not see the new registers. Where the fan speed register?

Ok. I tried reading the EC datasheet, but did not understand anything.
![1](https://user-images.githubusercontent.com/41929985/45268639-3b67a400-b488-11e8-96f4-8ce6c763edc0.png)
![2](https://user-images.githubusercontent.com/41929985/45268640-3b67a400-b488-11e8-875a-3fdde95fad23.png)
![3](https://user-images.githubusercontent.com/41929985/45268641-3b67a400-b488-11e8-83f1-8c97f720da2f.png)
![4](https://user-images.githubusercontent.com/41929985/45268642-3c003a80-b488-11e8-8bc1-bac9182d3847.png)
![5](https://user-images.githubusercontent.com/41929985/45268643-3c003a80-b488-11e8-88a9-465239917db9.png)
![6](https://user-images.githubusercontent.com/41929985/45268644-3c003a80-b488-11e8-86ae-35be8de4f0ea.png)
![7](https://user-images.githubusercontent.com/41929985/45268645-3c003a80-b488-11e8-92cf-fb7eb293e4f1.png)
Ok. I tried analyze DSDT, but did not understand anything. again...

[dsdt.txt](https://github.com/hirschmann/nbfc/files/2364618/dsdt.txt)

Please help...

**Comment by danil1petrov** [comment]
Sorry my english...

**Comment by danil1petrov** [comment]
Now i can turn off wifi and blink battery state led

**Comment by danil1petrov** [comment]
but I can not control the fan

**Comment by erkexzcx** [comment]
Well, can't help you even if I want to. Without owning the hardware it's impossible. But I see you've made a lot of progress and also you managed to find datasheet, so just don't give up and continue investigating. Also check similar models - maybe you will find answer there? :)

**Comment by dslul** [comment]
@danil1petrov can you provide a dump of the registers? (_ec-probe dump_). The Acer Aspire V3-571G, as your laptop and mine (Samsung NP350V5C) have the same KB9012 EC. I also tried the V3-571G, but nothing changed (only the 0xBD register from 0x53 to 0x5B). With this, my fan seems to run slower, and at high temperatures it does not spin to maximum speed (as in the normal configuration). I only manage to get it full speed with [this script](https://github.com/neduard/acer_5750G_fan_maximiser).
