### ISSUE TITLE
Releasing a new Beta Version ?

### ISSUE THREAD

**Issue by dan-and** [hirschmann/nbfc#558]
Hey @hirschmann ,

because of the new CPU detection, it would be awesome to have a new prebuild beta release of nbfc. As you may have seen, I have build a version on my fork, but I rather would like to see a beta release on your side. 

Especially for the AMD Ryzen users, the effect of 1.5.3-Beta is just starting and stopping all the time. With the rebuild, they can just create their profile like the usual intel cpu owners. 

Thanks,

Daniel

**Comment by hirschmann** [comment]
The new beta is out now :)
https://github.com/hirschmann/nbfc/releases/tag/1.6-beta1

Sorry it took so long, but I didn't have much spare time lately and I wanted to introduce a better branching and versioning model with this release which took a while.

**Comment by dan-and** [comment]
Awesome! I will let my known AMD notebook owners know that they should give your new beta a try
