### ISSUE TITLE
Asus G703VI request

### ISSUE THREAD

**Issue by Eldiel** [hirschmann/nbfc#561]
Hello @hirschmann,

If there is any tutorial, I would like to try to do myself as well.

If something goes wrong with fan profiles, what is the fix?

 I hope you receive an answer from you.

**Comment by user00101010** [comment]
The answer to all of your questions are contained in the [FAQ](https://github.com/hirschmann/nbfc/wiki/FAQ#does-nbfc-support-my-notebook). More particularly - the first, second and third questions.

**Comment by Eldiel** [comment]
I tried to create my own profile but I wasnt successful unfortunately. I hope that there will be a more experienced G703VI user which takes care of it. I only need less RPM during idle or web surfing. During load the fan profile is ok.

**Comment by Eldiel** [comment]
Thanks. I tried existing profiles and all profiles are erased from the selection list. There is no similar Asus laptop profile with gtx1080 so it seems I need to try harder or wait someone.

**Comment by user00101010** [comment]
That's what I meant, the laptop doesn't need to be GTX 1080. You can look for an older year laptop, or just try with random high-end laptop profiles.

For example I own the GX501JW, and as per my recommendation my father bought the UX301. I've opened both laptops and they are almost the same, although the build quality of the UX301 was a bit better. The fans however, and the internal design and structure was 1:1

**Comment by Eldiel** [comment]
I download the newest version and I will try again.  I hope that I can manage it. I already opened a ticket to Asus so that they add silent fan profile but unlikely they will do it

**Comment by user00101010** [comment]
I wouldn't hold my breath either. There is also [this thread on Reddit](https://www.reddit.com/r/ASUS/comments/98wlf3/asusrequest_manual_fan_control_in_rog_gaming/) requesting this feature, however I would prefer they just implement simple fan controls in the BIOS as opposed to bloatware apps I wouldn't want installed. 

I have in fact actually unlocked my BIOS and there are options for the Thermals, however the OS doesn't respect them, since I guess they are not implemented in that way. Hopefully I will get NBFC working which seems like a good solution.

**Comment by user00101010** [comment]
To keep you updated, I managed to get NBFC running both under Windows and Linux. However currently only my CPU fan is being detected. I will look for various ways to solve this over the coming weeks.

**Comment by Eldiel** [comment]
I actually only want to make a chance at CPU fan. Did you do everything from scratch for the profile?

**Comment by Eldiel** [comment]
> 
> 
> To keep you updated, I managed to get NBFC running both under Windows and Linux. It's working great, however currently only my CPU fan is being detected. I will look for various ways to solve this over the coming weeks.

I actually only want to make a change at CPU fan. Did you do everything from scratch for a new profile?
