### ISSUE TITLE
No configs in drop down list

### ISSUE THREAD

**Issue by laimtoh5** [hirschmann/nbfc#566]
I'm new to your software, and have a HP ENVY x360 Convertible 13-ag0xxx (W10 Home 64-bit) which I downloaded the correct xml file, to the C:\Program Files (x86)\NoteBook FanControl\Configs folder.

When I launch NoteBookFanControl.exe, no config is shown, then I try to choose one from the ... and Select Config, but none are shown in that list, despite the aforementioned Config folder being populated with many xml files.

Please advise how I can fix this issue.

**Comment by enzy** [comment]
Look into the Services view and start the NoteBook FanControl Service. It fixed the problem for me.

**Comment by laimtoh5** [comment]
Unfortunately it stops just after starting. I have pasted the event log entry below from event ID 1001:

Fault bucket 129312067140, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: NbfcService.exe
P2: 1.3.0.0
P3: 585520de
P4: StagWare.Hardware
P5: 1.0.0.0
P6: 585520e1
P7: c
P8: 60
P9: System.PlatformNotSupported
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER616.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER626.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER628.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER658.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_NbfcService.exe_a22b71b637da80981ae56770f7b764d4857a6e3d_4a3fa610_34f70a0c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5ce5a60f-49cb-4104-9c67-a74a25c1bf4e
Report Status: 268435456
Hashed bucket: 774d09d9d0482d9d4e48eeec6f5c422c
Cab Guid: 0

Can anyone help, please?

**Comment by hirschmann** [comment]
Please upload a service log, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by laimtoh5** [comment]
Thanks; I ran it through powershell ISE so I hope that's right. Here are the results:

   Index Time          EntryType   Source                 InstanceID Message                                                                                             
   ----- ----          ---------   ------                 ---------- -------                                                                                             
   10504 Oct 05 19:47  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10502 Oct 05 19:47  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10497 Oct 05 19:43  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10495 Oct 05 19:43  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10478 Oct 05 19:41  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10476 Oct 05 19:41  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10473 Oct 05 19:41  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10471 Oct 05 19:41  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10468 Oct 05 19:40  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10466 Oct 05 19:40  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10463 Oct 05 19:40  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10461 Oct 05 19:40  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10406 Oct 05 19:30  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10403 Oct 05 19:30  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10269 Oct 05 07:45  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10263 Oct 05 07:45  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
   10235 Oct 05 07:43  Information NoteBookFanContro...            0 Service started successfully.                                                                       
   10232 Oct 05 07:43  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
    9502 Oct 02 07:35  Information NoteBookFanContro...            0 Service started successfully.                                                                       
    9499 Oct 02 07:35  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....                                                     
    9280 Oct 01 18:52  Information NoteBookFanContro...            0 Service started successfully.                                                                       
    9277 Oct 01 18:52  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....

**Comment by hirschmann** [comment]
Your notebook's CPU is not supported in the version of NBFC you're using. Try the latest beta instead.

**Comment by laimtoh5** [comment]
Hi, 1.6 beta works fine so far, thank you very much for that and all your advice. I'll report back soon to update you in how it works, but so far I'm a very happy customer - no more ridiculous fan speeds whilst I'm hardly touching its very capable CPU.
