### ISSUE TITLE
Successfully building on Linux doesn't create a Linux/bin folder. Workarounds in related issues and versions 1.4.2, 1.4.4, 1.5.0, 1.5.3-beta and 1.6.1-beta1 all seem to fail in various ways.

### ISSUE THREAD

**Issue by user00101010** [hirschmann/nbfc#568]
**Describe the bug**
Following the instructions in the [First Steps](https://github.com/hirschmann/nbfc/wiki/First-steps) and [How to build](https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC) pages, the build terminates successfully (with 3 warnings), but there is no /Linux/bin folder generated.

At first the build was throwing many error messages, so I added the official mono-repository, updated from there and installed mono-complete. Upon doing that, the build completed successfully, but as mentioned the Linux/bin folder is missing so I cannot complete the install.

Please tell me if you want me to attach the full build output from terminal.

**To Reproduce**
1. cd /tmp
2. git clone https://github.com/hirschmann/nbfc.git
3. git checkout 1.5.0
4. cd nbfc
5. su
6. cert-sync /etc/pki/tls/certs/ca-bundle.crt
7. exit
8. ./build.sh
`Build succeeded.`
`Warnings:`
`/tmp/nbfc/Windows/Setup/NbfcSetup/NbfcSetup.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/tmp/nbfc/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/tmp/nbfc/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.`
`3 Warning(s)
0 Error(s)
Time Elapsed 00:00:06.6368530
/tmp/nbfc`
9. ls Linux
`continue-nbfcservice.sh  nbfc-sleep.service    start-nbfcservice.sh
nbfc.service             pause-nbfcservice.sh  stop-nbfcservice.sh`

I tried this twice with removing the folder completely, but both times the result was the same. I also try running ./build.sh as su but that produced the same result.

**Expected behavior**
Upon step 9. ls Linux the output should also contain a /bin folder so I can copy the files from there and install the application as instructed in the [First steps](https://github.com/hirschmann/nbfc/wiki/First-steps) page

**System information**
 - operating system: Fedora 27, updated before build
 - NBFC version: 1.5.0
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview)): It seems the log files are only generated upon successful install and subsequent run of the program. Please reply if you want me to provide the full terminal output log of the build.

**Additional context**
N/A

**Comment by user00101010** [comment]
Found a couple of related issues:

#491 And more particular [your comment ](https://github.com/hirschmann/nbfc/issues/491#issuecomment-411070018)informing that build for 1.5.0 is broken. Tried building 1.5.3 beta-1 as suggested but build fails with the below output:

> Build FAILED.

`Warnings:`

`/tmp/nbfc/Windows/Setup/NbfcSetup/NbfcSetup.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/tmp/nbfc/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/tmp/nbfc/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.`

`/tmp/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/tmp/nbfc/Core/StagWare.FanControl/StagWare.FanControl.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->`

	`/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL' not resolved`

`Errors:`

`/tmp/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/tmp/nbfc/Core/StagWare.FanControl/StagWare.FanControl.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->`

	`FanControl.cs(1,7): error CS0246: The type or namespace name 'NLog' could not be found (are you missing a using directive or an assembly reference?)
	Plugins/FanControlPluginLoader.cs(1,7): error CS0246: The type or namespace name 'NLog' could not be found (are you missing a using directive or an assembly reference?)
	Plugins/FanControlPluginLoader.cs(12,33): error CS0246: The type or namespace name 'Logger' could not be found (are you missing a using directive or an assembly reference?)
	FanControl.cs(39,33): error CS0246: The type or namespace name 'Logger' could not be found (are you missing a using directive or an assembly reference?)`

	 `4 Warning(s)
	 4 Error(s)`

Build for 1.6-beta1 fails with the following output:

`Importing into BTLS system store:
I already trust 132, your new list has 132
Import process completed.
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
Error parsing solution file at /tmp/nbfc/NoteBookFanControl.sln: Invalid Image
./build.sh: line 39: msbuild: command not found
/tmp/nbfc`

I also found #423 suggesting that doing the git clone in the /opt folder works, however it produced the same results for me.

#506 Suggests the issue was resolved by updating mono from the official repo, however I have already done that, otherwise the build doesn't complete at all on Fedora 27.

[The implemented workaround](https://github.com/hirschmann/nbfc/commit/92325ba70bf5c0b8b867054862da9a32f532d375) in the reported #158 does not seem to work for me.

I tried the workaround suggested in #56 however, upon running mono nuget.exe resotre I get the following output:

`The 'xunit 2.3.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'xunit.abstractions 2.0.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'xunit.analyzers 0.8.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'xunit.assert 2.3.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'xunit.core 2.3.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'xunit.extensibility.core 2.3.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'xunit.extensibility.execution 2.3.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'xunit.runner.visualstudio 2.3.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.`

The comments in #157 seem to be most helpful. Version 1.4.2 successfully builds but it's missing the files described in the First steps wiki. Version 1.4.4-beta builds successfully and contains all the files.

However I hit a wall once copying the necessary files. "nbfc config --apply "Asus ROG G501JW" outputs:

`bash: nbfc: command not found...`

nbfc.exe status outputs:

`bash: /opt/nbfc/nbfc.exe: cannot execute binary file: Exec format error`

**Comment by user00101010** [comment]
Thank you very much for the prompt response! Unfortunately adding mono before the line doesn't change the build behaviour for 1.6-beta1 for me. I get the following output:

`MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
Error parsing solution file at /tmp/nbfc/NoteBookFanControl.sln: Invalid Image
Cannot open assembly 'msbuild': No such file or directory.
/tmp/nbfc`

If I try to paste it manually I get:
$ mono msbuild /t:Clean,Build /p:Configuration=ReleaseLinux NoteBookFanControl.sln
`Cannot open assembly 'msbuild': No such file or directory.`

Running mono /opt/nbfc/nbfc.exe status for version 1.4.4-beta produces the following output:
`bash: /opt/nbfc/nbfc.exe: cannot execute binary file: Exec format error`

**Comment by hirschmann** [comment]
Looks like msbuild is either not installed on your system, or not in the PATH.

`Object reference not set to an instance of an object` probably means no config is selected.

**Comment by user00101010** [comment]
> Looks like msbuild is either not installed on your system, or not in the PATH.
> 
> `Object reference not set to an instance of an object` probably means no config is selected.

You were completely right. Running "dnf install msbuild" resolved the issue. I tested with and without mono-addins-msbuild and the latter is not needed.

When msbuild is installed, 1.6-beta builds successfully without any extra arguments. However when running nbfc itself, I have to preface the commands with "mono" or I get `bash: /opt/nbfc/nbfc.exe: cannot execute binary file: Exec format error`.

Notebook Fancontrol runs and operates successfully now! I'm closing this issue as resolved. I do however have a new issue now #578 and it would be amazing if you can help me again in the right direction (opened separately since it is a separate issue). Full details are inside and I'm very willing to put time into troubleshooting and researching this.

**I want to take the time to actually thank you for your development of this irreplaceable tool and support. I'm always amazed at the open source community because of people like you. Thank you for your work and time and I wish you all the best!**

The reason why I'm actually struggling so hard to get this working is because I have a hardware issue with my fans. The bearings are all messed up now, and my fan is making this extremely annoying and very loud rattling when running on low RPMs (the issue seems to fixed running on full speed). It's probably hitting a wall of the enclosure of the fan itself and producing the most annoying sound.

The fans are hard to find and where I was able to find them, they are more expensive than I can afford or it is economically worth to give in general. 

This renders my idle computer being louder at idle when it should be completely silent then when it is at full load. Not to mention that for some reason the BIOS is tuned so the fans are never off, just spin at a low RPM when there is no load. So I want to disable the fans completely when idle.

**Comment by weedy** [comment]
I want to add a FYI for anyone coming across this.
I have mono 5.18 installed and the updated nuget wasn't working. But an older version does.

```
$ wget https://dist.nuget.org/win-x86-commandline/v3.5.0/nuget.exe
$ MONO_TLS_PROVIDER=legacy mono nuget.exe restore
MSBuild auto-detection: using msbuild version '4.0' from '/usr/lib64/mono/4.5'.
Feeds used:
  /home/weedy/.local/share/NuGet/Cache
  https://api.nuget.org/v3/index.json

Restoring NuGet package xunit.2.2.0.
Restoring NuGet package xunit.assert.2.2.0.
Restoring NuGet package xunit.core.2.2.0.
Restoring NuGet package xunit.abstractions.2.0.1.
Restoring NuGet package xunit.runner.visualstudio.2.2.0.
Restoring NuGet package xunit.extensibility.core.2.2.0.
Restoring NuGet package xunit.extensibility.execution.2.2.0.
Adding package 'xunit.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Adding package 'xunit.assert.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Added package 'xunit.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Added package 'xunit.assert.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Adding package 'xunit.abstractions.2.0.1' to folder '/home/weedy/projects/nbfc/packages'
Added package 'xunit.abstractions.2.0.1' to folder '/home/weedy/projects/nbfc/packages'
Adding package 'xunit.extensibility.core.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Added package 'xunit.extensibility.core.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Adding package 'xunit.core.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Added package 'xunit.core.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Adding package 'xunit.extensibility.execution.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Added package 'xunit.extensibility.execution.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Adding package 'xunit.runner.visualstudio.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
Added package 'xunit.runner.visualstudio.2.2.0' to folder '/home/weedy/projects/nbfc/packages'
```

Just comment out the "nuget.exe update" from the build.sh script.
