### ISSUE TITLE
Lenovo IdeaPAd 330 15arr (Ryzen 5 2500u)

### ISSUE THREAD

**Issue by victoryus** [hirschmann/nbfc#572]
Dear Hirschmann!

Please support my notebook too. The Lenovo IdeaPad 510s profile is similar, and read temp+fan speed good, but can't set profile. I want to turn off fan under 55 celsius if possible.

**Comment by Koenees** [comment]
Yes me too, the lenovo ideapad 330s / lenovo81f5. loving the device but the fan....... turning on off. at 40c. Im prepared to donate some money if you could make the config work.

**Comment by drsupab** [comment]
Please... PLEASE... me too.. support 330s with ryzen 5 2500u...

**Comment by victoryus** [comment]
I have opened DSDT with Read&write utility, but i can't find LPCB or similar thing. 
If i search for EmbeddedControl, I founded an entry: 
OperationRegion(ERAM, EmbeddedControl, Zero, 0xFF)
					Field(ERAM, ByteAcc, Lock, Preserve)
					{
						VCMD, 8,
						Offset(0x60),	//Offset(96),
						SMPR, 8,
					}
This is, what i need?

**Comment by victoryus** [comment]
Now i can't play with GTA5, becouse at 60 celsius the fan switch to maximum speed, and the cpu to the minimum, lagging... till i close the game, The cpu temp with 100% fan decrease to 50-45, but  until it reaches 38 run on full throttle. After 38 degree switch to minimum speed...  Fucking fan rule. I can't restore the original condition.

**Comment by rpgod** [comment]
[LENOVO 81D2.zip](https://github.com/hirschmann/nbfc/files/3061981/LENOVO.81D2.zip)


fan control will work show stuck at 86.5% which is 100%
i  am not able to change other setting may be dev can help

**Comment by rpgod** [comment]
> Dear Hirschmann!
> 
> Please support my notebook too. The Lenovo IdeaPad 510s profile is similar, and read temp+fan speed good, but can't set profile. I want to turn off fan under 55 celsius if possible.

change write registry to 189
