### ISSUE TITLE
NOTICE: it won't work for OMEN by HP 15 (2018, 15-dc0xxx)

### ISSUE THREAD

**Issue by YamiOdymel** [hirschmann/nbfc#576]
Just saying for those people who's trying to solve the overheating issue on the OMEN by HP 15, it's **IMPOSSIBLE** to control the fan speed with NoteBook FanControl. 

Here's the DSDT file of the HP OMEN by HP Laptop 15-dc0xxx: https://gist.github.com/YamiOdymel/6d9283121379a4762d3fcee5ff4847d0

As you can see in the file, the `178` offset seems like the RPM of the fan.

```diff
Offset(0xAD),	//Offset(173),
SADP, 8,
Offset(0xB2),	//Offset(178),
RPM1, 8,
RPM2, 8,
Offset(0xBA),	//Offset(186),
CLOW, 8,
CMAX, 8,
```

And if you browse further more, there's a code for it. The logic of the code block looks [like the example from the wiki](https://github.com/hirschmann/nbfc/wiki/Analyze-your-notebook%27s-DSDT).

```
Name(REGN, "Processor Thermal Zone")
Name(FMAX, 0x1388)
Name(FMIN, Zero)
Method(FRSP, 0, NotSerialized)
{
    Store(Zero, Local2)
    If(LEqual(\_SB.PCI0.LPCB.EC0.ECOK, One))
    {
        Store(\_SB.PCI0.LPCB.EC0.RPM1, Local0)
        Store(\_SB.PCI0.LPCB.EC0.RPM2, Local1)
        ShiftLeft(Local1, 0x08, Local1)
        Or(Local0, Local1, Local0)
        If(LNotEqual(Local0, Zero))
        {
            Divide(0x00075300, Local0, Local0, Local2)
        }
    }
    Return(Local2)
}
```

But sadly, if you trying to set the `178` or `179` as the Read/WriteRegister, it just **WON'T** work. A HP user has talked about something like this on the [notebookreview forum](http://forum.notebookreview.com/threads/pavilion-g6-1339sg-dsdt-prob.666112/).

> it seems the Thermalzone only reports temperatures and the fancontroll is managed by the motherboard itself. editing the reported temperatures wont´t work as i wished it would do: raising up fanspeed.
Seems modifying the hardware is the only solution.

So ... yeah, maybe the fan control is **IMPOSSIBLE** for the OMEN by HP 15. I even got a CMOS checksum error just for test these stuffs.

**Comment by HostClubKea** [comment]
Found config which works perfectly for hp omen 15 2018 - HP Pavilion 17-ab240nd
