### ISSUE TITLE
Only one fan is detected

### ISSUE THREAD

**Issue by user00101010** [hirschmann/nbfc#578]
**Describe the bug**
Notebook FanControl is running successfully on my ROG G501JW laptop with the according G501JW config. However only one fan is discovered labelled "CPU fan". It appears the GPU fan is not being discovered at all.

**To Reproduce**
Upon running `mono /opt/nbfc/nbfc.exe set -f 1 -s 0` I get `Could not set fan speed: Specified argument was out of the range of valid values. Parameter name: fanIndex`

**Expected behavior**
Upon running `mono /opt/nbfc/nbfc.exe set -f 1 -s 0` the fan speed of the GPU fan is set to 0.

**System information**
 - Fedora 27
 - 1.6-beta. This was tested both on Windows and Linux and both experience the same behaviour.
- I have not attached logs, but please tell me if those are necessary and I will attach them

**Additional context**
I read the FAQ and the part about Optimus, however this isn't exactly the issue I'm experiencing. The fan doesn't get detected at all and thus I'm unable to control it. This is striking me as extremely odd, as the fan is the exact same model as the CPU fan, with accommodations made just for the physical outer shell size in order to fit into the laptop chassis (can post pictures if requested).

I tried running sensors-detect, selected yes to all and overwrote the file, however this didn't help. As mentioned above, the fan doesn't get detected in Windows either.

Enabling "Coolbits 12" doesn't give me control over the fan in the nVidia Control Panel either (as per specification it should).

I also tried running in Wayland where Optimus and nVidia cards don't work yet. The result was almost the same. Only difference is that when I ran sensors-detect, I lost the temperature reading of my nVidia card. It started displaying as NaN which is an indicator that the nVidia card indeed wasn't working in Wayland at all.

**BIOS**
I'm also willing to do experimenting with the BIOS if necessary. I did previously unlock all of the options of my BIOS with AMI Tools and some overclocking guides. It does have some settings for fan control, however they seem to be completely ignored by the OS (I tried to use them previously to discovering NBFC)

**Final thoughts**
Please point me in the right direction. I'm willing to invest time in troubleshooting this. I'm not sure that the issue is related to Optimus at all. I'm also willing to do some experimenting. Currently I'm running on Fedora, however I could install Ubuntu which as far as I remember had an option for disabling Optimus and running only from the integrated card. I can also research how to do this on Fedora.

**Comment by hirschmann** [comment]
NBFC doesn't try to detect fans. It just reads and applies the selected config.
In your case the ROG  G501JW config defines only one fan, so NBFC displays only one fan.

Give one of the other ROG configs with 2 fans a try, e.g. ROG G751JL
