### ISSUE TITLE
Please add support for these laptop models...

### ISSUE THREAD

**Issue by sweckform2** [hirschmann/nbfc#58]
I am a big fan of NBFC but other thank my ProBook 4530s, not a lot of popular laptop models are supported. Please add "template **profile** support" for the following models:
1. Sony VAIO SVF1541CDB (Sony Fit 15E)
2. Lenovo ThinkPad T420*
3. HP ENVY 17 (all models from 2014 onwards)*

_*these are very popular laptop models, please add support for these in the next NBFC release, as a lot of people have these_

Is there a functionality, whereby future versions of **NBFC can automatically scan the laptop system and adjust itself to the correct settings**? Such a feature would negate the need for templates and improve end user experience. Thanks.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
