### ISSUE TITLE
1.6 beta 2 NbfcService.exe not starting. Installation hangs

### ISSUE THREAD

**Issue by nutopaa5** [hirschmann/nbfc#587]
**Describe the bug**
Installing 1.6 beta 2 fails. NbfcService.exe not starting. Even starting from services.msc it fails.

**To Reproduce**
Tried installing 1.6 beta 2 after 1.6 beta 1 is installed.

**Expected behavior**
Previously I've not had any problems with the software. I don't want to do clear unistall, if I lose my configs and preferences. I repaired my setup from add/unistall windows programs in the control panel to revert back to prev version 1.6 beta 1.

**System information**
 - Win 7 64bit
 - 1.6 beta 1 is installed at the moment and during installation.
 - LOG file
[NoteBook_FanControl_20181105112906.log](https://github.com/hirschmann/nbfc/files/2547737/NoteBook_FanControl_20181105112906.log)

**Additional context**
Previous 1.6 beta 1 and 1.5.3 beta have been working and installed without problems.

**Comment by pressRtowin** [comment]
Rip. Feb 2019 and still no word on this. Several other issues here are dupes of this as well

**Comment by nutopaa5** [comment]
Problem fixed by installing latest version 1.6.3.
