### ISSUE TITLE
Does it work for rog zephyrus?

### ISSUE THREAD

**Issue by oceanone** [hirschmann/nbfc#592]
I have spent a lot of time and tried many different methods to adjust the fan speed on my rog gm501
It's not showing and current fan speed. Target fan speed seems doesn't affect the actual fan speed.
I have tried out every methods I could find from google. Appreciate if anyone can give any hints. Thanks

**Comment by Brainiarc7** [comment]
Hello there,

Have you tried out:

`nbfc.exe config --recommend`

What does it report?

**Comment by Brainiarc7** [comment]
Then that would mean that support for this SKU is not implemented (yet).
I own the Zephyrus M GM501GS-XS74. If I figure anything out (such as the EC registers used, etc) I'll post back.
