### ISSUE TITLE
Fan keeps starting and stopping; screen brightness changes by itself

### ISSUE THREAD

**Issue by Transmogriff** [hirschmann/nbfc#60]
Acer Aspire 4810, using modified Acer 5930 profile. I can control fan speed fine, however the fan intermittently stops for about a second and then starts again. How often this happens varies, sometimes it can be several times within 5 minutes, at other times less often. Leaving the laptop idle seems to increase occurrence of this behavior. Also, screen brightness suddenly increases or decreases slightly after fan control service has been running for some minutes, this also keeps reoccurring intermittently during operation.

**Comment by hirschmann** [comment]
Maybe some other software is interferring: https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc
