### ISSUE TITLE
no /Linux/bin/ReleaseLinux after build

### ISSUE THREAD

**Issue by beyimanman** [hirschmann/nbfc#601]
Hellow
First of all congratulations for the work of this package but im having problems to make function on ASUS ROG GL702ZC.
I have 5.16.0.220 mono version and when i do "sudo sh build.sh" in nbfc 1.5 it seems to be ok with 3 warnings but dont create any directory in /Linux/, only the *.services files so i cant run "mono nbfc.exe..." but i can start the service.
With de "master" version of nbfc i have an error when i run "sh build.sh" 

"Mono Certificate Store Sync - version 5.16.0.220
Populate Mono certificate store from a concatenated list of certificates.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Usage: cert-sync [--quiet] [--user] system-ca-bundle.crt
Where system-ca-bundle.crt is in PEM format
build.sh: 15: build.sh: Syntax error: "}" unexpected
"
what can i do? i really need to use this program for put my fans to work before i burn my laptop

PS: Sorry for my bad english, im spanish native speaker

**Comment by dandycheung** [comment]
I meet this problem too. The build was completed successfully, with the following output:

Done building project "/home/dandy/Workspaces/test/nbfc/NoteBookFanControl.sln".

Build succeeded.

Warnings:

/home/dandy/Workspaces/test/nbfc/Windows/Setup/NbfcSetup/NbfcSetup.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/dandy/Workspaces/test/nbfc/Windows/Setup/NbfcBootstrapper/NbfcBootstrapper.wixproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.targets, to import. Ignoring.
/home/dandy/Workspaces/test/nbfc/Windows/Setup/DriverSetupWixAction/DriverSetupWixAction.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/Microsoft/WiX/v3.x/Wix.CA.targets, to import. Ignoring.

	 3 Warning(s)
	 0 Error(s)

Time Elapsed 00:00:08.1257840

BUT, there is nothing in nbfc/bin:

➜  nbfc git:(stable) cd Linux 
➜  Linux git:(stable) ls -l
total 24
-rwxr-xr-x 1 dandy dandy  49 12月 30 11:11 continue-nbfcservice.sh
-rw-r--r-- 1 dandy dandy 191 12月 30 11:11 nbfc.service
-rw-r--r-- 1 dandy dandy 263 12月 30 11:11 nbfc-sleep.service
-rwxr-xr-x 1 dandy dandy  48 12月 30 11:11 pause-nbfcservice.sh
-rwxr-xr-x 1 dandy dandy  95 12月 30 11:11 start-nbfcservice.sh
-rwxr-xr-x 1 dandy dandy  39 12月 30 11:11 stop-nbfcservice.sh
➜  Linux git:(stable) cd bin
cd: no such file or directory: bin

**Comment by beyimanman** [comment]
Hi. I can installed nbfc downloading the 1.5.1 or 1.5.2 beta version i dont remember in this moment... Anyway that versión can be build and setup properly with some tweaks... You must have the Last mono versión installed and get the files.. Build and then copy to /opt/nbfc the /bin/release/Linux file and the *. services files in your services folder.. Then do  
"sudo sh nbfc.service start" 
 and 
"mono nbfc.exe config - - apply yournotebookmodel" 
and finally 
"mono nbfc.exe start" 
Check with 
"mono nbfc.exe status"
Please let me know if you need any help.. It was very frustrating but it works!

**Comment by katanakiwi** [comment]
For some reason the build no longer works with xbuild. As suggested by the output i replaced xbuild with msbuild in build.sh.
After building with msbuild everyting worked as expected for me.

**Comment by katanakiwi** [comment]
Related errors?

**Comment by SerhatTeker** [comment]
No errors as above examples; `build succeeded` but no bin/Release directory. However I found the issue: I was trying to build on the `stable` branch. When I switched back to  `master` and build it again issue resolved.
