### ISSUE TITLE
Lenovo Ideapad 310-15ISK

### ISSUE THREAD

**Issue by Fusseldieb** [hirschmann/nbfc#607]
Hi,
I dug around in the configs and found that the Lenovo 310 is not on the list.
I tried to pick other Lenovo's, but it obviosuly didn't work.
I would love to see if someone has figured it out how to control the fan on this particular model.

**Comment by Gitarski** [comment]
You can try running "nbfc config -r" from the directory where NBFC is installed.

This will recommend a config that might work.

If nothing shows up, you'll have to create a config yourself.  You may want to contribute that to NBFC once it's working properly.

You can use other configs as a template.  Instructions on how to do this can be found in the wiki.

**Comment by Fusseldieb** [comment]
I already tried all of them, none works.

> If nothing shows up, you'll have to create a config yourself. You may want to contribute that to NBFC once it's working properly.

I'm not even sure what those "registers" are and how I can find the right one... Any pointer in the right direction would be great.

**Comment by Gitarski** [comment]
If it showed some configurations that are compatible, that's a good sign.

First, make sure you are using NBFC properly.

The way I use it is to first enable it using the radio box in the NBFC window.  I believe it is not selected by default.  Following that, you can move the displayed slider to set the target fan speed.  It will take a few seconds to be put into effect.

You may have already done this, but wanted to confirm how you are enabling NBFC.

Does the temperature look correct?  Does the fan speed seem correct?  If you click on the buttons with the two dots, to select a config, the dialog box that shows up will have an edit button.  Clicking on the edit button brings up the config editor.

The Fan configuration tab in the config editor shows the fan configuration.  Mine only has one line for CPU fan.  Double-clicking that shows details of the configuration.  Probably the most interesting one here is the Temperature thresholds tab.  This shows the fan speed settings at different temperature settings.

So, to confirm, please explain how your NBFC is behaving and what you are expecting.

Just trying to help!

**Comment by renoxtv** [comment]
Hi. Set your config to Lenovo Yoga 510 and edit the write register to 189. This will allow you to set your fan speed only to 100% but its still useful to fight that 61C temp limit that im sure you hate :D

**Comment by Fusseldieb** [comment]
@renoxtv I did that just to test
![image](https://user-images.githubusercontent.com/4715129/52201452-92fd1680-2852-11e9-93c9-72213967ff5b.png)
Yeah, it works, somehow... It unfortunately only goes to near 100%. True 100% is a little louder.

But thanks for your effort nonetheless :)
