### ISSUE TITLE
Please share a config for Lenovo Thinkpad X380 Yoga

### ISSUE THREAD

**Issue by Penguinjumper** [hirschmann/nbfc#609]
I would be very greatful if a config for Lenovo Thinkpad X380 Yoga would be added as all the available configs for Lenovo Notebooks don't work on this one and the fan just keeps starting and stopping whenever CPU goes over about 30%, even for just a few seconds.
Its ANNOYING AS **** and I have spent a lot (!) of time trying to fix it, sadly with no succes until now.

I really hope someone can help me!

**Comment by NickJD** [comment]
Ping
