### ISSUE TITLE
Asus UX430UA doesn't work

### ISSUE THREAD

**Issue by aronluka** [hirschmann/nbfc#614]
I tried almost all version of NBFC, and a lot of Asus Zenbook profiles, none of them works.
Although a lot of users of UX430UA seems happy, it doesn't do anything for me. I can select the profile, I can adjust the fan speed, but the fan is still running on 100%. Tried all BIOS versions (303,304,305) from Asus download site. 

The program is even showing me, that the fan speed should be zero, but the fan is still at 100%.

Does anyone else have a similar problem?

I'm running reinstalled Windows 10 64-bit without Asus bloatware. Can this be the issue? I tried installing even some Asus programs, but no difference.

Thanks for any help.

**Comment by mmassic** [comment]
I also own an Asus UX430UA running on Windows 10, 64 bits, and it works fine!  I use this configuration:
https://github.com/hirschmann/nbfc/blob/master/Configs/Asus%20Zenbook%20UX430UA.xml

**Comment by aPosix** [comment]
That is the inbuilt config in latest beta, right? I tried all of them. Lot of versions lot of versions, even the new config on older version of NBFC.

@mmassic Could you please provide which BIOS version and Asus software you are having on your computer? Maybe even which Windows 10 version -> 1803 or 1809. 

- To get windows version just write "winver" into start and open.
![0de72177-0f55-4578-b87d-8ab8ecf2cd16](https://user-images.githubusercontent.com/46280932/53693271-66c7ad80-3d9e-11e9-9ebe-351c80458281.png)

- BIOS version should be in "msinfo" (again open from start menu). (Im at the moment on different machine)
![image](https://user-images.githubusercontent.com/46280932/53693327-3d5b5180-3d9f-11e9-90c6-685fe6111f1f.png)

- Asus software list would be best via image of "appwiz.cpl" sorted by Publisher.


Thanks in advance if you are going to provide help.

**Comment by mmassic** [comment]
Bios version: American Megatrends Inc. UX430UA,305, 2018-03-15 (Which is the latest if I am not mistaken)
Windows 10 64 Home Edition version: 1809, build 17763.316

As for Asus apps, here are the ones I have installed on my PC:

![image](https://user-images.githubusercontent.com/48139071/53695448-f878f000-3d89-11e9-9c43-913080ccbdb1.png)

The latest versions I found on the Asus tool/drivers website.

**Comment by aPosix** [comment]
Thank you very much, for all the information. It's so weird to see that working correctly for you but doesn't for me. I might try to set it up later again.

**Comment by mmassic** [comment]
![image](https://user-images.githubusercontent.com/48139071/53695641-252e0700-3d8c-11e9-93fd-e5ef4bfe032c.png)

**Comment by RavenTheDev** [comment]
As a note, this does not work for me on Linux. I haven't attempted on Windows as I don't run it. It seems to detect the temp and set and read the fan speed, but the physical speed of the fan does not change. Using the UX430UQ config works fine. Perhaps its in the way it controls the fan?
