### ISSUE TITLE
HP ZBOOK STUDIO G3 - fan 2 is out of control

### ISSUE THREAD

**Issue by osvon** [hirschmann/nbfc#616]
HP ZBOOK STUDIO G3. First fan is controllable but second is totally crazy with fan speed 110.5% and completely out of control. second fan is keep spining and making lots of noise..It is torturing me for 96 hours already.

Anyone can help?

![captureww](https://user-images.githubusercontent.com/46386652/50713748-782e5b00-1076-11e9-8ab8-8464ce94a2e8.JPG)

**Comment by DerChiller** [comment]
Hey,

attached a config-file which works perfekt on my Z-Book 15 G4 with two fans.
Can you test it?

[HP ZBook 15 G4.zip](https://github.com/hirschmann/nbfc/files/2729930/HP.ZBook.15.G4.zip)
