### ISSUE TITLE
ec-probe gives out just zeroes

### ISSUE THREAD

**Issue by makedir** [hirschmann/nbfc#622]
I tried using the ec-probe tool on a Dell XPS 15 9570 but it just gives out empty readings, even if started as admin:

C:\Program Files (x86)\NoteBook FanControl>ec-probe dump
   | 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
---|------------------------------------------------
00 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
10 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
20 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
40 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
50 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
60 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
80 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
90 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
A0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
B0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
C0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
D0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
F0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

How come so? Is there a way to fix this? Would be nice if you could give a standalone zip btw not to have NBFC to install to get this tool. Also give a hint in the FAQ what it means, if it gives out zeroes and why (not compatible?).

**Comment by Mezun** [comment]
ok damn then maybe i should downgrade my bios because 1.7.0 is shitty since my mainboard switch and updating its not acting right. 
Even with undervolting i have the 5 sec fan switch in battery mode 
thinking about liquid metaling it

**Comment by makedir** [comment]
@Mezun the fan issues with 1.7.0 are "normal" and Dell is Dell and ignorant and said "it is working as intended". Read about it here:

https://www.reddit.com/r/Dell/comments/akngpy/incompetent_dell_devs_answer_to_bios_170_fan/

**Comment by Mezun** [comment]
yeah i read about this but im not quite sure if a bios downgrade is so safe

**Comment by makedir** [comment]
@Mezun yes it is... Ive downgraded / upgraded from 1.7 to 1.6 to 1.7 to 1.6 now 10 times or so over the past 2 weeks.

**Comment by Mezun** [comment]
ok i think i will downgrade then 

thank you for your advise

**Comment by makedir** [comment]
Ok 👌
