### ISSUE TITLE
[Feature request] Xiaomi Gaming laptop (Timi TM1801)

### ISSUE THREAD

**Issue by Alex-302** [hirschmann/nbfc#629]
Please add support for Xiaomi Gaming laptop (motherboard `Timi TM1801` with Intel 8gen CPU)
![image](https://user-images.githubusercontent.com/8361299/51850868-59487f00-232b-11e9-9a80-1b9571cb0587.png)
BIOS: https://drive.google.com/file/d/1EJmH70nhunhtYO0RbSOTy305qYn4WQtR/view

**Comment by ecSpl01t** [comment]
update
