### ISSUE TITLE
Asus K501LX

### ISSUE THREAD

**Issue by ury2** [hirschmann/nbfc#63]
Please make a profile for your great program for Asus K501LX - it is very noisy notebook. The fan runs even when the CPU is 36 degrees and no load

**Comment by dangusev** [comment]
I have Asus K501LB and it's pretty the same model with 2 fans. I use the config file for model Asus Zenbook UX32LN and it's working for me.

**Comment by ury2** [comment]
Денис, спасибо. У меня тоже заработало.

**Comment by ig0r89** [comment]
I have Asus K501LX too and I use Zenbook UX32LN profile.

One issue that I have is sometimes my GPU fan makes "half" spins. When the temperature is like 30-50 degrees. I guess it starts to spin by itself, but then it is stopped by NBFC. And it's irritating - fan starts to spin for 1-2 seconds from time to time. Does anyone have same issues? How can I fix that? 

Russian: 
У меня при работающем и настроенном NBFC все равно время от времени включается кулер видеокарты. Включится на 1-2 секунды и выключается. У кого так же? Есть решение?

**Comment by ury2** [comment]
I have not seen this. Maybe because the notebook used for a Word and surf the Internet.

Слабо использую комп, в основном для набора текста и серфинга в инете. Возможно поэтому такого нет.

**Comment by dangusev** [comment]
I haven't run nbfc on windows yet. On Ubuntu 14.it works ok

**Comment by RedGoblinz** [comment]
For k501lx, on windows 10, does anyone have problem with touchpad stuttering when nbfc is enabled? That's the only thing stopping me from using this app :(

**Comment by goa48** [comment]
@RedGoblinz 

I have the same issue. Pls halp.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
