### ISSUE TITLE
automatically change fan speed depending on temperature

### ISSUE THREAD

**Issue by StojanovicMilos** [hirschmann/nbfc#631]
I think it would be great to have a functionality similar to what speedfan has: either stating temperatures that you want and that are too hot (and update fan speed automatically having that in mind) or making a graph which sets fan speed depending of current temperature.

**Comment by Jonas1312** [comment]
This is exactly what NBFC does...

**Comment by StojanovicMilos** [comment]
Unless I'm missing something I have to disagree. NBFC can only set a fixed fan speed, regardless of the temperature. What I suggested is a functionality such as: if temp is between 40 and 50, set speed to 30%, if it's between 50 and 60 set to 50%, and if temp is over 60, set to 100%. If I can do this, please teach me how, because I was not able to figure it out.

**Comment by Jonas1312** [comment]
Please read the wiki: [**"Defines how fast the fan runs at different temperatures."**](https://github.com/hirschmann/nbfc/wiki/Temperature-threshold)

**Comment by StojanovicMilos** [comment]
Thank you!
