### ISSUE TITLE
Lenovo IdeaPad 310/510-15ISK [attached config]

### ISSUE THREAD

**Issue by renoxtv** [hirschmann/nbfc#632]
Hi devs of NBFC. First of all great program, the only one that can actually change the fan speed of my laptop. Initially when I didnt see a Lenovo Ideapad 310 config i gave up but i searched arround and found that a user named @danielstuart14 found a partial solution some months ago. I just wanted to make a issue just for it and I hope the devs can add it even though it works only partially. The solution is to select the Lenovo Yoga 510 config and set the write register to 189. The end result is that you can only set the fan speed to 100% but its still something. I created a config file with the proper name and write register so you can just put it in your Configs folder and its done. I hope the devs can put this in the next version as we are fighting a crappy 61C GPU temp limit and 100% fan speed is needed sometimes, or better yet find the correct write register. Here is a link for my edited config: https://drive.google.com/open?id=1x5xCvAbDr9ik0ECOK9Bx3lr9J7erd9Yy

**Comment by xXBuilderBXx** [comment]
So i was testing this and saw that your could only go to 100% but the program shows 180% 👀

**Comment by renoxtv** [comment]
Your Read register is set to 6, right? Works fine here. 
https://postimg.cc/4mtCvnbz
Ideapad 310 15-ISK 80SM, on oldest bios 0XCN22WW if that matters.

**Comment by xXBuilderBXx** [comment]
@renoxtv sorrt for the late response and yes the read register is at 6

**Comment by renoxtv** [comment]
Idk. I noticed that if you block off the fan intake it starts spinning faster than 100% speed. My Fan's intake and exhaust are both fully clean and open

**Comment by xXBuilderBXx** [comment]
I've had the laptop for like 2/3 years now and it's still going strong, you said that the fan intake is blocked should i be concerned about that the laptop seems fine and dosen't overheat.
