### ISSUE TITLE
Lenovo e31-70

### ISSUE THREAD

**Issue by mmirkov** [hirschmann/nbfc#65]
Could someone share/create config for this model please?

**Comment by blyskawica** [comment]
I have till now:
register 6 is to read the fan speed (0x00 is fan off, 0x13 is fan minimal speed, 0x2C is fan max speed)
register 176 is to set up the fan speed:
0x00 is to stop the fan, precise binary 0000xxxx (x doesnt matter)
0x3C is to run the fan at min speed 00111100
0xC0 is to run the fan at max speed 11xxxxxx

But I cant till now find the register to disable automatic fan control function. So when you write something in register 176, after 3-4 second it will be reseted.

**Comment by mmirkov** [comment]
Thank you!!!

**Comment by mmirkov** [comment]
Actually this conf is for u31-70 instead of e31-70.

**Comment by blyskawica** [comment]
ah sry, i read u31-70 by mistake

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
