### ISSUE TITLE
Can you do setup for .net 4 ?

### ISSUE THREAD

**Issue by segant08** [hirschmann/nbfc#658]
I'm using xp sp3 and max support for .net version is 4.0.3 can you decrease it from 4.5 ?
And fujitsu ah530 support? :)

**Comment by wyxchari** [comment]
The same happens to me. Generally the oldest netbooks have Windows XP installed. In fact, the Packard Bell DOA150 is one of those included in this program and was only sold with Windows XP. I do not understand how a notebook program does not support XP.

**Comment by hirschmann** [comment]
NBFC 1.4.2 is the last version which targets .net 4.0. I can't switch back to 4.0 because NBFC relies on some framework features which don't exist in .net 4.0.
