### ISSUE TITLE
Configuration for Lenovo Ideapad 330s 15-arr?

### ISSUE THREAD

**Issue by Afterglowkid23** [hirschmann/nbfc#661]
Just would like a configuration for my Lenovo 330s 15-ARR to control the fan speed cause i don't mind the noise but i do mind the minor amount of thermal throttling. Thanks :)

**Comment by Tubbs915** [comment]
Would also like to see an applicable config. I was about to download the app anyway, and check if any recommended configs did the job have you been able to get any of them working?

**Comment by Afterglowkid23** [comment]
I have not but I will certainly keep checking back here for any possible updates

**Comment by rpgod** [comment]
In yoga 510config change write register to 189,only 100%speed work for 330 15arr maybe it can work for u too

**Comment by Afterglowkid23** [comment]
Tried Changing the Write Register to 189 on the yoga 510 configuration but yielded no results except a temperature reading so I guess it's a step in the right direction. :)

**Comment by rpgod** [comment]
Did u enabled it and set only to 100 % and also have to restart one time

**Comment by Afterglowkid23** [comment]
I will try those steps

**Comment by Tubbs915** [comment]
Has this worked for anyone? I'm about to try it myself after I get off the sh***er, and will post results if any. Thanks guys.

**Comment by Afterglowkid23** [comment]
Tried the steps and still no results
