### ISSUE TITLE
A10-9600P AMD APU: 0 configs are showing

### ISSUE THREAD

**Issue by scottLIR** [hirschmann/nbfc#662]
I am not getting any configs to show up on the list

**To Reproduce**
Open the main program in either Administrator Mode or regular.

**Expected behavior**
Any config to show, even if it's not related to my system.

**System information**
 - 15-ba079dx HP Notebook 15
 - 1.5 & 1.6.2
 -    Index Time          EntryType   Source                 InstanceID Message
   ----- ----          ---------   ------                 ---------- -------
    4418 Mar 24 20:30  Information NoteBookFanContro...            0 Service started successfully.
    4416 Mar 24 20:30  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    4409 Mar 24 20:30  Information NoteBookFanContro...            0 Service started successfully.
    4407 Mar 24 20:30  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    4393 Mar 24 20:28  Information NoteBookFanContro...            0 Service started successfully.
    4391 Mar 24 20:28  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    4382 Mar 24 20:26  Information NoteBookFanContro...            0 Service started successfully.
    4380 Mar 24 20:26  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    4350 Mar 24 20:21  Information NoteBookFanContro...            0 Service started successfully.
    4348 Mar 24 20:21  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    3763 Mar 24 03:28  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    3757 Mar 24 03:21  Information NoteBookFanContro...            0 Service started successfully.
    3747 Mar 24 03:21  Information NoteBookFanContro...            0 Service stopped successfully.
    3746 Mar 24 03:21  Information NoteBookFanContro...            0 Service started successfully.

**Additional context**
If it doesn't register CPU temperatures from my CPU how do I go about fixing that?

**Comment by gfanini** [comment]
I have AMD A10-9620P  family 15h revision 65h cpu

is this a typo 

nbfc-1.6.3\Core\Plugins\OpenHardwareMonitor\Hardware\CPU\AMD10CPU.cs

if (miscellaneousControlDeviceId /*miscellaneousControlAddress it cannot be an address it should be a device id */ == FAMILY_15H_MODEL_60_MISC_CONTROL_DEVICE_ID) {

it seems to read temperature ok this way, can you correct it ?
it is actually open hardware monitor but it seems a different code for A10 ?
