### ISSUE TITLE
Cant reach 100% fan speed on HP ZBook 15

### ISSUE THREAD

**Issue by EuphoriaCelestial** [hirschmann/nbfc#663]
**Describe the bug**
The current fan speed value can never reached 100%, both when auto and manual.

**To Reproduce**
When set to manual and slide the slider to 100%, fan speed only reach 82.5%. 
When set to auto and play game with high setting, doing render, it also reach around 80-82% fan speed

**Expected behavior**
Fan speed reach full 100%

**System information**
 - Windows 10 Pro build 1803
 - NBFC version 1.5.0

**Comment by andinek** [comment]
If it's G4, try 1.6 beta2 and this config. I'm using it since 3 months with my zbook G4 15 with 2 fans and it's working correctly and reaching 100%. Change the extension to xml and import it to nbfc.
[HP ZBook 15 G4_2.xlsx](https://github.com/hirschmann/nbfc/files/3002377/HP.ZBook.15.G4_2.xlsx)

**Comment by EuphoriaCelestial** [comment]
my ZBook is G1, with only 1 fan :(

**Comment by SamuelBTJ** [comment]
it happens exactly the same in 1.6 beta2 with Asus K55VD, I would like to be able to solve it since it is a great program!
