### ISSUE TITLE
Cant Reach 100% fan speed on ROG G752vl and no selection for this model

### ISSUE THREAD

**Issue by V37VOiYi** [hirschmann/nbfc#665]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**System information**
 - operating system
 - NBFC version
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview))

**Additional context**

**Comment by V37VOiYi** [comment]
The Fans on the gpu go all the way up i think but the cpu really only goes to about 25%

**Comment by V37VOiYi** [comment]
Win 10 64 bit 1 tb hdd 12 gb ram 2gb gram 965m same model in title

**Comment by f-r-i-t-z** [comment]
Under the G752VT I discover that the GPU ( nvidia ) Register is 165 (OXA5) and not 166 (OxA6)..
MY VT Variant have a fixed GPU (NVIDIA).
EXAMPLE:
160: ...,046,046,047,045,045,045,045,045,047,049,045,048,046,045,044,046,045,045,045,045,044,045,047,047,045,045
165: ...,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045,045
166: ...,046,046,047,045,045,045,045,045,047,049,045,048,046,045,044,046,045,045,045,045,044,045,047,047,045,045

160 and 166 are all the sane CPU Temperature and 165 changes togheter the GPU temperature. Maybe something related?
