### ISSUE TITLE
Lenovo 81D2 330 15arr(100% speed fan working help for other fan stages )

### ISSUE THREAD

**Issue by rpgod** [hirschmann/nbfc#667]
hi i was able to use fan at 86.5% which is 100% and cant set to other setting i made this by changing write register to 189 in yoga 510 config here config is attached below help to unlock more stages
[LENOVO 81D2.zip](https://github.com/hirschmann/nbfc/files/3061986/LENOVO.81D2.zip)

**Comment by stackerlon** [comment]
Thank you for your config, now the issue with fan speed is fixed on ubuntu which are very low always and my machine throttles a lot. Somehow this config fixed the speeds of my fan.

**Comment by rpgod** [comment]
As i said only 100% or brlow 10%works, dont use random setting it may cause some problem
