### ISSUE TITLE
GPU Temperature via EC Registers - how to use?

### ISSUE THREAD

**Issue by rolla-costa** [hirschmann/nbfc#678]
As discussed in #203 it would be nice to also include GPU temperature to determine necessary fan speed. @chandradeepdey pointed out it is possible to read GPU temperature via EC registers on his machine. Using ec-probe and MSI Afterburner it took less than five minutes to find out the GPU temperature EC register on my laptop. How could I make use of that knowledge? A simple maximum(T-CPU, T-GPU) would be completely fine.

**Comment by hirschmann** [comment]
Currently there is no easy way to make use of this knowledge. You'd have to create a temperature plugin for NBFC which reads from the register you found.

This class shows how a NBFC temperature plugin should look like:
https://github.com/hirschmann/nbfc/blob/master/Core/Plugins/StagWare.Plugins.CpuTemperatureMonitor/CpuTemperatureMonitor.cs

This class implements methods to access the EC:
https://github.com/hirschmann/nbfc/blob/master/Core/Plugins/StagWare.Hardware.LPC/EmbeddedControllerBase.cs
