### ISSUE TITLE
Can't remove WinRing0x64.sys

### ISSUE THREAD

**Issue by oaltena** [hirschmann/nbfc#679]
How can I remove WinRing0x64.sys?
I already tried to remove it via Kernel Mode Drivers Manager

**Comment by hirschmann** [comment]
If the NBFC setup doesn't remove the driver when you uninstall it (a reboot may be required), you can use autoruns (https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns) to delete the driver and then delete the file.

**Comment by symonxdd** [comment]
I'm having the same issue... also it appears it doesn't work at all with my MSI GS66... one particular service was constantly running in the background causing my CPU to overheat like hell and my fans to spin like a tornado.

Uninstalling with IOBit Uninstaller, did **not** uninstall the program. After a few days of constant CPU overheat and games bringing the temperature to about 96 degrees Celsius, which normally would be around 85; I went to search for the culprit, I almost thought I caught a virus... thank god it was just this obsolete piece of ?!@#
I needed to go into the installation folder myself to delete all the files, except this one couldn't get removed. I'll try the 'autorun' method, god bless me.

I don't understand who would make software with an uncomplete / no uninstaller, and make you search for tools to remove it, sounds like malware to me.

Don't install this shadyware, unless you trust the dev. 👍

**Comment by hadoooooouken** [comment]
1. Win+R \ services.msc \ Look for NBFC service \ Go to its properties \ Stop it and Copy service name
2. Win+R \ cmd \ type "sc delete NBFC_SERVICE_NAME (I just deleted it and forgot how it was named)"
3. Wir+R \ regedit \ Ctrl+F \ Search "WinRing0x64.sys" (it will be somewhere in Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\) \ Select and delete entire registry key (who has string value "C\Prorgram Files\Notebook Fan Control"
4. Done.

**Comment by symonxdd** [comment]
Hi there, the last reply was from 2022 though, oof!🥶
