### ISSUE TITLE
it stop working..

### ISSUE THREAD

**Issue by Ouyeahh** [hirschmann/nbfc#68]
When i start GTA V the config is being rewriten and it goes back to stock config, if i alt+tab it start working like i intend it to... but after not long will go back to stock... same for other games, some games  if i windows+borderless will work ok... otherwise it goes default until i alt+tab, and when i go back i ngame, after a minute goes back to stock... i tried to make it run always as admin aleardy

**Comment by Brisko007** [comment]
Have you restarted the Notebook Fan Control Windows Service after changing the values in the config file?

You have to do this or it will use the old values (and most likely overwrite your changes).

**Comment by hirschmann** [comment]
It is probably this issue: https://github.com/hirschmann/nbfc/wiki/FAQ#why-does-nbfc-stop-working-when-i-start-a-game
