### ISSUE TITLE
Wrong ASUS G752VT Config file?

### ISSUE THREAD

**Issue by f-r-i-t-z** [hirschmann/nbfc#681]
**Describe the bug**
Maybe not a bug but a wrong config file?

**To Reproduce**
The Asus ROG G752VT.xml have under:
<RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnWriteFanSpeed</WriteOccasion>
      <Register>166</Register>
      <Value>10</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>10</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
      <Description>GPU FAN</Description>
 </RegisterWriteConfiguration>

From my EC Read the correct for GPU is 165 (OxA5)? Or i'm missing something?

**Expected behavior**
The correct GPU FAN control.

**System information**
 - Antergos/ARCH Linux Asus ROG G752VT Nvidia GTX 970m, CPU: i7-6700HQ 
 - NBFC version 1.6.3.0
 - log files:
THE EC REGISTERS RETURN:
160: ...,046,046,046,047,046,046,047,047,046,046,046,046,046,047,046,049,048,046,046,046,046,048,046,048,046,046
165: ...,048,048,048,048,048,048,048,048,048,047,047,047,047,047,047,047,047,047,047,047,047,047,047,046,046,046
166: ...,046,046,046,047,046,046,047,047,046,046,046,046,046,047,046,049,048,046,046,046,046,048,046,048,046,046

**Additional context**
The 160 and 166 are identical for CPU temperatures. The 165 means GPU (The same return from NVIDIA CONTROL).
I'm missing something or the config XML file is wrong?

**Comment by hirschmann** [comment]
I can't verify this because I don't own a ASUS G752VT, but it could be an error in the config file.
Have you tried changing the register to 165? Does the behavior change?

**Comment by f-r-i-t-z** [comment]
@hirschmann Yes. It works well. And yes, seems a config file error. To complete my hardware reference. I'm using the "ASUSTeK COMPUTER INC. G752VT/G752VT, BIOS G752VT.304 06/29/2017"  ( bios version)
