### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by TheDarkLach** [hirschmann/nbfc#682]
**Describe the bug**
I have a rog strix gl503vm. When I started NBFC it automatically put in the config file for rog gl702. I played around with the fan controls and it did nothing. My laptop then suddenly crashed. Not sure if it was NBFC or just something else my laptop did. 

**To Reproduce**
Wrong config file?

**Expected behavior**
The screen would turn off, restart needed.

**System information**
windows 10 64 bit
 - NBFC version- 1.6.3
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview))

**Additional context**
you could have a message pop up saying that there isn't the right config file instead of it automatically putting the closest thing to your laptop.

**Comment by hirschmann** [comment]
NBFC 1.6.3 doesn't automatically select configs.
Have you maybe previoulsy installed NBFC and selected this config?
NBFC reading the selected config from previous settings would explain this behavior.
