### ISSUE TITLE
Different settings for charging and battery mode

### ISSUE THREAD

**Issue by IiroP** [hirschmann/nbfc#686]
**Is your feature request related to a problem? Please describe.**
Currently the fan speeds & tresholds are always the same, no matter if the device is charging or in the battery mode.

**Describe the solution you'd like**
Ability to customize fan speeds & tresholds separately for charging and battery mode.

**Comment by hirschmann** [comment]
I know this answer is a bit late, but I had to resurrect an old tool I wrote a couple of years ago, polish it up a little and write a tutorial on how to use it.
If you're still searching for a solution to this problem, take a look at [Power Event Provider](https://github.com/hirschmann/powereventprovider)

Hope this helps :)
