### ISSUE TITLE
HP ZBook 15v G5 config?

### ISSUE THREAD

**Issue by Buzingo** [hirschmann/nbfc#687]
Alright. So I am currently owning a HP ZBook 15v G5. I tried the config for the HP Zbook 15. It reads out the temperature of my CPU correcly. But i cant change the fan speed.. Changing the Target fan speed does literally nothing.. idk if u need any more specific information.. if so, just tell me 
My System Info:
Windows 10 PRO Build 1903
NotebookFanControl v1.6.3

**Comment by Buzingo** [comment]
btw i tried browsing DSDT.. but didnt find anything helpful
i would be glad if u could help me


Here my DSDT:
[DSDT.txt](https://github.com/hirschmann/nbfc/files/3191650/DSDT.txt)

**Comment by webloft** [comment]
As I found the same DSDT names maybe this info will help you:

see https://github.com/hirschmann/nbfc/issues/688#issuecomment-517526452

**Comment by youssefhamdanea15** [comment]
is there any news i need the config
