### ISSUE TITLE
asus k550jx

### ISSUE THREAD

**Issue by brattak** [hirschmann/nbfc#69]
please is possible have config for this notebook thanks

**Comment by brattak** [comment]
i enable powershell to execute your script but when execute have 88 error and not create .exe

**Comment by brattak** [comment]
please help or add my notebook i love this program thanks

**Comment by brattak** [comment]
please add k550jx hirschmann

**Comment by brattak** [comment]
up

**Comment by brattak** [comment]
why dont help me hirschmann?

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
