### ISSUE TITLE
Doesn't function after Windows 10 v1903 Update (Here's Why and Solution)

### ISSUE THREAD

**Issue by ghost** [hirschmann/nbfc#690]
Hey hirschmann. I've upgraded my Windows to May 2019 update and NBFC has stopped functioning and shows an odd temperature number. Restarting the NBFC service or OS didn't work.

 - Windows 10, v1903, build 18362.116
 - NBFC 1.6.3

![2019-05-22 171715](https://user-images.githubusercontent.com/50917967/58182288-0289fb00-7cb6-11e9-9a6e-707100da036a.jpg)

-Also tried reinstalling latest build again after deleting NBFC directories/settings and a reboot but didn't work.
-There is no hardware monitoring tools installed.

**Comment by XavierG96** [comment]
Same problem, updated to windows may 1903 and hasn't worked since. I have hp envy x360

**Comment by nicgofpat** [comment]
A quite research and I've found out that the same problem occured with programs that utilizes "WinRing0 after the Windows 10 May Update". As ThrottleStop author unclewebb says "**Starting with Windows 10 - 19H1, it looks like the Memory integrity setting can completely block the WinRing0 driver which will prevent ThrottleStop(NBFC in this case) from starting(utilizing WinRing0)**." 

So the solution is turning off the **memory intergrity**: 

_NOTE: Turning of Memory Integrity is a serious matter. Do not turn it off if you do not understand what you are doing. You may not be able to turn off Memory Integrity if your computer is joined to a corporate domain. Turning off memory integrity may violate your workplace's IT security policies._

The easiest way to disable memory integrity is via Windows Security as follows:
1. Double click windows security in the tray or run it by searching for it by name.
2. Select the Device Security Tab.
3. Select "Core Isolation Details"
4. Toggle off "Memory Integrity"
5. Follow the prompts to restart your computer.
6. Fresh install of NBFC if it needed.
 
And voilà, it works.

**Comment by XavierG96** [comment]
what are the risks of turning off memory integrity?

**Comment by XavierG96** [comment]
When i get in the Device Security tab it doesn't show "Core isolation details". It only shows "Security proccesor", "Secure boot", and "Standard Hardware security not supported"

**Comment by nicgofpat** [comment]
Okay, try the using .reg file option and restart? 
https://www.tenforums.com/tutorials/104025-turn-off-core-isolation-memory-integrity-windows-10-a.html

**Comment by XavierG96** [comment]
it is turned off, and still doesn't work. I guess I wont be able to use NBFC for a while.

**Comment by XavierG96** [comment]
So I managed to get it working. I disabled virtualization technology in BIOS settings and tried the .reg option and it worked. Thanks a lot!

**Comment by Sidtech88** [comment]
For me disabling VT in BIOS setting did the trick

**Comment by musteb244** [comment]
After i updated Windows 10 v1903. NFC has been blocked. I uninstalled it and tried to install again but it can't be installed. I tried everything ( I disabled virtualization technology in BIOS settings, turned off memory integrity etc.) But it can't be installed by set up exe file. Help me please.

**Comment by HeyImPuni** [comment]
Even tho this issue is closed. It is, at least for me, not related to the Windows v1903 update. I'm on build 1809 and had an update yesterday, since then NBFC is only showing me negative temperatures and isn't controlling the fans. Core isolation is disabled (not even supported on my device). 
Acer Aspire VN7-591G

![BDa04uX7CM](https://user-images.githubusercontent.com/54338492/87668775-035cd680-c76d-11ea-82b2-a2bf38705534.png)

EDIT:

I removed my latest Windows update (sorry, forgot to write it down). I'm on build 17763.1339. 
It's probably [this update](https://support.microsoft.com/en-us/help/4566516/kb4566516-cumulative-update-for-net-framework)

**Comment by joaofbravo** [comment]
Also happened to me after an early 2023 Windows update (Asus TP301UJ)

**Comment by svetlisashkov** [comment]
I have the same problem with Acer Aspire VN7-793G V17 Nitro BE and Windows 10 Pro 22H2 with the latest updates (July 2023).
