### ISSUE TITLE
Keyboard bug from the nbfc service (Asus G750JZ)

### ISSUE THREAD

**Issue by kobart1101** [hirschmann/nbfc#696]
The bug seems to be that the nbfc seems to trigger "enter" on the G750JZ. After starting the laptop in normal mode (with the service enabled on startup) the computer has Ghost enter strokes, as if the enter key was being pressed or the keyboard was faulty. But when booting in safe mode or disabling the service on startup that problem is no longer present.

**To Reproduce**
Use the Asus ROG G751JL preset on an Asus ROGG G750JZ laptop.
Have the NBFC service enabled to start on startup.

**Expected behavior**
You should be getting random enters at seemingly random intervals. Personally I used a word document or having right click menu open on the desktop and hoovering over an option. If you're experiencing the bug the enter should be registered within 5-10 minutes if you just leave the laptop there. 

**System information**
 - Windows 10 (version 1903 build 18362.116)
 - NBFC version 1.6.3
 - log files:
[NbfcServiceLog.2019-05-26.txt]
(https://github.com/hirschmann/nbfc/files/3227203/NbfcServiceLog.2019-05-26.txt)

[NbfcServiceLog.txt]
(https://github.com/hirschmann/nbfc/files/3227204/NbfcServiceLog.txt)

**Comment by hirschmann** [comment]
This can happen if other tools interfere with NBFC, see https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc

Also, the ROG G751JL config could not be fully compatible with your ROG G750JZ

**Comment by kobart1101** [comment]
> This can happen if other tools interfere with NBFC, see https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc
> 
> Also, the ROG G751JL config could not be fully compatible with your ROG G750JZ

I did use speed fan a couple of times but it's not running on startup so maybe it's some other stuff running in he background.

And yeah I thought that the fact that it's not the same config might cause problems. I was going try to make a config of my own but that is beyond my skills
