### ISSUE TITLE
Unable to donate

### ISSUE THREAD

**Issue by kefs** [hirschmann/nbfc#7]
I searched your repo for the [donate link](https://github.com/hirschmann/nbfc/blob/c28798691dd3d57603807dea781c4c92172378a6/Windows/NbfcClient/Windows/MainWindow.xaml#L119), but i'm not able to donate via that paypal hosted button [[error received](https://i.imgur.com/pYY3o2W.png)]..  

How can I donate for your awesome contribution to the world? Thanks!

**Comment by hirschmann** [comment]
I'm gald you like my work :)

You can't just copy the link from XAML code into your browser because the ampersand (`&`) is escaped (`&amp;`)

This link should work: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HUALCC9HY9MKC
