### ISSUE TITLE
Adjusting EC Polling rate doesn't match settings

### ISSUE THREAD

**Issue by Dainslaif** [hirschmann/nbfc#703]
**Describe the bug**
I have a config for my G75VW laptop that correctly reads and writes the values for my fans.  No matter what the EC Poll Interval value is, the values only update every 2500ms.

**To Reproduce**
Start NBFC and load the config matching your laptop.
Set the EC Poll Interval to 500ms.
Watch the values, which only update once every 2.5 seconds

**Expected behavior**
The Temperature and Fan speed readings to update at the rate I set in the EC Poll Interval.

**System information**
Windows 8
NBFC 1.6.3
[NbfcService.zip](https://github.com/hirschmann/nbfc/files/3251793/NbfcService.zip)

**Additional context**
Apps like Coretemp and MSI Afterburner read and update values rapidly, but I'm assuming they use different methods, so I'm not sure if there's another limiting factor taking place.

**Comment by hirschmann** [comment]
The poll interval defines at which rate the NBFC service polls/updates the EC.
It doesn't affect at which interval the Windows client (GUI) is updated. Currently the client update interval is 3 seconds and cannot be changed.

**Comment by Dainslaif** [comment]
Alright, I'll submit it as a feature request, then.
