### ISSUE TITLE
Add variable to control temperature polling rate

### ISSUE THREAD

**Issue by Dainslaif** [hirschmann/nbfc#704]
**Is your feature request related to a problem? Please describe.**
The temperature polling rate is hard-set to 3 seconds (per comments at https://github.com/hirschmann/nbfc/issues/703), so it lags quite a bit behind my computer's actual temperature, letting it spike before it kicks in and turns on the fans.

**Describe the solution you'd like**
Add in a variable that lets the user define their temperature polling rate.  This would set how often NBFC updates the temperature value it operates from.

**Additional context**
Probably should have a low max value (3 seconds?) for the sake of safety.

**Comment by hirschmann** [comment]
The temperature polling rate is the same as the EC polling rate and can be set via config.
Only the UI update rate is fixed at 3 seconds. The UI update rate doesn't affect the functionality of the NBFC service at all.

**Comment by Dainslaif** [comment]
Interesting, is there a reason they don't just update at the same timing?

**Comment by hirschmann** [comment]
I wanted to avoid putting too much load on the system, especially when multiple clients are running at the same time. Also the client currently has no way of querying the service's poll interval.

I consider pushing changes to the client instead of polling in the future, though.
