### ISSUE TITLE
Config for Voyo vBook i7 plus

### ISSUE THREAD

**Issue by Lennart13** [hirschmann/nbfc#705]
Hi guys, i tried to create a config the way you show it on your tutorial. 
At first I looked at the mainboard to find the correct chip where the EC is located. I didnt open the tablet but someone else did and I attached the picture to this post. According to the picture the chip is called ENE KB3930 A1. As you guys suggested I looked for a datasheet online and found it, I will also attach it. In this datasheet it says that the relevant pins for the fan controls are 26, 27, 28 and 29. I then tried to check them by dumping the EC and then setting a value for the certain pins. 
Sadly, nothing changed.
So I tried to look into the DSDT with RW-Everything. After looking for `Embedded`, I found two entries which have something to do with the fans. I will also attach the screenshot for this. To check the pins I tried the same thing as above and nothing changed.

Can you guys tell me what I did wrong or help me in general? 

Thank you for your time

![20181214_211753](https://user-images.githubusercontent.com/51486938/59115321-54cf4b00-8949-11e9-9e1d-2322dcda7d1d.jpg)

[KB3930_ENE.pdf](https://github.com/hirschmann/nbfc/files/3266571/KB3930_ENE.pdf)

![EC Code](https://user-images.githubusercontent.com/51486938/59115365-6a447500-8949-11e9-827b-57156626eb3c.PNG)

**Comment by xzero105** [comment]
Tell me how to reset the BIOS on i7 plus

**Comment by xzero105** [comment]
Tell me how to reset the BIOS on i7 plus
