### ISSUE TITLE
HP 15-bw018ur config request

### ISSUE THREAD

**Issue by Moattasam** [hirschmann/nbfc#706]
I really need a config file for my laptop. It overheats very much
HP Notebook - 15-bw018ur Product Specifications - https://support.hp.com/au-en/document/c05532100

**Comment by Moattasam** [comment]
https://github.com/hirschmann/nbfc/pull/835
[That](https://github.com/hirschmann/nbfc/files/4268812/HP.Laptop.15-db1xxx.txt) config works

**Comment by xCuri0** [comment]
I can confirm it works on HP Notebook 15-ac111tu too
