### ISSUE TITLE
Config for Lenovo 730 15

### ISSUE THREAD

**Issue by Felix048** [hirschmann/nbfc#707]
Hey there, I'm quite new here, but I really do need a config for the Lenovo 730 15.
I didn't find it in the Dropbox so I guess its not done yet.
Can someone maybe help me with it becaus I really don't know how all this works.
Can I maybe use a different config?
Thank you for any response and have a great day!

**Comment by AdelKS** [comment]
Hello @Felix048 

Can you try to go first by yourself through the tutorial here: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

Keep us updated!

**Comment by Felix048** [comment]
> 
> 
> Hello @Felix048
> 
> Can you try to go first by yourself through the tutorial here: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
> 
> Keep us updated!

Hey Adel, thanks for your response. I have to say that I am just annoyed of the fan, but I dont know or understand anything of that programming stuff. At the moment i just have to learn a lot, so I dont really have time to get into it so I just asked if there is anyone who has a config for the laptop and would like to share it. 
Cheers

**Comment by AdelKS** [comment]
I think that if anyone has the config for your specific laptop with this specific program, he would have already shared it :/

**Comment by deebfeast** [comment]
What helped in my case with the 730 model is to switch videocard to Intel in the Nvidia driver setting. This changed some of the fan control as the Nvidia mode introduces some overrides.

For now I'm loading Lenovo Yoga 2 13 config but this needs still work for regulation.
The fan controller can be signaled down/reset by running "ec-probe.exe write 171 8" which works okay but this needs to be translated to a configuration file.

If I've a better config I'll submit it.

**Comment by zahradkav** [comment]
Hallo @deebfeast and @Felix048 ,
have you made any progress with Yoga 730 15? I would like to improve the fan control as well (to set the initial treshold for the fans to 50°C for example) but I was not successful so far. 

Cheers,
Vaclav

**Comment by Jellyyz** [comment]
yup, has anyone found a config?

**Comment by Jellyyz** [comment]
whats the ec probe, can't find anything useful

**Comment by deebfeast** [comment]
Sorry, no good config found, there's probably some "intelligent" cooling kicking in and no way to keep overriding it. It's not something I like to say but the thermal design of the 730-15 simple does not work! To keep the temperature down it requires power down of the Nvidia card, throttling or limiting the CPU or generally run it in some laptop low-power, low-cpu mode. With Linux this is even harder to do as Windows 10 has an "Energy Manager Driver" with Yoga mode control https://pcsupport.lenovo.com/nl/en/products/laptops-and-netbooks/yoga-series/yoga-730-15iwl/downloads/ds541250 but I have not checked it (might be there on default installs).

It all seems similar to the extensive research done here: https://github.com/hirschmann/nbfc/issues/526 which means it won't be solved.  For me "ec-probe.exe write 171 8" under a speed key helps. Other people have suggested replacing fans, paste, increase air flow by angle etc.

**Comment by Jellyyz** [comment]
Hey @deebfeast can you pm me on discord, I have some questions. Jelly#8007

**Comment by Jellyyz** [comment]
[dsdt lenovo yoga 730.txt](https://github.com/hirschmann/nbfc/files/4006575/dsdt.lenovo.yoga.730.txt)

**Comment by deebfeast** [comment]
Like with the efforts for the Lenovo Ideapad Y700-15IS as linked to above, it's not that simple to derive much from only the DSDT. My own find was done by watching how registers behaved and poking around. But I checked now to see if 0xAB (171) is in the DSDT.

The reset code might be visible in methods _WAK (wakeup, init?) calling P8XH also mentioning _SB.PCI0.LPCB.OSTP (stop?). This might explain why 171 could be linked to some reset. And after trial and error I noticed that writing 8 to it powers the fan down as long as temps are under 50. Which for me was good enough to have it a bit more silent but does not equal regulation. The Nvidia card has its own cooling logic (cool bits) but does not seem to work with my driver.

```
Method(_WAK, 1, Serialized)
	{
		P8XH(One, **0xAB**)
		\_SB.PCI0.LPCB.OSTP()
		If(LEqual(Arg0, One))
		{
			H2OP(0xE1)
		}
                ....

```

**Comment by Jellyyz** [comment]
Hey guys, after taking apart my laptop and almost bricking it, i found the ec- https://www.ebay.com/itm/1pcs-New-ENE-KB9022Q-D-TQFP-IC-Chip-KB9022QD-KB9O22Q-K89022Q-KB9022Q-D-/201416789178

hope this helps?

this is mine: https://ibb.co/S6kFSqV

**Comment by deebfeast** [comment]
Check out https://github.com/hirschmann/nbfc/issues/652 where HP 15-bs183 owner reports ENE KB9022Q D and seems in the same boat. Check out the configs mentioned.

I've checked schematics of KB9022/KB9032 but that won't help that much with the config.
