### ISSUE TITLE
Config for Vivobook S430FN

### ISSUE THREAD

**Issue by Ramonivandy** [hirschmann/nbfc#719]
There's a config for this model ? or other config work with this model ? already try with vivobook config but it did not work.

**Comment by FlorianJourde** [comment]
Hey !

I would also need to control fan noise for a similar computer, an Asus Vivobook X512FA ! I'm making music production, and sometimes I really need quite environment, while recording voices, for exemple !

Thank you for listening !

**Comment by Ramonivandy** [comment]
> Hey !
> 
> I would also need to control fan noise for a similar computer, an Asus Vivobook X512FA ! I'm making music production, and sometimes I really need quite environment, while recording voices, for exemple !
> 
> Thank you for listening !

For now i just setting my nvidia control panel to auto, so the fan will spin faster if the cpu getting hot..
