### ISSUE TITLE
Asus N750JK

### ISSUE THREAD

**Issue by HoreaM** [hirschmann/nbfc#72]
Is there any way to make this program control my fans on my Asus N750JK Notebook? Are there any configs? I've been searching everywhere... Thank you

**Comment by RypeDub420** [comment]
Have you tried using another ROG or any other ASUS config and see if it works for you?

**Comment by HoreaM** [comment]
I managed to set it up in th end, but I have 2 fans and they are both affected by the NBFC config O made. Is it possible they are linked together?

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
