### ISSUE TITLE
Config file for HP OMEN 15 2018 models (dc0xxx)

### ISSUE THREAD

**Issue by mkroshana** [hirschmann/nbfc#722]
I created a config file for HP OMEN 15 - 15-dc0120tx can anyone check that this will work on all 2018 models ?

**Comment by iZN1337** [comment]
I'm interested. I own a dc0051nr and would like to test.

**Comment by FanFanFantastic** [comment]
same here dc0041nr, really aggressive fan profile an awful play by HP. I can't even roll back my bios.

**Comment by iZN1337** [comment]
...so any news? @mkroshana would be really great if you could share it.

**Comment by Juanbanpar** [comment]
@iZN1337 @FanFanFantastic @mkroshana please check #749
