### ISSUE TITLE
The fan disappears when restarting

### ISSUE THREAD

**Issue by Aryqs-Ipsum** [hirschmann/nbfc#727]
Hello, I installed the application and everything is normal, I can change the speed. I restarted my PC and when I get back on the app, I see only the tempertaure. I tried to reinstalled, repair but everything remains buggy, I even have profiles that become unreachable. The only solution I found was to remove all program and AppData folders and resinstall everything. **Only, after each restart, everything must be reinstalled** carefully.
![bug NBFC](https://user-images.githubusercontent.com/45895096/61160115-a6499780-a4fe-11e9-804f-d301a8a16cb7.PNG)
_Laptop : Acer E5 537G, (E5 575G profile) Windows 10 1903_

**Comment by kirkokuev** [comment]
Can confirm, nothing works after restart
