### ISSUE TITLE
Compatibility Report

### ISSUE THREAD

**Issue by Eldurinn** [hirschmann/nbfc#73]
This isn't an issue, but I didn't know where else to submit it. I wanted to let the dev know that this software works very well on my Acer Aspire V13 (V3-372t-5051) using the Acer Aspire E1-522 config. I haven't done much testing using auto mode as of yet though, but manual control works like a dream.

Skylake i5-6200U, IntelHD 520 BIOS 1.02

**Comment by hirschmann** [comment]
Thanks for your report, I added a config for the Aspire V13: 3502e6206fbe2c87056e524b8f53af4f7a9e6168
