### ISSUE TITLE
Config for Lenovo Legion Y530 i7 8th generation

### ISSUE THREAD

**Issue by KingIulian** [hirschmann/nbfc#735]
Is there any config that works with Legion Y530 i7 processor?

Best regards!

**Comment by saturnotaku** [comment]
I would like a config for this model as well.

**Comment by Saganeiro** [comment]
I olso request for config for this model :)

**Comment by mehrdadpfg** [comment]
me also :)

**Comment by lopshopedun** [comment]
Hi there, I'm an owner of Lenovo Legion Y530-15ICH-1060. I've just picked `Lenovo Yoga 510` config and it works fine. I'm pretty satisfied with changed cooling curve. Thanks to @hirschmann. It became more pleasant to use notebook.
