### ISSUE TITLE
to delete

### ISSUE THREAD

**Issue by majkwro** [hirschmann/nbfc#739]
to delete

**Comment by joaomamede** [comment]
Better that way believe me. My Y540 with the new BIOS doesn't put the fans at max right away. It reaches 95degrees in a few seconds. Everyone has been undervolting the cpus to be able to cope with it. I wish I could controls the fans in my laptop thinkpad_acpi doesn't work (only reads values and nothing changes) and there's no module to control them.

**Comment by majkwro** [comment]
dont need anymoew with new bios is better
