### ISSUE TITLE
Dell XPS 15 9550

### ISSUE THREAD

**Issue by eminos** [hirschmann/nbfc#74]
Just a request for the config profile for Dell XPS 15 9550.
Or is there maybe some other profile I could test that might work?
http://www.dell.com/us/p/xps-15-9550-laptop/pd

**Comment by makedir** [comment]
Would be interested in if NBFC supports the Dell XPS 15 9550/9560 too, does it?

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
