### ISSUE TITLE
ASUS ZenBook Pro 15 UX580GE

### ISSUE THREAD

**Issue by Lopicl** [hirschmann/nbfc#742]
I tried every recommended config file but any of them cant read nor write fan speed.

I gave a shot at creating a config but i cant find any documentation on this notebook EC it8225vg-128 by ITE, i also tried looking at DSDT but i am not really sure to what to look at.

Can someone help with this? thanks

**Comment by whdgmawkd** [comment]
i  tried ACPI method call like \_SB.PCI0.LPCB.EC0.ST83 and \_SB.PCI0.LPCB.EC0.ST98 but not working.
even i cant find datasheet for it8225vg.
ec-probe always return all zero values.

**Comment by Kunkerlv** [comment]
Im having this exact issue. If i try probe the EC it always returns 0x00 . Also the EC has no datasheets.

**Comment by UDPSendToFailed** [comment]
UX434FLC has the same EC too, same problem. There is an option to set lower fan speeds in MyAsus application, but that's all, no more control over it.

**Comment by ValerieRen** [comment]
I ran into the same issue with the UX480FD. Any hints would be appreciated.

**Comment by UDPSendToFailed** [comment]
![kép](https://user-images.githubusercontent.com/16057404/91645261-f7d71d80-ea43-11ea-8e23-a3c421509209.png)
