### ISSUE TITLE
ASUS Zephyrus G GA502

### ISSUE THREAD

**Issue by swilwerth** [hirschmann/nbfc#748]
I'm having some trouble to set up my new laptop. The cpu clock runs very slow because the fan speed doesn't seem to control properly, then the laptop runs very slow.
I've been downloaded the latest stable version, and built it on Ubuntu 18.04 with kernel 5.2.7-050207-generic

```
 $ mono nbfc.exe config --recommend
 Asus Transformer 3 Pro

``` 
 

```
$ mono nbfc.exe status -a
Service enabled		: True
Read-only		: False
Selected config name	: Asus Transformer 3 Pro
Temperature		: 58

Fan display name	: Fan #1
Auto control enabled	: False
Critical mode enabled	: False
Current fan speed	: 0.00
Target fan speed	: 100.00
Fan speed steps		: 8

```

This does absolutely nothing.
`mono nbfc.exe set -s 100`

This seems to be related with #592 
Any advice?

**Comment by cherryghost** [comment]
I'm strugging to get it working at all on GA502

**Comment by cherryghost** [comment]
I found the EC chip; IT8225E-128. Unfortunately details are sparse.
