### ISSUE TITLE
Hp pavilion 15-cx0026nt config request

### ISSUE THREAD

**Issue by RiotThanos** [hirschmann/nbfc#751]
There is no config for hp pavilion gaming laptops

**Comment by Juanbanpar** [comment]
Hi, as far as I know your laptop is pretty similar internally with the same year realeased Omen 15 (dc0xxxxx) so you may want to check #749 , if it works for you it will be nice but it's possible that some modifications on values for max or min settings are needed.

**Comment by RiotThanos** [comment]
It's not working

**Comment by Juanbanpar** [comment]
Well, you can check if some configurations are compatible
https://github.com/hirschmann/nbfc/wiki/Search-for-datasheets-or-configs-of-similar-notebooks
If one works (or partially works) it's good, because it will mean it doesn`t requiere modifications or just a little bit.
If not you can check the wiki and try to create one if you want.

**Comment by deathmake317** [comment]
Hey i just got this working on my hp pavilion 15-cx0056wm use the config file from #740 i copied the file and now i have full control over my fan!!!!!

**Comment by RiotThanos** [comment]
> Hey i just got this working on my hp pavilion 15-cx0056wm use the config file from #740 i copied the file and now i have full control over my fan!!!!!

its works thank you but only one fan my pc has two fans

**Comment by deathmake317** [comment]
> > Hey i just got this working on my hp pavilion 15-cx0056wm use the config file from #740 i copied the file and now i have full control over my fan!!!!!
> 
> its works thank you but only one fan my pc has two fans

same actually, seems to be my left fan it works for which is BETTER than before as my fans before would only kick to 100% at 95 degrees which is ABSURD! if anyone figures out how to get the right fan going too would be AMAZING!

**Comment by mtamer93** [comment]
> > > Hey i just got this working on my hp pavilion 15-cx0056wm use the config file from #740 i copied the file and now i have full control over my fan!!!!!
> > 
> > 
> > its works thank you but only one fan my pc has two fans
> 
> same actually, seems to be my left fan it works for which is BETTER than before as my fans before would only kick to 100% at 95 degrees which is ABSURD! if anyone figures out how to get the right fan going too would be AMAZING!

Is there any config file that control two fans.

**Comment by RiotThanos** [comment]
For now no

25 Ara 2019 Çar 14:34 tarihinde mtamer93 <notifications@github.com> şunu
yazdı:
