### ISSUE TITLE
doesn't work with hp pavilion gaming laptop 15-cx0 

### ISSUE THREAD

**Issue by vasil211** [hirschmann/nbfc#753]
pls, this is my final hope.
i have tried every other program and possibility
and i know the fans are not even at 70% when im playing any game, and the cpu is at 94C with the best thermal paste(thermal grizzly kryonaut)

**Comment by vasil211** [comment]
and no, other presets does not work

**Comment by abucodonosor** [comment]
I am not an expert in Windows but I do know HP gaming laptops have an  HP CoolSense option
in power plan settings, which you need to enable, then you can set Fans to always on in BIOS I think.

So at least when you game ( for now ) your fans are full speed all the time.
