### ISSUE TITLE
HP Pavilion 15 cx0013nq

### ISSUE THREAD

**Issue by ghost** [hirschmann/nbfc#757]
This laptop kills me, it`s past 4am in the morning and i can`t fix it. I`d would really love a config for this model as it overheats way too much.

I`ve tryed for some hours to create one by myself, but I just couldn`t do it. None of the recommended config works :(
Also, I have followed the tutorial on how to create your own config, for a moment I thought that I`ve found the registers as 0xF2 and 0xF3, but I can`t modify them, also, maybe I am wrong.

This is my DSDT table: https://ufile.io/ovxwti7t . I searched in it a lot, if you search for "EmbeddedControl" you find something similar with the tutorial, but I couldn`t do the job.

OperationRegion(ERAM, EmbeddedControl, Zero, 0xFF)
			Field(ERAM, ByteAcc, Lock, Preserve)
			{
				Offset(0x5F),	//Offset(95),
				ERBD, 8,
				SMPR, 8,
				, 8,
			}
			OperationRegion(CCLK, SystemIO, 0x1810, 0x04)
			Field(CCLK, DWordAcc, NoLock, Preserve)
			{
				, 1,
				DUTY, 3,
				THEN, 1,
				, 3,
				FTT, 1,
				, 8,
				TSTS, 1,
			}

Recommended configs: (I have tryed them all, none works)
HP Laptop 14-cm0xxx
HP Pavilion 14-v066br
HP Pavilion 17-ab240nd
HP Pavilion dv6 6190
HP Pavilion dv6
HP ENVY x360 Convertible 13-ag0xxx
HP Compaq 15-s103tx
HP Spectre x360 Convertible 13-ae0xx
HP Compaq 615
HP EliteBook Folio 9470m_i5-3427u_bios-F.66
HP Compaq 6735s Turion X2 RM-72
HP Compaq Presario CQ40 Turion X2 RM-74
HP ZBook Studio G3
HP ProBook 4520s
HP ProBook 4720s
HP ProBook 6455b

Oh, except the fact that HP Compaq 15-s103tx changes the speed of my left cooler(as this laptop has 2) but not as it is written there. Any value I put to the slider, nothing changes. Only if I Enable and Disable this config the fan changes rotations.

I will appreciate any help !
Thank you !

**Comment by deathmake317** [comment]
Hey i just got this working on my hp pavilion 15-cx0056wm  use the config file from #740 i copied the file and now i have full control over my fan!!!!!

**Comment by Manuzor** [comment]
I also got this working on my HP Pavilion Gaming 15-cx0005ng just like @deathmake317 said using the config file from #740.

**Comment by GavrusDanut** [comment]
@deathmake317  @Manuzor Wow, it works for me as well ! I can't believe the difference this makes in video games, before I had 90+ degrees often with an average of 85 or so and a lot of throttling, now I get maybe, just maybe, 85 at most and an average of 75 or so. Incredible ! Thanks a lot !
Btw, this one works for the Cpu cooler, is there on the internet something for the Gpu cooler ? Or it would make no difference ? My Gpu has an average between 70-75 I think. Thanks again !
