### ISSUE TITLE
How to start NBFC minimized using scheduler?

### ISSUE THREAD

**Issue by fusk-l** [hirschmann/nbfc#761]
When using scheduler nbfc won't start minimized, i tried the /min arguments which i understand should be default for minimized, that is not working and i don't know which argument nbfc would accept for minimized. 
But why use scheduler, because nbfc is the last app to start, i want it to be the first app to start, scheduler let's me do that.

**Comment by hollowstrawberry** [comment]
I want this too

**Comment by hollowstrawberry** [comment]
You do it with the -tray parameter
