### ISSUE TITLE
Config for HP Pavilion Laptop 15-cs1xxx

### ISSUE THREAD

**Issue by Rocket1111** [hirschmann/nbfc#769]
Hello guys,
I've been trying to setup my config for hours, but I'm not able to get the EC/DSDT. Also none of the available configs work for my laptop. Yesterday the config"HP Pavilion 17-ab240nd" kinda worked, but there were some differences between the shown cpu temperature and fan speed compared to the real ones. My Notebook does have a HP 856A motherboard, using an I5-8265U and an GTX 1050.
I tried everything to fix those annoying fans. The one who helps me to fix my problem will get a 5$ amazon voucher. :-)

**Comment by Corebull** [comment]
Hey, please look into my issue. The 15-cs and 15-cw series are pretty similar. Maybe we can find a solution together! 

https://github.com/hirschmann/nbfc/issues/770

**Comment by liudve612** [comment]
Did you manage to fix this?
