### ISSUE TITLE
HP ProBook 4540s profile missing, possible fix

### ISSUE THREAD

**Issue by TomKTW** [hirschmann/nbfc#77]
I've noticed that you have removed profile for HP ProBook 4540s due to embedded controller issue [https://github.com/hirschmann/nbfc/issues/3] (keyboard fails to work after some time).

When I did use new profile that has been removed from repository, I've ended up with sensor faking low temperature from 20°C to sudden 90°C+ and ending up with instant shutdown due to false alarm of overheat. Fan speed at 0% ends up with 220%+ of speed. Along with that, I've also got issues with keyboard not working.
After checking EC, something keeps shifting right everything by 2 characters, causing unexpected results. I'm not sure what's causing that.

However, I've managed to get the old profile of NBFC configuration that doesn't seem to cause those issues anymore. Sensors are normal, fan speed is also okay, keyboard works.

Though, I'm getting following issues in event viewer:

"The embedded controller (EC) did not respond within the specified timeout period. This may indicate that there is an error in the EC hardware or firmware or that the BIOS is accessing the EC incorrectly. You should check with your computer manufacturer for an upgraded BIOS. In some situations, this error may cause the computer to function incorrectly."
This issue occurred insanely high amount of times with new profile, but it didn't occur often when using old profile.

"The embedded controller (EC) returned data when none was requested. The BIOS might be trying to access the EC without synchronizing with the operating system. This data will be ignored. No further action is necessary; however, you should check with your computer manufacturer for an upgraded BIOS."
This issue occurs randomly, not affecting the system.

I've uploaded zipped file with old XML profile:
[HP ProBook 4540s.zip](https://github.com/hirschmann/nbfc/files/204954/HP.ProBook.4540s.zip)

**Comment by hirschmann** [comment]
Thanks for the config.
I added it to the repo: 364b91940d109f747a71cd23069896fab0be1511

You can ignore the issues in the event viewer.
Windows just complains that NBFC bypasses the ACPI subsystem ;)
