### ISSUE TITLE
HP Pavilion 15-cw / My findings.

### ISSUE THREAD

**Issue by Corebull** [hirschmann/nbfc#770]
Hey,
I purchased an "HP Pavilion 15-cw1106ng" and guess what, I wan't to increase the Temp. when the Fan starts to kick in. I share my findings so all Pavilion Users could come together to find the final Solution.

I spend the last 3 Days with ec-probe and DSDT reading. I've never done it before so my findings so far, makes me a litte bit proud :)

So:

0x58 = 88 CPU Temp. :
- If you write low Temps, like 10C or 20C (Basically everything from 39C and Below) to it, the Fan stops spinning for a small period.

0x5A = 90 GPU Temp.:
- Writing low Temps to it does not have a affect, since there is no dedicated GPU Fan.

0xAC = FAN Target Speed Level:
- Takes Values from 00 to 07 (with 00 lowest & 07 highest setting)
- The Fan reacts, but the EC wants to apply it's own Target Speed
- If you set EC Poll Interval to 500ms you get Better results
- You can't stop the Fan if you have Temps >= 44 C but you can get the Fan to Max RPM when you set it to 07 even when your CPU is cool. And yes, I disabled "Fan Alway On" in my BIOS

Now it gets Funky:

0x95 = HP Coolsense Stuff?
So i installed the newest Official HP CoolSense Driver Version from the Official Website. When you Activate CoolSense the Offset(0x95) Turns to 01, and when you Disable it, to 00. Other than that, it doesn't do or help much. I only discovered that it lets the Fan "Gitter" when put much load on the CPU (Cinebench R15).

So there must be a Way to Control the Fan, Since CoolSense has an Effect on it.

What is missing?

We need to find the Offset where the EC switches to Manual Mode and back, so we can apply the Target Fan Speed. Any help would be appreciated!!

Could anyone who can actually read ASL, look into my DSDT? I looked EVERYWHERE but didn't even found the Offset(0xAC) in it. I need the EC Manual mode so bad.

https://drive.google.com/open?id=1zM0c85ZmcBgPOpdCbrTDx1LWJ33m4RIy

**Comment by liudve612** [comment]
Did you find anything?

**Comment by Corebull** [comment]
> Did you find anything?

Sadly nothing at all.
