### ISSUE TITLE
Notebook Fan Control crashing

### ISSUE THREAD

**Issue by dddwilliams** [hirschmann/nbfc#771]
I have an Asus G751JY running the absolute latest Windows 10 Build, it works loads with windows but if i got to click on the tray icon it crashes, i believe this is more an issue with the latest windows 10 build and not the app or the laptop specifically can you fix this and is there anything i can provide you to help?

Regards
David

**Comment by polki** [comment]
I'm having the same issue. NBFC was working perfectly, over the past 2 years it stopped working once but updating it fixed the problem. Now I believe the latest Windows 10 updates are preventing it from working properly. It appears the service is running but the application cannot. Found crash log events attached.
<a href="https://ibb.co/7yCQ3gV"><img src="https://i.ibb.co/7yCQ3gV/Annotation-2019-10-22-081428.png" alt="Annotation-2019-10-22-081428" border="0"></a>

**Comment by polki** [comment]
I had the same issue on my G752vy, after dealing for the past year I've just tried to fix again, BIOS update fixed my issue, look into that guys if you haven't had an update for a while.
