### ISSUE TITLE
Eventual Flatpak/PPA Support?

### ISSUE THREAD

**Issue by OdinVex** [hirschmann/nbfc#774]
Would very much like to see Flatpak/PPA releases if possible for us non-Snap/AUR users. This feature request is somewhat a duplicate of #764.

Many thanks for the GL702ZC configuration.

**Comment by rijnhard** [comment]
THis would be great, I dont think this has gone away (more for flatpak than snap imho)

**Comment by OdinVex** [comment]
I doubt Flatpak/Snap would allow MSR reads/writes. I ended up writing my own tool for my laptops instead.
