### ISSUE TITLE
Peformance decrease

### ISSUE THREAD

**Issue by tarakula** [hirschmann/nbfc#776]
hi.. im using acer e5 476G. but my device doesnt on the support list so im using e5 475G option in the app and it work, but when i try to playing games. its look like stuttering or lag, can you make e5 476G on support list or fix the lag issue? i tested on elsword game.

**Comment by renanwp2** [comment]
I know that is not completely right way. What I  did? I looked my motherboards on the internet and then compared with the nbfc --recommend motherboards. If the other motherboard looks equal, then I tried that one and did a reverse engineer approach to see if it worked; I stopped (you can put the fan at 100% as well) for a moment my CPU and put it on load. If the CPU is yet stopped even on medium load then it was correct! Yes, is too much work, but I think I could get my model in 20 hours of trials. Luls

**Comment by renanwp2** [comment]
Duda, I am suffeting the same problem! I suppose that the system is acusing Thottling! If you are having problems try to put Criticam temperatures at 100°C. I reainstalled my sistem, but Im suffeting the same problem as you, unfortunately.
