### ISSUE TITLE
Fujitsu e754 i7

### ISSUE THREAD

**Issue by keven1239** [hirschmann/nbfc#78]
I have a problem with the fan, he's running all time and its very disturbing. I sent vial canada post my laptop to Fujitsu repair center. 40 day later. I received my laptop with the same problem. grrrrrrrrrrr. 
When CPU is 0% the temperature is 45Celcius
When the CPU is 100% the temperature is 100Celcius

Sometime I have 100Celcius at 40% CPU...... I don't understand.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
