### ISSUE TITLE
Config File for thinkbook 13s-IWL

### ISSUE THREAD

**Issue by nicolasjafelle** [hirschmann/nbfc#785]
**Is your feature request related to a problem? Please describe.**
Trying to create a config file for the Lenovo Thinkbook 13s-IWL could not make it at the moment. One of the big concerns is that the laptop has two fans and is much complex to find the read registers and write registers.

**Describe the solution you'd like**
If someone could help me creating this config file I will really appreciate

**Additional context**
This is a sample taken with ec-probe. I am not sure if it is helpful

[EC-PROBE SAMPLE](https://i.postimg.cc/pTXPpgnw/Capture.png)

[EC-PROBE SAMPLE LARGER](https://i.postimg.cc/gjMDXv9K/report.png)

**Comment by maximdorko** [comment]
I would like to request help as well. I have ThinkBook 13s-IMl, but same here, EC Probe doesn't help at all. Same config, 2 fans, no luck with EC data.
