### ISSUE TITLE
Support for Ice Lake

### ISSUE THREAD

**Issue by dn00** [hirschmann/nbfc#788]
I'm getting "Failed to access CPU temperature sensors" in the logs. Error happens with similar issues where architecture isn't supported in the code. Any plans to add Ice Lake support?

**Comment by dn00** [comment]
Added a case for 0xFE (Ice Lake code) in IntelCPU.cswith Coffee Lake's case logic and it's now working on i5-1065g4. Quick fix for myself nbfc is updated.

  ```
case 0x5C: // Intel ApolloLake
                microarchitecture = Microarchitecture.ApolloLake;
                tjMax = GetTjMaxFromMSR();
                break;			    
case 0xAE: // Intel Core i5, i7 8xxxx (14nm++)
                microarchitecture = Microarchitecture.CoffeeLake;
                tjMax = GetTjMaxFromMSR();
                break;
case 0xFE:
                microarchitecture = Microarchitecture.CoffeeLake;
                tjMax = GetTjMaxFromMSR();
                break;
default:
                microarchitecture = Microarchitecture.Unknown;
                tjMax = Floats(100);
                break;
            }
```

**Comment by hirschmann** [comment]
Thank you for the info! I'd like to add Ice Lake support to NBFC as soon as possible :)
May I ask where you found the CPU model id (0xFE)?

According to [WikiChip](https://en.wikichip.org/wiki/intel/cpuid) and the [Linux kernel](https://github.com/torvalds/linux/blob/master/arch/x86/include/asm/intel-family.h) the Ice Lake (extended) model id should be 0x7D/0x7E.

Could you please download [Libre Hardware Monitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor), create a report (file --> save report) and attach it here?

**Comment by dn00** [comment]
You're right. The model Id is 0x7E for Ice Lake mobile cpus. The original post was made pretty late.

I'll be able to post a report in a couple hours.

**Comment by dn00** [comment]
Here's the report. Note that I don't see any readings for CPU temps.

[Uploading HP 14-dq1033cl i51035g4.txt…]()

**Comment by hirschmann** [comment]
Thanks for the report. I've added support for Ice Lake: 5fde12a32c32746b0314c86b9047f73cc00a873e
Give it a try: https://ci.appveyor.com/project/hirschmann/nbfc/build/artifacts

Hope it works as expected :)

**Comment by dn00** [comment]
Working great!

**Comment by PoNdaBear** [comment]
> [HP 14-dq1033cl i51035g4.txt](https://github.com/hirschmann/nbfc/files/3867154/HP.14-dq1033cl.i51035g4.txt)
> Here's the report. Note that I don't see any readings for CPU temps.

Hello, I have this same model with just 12gb ram instead of 4gb. Can you help with loading opencore? Having some issues with reboots after installation or sharing your efi?
