### ISSUE TITLE
proplem with nbfc hp 4520s

### ISSUE THREAD

**Issue by magyfan** [hirschmann/nbfc#79]
i used nbfc 1.4.2 with win7 on my laptop hp 4520s
it's work great but have one problem 
when i put the Fan speed to 2.5% it works in max speed
when i put the Fan speed to 100% it works in min speed
so if i put it on auto ...
when the temp getting hotter the speed of the Fan getting slower!!!!
how can i fix that ?????
plz help

**Comment by hirschmann** [comment]
In your config, just swap MinSpeedValue and MaxSpeedValue.
See: https://github.com/hirschmann/nbfc/wiki/Basic-fan-configuration
