### ISSUE TITLE
Config request for Asus Zenbook UX533FD (A8079T) Intel Core i5

### ISSUE THREAD

**Issue by AleksandrovM** [hirschmann/nbfc#790]
Hello,

I download the last version of NoteBook FanControl but I didn't find my Asus Zenbook  UX533FD . Any other Asus models configs do not work

Can someone help please create the configuration file? thanks !

**Comment by bodomalo** [comment]
Is the fan on the Zenbook UX533FD on all time? Or is it quiet when you just use it for office/email/websites ? (when I say quiet, I mean complete quiet in a absolute quiet room...not like: yeah okay it does not bother me)

I bought the MSI PRESTIGE right now. With some hacks I was able to make it quiet when it is only used a little bit.

I am interested in creating nbfc profiles too.

**Comment by AleksandrovM** [comment]
> Is the fan on the Zenbook UX533FD on all time? Or is it quiet when you just use it for office/email/websites ? (when I say quiet, I mean complete quiet in a absolute quiet room...not like: yeah okay it does not bother me)
> 
> I bought the MSI PRESTIGE right now. With some hacks I was able to make it quiet when it is only used a little bit.
> 
> I am interested in creating nbfc profiles too.

Fan is quite until I run something CPU-bound. But even after load is gone - the fan is running for half of a hour

**Comment by CaliforniaMountainSnake** [comment]
I also need this config
