### ISSUE TITLE
ASUS ROG G731GW Support

### ISSUE THREAD

**Issue by torrycrass** [hirschmann/nbfc#802]
**Is your feature request related to a problem? Please describe.**
Looking for information on if anyone has gotten ASUS ROG G731GW (or likely anything in the series) working with NBFC? I have tried to figure out how to detect the registers and create a config but have failed pretty badly so far.

If not already in the works, I'd like to request support for it or if someone has a step-by-step walk through of how to get the information needed I'll be happy to try it.

**Describe the solution you'd like**
Support in NBFC for ASUS ROG G731GW model laptops

**Comment by RoiIam** [comment]
hey, did you manage to get the EC controller type?

**Comment by torrycrass** [comment]
I did not, I'm not sure how to find this information out.
