### ISSUE TITLE
Problem with HP ProBook 4720s / W7

### ISSUE THREAD

**Issue by klusik** [hirschmann/nbfc#81]
Hi, I have a problem, I've instaled the 1.4.2 version, it worked well -- under I've restarted PC, then I cannot choose the right model of my PC and start "fan control service" ;( So it doesn't work anymore, what happened? :-)

**Comment by hirschmann** [comment]
Give NBFC 1.5.3 a try. There were many stability improvements since 1.4.2 and 1.5.3 creates more useful logs, which makes it easier to track down problems like this.
