### ISSUE TITLE
Intel i5-10210U (Asus zenbook 15 533FTC)

### ISSUE THREAD

**Issue by Oxygen2c** [hirschmann/nbfc#816]
Hey, I have asus zenbook 15 533FTC with i5-10210 processor, can't control anything on it.  Is comet lake processor supporting possible? Fans on my zenbook are very loud.

**Comment by dgw** [comment]
I've been digging around in the DSDT for my UX533FD with no luck (I'm way out of my depth with this ACPI/AML stuff; it's entirely new to me). Found this issue, but I'm guessing you aren't even working on the same notebook? i5-10210 sounds like a UX534FTC, the next model year after what I have, if you want to update the issue title.
