### ISSUE TITLE
HP Pavilion dv6 Fail

### ISSUE THREAD

**Issue by sqgl3** [hirschmann/nbfc#82]
GUI reflects whatever I manually set the speed to but I cannot hear the fan changing speed. In fact when I set it to 0% the fan is not turned off (and note that I had changed min speed to zero in config).

Could the problem be that I replaced the original fan with a non HP part or is that irrelevant because the work is done in a sensor on the mobo?

**Comment by sqgl3** [comment]
A [youtube user says](https://www.youtube.com/watch?v=3BiMA8Bb2Cc&google_comment_id=z12jsrqbsueag5kiw04ccdjabq2isvepv1c) it does work with his DV6 (including hearing the fan change pitch).

**Comment by ranyyy** [comment]
I am also facing this issue :(

**Comment by ranyyy** [comment]
It does change pitch when I click enable but I change the fan speed.

**Comment by ranyyy** [comment]
Target fan speed: 100% (Critical)
Do you get that too?

**Comment by ranyyy** [comment]
If you got the critical msg just change the config critical temp to something higher than what you are experiencing (I chose 90C). This is really not an issue in my opinion :). Just be sure to click apply after you change the config.

**Comment by ranyyy** [comment]
Please reply back if it helped.

**Comment by ranyyy** [comment]
@sqgl3 also to turn off fan you will have to disable "fan always on" in BIOS :)
