### ISSUE TITLE
How to control the GPU fan an hp pavilion gaming cx0xxx laptop??

### ISSUE THREAD

**Issue by jhonsitox** [hirschmann/nbfc#821]
I have a nbfc and I could control the cpu fan with the configuration HP Notebook 15-ba010ng, but the GPU fan doesn't control. I read the other issues about it and that moment don't the way for fix it.

Excuse me for my poor English, because I'm Colombia and my native language is Spanish.

**Comment by Jusaw8663** [comment]
ddd
