### ISSUE TITLE
After using NBFC battery dont charge when AC is plugged

### ISSUE THREAD

**Issue by AdamKoc** [hirschmann/nbfc#825]
Hello.
I have config on Acer Helios 300 PH351-52
Config obviously works, but as soon as I start it it stops charging the laptop. As soon as I remove the AC adapter, the battery drops to 96 percent and once I plug in the battery is 100% suddenly, but the laptop will no longer charge 96% or less because it discharges. can this problem cause a given config?
And if so is it possible that this config has other values that my NTB does not fit exactly I need to create a new one for myself?

**Comment by Maxinator500** [comment]
Same way!
That Acer config causes power loss on the HP 15-baxxx laptop series. During my thoughtless (but successful) sorting of configs, I came across this one and the battery stopped charging. So, whenever power indicator showed a full charge it was any percent.
A lite reset by holding power button benefited and all changes dissapeared.
If you haven't done it yet, use ec-probe witho those keys in the config to check everyone's purpose.
