### ISSUE TITLE
NBFC Does Not Read CPU Temperature on HP x360 m6

### ISSUE THREAD

**Issue by jmgelman** [hirschmann/nbfc#827]
For some reason, the temperature in NBFC is **always** displaying as 0 C, despite that obviously not being the case.

![screenshot](https://i.imgur.com/YqEzsmF.png)

If needed, [here is a link to my system information](https://pastebin.com/raw/gtWv4fMv) from Open Hardware Monitor.

Any help would be greatly appreciated. Thank you.

**Comment by sensus261** [comment]
I had this problem aswell when I tried on my laptop.
The solution was to clone the repo and rebuild the whole project, because the latest release (Apr 14, 2019) is dating way back Ice Lake (in my situation) was released.

Wish you good luck :)
