### ISSUE TITLE
Unstoppable fan in HP 15-ba

### ISSUE THREAD

**Issue by Maxinator500** [hirschmann/nbfc#831]
### I would like to share one regist for HP-based laptop
If you put 1 on 189 by EC-probe, then your cooler will work **EVERYTIME** on full.

**Comment by Mattwmaster58** [comment]
This isn't really an issue...

**Comment by Maxinator500** [comment]
> This isn't really an issue...

I bring it in issues because someone should make percents control real.

**Comment by Maxinator500** [comment]
> This isn't really an issue...


Thank you for your comment. I just wanted to know the registers. Now everything has worked out, I’ll only talk about 189, which in the value 0 or 1 disables speed control by the temperature sensor. Accordingly, I will make the issue more specific.
