### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by Slykk** [hirschmann/nbfc#833]
the windows are shown blank, i have tried both latest version and beta version, between each did reinstall completely, as well as powershell check.
the degrees showed before but after reinstall shows as 0 (due to probably not activated when installing).

using asus zenbook ux430

**Comment by sensus261** [comment]
I had this problem aswell when I tried on my laptop.
The solution was to clone the repo and rebuild the whole project, because the latest release (Apr 14, 2019) is dating way back Ice Lake (in my situation) was released.

Wish you good luck :)

**Comment by Slykk** [comment]
not quite sure i understand,
im using the regular stable installation

**Comment by sensus261** [comment]
Uninstall current installed nbfc
Then you have to clone this repository and rebuild the code again using a software like Visual Studio.
After you release it you need to reinstall it normally.
Enjoy
