### ISSUE TITLE
Alienware M18x R2 manual register

### ISSUE THREAD

**Issue by JD21P** [hirschmann/nbfc#839]
Hi, I have an Alienware M18x R2 which has an ENE "kb3930qf a1" EC.

I have successfully found the registers to control the fans and created a config which is working but have been unable to find the registers for manual mode, here is the datasheet for this EC:
https://www.bulcomp-eng.com/datasheet/KB3930.pdf

Would someone be able to help me find the correct registers for manual mode? :-)

Currently the fans slow down and speed up every few seconds because the EC is trying to take over, I have set the polling down to 100 which is better but still not enough. Thanks :-)

**Comment by Ashymad** [comment]
Could you share your config? It would be useful to know what you have already discovered.

**Comment by JD21P** [comment]
Here is what I have which controls the GPU and CPU fans individually.
https://pastebin.com/dQMMuQ3a

Once nbfc is able to implement GPU temperature then I can get the GPU temp threshold to work, but atm GPU temp is set to react to CPU temp, or just set manual GPU fan speed.

**Comment by JD21P** [comment]
> Could you share your config? It would be useful to know what you have already discovered.

Here is what I have which controls the GPU and CPU fans individually.
https://pastebin.com/dQMMuQ3a

Once nbfc is able to implement GPU temperature then I can get the GPU temp threshold to work, but atm GPU temp is set to react to CPU temp, or just set manual GPU fan speed.

**Comment by JD21P** [comment]
Any luck? :-D

**Comment by Ashymad** [comment]
Well, yeah, I hoped that the config will work for my laptop, MSI PE60, because it uses the same EC, however it seems that the registers are mapped differently :(

**Comment by JD21P** [comment]
The way I got my fans to work was to apply every profile included in the program until my fans started spinning, I found that the only MSI laptop included in the program atm used the same fan location as my laptop, from there I was able to fine tune it, but can't find the manual fan mode trigger. :-)
