### ISSUE TITLE
HP Pavilion Gaming Notebook - 15-ak100nx

### ISSUE THREAD

**Issue by Axtreme1** [hirschmann/nbfc#843]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
If you're about to request a config for a specific notebook model, please follow these steps before creating a new issue: [**Config requests**](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)

**Describe the solution you'd like**

**Additional context**

**Comment by tekoszi** [comment]
I would also need one for 15-cx0060nw
