### ISSUE TITLE
ec-probe monitoring has no output

### ISSUE THREAD

**Issue by Adeptius** [hirschmann/nbfc#846]
![image](https://user-images.githubusercontent.com/19186103/77473576-55749780-6e1e-11ea-9954-33562e8a86de.png)
After run  ec-probe.exe monitor with admin rights it has no output. Just one "monitoring..." text only

 - operating system Windows 10 1909 x64
 - NBFC version 1.6.3

**Comment by Adeptius** [comment]
Little googling shows that RWEverything does not work too
![image](https://user-images.githubusercontent.com/19186103/77475113-f5332500-6e20-11ea-84a3-f0f68ea71042.png)

**Comment by ghost** [comment]
Same issue Asus VivoBook Pro 17
BIOS :  X705FD.314

Windows 10 1809 x64 
NBFC version 1.6.3

so far i have tried:

Hyper-Threading (on/off)
Intel Virtualization (on/off)
Intel AES-NI (on/off)
VT-D (on/off)
Memory Integrity (off/on)

**Comment by citizenserious** [comment]
Same issue here: https://github.com/hirschmann/nbfc/issues/848

**Comment by citizenserious** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/19186103/77473576-55749780-6e1e-11ea-9954-33562e8a86de.png)
> After run ec-probe.exe monitor with admin rights it has no output. Just one "monitoring..." text only
> 
>     * operating system Windows 10 1909 x64
> 
>     * NBFC version 1.6.3

Monitor the EC registers and save a report: ec-probe.exe monitor -r report.txt
If no timespan is provided, ec-probe will run until you cancel it by pressing Ctrl + C.

**Comment by Adeptius** [comment]
> Monitor the EC registers and save a report: ec-probe.exe monitor -r report.txt
> If no timespan is provided, ec-probe will run until you cancel it by pressing Ctrl + C.

i run "ec-probe.exe monitor -r report.txt" after few seconds console just going blank and thats it... no any report.txt files appear. 
If i press ctrl+с than it show stack trace.
![image](https://user-images.githubusercontent.com/19186103/78831850-fd7b8a80-79f2-11ea-8e21-3e2bcbdd62c4.png)
It means "Unhandled exception: The path cannot be empty"

**Comment by ghost** [comment]
> > Monitor the EC registers and save a report: ec-probe.exe monitor -r report.txt
> > If no timespan is provided, ec-probe will run until you cancel it by pressing Ctrl + C.
> 
> i run "ec-probe.exe monitor -r report.txt" after few seconds console just going blank and thats it... no any report.txt files appear.
> If i press ctrl+с than it show stack trace.
> ![image](https://user-images.githubusercontent.com/19186103/78831850-fd7b8a80-79f2-11ea-8e21-3e2bcbdd62c4.png)
> It means "Unhandled exception: The path cannot be empty"

Absolutely the same issue i also tried to put Windows in Test mode but that had no effect.
NBFC Shows my CPU temp without a problem.
Some Configs show fan speed but its incorrect mostly around 150-160%

**Comment by Adeptius** [comment]
> NBFC Shows my CPU temp without a problem.

For me too.

> Some Configs show fan speed but its incorrect mostly around 150-160%

Shows only or you can set some value?

**Comment by ghost** [comment]
> > NBFC Shows my CPU temp without a problem.
> 
> For me too.
> 
> > Some Configs show fan speed but its incorrect mostly around 150-160%
> 
> Shows only or you can set some value?

I can click enable and move the slider but nothing happens i find it weird that it even shows anything different than 0 on some profiles because the whole EC is only 00.

I was able to find what EC chip my laptop has it might be a good idea to post your also.

ITE
IT8995E-128
1735-DXS
S00G3A

**Comment by Adeptius** [comment]
EC chip? Do you mean that need to disassemble laptop to find it?

**Comment by ghost** [comment]
> EC chip? Do you mean that need to disassemble laptop to find it?

No just go on google and look for a dissasembly video of your laptop model and look for a chip that has any of these names on it. 
ITE
Microchip/SMSC
Nuvoton
Renesas

I also found that my chip is not listed as supported on the RWeverything website :(
