### ISSUE TITLE
Request for config on asus UX433FN

### ISSUE THREAD

**Issue by Tedward765** [hirschmann/nbfc#848]

**Comment by citizenserious** [comment]
This would be just awesome!

**Comment by citizenserious** [comment]
I found out, that the chip is a iTE, but unfortunately I couldn't find a high res picture to read the model number. So I decided to go to the next step and analyze the DSDT. The DSDT editor states an Error Message: "Pairs of brackets don't match. Tree not updated." and in the List it says "Could not parse ACPI tables, AE_ALREADY_EXISTS". So I gave RWEverything a try, I could get out a reading of the ACPI table at the DSDT section but I stuck there because I don't understand it enough, I even found some parts which a "FAN" is mentioned for example: 

	Method(RFAN, 1, NotSerialized)
		{
			If(\_SB.PCI0.LPCB.EC0.ECAV())
			{
				Store(\_SB.PCI0.LPCB.EC0.ST83(Arg0), Local0)
				If(LEqual(Local0, 0xFF))
				{
					Return(Local0)
				}
				Store(\_SB.PCI0.LPCB.EC0.TACH(Arg0), Local0)
				Divide(Local0, 0x64, , Local0)
				Add(Local0, One, Local0)
				If(LLessEqual(Local0, 0x3C))
				{
					Store(Local0, FANS)
				}
				Else
				{
					Store(FANS, Local0)
				}
			}
			Else
			{
				Store(Zero, Local0)
			}
			Return(Local0)

I can't get much out of the DSTD and stuck there, I am just a user and did my best so far. could really use some help here (: Thanks a lot. I would paste the whole DSDT here but I don't know if there are sensitive information in it.

![cooling-2](https://user-images.githubusercontent.com/62773866/78154837-068dba00-743d-11ea-931b-15266b0fd217.jpg)
![DSDTEditor1](https://user-images.githubusercontent.com/62773866/78154844-07bee700-743d-11ea-95a7-196db88f4aa4.PNG)
![DSDTEditor2](https://user-images.githubusercontent.com/62773866/78154846-07bee700-743d-11ea-8080-0493fd2400f0.PNG)

**Comment by citizenserious** [comment]
[DSTD.txt](https://github.com/hirschmann/nbfc/files/4416896/DSTD.txt)

**Comment by citizenserious** [comment]
[DSTD_ASUS-ZenBook-14-UX433FN.txt](https://github.com/hirschmann/nbfc/files/4416902/DSTD_ASUS-ZenBook-14-UX433FN.txt)

**Comment by UDPSendToFailed** [comment]
I don't know if this helps or not, my UX434FLC has an ITE IT8225VG-128 EC. Found a review with high-res pictures, their motherboards look similar.

![kép](https://user-images.githubusercontent.com/16057404/78435151-89e62000-7676-11ea-8e0c-a4ef1de7c931.png)

**Comment by citizenserious** [comment]
> 
> 
> I don't know if this helps or not, my UX434FLC has an ITE IT8225VG-128 EC. Found a review with high-res pictures, their motherboards look similar.
> 
> ![kép](https://user-images.githubusercontent.com/16057404/78435151-89e62000-7676-11ea-8e0c-a4ef1de7c931.png)

Thanks you very much for your help (: unfortunately I can't find the data sheet.

**Comment by citizenserious** [comment]
I dumped all EC registers into a file and that's what I got out :(

   | 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
---|------------------------------------------------
00 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
10 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
20 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
30 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
40 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
50 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
60 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
70 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
80 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
90 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
A0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
B0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
C0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
D0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
E0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
F0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

I couldn't get an result out of the ec-probe.exe monitor -r report.txt
It states: 

Unhandled Exception: System.ArgumentException: Path cannot be the empty string or all whitespace.
   at System.IO.Directory.CreateDirectory(String path)
   at NbfcProbe.Program.SaveRegisterLogs(String path, RegisterLog[] registerLogs, Boolean clearly, Boolean decimalFormat)
   at NbfcProbe.Program.<>c__DisplayClass11_0.<ECMonitor>b__0(Object sender, ConsoleCancelEventArgs e)
   at System.Console.ControlCDelegate(Object data)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
PS C:\Program Files (x86)\NoteBook FanControl>

I am absolutely lost now.

**Comment by citizenserious** [comment]
I have looked at the website of RWeverything "IT8225VG" is not supported.

**Comment by UDPSendToFailed** [comment]
> 
> 
> I dumped all EC registers into a file and that's what I got out :(
> 
> | 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
> ---|------------------------------------------------
> 00 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 10 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 20 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 30 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 40 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 50 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 60 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 70 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 80 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 90 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> A0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> B0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> C0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> D0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> E0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> F0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 

Same here, the EC looks completely empty. Maybe it uses a different port number at EC_SC / EC_DATA?

![kép](https://user-images.githubusercontent.com/16057404/78938666-e43a1300-7ab2-11ea-828f-8efbf317cb27.png)

**Comment by Killerbockwurst** [comment]
I also would like to change the fan values! I´m not able to do it myself, but could send information about the hardware or test something

**Comment by dpaulo** [comment]
UX433FN owner here. I am lost with the same problem. Could not get any result no matter how hard I try. Any updates on this issue?

**Comment by UDPSendToFailed** [comment]
🅱
