### ISSUE TITLE
How to control two fans on my Thinkpad X1 Extreme Gen 1

### ISSUE THREAD

**Issue by nhtha** [hirschmann/nbfc#851]
My laptop is Lenovo Thinkpad X1 Extreme gen 1.
It has 2 fans, in some topics, I found that two fans use the same register (https://www.reddit.com/r/thinkpad/comments/a94kev/tpfancontrol_for_x1_extreme_i_can_make_it_work/).
here is code from TPFancontrol:
#define TP_ECOFFSET_FAN_SWITCH	(char)0x31
#define TP_ECOFFSET_FAN1	(char)0x0000
#define TP_ECOFFSET_FAN2	(char)0x0001
#define TP_ECOFFSET_FAN		(char)0x2F	// 1 byte (binary xyzz zzz)
#define TP_ECOFFSET_FANSPEED 	(char)0x84 // 16 bit word, lo/hi byte
#define TP_ECOFFSET_TEMP0    	(char)0x78	// 8 temp sensor bytes from here
#define TP_ECOFFSET_TEMP1    	(char)0xC0 // 4 temp sensor bytes from here

How can I read and control both 2 fans with NBFC?

Many thanks,
Nguyen Huu Trung Ha

**Comment by ppo-38** [comment]
Good question ! I have the same problem with my Thinkpad P53. I can switch between left and right fan with ec-probe.exe program (thanks to your message) but how can we control the two fans simultaneously ? with ec-probe.exe and mostly with nbfc ?

**Comment by ppo-38** [comment]
Maybe one possibility would be to add a new option in NBFC to configure the registry for this switch? In the "Fan Configuration" screen under the "Read Register" option.

@hirschmann, is there another possibility to configure it in the actual version (1.6.3) ?

Thank you.

**Comment by ppo-38** [comment]
For information, I have created a specific issue to follow this common point : 
https://github.com/hirschmann/nbfc/issues/905
