### ISSUE TITLE
I confirm T540p's config work on T440p, but I'm wondering could it be used to reduce the minimum fan speed?

### ISSUE THREAD

**Issue by dalao3** [hirschmann/nbfc#858]
There is no T440p config yet. I tried the T540p's config and it works. https://github.com/hirschmann/nbfc/blob/master/Configs/Lenovo%20ThinkPad%20T540p.xml

However, there is an issue that even level 1 (the register is 0x01) is very noisy. So I'm wondering could the program to constantly set level 0 and level 1, like PWM to reach a level of 0.5 to reduce the fan noise?

I just made a quick python code, but the time seems need to be fine tuned.

```
import subprocess
import time
   
cmdSet0 = "ec-probe.exe write 47 0x00"
cmdSet1 = "ec-probe.exe write 47 0x01"
while 1:
    p = subprocess.Popen(cmdSet1, stdin = subprocess.PIPE, stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell = True)
    time.sleep(0.5) # sleep
    p = subprocess.Popen(cmdSet0, stdin = subprocess.PIPE, stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell = True)
    time.sleep(0.8) # sleep
```

**Comment by matedon** [comment]
Sound's good. Does it work? Did you implemented? How about the fan noise and the temp?
