### ISSUE TITLE
[Config Req] NBFC for Acer Spin 3 SP314-51 (2018)

### ISSUE THREAD

**Issue by dantfusie** [hirschmann/nbfc#873]
Does anyone have a config for the Acer Spin 3 (2018)?

Would be appricated!

**Comment by FlyGst** [comment]
> Does anyone have a config for the Acer Spin 3 (2018)?
> 
> Would be appricated!

Please make screenshot with RWEverything https://github.com/hirschmann/nbfc/wiki/Probe-the-EC%27s-registers
