### ISSUE TITLE
Best method to find which EC register does what

### ISSUE THREAD

**Issue by softlion** [hirschmann/nbfc#88]
A Wiki entry on the method to use to find which ec register control a fan speed and which one report temperature and which one does another thing would be nice.

I used the ec tool on asus ux303 to find out how to control the fan speeds. Some register values are changing at each probe, so they should be temperature read registers.
The current fan is full speed, meaning the register controlling this fan speed should be non zero and somehow between 80 and FF.

It still leaves lots of registers to check.
What is the best method to find it ?

**Comment by hirschmann** [comment]
See https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by dataslug1** [comment]
Hello I found this by searching UX303 as this is my notebook, which has suddenly started switching fan to full despite no load.  Were you ever able to get it working with NBFC please?  Many thanks!

**Comment by softlion** [comment]
No :)

**Comment by dataslug1** [comment]
Disappointing but at least you saved me a few wasted hours 😄
