### ISSUE TITLE
Fan curve controls

### ISSUE THREAD

**Issue by gotumjee** [hirschmann/nbfc#883]
I'm using the HP Pavilion 15 Gaming laptop (cx0056wm) and thanks to the configuration made by Webloft, I can finally combat thermal throttling.
However, the fan's tuning is rather aggressive on Auto, quickly ramping up to 70-80% (which it had never reached before in its lifetime, except maybe during BIOS updates) when merely opening applications.

Would it be possible to finetune the temperatures at which the fans should start ramping up and so on?

**Comment by hirschmann** [comment]
Sure, you can edit the fan curve as you like: https://github.com/hirschmann/nbfc/wiki/Temperature-threshold

**Comment by gotumjee** [comment]
Oh right, thanks for your help (and the software too)!
