### ISSUE TITLE
Vanguard compability 

### ISSUE THREAD

**Issue by emrecangrbz** [hirschmann/nbfc#884]
Hello, I would like to point out that Noebook Fan Controller does not work with Riot Games, Vanguard anti-cheat software. It is blocking the WinRing0x64.sys file. As a result of this NoteBook Fan Contoller does not start.

![Screenshot_45](https://user-images.githubusercontent.com/64873971/81125482-ee7bef80-8f40-11ea-8d9b-87caf6964146.jpg)

**Comment by thederp** [comment]
I'm having the same exact issue. Riot Vanguard will block Fan Control on startup.
![fan1](https://user-images.githubusercontent.com/5713315/81183692-77b11780-8f7d-11ea-84d0-d951138caa3f.png)

**Comment by hirschmann** [comment]
I can't do anything about this.

WinRing0x64.sys is the driver which is required by NBFC to access the fans and read hardware temperatures.
It's not possible to get hardware access without loading a driver.

You could ask in the riot forums if they could whitelist this driver, maybe they will listen.
In my opinion it's really bad practice when an anti-cheat tool has to have complete control over your system and randomly prevents other software from running even if the game itself isn't running.
I hope enough people are annoyed by this bullshit and complain in the Riot forums and their social media channels or maybe even boycott their games until they stop these shenanigans.

**Comment by hirschmann** [comment]
Fortunately Riot has changed Vanguard's blocking behavior: https://github.com/hirschmann/nbfc/issues/885#issuecomment-626208192

Running Valorant/Vanguard and NBFC side by side seems to be no problem anymore :)
