### ISSUE TITLE
Valorant Vanguard Problem

### ISSUE THREAD

**Issue by cruelly1903** [hirschmann/nbfc#886]
Please fix the vanguard problem for NotebookFanControl
We need new update

**Comment by hirschmann** [comment]
Disable vanguard

**Comment by cruelly1903** [comment]
i want play valorant with fancontrol

**Comment by hirschmann** [comment]
Unfortunately this is not possible and I can't do anything about it, see https://github.com/hirschmann/nbfc/issues/884

**Comment by hirschmann** [comment]
Just wanted to let you know it works again with the latest version of Vanguard: https://github.com/hirschmann/nbfc/issues/885#issuecomment-626208192

**Comment by cruelly1903** [comment]
im so happy thank you <3
