### ISSUE TITLE
Config for HP Omen 17 w200 series? (specifically w247nf)

### ISSUE THREAD

**Issue by raymonders** [hirschmann/nbfc#887]
**Is your feature request related to a problem? Please describe.**
 [**Config requests**]Hello. I read the page about making my own config but I'm useless at this kind of things, i couldnt understand any of it, so please forgive me for making this issue anyway.

**Describe the solution you'd like**
I would like a config for HP Omen 17 w200 series laptops, specifically the w247nf model

**Additional context**
This is the laptop model specs, according to HP's own site.
https://support.hp.com/sg-en/document/c05559314

Thank you in advance

**Comment by The-Quantum-Guy** [comment]
ya i did manage to make one for my hp omen  17-w200nx



[HP OMEN by HP Laptop.zip](https://github.com/hirschmann/nbfc/files/4605564/HP.OMEN.by.HP.Laptop.zip)

however your model has a little bit of a lower spec so i wouldnt but the fan on 100% on this profile i would start at a maximum of 80% and see if it doesnt crash 
please lemme know if it works for you too!

**Comment by The-Quantum-Guy** [comment]
oh almost forgot to be able to use it extract the archive in configs folder in your installation file and you should see it in the options for configs after extracting it and restarting notebook fan control

**Comment by raymonders** [comment]
Thank you @The-Quantum-Guy ! it's working so far at 100% for 5 minutes straight (thought i'd stress test it haha) also i checked out the w200nx specs, those are nice! this is unrelated to Fan Control, but do you think your battery would be compatible with my model (it seems to be the same chassis)? 95Wh is wayyyy better than my 62Wh

**Comment by The-Quantum-Guy** [comment]
Daimn am so happy it worked for you too 

and ya i think my battery should work with yours too
judging from this listing
https://www.batterie-chargeurs.com/original-958wh-batterie-hp-omen-17w247nf-p-159600.html
its 95w battery for your omen 17 w247nf

**Comment by The-Quantum-Guy** [comment]
now my config works but it aint complete am working on a version for dual fan control so i might send you another one to test soon if you dont mind :D

**Comment by The-Quantum-Guy** [comment]
@raymonders  one more hack that i successfully applied to my laptop is changing the vbios to allow to  increase the ammount of power my gpu had access to which literally made me abe to easily over clock it by 200mhz for free lol i know if i ried i can get more but i have no time lol

**Comment by raymonders** [comment]
> Daimn am so happy it worked for you too
> 
> and ya i think my battery should work with yours too
> judging from this listing
> https://www.batterie-chargeurs.com/original-958wh-batterie-hp-omen-17w247nf-p-159600.html
> its 95w battery for your omen 17 w247nf

i looked at the listing and the picture in that listing looks noooothing like the one my laptop has :O but thanks for looking it up!

im not sure how i can help with dual fans since mine only has a single fan, but i'll try that bios trick at some point 🍭
