### ISSUE TITLE
N55sf max speed?

### ISSUE THREAD

**Issue by AMeEeRo** [hirschmann/nbfc#89]
I have N55sf i tried to make my own config but it didn't work, please tell us which settings should we edit or please add n55sf, thanks

**Comment by timhovius** [comment]
It works for me, copy the N550JV config file :+1:

**Comment by AMeEeRo** [comment]
Thanks for replying it looks working for me too but it's not full speed or 100% is full speed for all there is no other number like rpm numbers or idk?

**Comment by hirschmann** [comment]
100% should be full speed. If it is not, then change [MaxSpeedValue](https://github.com/hirschmann/nbfc/wiki/Basic-fan-configuration#maxspeedvalue) in your config.
