### ISSUE TITLE
control the fan of Miix 520

### ISSUE THREAD

**Issue by PixDel** [hirschmann/nbfc#890]
Hello, 
im new here, and sry. for my english :).
So, i bought an used but "new" Miix 520, the model with the i3 7130u. And i like the device. But the Fan.... its not "BAD" but it start to fast. at 40°C the fan start.. have someone a config that i can import in nbfc? so i can control him myself? :/  or tips for me to create one. I found an pdf file that show how to create an own config, but i dont understand this lol :((

**Comment by Boom-Hacker** [comment]
https://mclub.lenovo.com.cn/forum.php?mod=viewthread&tid=5762073&extra=page%3D1&page=1&forcemobile=1
