### ISSUE TITLE
Config xml for Asus Rog GL552VW

### ISSUE THREAD

**Issue by DeadKurt** [hirschmann/nbfc#892]
Hello is it possible to make a config for the asus rog gl552vw series notebook?
i5-6300HQ + GTX 960M
thanks.

**Comment by jhonsitox** [comment]
Use of any config that ends in VW or VD in ASUS. I had this pc and i controlled the fan.

**Comment by DeadKurt** [comment]
> Use of any config that ends in VW or VD in ASUS. I had this pc and i controlled the fan.

Thanks for the answer I will try, but those two VD that are there, do not have the same specifications as my laptop
