### ISSUE TITLE
Fan configuration not applied sometimes

### ISSUE THREAD

**Issue by dariodjuric** [hirschmann/nbfc#9]
Hi,

excellent tool you have there. I own a Probook 650 G1 and this tool kept my fan mostly under control.

Sometimes, however, the fan starts running at 80% speed for a few minutes and then stops. This happens even while CPU is idle, which is also visible from the tool as well:

* Temperature (CPU): 53 C
* Target fan speed: 0% (Auto)
* Current fan speed: 80%

Normally it runs for about a minute and then goes back to 0%.

Do you have any suggestions where to look? What could be causing this?

**Comment by hirschmann** [comment]
Have you tried to restart the service if the fan speed is stuck at 80%?
Maybe some other hardware montioring software is interferring with NBFC.

**Comment by dariodjuric** [comment]
Hi, thanks for the reply. Unfortunately it doesn't help. Restarting the service does not have any impact, the fan continues running at 80% for about 30 seconds and it does so roughly every two minutes or so.

I'm not sure exactly what triggers this fan behavior, but what I have noticed is that it starts happening while I am on battery - which particularly bothers me because battery is getting discharged faster that way.

Any other proposals?

**Comment by hallelulius** [comment]
Hi, I have a similiar problem. For me it seems to occur after the computer has entered sleeping mode a couple of times. Restarting the computer solves the problem though. I also have problems with infinity rpm readings on the fans, so it could be related to the hardware aswell.

**Comment by sweckform2** [comment]
Hi, I also have a few HP ProBooks and came across a similar issue awhile back. I fixed it by adjusting the settings for "NoteBook FanControl Service" directly in "Services".

[_Properties > Recovery > "Restart the Service for 1st and 2nd failures"_]
**also**
[_Properties > Log On > Local System Account check the box for the feature "Allow service to interact with desktop_"]

**Comment by sweckform2** [comment]
Forgot to mention, the **HP Support Assistant** (installed on all HP notebooks) is known to interfere with software programs that request exclusive startup privileges - try disabling it to see if it corrects your problem.

You will need to disable both the startup program entry (use _MS Autorun_) and prevent the associated service (under Services), from running at startup
