### ISSUE TITLE
Asus k501u

### ISSUE THREAD

**Issue by greenjao** [hirschmann/nbfc#90]
Can you create an asus k501u config please?
(as far as i know all the asus k501() notebooks have a problem in the fan control)

Thank you very much for your work :)

**Comment by shinji2009** [comment]
https://github.com/hirschmann/nbfc/blob/master/Configs/Asus%20K501LX.xml

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
