### ISSUE TITLE
NBFC is not fully controlling the fans

### ISSUE THREAD

**Issue by Wolf00S** [hirschmann/nbfc#915]
**Describe the bug**

I (at least) tryed to setup NBFC for my Asus G750. After setting the temps and the fan rpms I tried to "apply" the settings and let NBFC do the work.

But even if NBFC shows me "Target fan speed "0"; current fan speed "0"", the fans are spinning up for one or two seconds and turn to 0, than spinning again up for one or two seconds and turn to 0 again.
It seems like I made some mistakes with all the variables I dont need but you have to fill in. I only would need "critical temp", "temp", "fans rpms". Man, such an simple tool would be perfect.

**To Reproduce**
Steps to reproduce the behaviour.

[https://s12.directupload.net/images/200606/by3uk28o.jpg](url)

<a href="https://www.directupload.net" target="_blank"><img src="https://s12.directupload.net/images/200606/by3uk28o.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

**Expected behavior**
What I expect to happen? Create a software with only ONE window. In that window there are ONLY 4 things I can do:
1) Select the model 
2) Set up critical temp where NBFC goes to 100% in THE SAME window in °C 
3) Set up a specific temp in °C and a fan rpm (% of 100) in THE SAME window
4) Hit the "apply button" in THE SAME window
5) Instead of a wiki "pop up infos" above every field
6) Have the actual version number of NBFC in the header
7) Implement, like HWMonitor can do it even it is a windows program, the GPU temp in THE SAME window
8) ???
9) profit

Dont bother me with variables have to be set on a certain way. Do it.
And why a wiki if you dont tell me what "0-255" means, like what does your software if I put in 133 or 203? I dont want to need to put in numbers if they are not directly correlated to "°C" or "% of max rpm".

**System information**
OS: Windows 8.1; 64
NBFC version: NBFC does not show the version in the header (mabye this would be a good feature, you know because you are asking people for the version of your software but you are not willing to show the version on the most simplest way)

**Additional context**

The main problem is that really smart people try to impress dump people like me with all there knowledge. So the tend to include more and more feature in a software no one really needs, but hey they are so smart. So maybe in future we will have fan controlling software with a mathematical calculator in it.
I dont want to learn variables, I just want to set up the temp and the fan speed. Like **just a fan controlling software**. It would also be nice NOT to have to look to three or four different windows, read tons of sites in a wiki to get an app started... how about only ONE window, with popup infos, where I can set up ALL I need. Seems a lot simpler to me.

**Comment by Lamb3** [comment]
While I agree with some of your frustrations especially regarding the user-friendliness of the app (when it's widely marketed as being user-friendly), I don't think it's right to be downright condescending. I can see why the app is built this way as meddling with the EC is not a straightforward matter.

However back to the topic, I do have more or less the same issue as you whereby the default fan settings just keep overwriting my custom config. Making the fans ramp up and down in a matter of seconds.

I'm starting to think that it might be an issue with Windows EC polling itself interfering with the software's polling intervals. I could be wrong but who knows, hope the author could outline this problem asap as I think he's done a great job creating this software.
