### ISSUE TITLE
NBFC doesn't open.

### ISSUE THREAD

**Issue by damiangodz** [hirschmann/nbfc#916]
I have an Acer Aspire E5-575G laptop. And until 3 days ago it worked perfectly for me.
But today, when I tried to get my fan faster, my application does not open.
I uninstalled the application 10 times. I installed previous versions, but nothing.
I restarted the computer and still nothing. I do not know what to do. I want to turn on my fan harder and the application does not open.
The NBFC service appears in my Task Manager and when I open the application itself, it gives me Suspended and does not open. Help?

**Comment by jfwerner** [comment]
https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md

See "Issues"

**Comment by g34rn1nja** [comment]
Same issue for me, I have to repair the installation after every restart, seems like it's a .Net Framework issue. Don't reinstall, just modify & repair
