### ISSUE TITLE
Config request for Lenovo Ideapad 5-15ARE05 Type 81YQ 

### ISSUE THREAD

**Issue by iloveeclipse** [hirschmann/nbfc#919]
Just wanted to create a request for Lenovo Ideapad 5-15ARE05 Type 81YQ config - this is a new model using brand new Ryzen 5 4600 CPU, so I haven't found a candidate here in existing configs.

I'm in theory OK with the default fan on that laptop, but it seem to jump in as soon as CPU temperature is over ~50°, runs for few seconds and switches off - that makes unneeded spikes. I believe moving the range of the fan start to 55° would be already of big help, because CPU itself seem to be pretty "cold".

I know that one shouldn't create config requests - but I have no time for fan debugging on this NB, it is not my own.

**Comment by G2424** [comment]
I also have the same notebook with Ryzen 7 4800U and tried something. Maybe it helps someone to create a config.

![Anmerkung 2020-06-11 213943](https://user-images.githubusercontent.com/66842318/84528613-506a0a80-ace0-11ea-8c67-e4cfbdb4a3ee.png)

**Comment by Loki-T** [comment]
Yes, i have the same "problem". I think, that moving the range of the fan start to 55° or 60° would be really very nice.

**Comment by werzum** [comment]
> 
> 
> I also have the same notebook with Ryzen 7 4800U and tried something. Maybe it helps someone to create a config.
> 
> ![Anmerkung 2020-06-11 213943](https://user-images.githubusercontent.com/66842318/84528613-506a0a80-ace0-11ea-8c67-e4cfbdb4a3ee.png)

Hey G2424, could you share this config? I have the same model and am trying to find a solution for my fan issues.
Thanks a lot!

**Comment by G2424** [comment]
> Hey G2424, could you share this config? I have the same model and am trying to find a solution for my fan issues.
> Thanks a lot!

Hey, I still couldn't create a config, but if you really have the same model, you can just update to newest bios:

https://pcsupport.lenovo.com/fr/de/products/laptops-and-netbooks/5-series/ideapad-5-15are05/downloads/DS544050

This fix (in my opinion) the fan issues. Than install Lenovo Vantage (Windows Store) and you are able so choose different profiles (15W Energy Save, 20W Intelligent Cooling and 37W Performance). On Energy Save the fan is silent in 99% of daily-use-task.

**Comment by IlIlIlIlIlIlIl** [comment]
Any success stories to share with Lenovo ryzen laptops? I tried EC probing with my Lenovo Yoga Slim 7 4800U model, didn't find any good correlations with fan speed...

**Comment by ElieSDK** [comment]
> 
> 
> Any success stories to share with Lenovo ryzen laptops? I tried EC probing with my Lenovo Yoga Slim 7 4800U model, didn't find any good correlations with fan speed...

Is the Yoga Slim quiet? Fan starts at 50 degres like the Ideapad ?

**Comment by lukyanenkomax** [comment]
I have updated BIOS and set "Battery saver" mode at Lenovo Vantage, now I hear fan noise very rarely and I have no any performance issues. Fan starts when temperature get over 75C

**Comment by IlIlIlIlIlIlIl** [comment]
Yoga Slim 7 is relatively quiet, but I'm coming from a completely passive chromebook so all fan noise bothers me :) It starts around 52C and turns off after it has dropped to ~42C. Adjusting this a bit would make it perfect.

I've found out that disabling turbo boost and using "Energy Saver" mode that caps CPU power to 10W makes it practically passive when browsing web or watching a video

**Comment by G2424** [comment]
> I have updated BIOS and set "Battery saver" mode at Lenovo Vantage, now I hear fan noise very rarely and I have no any performance issues. Fan starts when temperature get over 75C

Just install "Lenovo Vantage" and "Lenovo Utility" in the MS App Store (no account required) and you can change the profiles (Energy Saver, Intelligent Cooling, Performance) on-the-fly without enter into BIOS. I think the shortcut was Fn + Q.

In Ideapad 5 the profile Energy Saver cap the CPU powerlimit to 15W long duration. With the new BIOS Update the laptop is complete passive even if the CPU is 90 degrees hot. After the update the fan is a lot less proactive in "Energy Saver".
