### ISSUE TITLE
Need config for HP Pavilion 15-dk0xxx Please.

### ISSUE THREAD

**Issue by ImYosrii** [hirschmann/nbfc#930]
**Is your feature request related to a problem? Please describe.**
hi, I'm requesting that u add a HP Pavilion Gaming Laptop 15-dk0xxx config as my laptop is running far too hot and it turns out its the specific one that overheats and I'm not comfortable with the stock fan speeds.

**Describe the solution you'd like**
new config

**Additional context**
Thank you.

**Comment by jfwerner** [comment]
> > Config requests
> 
>     Before creating a new issue, give the configs recommended by NBFC a try: nbfc.exe config --recommend (for further information, have a look at the NBFC command line interface)
>     Don't ask if someone can create a configs for you. Instead, read the tutorial of how to create a NBFC config and try to create a config on your own
>     In case you've read the tutorial, but you're stuck, please try to provide as much information as possible about your notebook, e.g. manufacturer, model, EC/SuperI/O-chip name, interesting EC registers etc.
>     In general, a forum dedicated to your notebook model is probably the best place to find other users who want to help create a config
> 

Have you tried this?

**Comment by siparacetamol** [comment]
I've tried the recommended setting by NBFC, none of them works for HP Pavilion 15-dk0xxx. Please help up to find the correct configuration for this laptop model. Thank you.

**Comment by hpcoolsense** [comment]
I am with the same problem I hope we can find a quick solution

**Comment by hpcoolsense** [comment]
Have you already tried creating an nbfc on your own? as English is not my main language I could not
