### ISSUE TITLE
Config File for Lenovo miix 510-12isk 80u1

### ISSUE THREAD

**Issue by siminio7** [hirschmann/nbfc#932]
**Is your feature request related to a problem? Please describe.**
Hello, I'm stuck on creating a config file for my device. Maybe someone has had the same problem and is willing to share his solution or wants to create a config file with me.

**Describe the solution you'd like**
I would like you to help me with the config for my notebook to turn of my fans when I am doing light usage.

Thank you in advance. A working solution will definetly be rewarded! :)

**Comment by Boom-Hacker** [comment]
https://mclub.lenovo.com.cn/forum.php?mod=viewthread&tid=5762073&extra=page%3D1&page=1&forcemobile=1
