### ISSUE TITLE
A video demonstration for complete beginners!

### ISSUE THREAD

**Issue by neospeed83** [hirschmann/nbfc#938]
First of all, I am sorry I created this issue. I did not know where to put my idea.
This is not a bug but something I feel is helpful for new users who are not tech-savvy.

I think adding this video link to the readme would help a lot of beginners and non-techy people.
This video is not monetized and only made with the sole intention of making it as easy as possible to understand the installation.
Link to the video: [https://youtu.be/SxdisSI2W3c](url)

@hirschmann I would really appreciate it if this is added to the repo in any way. Thanks for making this beautiful software!

**Comment by tomprost** [comment]
Nice idea, but I' pretty sure, Windows users need no guide !?? What about Linux ? It seems more complicated, than I thought ... :-(
