### ISSUE TITLE
Asus vivobook tp301ua

### ISSUE THREAD

**Issue by fusk-l** [hirschmann/nbfc#94]
I noticed someone else doing this, but i'm sure i'm totally doing it wrong considering this is more a request than an issue. But how would i go about using this on a asus tp301ua?
It's a skylake chipset, so using  the config from an older vivobook wouldn't be the right choice i imaging, as the temperature thresholds are probably not the same.

**Comment by cdosorio** [comment]
I also have a tp301ua, and the config from zenbook ux360uak works right for me. I just needed to adjust the first range of temperatures, to get fan stopped at lowers temps.  I tried to upload it but get an error. 

About your question, IMHO the ranges should be very similar, but you could be conservative, and adjust the upper ranges, increasing its fanspeed parameters.

**Comment by cdosorio** [comment]
![temperatures ranges](https://cloud.githubusercontent.com/assets/17026794/24833266/8678a72e-1c99-11e7-9c4d-c38a84909cc6.PNG)

In the image you can see my settings. I forgot to mention that also changed the other fan speed percentages, to coincide with the values availables in the "Target fan speed" slider of the main screen.

**Comment by ngnh** [comment]
Just as a note, that post was from June 2016, so i did figure it out. I used the config from UX302LA. But from your pic i run my machine very differently from yours. Mine is nearly 100% silent. And with XTU i'm running -95mV on the cpu and -70mV on the gpu. It's completely silent during day to day usage.

![udklip](https://cloud.githubusercontent.com/assets/6765298/24833435/231b5616-1cc8-11e7-99f6-1aceb3cd95e9.PNG)

**Comment by cdosorio** [comment]
I'll try your settings, to get more periods of silence, thanks a lot.

I noted the date, but didnt want to open a new thread for the same model. Great laptop, except by the intermitent wifi connection I get.

**Comment by ngnh** [comment]
Fair enough. But i don't have the wifi issue, so might be something wrong with the hardware in yours.
Also, in power management. Where you have minimum and maximum processor %. In maximum on battery you can set it to 83% and that will also keep the cpu cooler as it won't clock higher than 1.97ghz. Which imo is more than fine for every day tasks.
