### ISSUE TITLE
No Support for Dell Latitude (R) 3340.

### ISSUE THREAD

**Issue by TheSystemGuy1337** [hirschmann/nbfc#941]
So i wanted to crank up my fans on my Latitude 3340 for fun. but after SpeedFan not working I came here. Not only I was unable to enable Fan ctrl, but My System was also unsupported! My system might have been from a School or was aimed at schools witch means My system was **NOT** intended to be cranked hard or put under heavy load. but if you add support for the Latitude 3340, I will be Happy

**Solution**
Add Support for The **Latitude **3340****

**Additional context**
In the list of supported machines, The Latitude 3340 was **not** on the _list._

**Comment by neospeed83** [comment]
Did you try the nbfc cli recommendation? If not, I recommend you do try the top 3 at least. 
You can check out this video to see how to  [https://youtu.be/SxdisSI2W3c](url)

**Comment by TheSystemGuy1337** [comment]
> Did you try the nbfc cli recommendation? If not, I recommend you do try the top 3 at least.
> You can check out this video to see how to [https://youtu.be/SxdisSI2W3c](url)

If its not supported, **Then Its NOT supported** You did not help and you are not helping at all. get out and leave me alone

**Comment by TheSystemGuy1337** [comment]
WHO NEEDS THIS, THIS ENTIRE THREAD IS 100% USELESS. I am closing the thread. ENOUGH IS ENOUGH
