### ISSUE TITLE
Config request for HP envy x360 15m-ee0023dx

### ISSUE THREAD

**Issue by oryydin** [hirschmann/nbfc#943]
The pavillion 14-v066br config _seems_ to have some degree of fan control, but it ramps from completely off to something like 50% fan speed when toggled from 29% to 30%. Does anyone have a proper config for the 15m-ee0023dx? The default is just way too aggressive - I barely break 60% with heavy load and the fans off.

**Comment by maxcurrent420** [comment]
I have the HP envy x360 15m-ed0023dx and the Pavillion 14-v066br profile results in maxed out fan speeds on at least on of the fans and shows -100 current fan speeds. The other profiles I tried had no effect and showed negative fan speed in the thousands. Would love a good config for this. There are some other dual fan configurations that detect the fan but don't seem to work and I've no idea how to set the second fan speed.
