### ISSUE TITLE
Asus ROG G750JS configuration

### ISSUE THREAD

**Issue by alex21112** [hirschmann/nbfc#95]
Hello can anyone help me make the configuration for the Asus ROG G750JS?
I tried using the ROG G751JY buy it only shows one fan.
I'll provide any info necessarly(tell me where to look and what to send)

**Comment by RypeDub420** [comment]
Was the Asus ROG G751JY the ONLY config that gave you anything?

If so, then which fan exactly did it find for you? What is the register number like 151 or 152, etc.?

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
