### ISSUE TITLE
EC doesn't change register

### ISSUE THREAD

**Issue by super-eye** [hirschmann/nbfc#963]
Hi

EC Probe isn't changing the register values of my laptop (ASUS X571GD). Read another post about this but it has no solution yet. Could anybody help me with this?
![git_hub_question](https://user-images.githubusercontent.com/61566133/89722213-eac29380-d99b-11ea-94cf-04dd08f3a9cc.png)

**Comment by Valdiralita** [comment]
that just means something else overwrites your written value.
Sometimes you have to enable manual fan control first before setting a value. if you dont set manual mode, the automatic fan control will overwrite your value

**Comment by super-eye** [comment]
Hi, thanks for helping. Sorry for the late response but I've been having a lot of work to do 

How can enable manual fan control.

 I tried opening nbfc with "Fan control service Status" selected

But that register didn't change. How may I do this? 
Couldn't find anything on the wiki or on issues.
