### ISSUE TITLE
Request Asus gm501gs

### ISSUE THREAD

**Issue by mehmetariftasli** [hirschmann/nbfc#967]
Im trying to make a config file for my laptop but im completly lost over the DSTD file that is generated.

[DTDS.txt](https://github.com/hirschmann/nbfc/files/5060055/DTDS.txt)

**Comment by mehmetariftasli** [comment]
RW everything EC - https://prnt.sc/ty3rwa
its all 00

**Comment by NobleUpFront** [comment]
Did you solve it?
