### ISSUE TITLE
Samsung NP355V5C

### ISSUE THREAD

**Issue by dragunylmz** [hirschmann/nbfc#97]
Helloi I want to config file for my NP355V5C laptop. I tried all of that config but I couldn't find right config. I tried make it myself but I coulnd't. Please help me.

**Comment by dragunylmz** [comment]
up

**Comment by dragunylmz** [comment]
up

**Comment by dragunylmz** [comment]
up again please do something

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
