### ISSUE TITLE
Clevo NH58AC works with Asus ROG GL702ZC default, edits work

### ISSUE THREAD

**Issue by BreenyBaby** [hirschmann/nbfc#974]
I don't have an issue, just letting you know that my new Clevo NH58AC laptop with Ryzen 9 3900, GTX 1660Ti is working with default ROG GL702ZC, allowing adjustments too.  I increased fan speeds for temps at and above 65C, with goal of keeping temps below 80C at all times using this monstrous 12 core processor in my laptop.  Using the default and increasing fan speeds by 12.5% at 65 and above using default steps works perfectly.

I 'bought you a beer' using the price of a pint of Leffe Blonde, my favorite beer, the best that I could find by approximating the cost of 50CL Leffe in Germany the best I could using the internet as a research platform ;)

I couldn't find any other way to contact hirschmann, sorry to use this inappropriately.

**Describe the solution you'd like**
I want Stefan to enjoy what is in my experience the best beer ever made on Earth, Leffe.
**Additional context**

**Comment by Curious-r** [comment]
Thanks for your infomation! It's useful for my NH55 laptop.
