### ISSUE TITLE
Add Configuration for HP Spectre x360 Convertible 15-df1xxx

### ISSUE THREAD

**Issue by JacksonWan** [hirschmann/nbfc#976]
**Adding HP Spectre x360 Convertible 15-df1xxx fan configuration**

[HP Spectre x360 Convertible 15-df1xxx.txt](https://github.com/hirschmann/nbfc/files/5113104/HP.Spectre.x360.Convertible.15-df1xxx.txt)
(I can't upload XML file here, you can convert it back to XML file by changing the *.txt* to *.xml*)

I had spent several days experimenting with NBFC on my laptop and I want to send this submission to you guys so that everyone who had similar laptops as mine could enjoy this feature of having to control their computer fan speed. Please don’t change any of the fan configurations (if you’ll like to change the temperature thresholds, you can) as all settings have a purpose.

**Additional context**
HP Spectre x360 Convertible 15-df1xxx runs at 4 stages in terms of fan control. The configuration is set up so that you can control the fan at ~4500 RPM (lowest state), ~5200 RPM, ~5500 RMP, ~5600 RMP (highest state). This statistics of fan speed is gathered using SpeedFan. 

**I'll like this configuration to be available to all users who had HP Spectre x360 Convertible**

**Comment by Pecacheu** [comment]
It's not working for me :/
The program just loads/unloads the profile repeatedly and then freezes and crashes after a while.
