### ISSUE TITLE
Unable to get recommended from nbfc.exe on Windows 7. "Unknown argument name 'r'."

### ISSUE THREAD

**Issue by TheSystemGuy1337** [hirschmann/nbfc#977]
When attempting to show recommended from the nbfc.exe command line, it displays this error and crashes to the C prompt

"Unknown argument name 'r'."

OS: Windows 7, Ultimate, x64

System: Vostro 1720

**To Reproduce**
With either the same system or something similar to the Vostro 1720 running x64 Windows 7, type the following command:

nbfc.exe -r

**Expected behavior**
nbfc.exe showing recommended.

eg

Latitude 3340

Vostro 1220.

from the command line.

**Comment by oczkoisse** [comment]
I think you're supposed to use `-r` switch with `config` subcommand like so:
```
nbfc config -r
```
