### ISSUE TITLE
Please add support for the Acer Helios PH315-52

### ISSUE THREAD

**Issue by imad20010** [hirschmann/nbfc#981]
We, helios users, have been waiting years for acer to fix their fan curves, but they are horribly aggressive, the gpu fan is very audible even at idle. We, advanced users, wish for a better fan control utility but can't find any. You are our only hope.

Helios 2019 Model from Acer.

**Comment by priatnaadnyana** [comment]
someone already made nbfc config for ph315-52 and ph317-53 : https://community.acer.com/en/discussion/574033/helios-300-ph317-53-72p5-rtx-2060-fan-stopping/p8
