### ISSUE TITLE
Acer Aspire 5 A515 51G Support

### ISSUE THREAD

**Issue by oppalla** [hirschmann/nbfc#984]
as it was close on this issue topic, i'm reopening here...
if anyone have a valid conf or even a way to make it work will be awesome.

https://github.com/hirschmann/nbfc/issues/550

**Comment by hari0943** [comment]
Have you tried all the profiles from acer
Generally manufacturers dont change the regs to much.
For example ,the acer predator and nitro series configs are the same

**Comment by oppalla** [comment]
i've tried a lot and not a single one works.

its very important to me to be able to control fan speed...

**Comment by erdemiri** [comment]
[kb9022.pdf](https://github.com/hirschmann/nbfc/files/6137337/kb9022.pdf)

I reached the motherboard information. I tried to prepare a fan control file using the information here but failed. A more knowledgeable friend can do this. Can you help me?

**Comment by oppalla** [comment]
unfortunately, 10 months later, there is nothing new about this issue. 

maybe @hirschmann can enlighten us?

**Comment by oppalla** [comment]
nothing new yet
