### ISSUE TITLE
Please Add config for PH315-53 (predator Helios 300 2020)

### ISSUE THREAD

**Issue by priatnaadnyana** [hirschmann/nbfc#988]
actually someone already made a config for Ph315-52 which is Helios 300 2019 version
I tried that one, but not work.

if anyone can make that nbfc config for helios 300 2020 , that'd be great

**Comment by hari0943** [comment]
hello @priatnaadnyana ,have you tried the profile Acer Predator G3-572.xml .
Acer generally has the same registers for all predator and nitro products .It worked for my nitro 7.

**Comment by priatnaadnyana** [comment]
> hello @priatnaadnyana ,have you tried the profile Acer Predator G3-572.xml .
> Acer generally has the same registers for all predator and nitro products .It worked for my nitro 7.

Yes already tried that, it's not working

**Comment by sugat009** [comment]
Someone should work on this, predator helios 300 needs fan control
