### ISSUE TITLE
Asus X552MJ

### ISSUE THREAD

**Issue by Duxily** [hirschmann/nbfc#99]
Hello all.

Could someone make a config for this lappy ?
I looked but i have no clue with those settings and and i am too afraid to break something.
I would be really happy.
I tried some and one works, i can control my fan, its for another Asus laptop but i am again afraid it might break something :(
I dunno if i should provide some info or something :/

Thanks anyway :)

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
